### ISSUE TITLE
Incorrect origin when using mysql

### ISSUE THREAD

**Issue by nehalist** [TryGhost/Ghost#10072]
### Issue Summary

When using mySQL for database Ghost doesn't work in the latest version. Admin shows 500 page throws console errors:

```
Error while processing route: posts.index Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o.deserialize (domain/ghost/assets/ghost.min-cb9cedd474b87c1e57a494b014040dcb.js:1027:13)
    at e.eachTransformedAttribute (domain/ghost/assets/vendor.min-b6c746e6d718a54841a93b04223a8094.js:13361:8)
   ...
```

When trying to call `ghost/api/v2/admin/roles` the following error is returned:

> Request made from incorrect origin. Expected 'domain' received ''."

Everything works fine when using sqlite.

### To Reproduce

1. Fresh 2.3.0 install
2. Run with mySQL

### Technical details:

* Ghost Version: 2.3.0
* Node Version: 8.12
* Browser/OS: Chrome (shouldn't be relevant)
* Database: mySQL

**Comment by kirrg001** [comment]
I can't reproduce your report. A fresh installation with Ghost 2.3.0 and MySQL works fine.

The error looks to me that the admin client receives a broken JSON string from the server.
Which MySQL version are you using?

> Request made from incorrect origin. Expected 'domain' received ''."

@allouis Any idea? What does this error message mean?

**Comment by nehalist** [comment]
SQL version is `5.1.73`

**Comment by allouis** [comment]
Ghost stores the origin of the session you signed in with in the session store - it validates that the origin is the same for each request made with that session. This is to protect against CSRF attacks. 

Are you switching between databases, but using the same login session?

> Request made from incorrect origin. Expected 'domain' received ''."

This error suggests that you logged in with the origin 'domain', but the request was made with an origin of '.'.

> Browser/OS: Chrome (shouldn't be relevant)

This is relevant because browsers send different headers to identify the origins that the requests are made from.

We use the `Origin` header if present, the `Referer` header if that is missing and the `Referrer` header if that is missing.

Could you includes the request headers that are being made from your browser? and ensure you clear cookies between switches databases (if that is happening)

**Comment by allouis** [comment]
@nehalist Is this still an issue?

**Comment by nehalist** [comment]
Will give you more information within the next days, had no time to investigate any further on this the last weeks.

**Comment by Memphizzz** [comment]
I just started to have the same Issue but only after login. I can see the blog just fine https://blog.x-toolz.com but after I enter the correct credentials I get: Request made from incorrect origin. Expected 'https://blog.x-toolz.com' received ''.

I did do an update lately but I'm pretty sure I edited some articles after that so I can't tell why this starts happening now. Is there any external request that might fail?

**Comment by Memphizzz** [comment]
Anyone?

**Comment by kirrg001** [comment]
@allouis ping

**Comment by allouis** [comment]
@Memphizzz could you include some more information - as detailing here: https://github.com/TryGhost/Ghost/issues/10072#issuecomment-433788886

**Comment by Memphizzz** [comment]
As I don't know what you exactly need, here is the last 3 request from Opera's Developer Menu.

https://gist.github.com/Memphizzz/9bf19bf7a377a7c92f96e56af489d812

"session" seems to be last OK response. And here is the relevant part of nginx conf:

	location / {
		proxy_hide_header X-Powered-By;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
		proxy_set_header X-NginX-Proxy true;
		proxy_set_header Host $http_host;
		proxy_pass http://127.0.0.1:2368;
		proxy_redirect off;
}

**Comment by Memphizzz** [comment]
I just found a fix. This issue might be related to an nginx update?
The following post works: https://github.com/TryGhost/Ghost/issues/9972#issuecomment-430004131

Basically you have to add:

		add_header 'Access-Control-Allow-Origin' 'https://www.x-toolz.com';
		add_header 'Access-Control-Allow_Credentials' 'true';
		add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
		add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Max-Age' 1728000;
			add_header 'Content-Type' 'text/plain charset=UTF-8';
			add_header 'Content-Length' 0;
			return 204;
		}

Please don't ask me which line exactly makes it work but it does.

**Comment by Memphizzz** [comment]
And I've narrowed that down to:

add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';

This is what I needed to add.

**Comment by allouis** [comment]
Hey @Memphizzz Thanks for the extra info!

Can I ask what browser you were having this error with? Was it just opera?

The middleware is crapping out because there is no `Origin` or `Referer` header you *might* be able to just do
```
add_header 'Access-Control-Allow-Headers' 'Origin'
```

This doesn't feel like the correct fix as really CORS headers should be set by the API itself, i'd be interested to know if it's just an issue with opera :crossed_fingers: ? That would make it a lot easier to replicate and fix (hopefully) inside of Ghost

**Comment by Memphizzz** [comment]
I've tried all browsers I have installed. Same Result on: Edge, Firefox and Opera.

**Comment by Memphizzz** [comment]
From the other Issue I now also tested: `add_header Referrer-Policy "origin";` which might be safer? What would you say is the recommended way?

**Comment by allouis** [comment]
`add_header Referrer-Policy "origin"` Is deffo preferred as you're not modifying cors headers :relaxed: Thanks for all your info - I'll have another dig into this and see if i can replicate

**Comment by Memphizzz** [comment]
Sure, you're welcome. nginx version was: nginx/1.14.0 (Ubuntu) in case you need it.
Thanks and keep up the great work (except for the android app -.- )!

**Comment by ErisDS** [comment]
Closing due to inactivity
