### ISSUE TITLE
Subscriber webhooks fail

### ISSUE THREAD

**Issue by m1guelpf** [TryGhost/Ghost#10139]
After setting a webhook for subscriber deletion, I get this when triggering it:
```log
INFO [2018-11-11 19:17:54] "DELETE /ghost/api/v2/admin/subscribers/5be88051e517fd0001c6ebfb/" 204 160ms


[2018-11-11 19:17:54] INFO webhook.trigger subscriber.deleted https://m1guelpf.me 


[2018-11-11 19:17:56] ERROR




NAME: InternalServerError


CODE: ETIMEDOUT


MESSAGE: The server has encountered an error.




level:normal




{"id":"5be88038e517fd0001c6ebfa","event":"subscriber.deleted","target_url":"https://m1guelpf.me","payload":{"subscribers":[{"id":"5be88051e517fd0001c6ebfb","name":null,"email":"a@a.com"}],"event":"subscriber.deleted"}}


empty


ERROR DETAILS:


    empty




InternalServerError: The server has encountered an error.


    at new GhostError (/var/lib/ghost/versions/2.5.0/core/server/lib/common/errors.js:10:26)


    at request.then.catch (/var/lib/ghost/versions/2.5.0/core/server/services/webhooks/trigger.js:50:34)


    at tryCatcher (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/util.js:16:23)


    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/promise.js:512:31)


    at Promise._settlePromise (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/promise.js:569:18)


    at Promise._settlePromise0 (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/promise.js:614:10)


    at Promise._settlePromises (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/promise.js:690:18)


    at _drainQueueStep (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/async.js:138:12)


    at _drainQueue (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/async.js:131:9)


    at Async._drainQueues (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/async.js:147:5)


    at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/async.js:17:14)


    at runCallback (timers.js:810:20)


    at tryOnImmediate (timers.js:768:5)


    at processImmediate [as _immediateCallback] (timers.js:745:5)




RequestError: Request timed out


    at timeoutFn (/var/lib/ghost/versions/2.5.0/node_modules/got/index.js:131:53)


    at asPromise (/var/lib/ghost/versions/2.5.0/node_modules/got/index.js:134:9)


    at got (/var/lib/ghost/versions/2.5.0/node_modules/got/index.js:386:10)


    at request (/var/lib/ghost/versions/2.5.0/core/server/lib/request.js:15:12)


    at _.each (/var/lib/ghost/versions/2.5.0/core/server/services/webhooks/trigger.js:22:9)


    at arrayEach (/var/lib/ghost/versions/2.5.0/node_modules/lodash/lodash.js:516:11)


    at Function.forEach (/var/lib/ghost/versions/2.5.0/node_modules/lodash/lodash.js:9344:14)


    at makeRequests (/var/lib/ghost/versions/2.5.0/core/server/services/webhooks/trigger.js:14:7)


    at wrapper (/var/lib/ghost/versions/2.5.0/node_modules/lodash/lodash.js:5199:19)


    at runTask (/var/lib/ghost/versions/2.5.0/core/server/lib/promise/pipeline.js:16:24)


    at /var/lib/ghost/versions/2.5.0/core/server/lib/promise/pipeline.js:26:20


    at tryCatcher (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/util.js:16:23)


    at Object.gotValue (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/reduce.js:157:18)


    at Object.gotAccum (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/reduce.js:144:25)


    at Object.tryCatcher (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/util.js:16:23)


    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.5.0/node_modules/bluebird/js/release/promise.js:512:31)




[2018-11-11 19:17:56] WARN Unable to update last_triggered for webhook: 5be88038e517fd0001c6ebfa 
```

Same for the subscriber added webhook

**Comment by rishabhgrg** [comment]
Hey @m1guelpf 👋, the reason webhooks fail here is because the target URL(https://m1guelpf.me) isn't configured to handle `POST` requests sent by the server. Updating it to a valid target URL should work without any errors: [Setting up a webhook](https://docs.ghost.org/api/webhooks/#setting-up-a-webhook)

That being said, the error here definitely needs update to reflect this correctly as a warning, will get that sorted.

**Comment by m1guelpf** [comment]
@rishabhgrg actually I changed the URL from the logs, the real URL should handle POST requests perfectly ([see source](https://github.com/m1guelpf/ghostletter))

**Comment by rishabhgrg** [comment]
@m1guelpf The above logs indicate the request to the actual URL was sent by server, but server did not receive any response back and so timed out on request. It could be the case where URL is able to perfectly handle requests but is not sending any response back, I'd suggest if possible to use `curl` or similar external tool to test `POST` request/response flow for the actual target URL to make sure its handled properly.

**Comment by m1guelpf** [comment]
@rishabhgrg I was testing it with an exactly identical copy of the blog locally (the only different setting is that it has the developer flag on) and it worked 🤷‍♂️ . Will try to deploy a test URL when I get home

**Comment by rishabhgrg** [comment]
@m1guelpf Closing this for now.
