### ISSUE TITLE
TypeError: argument sql must be a string

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10155]
**This only happens with a very very specific situation!**

## Error

```
TypeError: argument sql must be a string
    at Object.raw (ghost-workspace2/node_modules/sqlstring/lib/SqlString.js:188:11)
    at Builder.raw (ghost-workspace2/node_modules/mysql/index.js:106:20)
    at Formatter.compileCallback (ghost-workspace2/node_modules/knex-migrator/node
```

## Steps to reproduce

`knex-migrator reset`
`knex-migrator init`

-> cancel the process after the tables were created
-> release the migration lock

`knex-migrator migrate`

Ghost: master
knex-migrator: latest
db: mysql

**Comment by kirrg001** [comment]
https://github.com/TryGhost/knex-migrator/commit/75011038fd832c1b2e510a34ef182691e93c2832s should help to avoid this situation.
