### ISSUE TITLE
Unused page-***.hbs file crashes Ghost unless it is in /partials

### ISSUE THREAD

**Issue by pkail** [TryGhost/Ghost#10172]
### Issue Summary
Unused hbs file needs to be present, or Ghost crashes.

A summary of the issue and the browser/OS environment in which it occurs.
A file named "page-causes.hbs" needs to be present either in the main theme directory or in /partials, even though it is not referenced anywhere in the code.  If this file is removed or put into a different sub-directory Ghost crashes with the following error message:

TypeError: Cannot read property 'engine' of undefined
    at ghostLocals (D:\ghost\versions\2.6.0\core\server\web\shared\middlewares\ghost-locals.js:16:53)
    at Layer.handle [as handle_request] (D:\ghost\versions\2.6.0\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:317:13)
    at D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:335:12)
    at next (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:275:10)
    at compression (D:\ghost\versions\2.6.0\node_modules\compression\index.js:220:5)
    at Layer.handle [as handle_request] (D:\ghost\versions\2.6.0\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:317:13)
    at D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:335:12)
    at next (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:275:10)
    at logRequest (D:\ghost\versions\2.6.0\core\server\web\shared\middlewares\log-request.js:29:5)
    at Layer.handle [as handle_request] (D:\ghost\versions\2.6.0\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:317:13)
    at D:\ghost\versions\2.6.0\node_modules\express\lib\router\index.js:284:7

### To Reproduce
1. This is the first step
Create the template, restart Ghost, change the navigation to get it to access this template, restart Ghost, try this a few more times and then give up because the page-***.hbs feature obviously doesn't work (it picks up one template but uses page.hbs for the rest).

In the process, Ghost seems to store a reference to this file, presumably in the database.  It then needs to find it on start-up, even if this file is not actually being used.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Ghost shouldn't crash.  There is also a related issue in that page-***.hbs files aren't used properly (although the documentation is so opaque on this that it's difficult to know what the correct behaviour should be). 

Completely clearing the Chrome cache doesn't solve the problem.

### Technical details:
* Ghost Version: 2.6.0
* Node Version: 8.11.3
* Browser/OS: Chrome 70.0.3538.102 (Official Build) (64-bit)
* Database: default (presumably MySQL).

**Comment by gargol** [comment]
Hey @pkail , from the error message you've shared it seems like the theme you are trying to modify doesn't have the `engine` property specified in 'package.json' of the theme you are trying to modify. It should be something like [here](https://github.com/TryGhost/Casper/blob/master/package.json#L6-L8).

 Where did `page-***.hbs` come from, what were you trying to accomplish?

**Comment by pkail** [comment]
If you mean 'engines', it does.  It doesn't have 'engine', though.

**Comment by ErisDS** [comment]
Closed as explained inhttps://github.com/TryGhost/Ghost/issues/10173
