### ISSUE TITLE
SQLITE_ERROR: no such table: sessions

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#10235]
### Issue Summary

Main error: SQLITE_ERROR: no such table: sessions

To my knowledge, there was never a 'sessions' table in the Ghost's DB.

### Surfing on the website

go to mysite.com/blog/website

```
d40e60412a6a / docker logs --follow d40e60412a6a
[2018-12-03 17:08:12] INFO Finished database migration!
[2018-12-03 17:08:18] INFO Ghost is running in production...
[2018-12-03 17:08:18] INFO Your blog is now available on http://play-with-ghost.com/live-demo-discover-ghost-v2/
[2018-12-03 17:08:18] INFO Ctrl+C to shut down
[2018-12-03 17:08:18] INFO Ghost boot 5.964s
INFO [2018-12-03 17:08:21] "GET /live-demo-discover-ghost-v2" 301 37ms
INFO [2018-12-03 17:08:28] "HEAD /live-demo-discover-ghost-v2/" 200 699ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/" 200 318ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/assets/built/screen.css?v=c42f446c57" 200 19ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/public/ghost-sdk.min.js?v=c42f446c57" 200 14ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/assets/css_firepress/css_simplegrid/simplegrid.min.css?v=c42f446c57" 200 22ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/assets/css_firepress/css_unicorn/buttons.min.css?v=c42f446c57" 200 28ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/assets/built/jquery.fitvids.js?v=c42f446c57" 200 6ms
INFO [2018-12-03 17:09:49] "GET /live-demo-discover-ghost-v2/assets/built/infinitescroll.js?v=c42f446c57" 200 5ms
INFO [2018-12-03 17:09:51] "GET /live-demo-discover-ghost-v2/welcome/" 200 277ms
```

Everything looks normal here. Good.

### Go to admin panel

I go on mysite.com/blog/ghost/

```
INFO [2018-12-03 17:11:44] "GET /live-demo-discover-ghost-v2/ghost/" 200 154ms
ERROR [2018-12-03 17:11:45] "GET /live-demo-discover-ghost-v2/ghost/api/v2/admin/users/me/?include=roles" 401 37ms

NAME: UnauthorizedError
MESSAGE: Access denied.

level:normal

empty
empty
ERROR DETAILS:
    empty

UnauthorizedError: Access denied.
    at new UnauthorizedError (/var/lib/ghost/versions/2.6.2/node_modules/ghost-ignition/lib/errors/index.js:101:23)
    at ensureUser (/var/lib/ghost/versions/2.6.2/core/server/services/auth/session/middleware.js:98:10)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:137:13)
    at getUser (/var/lib/ghost/versions/2.6.2/core/server/services/auth/session/middleware.js:82:16)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:137:13)
    at cookieCsrfProtection (/var/lib/ghost/versions/2.6.2/core/server/services/auth/session/middleware.js:107:16)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:137:13)
    at session (/var/lib/ghost/versions/2.6.2/node_modules/express-session/index.js:454:7)
    at getSession (/var/lib/ghost/versions/2.6.2/core/server/services/auth/session/middleware.js:48:12)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:95:5)

INFO [2018-12-03 17:11:45] "GET /live-demo-discover-ghost-v2/ghost/api/v2/admin/configuration/" 200 16ms
INFO [2018-12-03 17:11:45] "GET /live-demo-discover-ghost-v2/ghost/api/v2/admin/authentication/setup/" 200 27ms
```

Weird.
Now it's time to enter my user + pass

### Click sign in

```
INFO [2018-12-03 17:12:59] "POST /live-demo-discover-ghost-v2/ghost/api/v2/admin/session" 201 384ms
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/response.js:267:15)
    at _private.JSONErrorRenderer (/var/lib/ghost/versions/2.6.2/core/server/web/shared/middlewares/error-handler.js:66:9)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:67:12)
ERROR [2018-12-03 17:12:59] "GET /live-demo-discover-ghost-v2/ghost/api/v2/admin/users/me/?include=roles" 500 8ms

NAME: InternalServerError
CODE: SQLITE_ERROR
MESSAGE: select `sessions`.* from `sessions` where `sessions`.`session_id` = '-PjqO9qjrYWNsP7bPof0zEqvSJLLQRv_' limit 1 - SQLITE_ERROR: no such table: sessions

level:normal

empty
empty
ERROR DETAILS:
    empty

InternalServerError: select `sessions`.* from `sessions` where `sessions`.`session_id` = '-PjqO9qjrYWNsP7bPof0zEqvSJLLQRv_' limit 1 - SQLITE_ERROR: no such table: sessions
    at new GhostError (/var/lib/ghost/versions/2.6.2/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/var/lib/ghost/versions/2.6.2/core/server/web/shared/middlewares/error-handler.js:42:19)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:275:10)
    at /var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:635:15
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/index.js:260:14)
    at next (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/var/lib/ghost/versions/2.6.2/node_modules/express/lib/router/layer.js:67:12)

Error: SQLITE_ERROR: no such table: sessions
```

Here is the big error: Error: SQLITE_ERROR: no such table: sessions

### Details about my setup

* Ghost Version: 2.6.2
* CLI version: 1.9.4
* Node Version: 10.14.0
* Browser/OS: chrome 66, osx 10.13.4
* Server-side: Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/jobs/428717032)
* Database: sqlite

Thank you!
P

**Comment by pascalandy** [comment]
Hey Fabien!,

It is `[2018-12-03 04:00:50] INFO Creating table: sessions `
See here -> https://travis-ci.org/firepress-org/ghostfire/jobs/462637480#L1069

Also, it's mentioning that I at some point, [I was running Ghost v2.2.2](https://github.com/firepress-org/ghostfire/blob/2.2.2/Dockerfile#L12).

**Comment by allouis** [comment]
Hmm, I notice you have the content dir set as a volume here: https://github.com/firepress-org/ghostfire/blob/2.2.2/Dockerfile#L60

Is it possible that you've mounted a volume that has a previous version of the database, which would override any locally created files such as in travis? :thinking:

**Comment by pascalandy** [comment]
On my server, I see
```
fakeuser@vps11 .../ghost/content/data# ls
ghost.db
```

For me, there is no other version than the one that is running (2.6.2).

Also, this Ghost website is running normally but... I can't log in into it anymore.
This docker image drives more than 30 websites at the moment. It's following the release from the official docker team. 

I could share my ghost.db if you want. Thanks!

**Comment by pascalandy** [comment]
When I open the DB with Tableplus, how can I see the « version » of this DB ?
![screen shot 2018-12-04 at 1 35 01 pm](https://user-images.githubusercontent.com/6694151/49464633-6df41500-f7c9-11e8-9dcb-96cb7db5aa9c.jpg)

**Comment by pascalandy** [comment]
Reporting back. I updated to 2.7.0 and restarted the service. Everything runs normally now. 
I can't prove it, but IMHO there was a bug with v2.6.2

Thanks for everything!

**Comment by allouis** [comment]
@pascalandy Glad you got everything working - very strange though. 2.7.0 didn't change any DB stuff :confused:

**Comment by pascalandy** [comment]
I know very strange :-p
