### ISSUE TITLE
SQLITE_ERROR: no such table: sessions

### ISSUE THREAD

**Issue by Klar** [TryGhost/Ghost#10325]
### Issue Summary

Running Ghost on Docker with Sqlite DB.

### To Reproduce

Trying to login
NAME: InternalServerError
CODE: SQLITE_ERROR
MESSAGE: select `sessions`.* from `sessions` where `sessions`.`session_id` = '2YtY4GK1Kpm49iubqCaU9np8j2fs0Wds' limit 1 - SQLITE_ERROR: no such table: sessions

Upgrade status is green all good, site is loading. Not sure how or when the sessions table is created.

### Technical details:

* Ghost Version: 2.9.1
* Node Version: 1.9.8
* Browser/OS: Docker / Alpine 8
* Database: Sqlite

```
 InternalServerError: select `sessions`.* from `sessions` where `sessions`.`session_id` = '2YtY4GK1Kpm49iubqCaU9np8j2fs0Wds' limit 1 - SQLITE_ERROR: no such table: sessions
     at new GhostError (/var/lib/ghost/versions/2.9.1/core/server/lib/common/errors.js:10:26)
     at _private.prepareError (/var/lib/ghost/versions/2.9.1/core/server/web/shared/middlewares/error-handler.js:42:19)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:71:5)
     at trim_prefix (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:315:13)
     at /var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:284:7
     at Function.process_params (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:335:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:275:10)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at trim_prefix (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:315:13)
     at /var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:284:7
     at Function.process_params (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:335:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:275:10)
     at /var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:635:15
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/index.js:260:14)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:127:14)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Layer.handle_error (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/layer.js:67:12)
     at next (/var/lib/ghost/versions/2.9.1/node_modules/express/lib/router/route.js:135:13)
     at Child.<anonymous> (/var/lib/ghost/versions/2.9.1/node_modules/express-session/index.js:466:11)
     at Child.tryCatcher (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:690:18)
     at _drainQueueStep (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/async.js:138:12)
     at _drainQueue (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/async.js:131:9)
     at Async._drainQueues (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/async.js:147:5)
     at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.9.1/node_modules/bookshelf/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:810:20)
     at tryOnImmediate (timers.js:768:5)
     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by allouis** [comment]
This sounds like a similar issue to this: https://github.com/TryGhost/Ghost/issues/10235 A browse of the comments there might spark something for you.

Could you look at the migrations table and see the lastest migration to have run?

**Comment by Klar** [comment]
I did now a export from an old Version which still worked and did an import in the latest ghost version.

Seems to work that way. 

Thanks for your help.
