### ISSUE TITLE
Sign-in Unknown Error

### ISSUE THREAD

**Issue by beraybentesen** [TryGhost/Ghost#10506]
NAME: InternalServerError
CODE: ER_BEFORE_DML_VALIDATION_ERROR
MESSAGE: Unknown error

level: critical

InternalServerError: Unknown error
    at new InternalServerError (/var/www/ghost/versions/2.14.3/node_modules/ghost-ignition/lib/errors/index.js:77:23)
    at Object.handleStoreError (/var/www/ghost/versions/2.14.3/core/server/web/shared/middlewares/api/spam-prevention.js:27:25)
    at module.exports.<anonymous> (/var/www/ghost/versions/2.14.3/node_modules/express-brute/index.js:84:19)
    at tryCatcher (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Error: ER_BEFORE_DML_VALIDATION_ERROR: The table does not comply with the requirements by an external plugin.
    at Query.Sequence._packetToError (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/ghost/versions/2.14.3/node_modules/mysql/lib/Connection.js:200:25)
    at /var/www/ghost/versions/2.14.3/node_modules/knex/lib/dialects/mysql/index.js:161:18
    at Promise._execute (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/var/www/ghost/versions/2.14.3/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/var/www/ghost/versions/2.14.3/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/var/www/ghost/versions/2.14.3/node_modules/knex/lib/runner.js:155:36)
    at Runner.tryCatcher (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/method.js:15:34)
    at /var/www/ghost/versions/2.14.3/node_modules/knex/lib/runner.js:61:21
    at tryCatcher (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/util.js:16:23)
    at /var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.14.3/node_modules/bluebird/js/release/promise.js:512:31)

**Comment by beraybentesen** [comment]
This is bug not asking for help

**Comment by allouis** [comment]
If you believe this is a bug, could you please include some reproducible steps so that we can determine what's causing it, and how we might fix it? :relaxed:

**Comment by adamelliotfields** [comment]
It's a bug. I'm running into it now and will try to isolate it.

It has to do with MySQL [strict mode](https://dev.mysql.com/doc/refman/8.0/en/faqs-sql-modes.html) from what I can gather. @beraybentesen posted the fix on the [Ghost Forum](https://forum.ghost.org/t/external-mysql-connection-error/5748) as being due to missing primary keys in the `brute` and `migrations_lock` tables.

My setup is unique and unsupported (Kubernetes, MySQL 8.0.11 InnoDB Cluster with MySQL Router), so I'm going to try to reproduce it in a simpler environment.

**Comment by beraybentesen** [comment]
@adamelliotfields If the database is not intended to clustering, there is no problem like this. Single instance DBs work fine. I installed on single instance MySQL Server on Azure and no problem occurred. However, when I install on clustering-enabled solutions like IBM Compose, the error occurs. So I think the Ghost team must document this problem.

**Comment by adamelliotfields** [comment]
I confirmed your fix worked. Here are the necessary changes the Ghost team would have to make:

<https://github.com/TryGhost/Ghost/blob/2.18.3/core/server/data/schema/schema.js>

```diff
brute: {
+   key: {type: 'string', maxlength: 191, nullable: false, primary: true},
-   key: {type: 'string', maxlength: 191},
```

<https://github.com/TryGhost/knex-migrator/blob/v3.2.6/lib/index.js>

```diff
return self.connection.schema.createTable('migrations_lock', function (table) {
+   table.string('lock_key', 191).nullable(false).primary();
-   table.string('lock_key', 191).nullable(false).unique();
```

**Comment by kirrg001** [comment]
Yeah, we should document that the group replication plugin is not supported atm, because this plugin requires to have a not-nullable primary key for each table, which is not the case yet. This should be independent of running MySQL 5 or 8.

A feature request in the forum is the best place to put it for now 👍 

If somebody from the community wants to work on this, it requires to write migration scripts for the target tables.
