### ISSUE TITLE
my story screen yields error 500 with an 403 internal error

### ISSUE THREAD

**Issue by cl1ent** [TryGhost/Ghost#10503]
### Issue Summary

When I want to view and edit my stories on the `Stories` screen, I get an error 500 in the browser.
I am logged in as an admin user and have already created posts.
I also tr

### To Reproduce

1. Clear cache/cookies
2. Login to /ghost as admin user
3. Click on `Stories`
4. Get 500 error in browser

I expect to see my stories and be able to edit them.

### Technical details:

* Ghost Version: 2.13.2
* Node Version: v8.12.0
* Browser/OS: latest chrome on win10
* Database: mysql 5.1.73 (super old)

Error log:
```
@400000005c6ab1ce0d679e24 INFO [2019-02-18 13:23:16] "GET /ghost/" 200 181ms
@400000005c6ab1ce12d9f35c INFO [2019-02-18 13:23:16] "GET /ghost/assets/vendor.min-a669fa271a66edf241764281a0d306d1.css" 200 10ms
@400000005c6ab1ce145e31fc INFO [2019-02-18 13:23:16] "GET /ghost/assets/ghost.min-583b94b8d9b97dee28f64db3ef6e0e54.css" 200 40ms
@400000005c6ab1ce1694e04c INFO [2019-02-18 13:23:16] "GET /ghost/assets/ghost.min-58a92d0509af303859acd55b0c67a428.js" 200 77ms
@400000005c6ab1ce2114b63c INFO [2019-02-18 13:23:16] "GET /ghost/assets/vendor.min-b17fb714431280c44b09ba07ede46229.js" 200 259ms
@400000005c6ab1ce3230424c ERROR [2019-02-18 13:23:16] "GET /ghost/api/v2/admin/users/me/?include=roles" 403 14ms
@400000005c6ab1ce32304e04
@400000005c6ab1ce323051ec NAME: NoPermissionError
@400000005c6ab1ce323055d4 MESSAGE: Please sign in or authenticate with an API Key
@400000005c6ab1ce323059bc
@400000005c6ab1ce32305da4 level:normal
@400000005c6ab1ce32305da4
@400000005c6ab1ce3230618c empty
@400000005c6ab1ce32306574 empty
@400000005c6ab1ce32318684 ERROR DETAILS:
@400000005c6ab1ce32318a6c     empty
@400000005c6ab1ce32318e54
@400000005c6ab1ce3231923c NoPermissionError: Please sign in or authenticate with an API Key
@400000005c6ab1ce32319624     at new NoPermissionError (/home/ghost/ghost/node_modules/ghost-ignition/lib/errors/index.js:114:23)
@400000005c6ab1ce32319a0c     at authorizeAdminApi (/home/ghost/ghost/core/server/services/auth/authorize.js:72:25)
@400000005c6ab1ce32319df4     at Layer.handle [as handle_request] (/home/ghost/ghost/node_modules/express/lib/router/layer.js:95:5)
@400000005c6ab1ce3231ec14     at next (/home/ghost/ghost/node_modules/express/lib/router/route.js:137:13)
@400000005c6ab1ce3231effc     at authenticate (/home/ghost/ghost/core/server/services/auth/session/middleware.js:103:16)
@400000005c6ab1ce3231f3e4     at Layer.handle [as handle_request] (/home/ghost/ghost/node_modules/express/lib/router/layer.js:95:5)
@400000005c6ab1ce3231f7cc     at next (/home/ghost/ghost/node_modules/express/lib/router/route.js:137:13)
@400000005c6ab1ce32323a34     at authenticate (/home/ghost/ghost/core/server/services/auth/api-key/admin.js:42:16)
@400000005c6ab1ce32323e1c     at Layer.handle [as handle_request] (/home/ghost/ghost/node_modules/express/lib/router/layer.js:95:5)
@400000005c6ab1ce32324204     at next (/home/ghost/ghost/node_modules/express/lib/router/route.js:137:13)
@400000005c6ab1ce323245ec     at Route.dispatch (/home/ghost/ghost/node_modules/express/lib/router/route.js:112:3)
@400000005c6ab1ce3232652c     at Layer.handle [as handle_request] (/home/ghost/ghost/node_modules/express/lib/router/layer.js:95:5)
@400000005c6ab1ce32326914     at /home/ghost/ghost/node_modules/express/lib/router/index.js:281:22
@400000005c6ab1ce32326cfc     at param (/home/ghost/ghost/node_modules/express/lib/router/index.js:354:14)
@400000005c6ab1ce323270e4     at param (/home/ghost/ghost/node_modules/express/lib/router/index.js:365:14)
@400000005c6ab1ce32329024     at Function.process_params (/home/ghost/ghost/node_modules/express/lib/router/index.js:410:3)
@400000005c6ab1ce3232940c
@400000005c6ab1cf029385e4 INFO [2019-02-18 13:23:17] "GET /ghost/api/v2/admin/configuration/" 200 32ms
@400000005c6ab1cf07598204 INFO [2019-02-18 13:23:17] "GET /ghost/api/v2/admin/authentication/setup/" 200 17ms
@400000005c6ab1e12a61ad94 INFO [2019-02-18 13:23:35] "POST /ghost/api/v2/admin/session" 201 198ms
@400000005c6ab1e130de4eac INFO [2019-02-18 13:23:35] "GET /ghost/api/v2/admin/settings/?type=blog%2Ctheme%2Cprivate" 200 53ms
@400000005c6ab1e1312ce7c4 INFO [2019-02-18 13:23:35] "GET /ghost/api/v2/admin/users/me/?include=roles" 200 62ms
@400000005c6ab1e13a0a834c INFO [2019-02-18 13:23:35] "GET /ghost/api/v2/admin/notifications/" 200 65ms

```

i get a valid response when i run this in developer tools:
```
fetch('https://url.com/ghost/api/v2/admin/users/me/?include=roles')
  .then(res => res.json())
  .then(console.log)
```

request header before i am logged in:
```
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
App-Pragma: no-cache
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Cookie: ghost-admin-api-session=s%3A5rHlAranbSO7fhjbla7rqa-U7.%2FSllyD8JUzblamRHZq5MzhL%2BueKVaiA
DNT: 1
Host: url.com
Pragma: no-cache
Referer: https://url.com/ghost/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
X-Ghost-Version: 2.14 (ive upgrade in the meantime, problem still persists)
X-Requested-With: XMLHttpRequest
```
response:
```
{"errors":[{"message":"Please sign in or authenticate with an API Key","errorType":"NoPermissionError"}]}
```
it works for the second call after i am logged in
![image](https://user-images.githubusercontent.com/12105446/52962514-b4efb080-339d-11e9-8fea-c0753b831fd0.png)

**Comment by ErisDS** [comment]
@cl1ent We can see nothing here that looks like a bug in Ghost - it's most likely something to do with your environment. The [forum](https://forum.ghost.org) is the best place to get help with your setup. If it turns out there is a bug, we can always reopen.

**Comment by cl1ent** [comment]
i honestly don't know what the problem was. exporting the database as .json, deleting the database and importing the json helped tough. it just killed some excerpts and the contents of one post but that's okay to fix. is the import/export a experimental feature?

**Comment by kirrg001** [comment]
> is the import/export a experimental feature?

Yes, but it should not remove post content. Do you have exact steps to reproduce for me?
