### ISSUE TITLE
Internal Server Error after creating an invite for a recently deleted user

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#10539]
### To Reproduce

1. Delete a user via the Staff screen (taking a note of their email address)
2. Create an invite using the same e-mail address
3. Note the generic "Internal server error" message
4. Refresh the admin and you can see that the invite was actually created although no e-mail was sent

```
INFO [2019-02-26 04:10:34] "DELETE /ghost/api/v2/admin/users/5c74bac46a797d14d8136697/" 204 120ms
INFO [2019-02-26 04:10:34] "GET /ghost/api/v2/admin/invites/?limit=all" 200 64ms
INFO [2019-02-26 04:10:34] "GET /ghost/api/v2/admin/users/?limit=all&include=roles" 200 90ms
INFO [2019-02-26 04:10:36] "GET /ghost/api/v2/admin/roles/?permissions=assign" 200 71ms
INFO [2019-02-26 04:10:44] "GET /ghost/api/v2/admin/users/?include=roles" 200 90ms
INFO [2019-02-26 04:10:44] "GET /ghost/api/v2/admin/invites/" 200 92ms
INFO [2019-02-26 04:10:44] "GET /ghost/api/v2/admin/invites/" 200 76ms
INFO [2019-02-26 04:10:44] "GET /ghost/api/v2/admin/users/?include=roles" 200 88ms
ERROR [2019-02-26 04:10:45] "POST /ghost/api/v2/admin/invites/" 500 523ms

NAME: InternalServerError
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/Users/kevinansfield/code/ghost/Ghost/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/Users/kevinansfield/code/ghost/Ghost/core/server/web/shared/middlewares/error-handler.js:43:19)
    at Layer.handle_error (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:275:10)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:635:15
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:260:14)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/route.js:127:14)
    at apiImpl.then.then.catch (/Users/kevinansfield/code/ghost/Ghost/core/server/api/shared/http.js:84:17)
```

### Technical details:

* Ghost Version: master
* Node Version: 10.15.1
* Database: MySQL

**Comment by kirrg001** [comment]
Can't reproduce 🤔
