### ISSUE TITLE
Unexpected field when uploading theme

### ISSUE THREAD

**Issue by mceachen** [TryGhost/Ghost#10545]
### Issue Summary

Ghost 2.14.3 imports the [atilla](https://github.com/zutrinken/attila) theme successfully. 

Ghost 2.16.1 fails to import the theme, failing with "Unexpected field".

Here's the stacktrace from the error log:

```
InternalServerError: Unexpected field
    at new GhostError (/var/www/blog/versions/2.16.1/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/var/www/blog/versions/2.16.1/core/server/web/shared/middlewares/error-handler.js:43:19)
    at Layer.handle_error (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/var/www/blog/versions/2.16.1/node_modules/express/lib/router/layer.js:67:12)

MulterError: Unexpected field
    at wrappedFileFilter (/var/www/blog/versions/2.16.1/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/var/www/blog/versions/2.16.1/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:147:13)
    at Busboy.emit (events.js:224:7)
    at Busboy.emit (/var/www/blog/versions/2.16.1/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/var/www/blog/versions/2.16.1/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:116:13)
    at PartStream.emit (events.js:211:7)
    at HeaderParser.<anonymous> (/var/www/blog/versions/2.16.1/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:116:13)
    at HeaderParser.emit (events.js:211:7)
    at HeaderParser._finish (/var/www/blog/versions/2.16.1/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/var/www/blog/versions/2.16.1/node_modules/dicer/lib/HeaderParser.js:40:12)
    at emitMany (events.js:147:13)
    at SBMH.emit (events.js:224:7)
    at SBMH._sbmh_feed (/var/www/blog/versions/2.16.1/node_modules/streamsearch/lib/sbmh.js:159:14)
```

### Technical details:

* Ghost Version: `2.14.3` & `2.16.1`
* Node Version: `v8.15.0`
* Browser/OS: n/a
* Database: `mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper`

**Comment by kirrg001** [comment]
Can confirm. Theme upload is broken. Admin Client sends wrong field name.

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/commit/5b484cb586b5b9174cd059f7e03d3d2f9190c77c.

**2.16.2** is on the way 🚀

**Comment by kirrg001** [comment]
[2.16.2](https://github.com/TryGhost/Ghost/releases/tag/2.16.2) was released.

@mceachen Thanks for your quick report 👍

**Comment by mceachen** [comment]
This isn't the first time the theme uploading has broken, perhaps an integration test could be added?

Thanks for the fast update!
