### ISSUE TITLE
Update to 2.16.2 causes loss of functionality re: email (invites/test) 500 errors

### ISSUE THREAD

**Issue by shadowbottle** [TryGhost/Ghost#10563]
### Issue Summary
Update to 2.16.2 causes loss of functionality re: email (invites/test, nodemailer, default email setup)

### To Reproduce

1. ghost-cli... ghost update (previous 2.15)
2. Update successful (the output from update is longer than usual, see below)
3. Attempt to send an invite using any role results in red bar indicating an error in sending email and generic 500 error message in log (log output also below).
or
4. Use Labs >> Test email. Results in identical error log.

This had been working fine in 2.15. There have been no configuration changes, and this is now happening on a parallel install of Ghost on a subdomain I have (happening @ domain.com and sub.domain.com) after updating to 2.16.2 from 2.15.

Update output, domain has been removed, replaced with [*domain*]:
```
$ ghost upgrade
+ sudo systemctl is-active ghost_[*domain*]-org
? Sudo Password [hidden]
✔ Checking system Node.js version
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking for available migrations
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v2.16.2
+ sudo systemctl is-active ghost_[*domain*]-org
+ sudo systemctl stop ghost_[*domain*]-org
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
+ sudo systemctl is-active ghost_[*domain*]-org
☱ Stopping Ghost✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
☲ Restarting Ghost✔ Checking current folder permissions
+ sudo systemctl is-active ghost_[*domain*]-org
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
+ sudo systemctl start ghost_[*domain*]-org
✔ Restarting Ghost
✔ Removing old Ghost versions
```

Log output, machine name removed, replaced with [*machine*]:

```
[2019-03-04 20:52:50] ERROR "POST /ghost/api/v2/admin/mail/test/" 500 837ms

NAME: EmailError
MESSAGE: Failed to send email.

level: normal

"Please see https://docs.ghost.org/mail/ for instructions on configuring email."
EmailError: Failed to send email.
    at EmailError.GhostError (/var/www/[*machine*]/versions/2.16.2/core/server/lib/common/errors.js:10:26)
    at new EmailError (/var/www/[*machine*]/versions/2.16.2/core/server/lib/common/errors.js:34:20)
    at EventEmitter.<anonymous> (/var/www/[*machine*]/versions/2.16.2/core/server/services/mail/GhostMailer.js:93:31)
    at Object.onceWrapper (events.js:277:13)
    at EventEmitter.emit (events.js:189:13)
    at EventEmitter.emit (domain.js:441:20)
    at DirectMailer.<anonymous> (/var/www/[*machine*]/versions/2.16.2/node_modules/directmail/lib/mailer.js:174:38)
    at SMTPClient.<anonymous> (/var/www/[*machine*]/versions/2.16.2/node_modules/directmail/lib/mailer.js:292:13)
    at Object.onceWrapper (events.js:277:13)
    at SMTPClient.emit (events.js:189:13)
    at SMTPClient.EventEmitter.emit (domain.js:441:20)
    at SMTPClient._destroy (/var/www/[*machine*]/versions/2.16.2/node_modules/simplesmtp/lib/client.js:310:10)
    at SMTPClient._onEnd (/var/www/[*machine*]/versions/2.16.2/node_modules/simplesmtp/lib/client.js:410:10)
    at Socket.emit (events.js:194:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
```

### Technical details:
*Ghost blog hosted on primary domain (I host one on subdomain as well and both are generating 500s with email now)
*Ubuntu Bionic 18.04.2 LTS
* Ghost Version: Ghost-CLI version: 1.9.9
Ghost version: 2.16.2
* Node Version: v10.15.2
* Browser/OS: Any
* Database: mysql

**Comment by kevinansfield** [comment]
Hi @shadowbottle 👋 Ghost hasn't changed anything to do with mail between 2.15 and 2.16.x. From the log you've shown it starts with an `endReadableNT` error which suggests that whatever mail service Ghost is trying to talk to has hung up or otherwise killed the connection.

I'm going to mark this as a support request which are handled on our [forum](https://forum.ghost.org) rather than here on GitHub. If after getting support/investigating there is a clear indication of a bug then we can re-open.
