### ISSUE TITLE
Oembed parser: optimise catch handler

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10624]
We saw a couple of errors coming from oembed API:

```
ERROR [2019-03-20 08:02:50] "GET /ghost/api/v2/admin/oembed/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dfywf4AMrSK8" 500 336ms

invalid json response body at 
https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dfywf4AMrSK8 

reason: Unexpected token U in JSON at position 0
----------------------------------------
```

Example:

```
> parser.extract('https://www.youtube.com/oembed?format=json&url=http://youtube.com/test').catch((err) => {console.log(err);})
> { FetchError: invalid json response body at https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Foembed%3Fformat%3Djson%26url%3Dhttp%3A%2F%2Fyoutube.com%2Ftest reason: Unexpected token N in JSON at position 0
    at /Users/kirrg001/dev/ghost/ghost-workspace2/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Foembed%3Fformat%3Djson%26url%3Dhttp%3A%2F%2Fyoutube.com%2Ftest reason: Unexpected token N in JSON at position 0',
  type: 'invalid-json' }
```

Youtube response is **'Not Found'**.

This needs catching & handling and maybe reporting to oemed-parser.

Ghost: master

**Comment by jbfriedrich** [comment]
I just encountered this problem today. It seems to be the same issue:
```
"err": {
    "code": null,
    "domain": "https://mydomain.tld",
    "id": "95093690-a7bc-11e9-8a98-bdc933ed02ad",
    "level": "critical",
    "message": "invalid json response body at https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dcc-elFcs96Y reason: Unexpected token U in JSON at position 0",
    "name": "InternalServerError",
    "stack": "InternalServerError: invalid json response body at https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dcc-elFcs96Y reason: Unexpected token U in JSON at position 0\n    at new InternalServerError (/var/www/ghost/versions/2.25.7/node_modules/ghost-ignition/lib/errors/index.js:77:23)\n    at extract.catch (/var/www/ghost/versions/2.25.7/core/server/api/v2/oembed.js:62:43)\n    at tryCatcher (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:695:18)\n    at _drainQueueStep (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
    "statusCode": 500
  },
```
I have opened [issue#39](https://github.com/ndaidong/oembed-parser/issues/39) with the oembed-parser project.
