### ISSUE TITLE
Upgrade to 2.x failed with knex  error: `client` is missing

### ISSUE THREAD

**Issue by TonnyXu** [TryGhost/Ghost#10630]
before reporting this issue, I've tried https://forum.ghost.org, but had no luck on this issue.

### Issue Summary

upgrade ghost from 1x to 2x failed with error:
> knex: Required configuration option 'client' is missing.

### To Reproduce

1. install ghost 1.25.7 in ubuntu 16.04 LTS in vagrant
2. run CLI command: `ghost update`

got the error:
> ✖ Updating to a major version
> An error occurred.
> Message: 'knex: Required configuration option 'client' is missing.'

### Technical details:

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v10.15.3
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost update --force'
    Database: MySQL version: 5.7.25-0ubuntu0.16.04.2 (Ubuntu)
    OS: Linux ubuntu-xenial 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Log file

```
Stack: Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/vagrant/ghost/versions/2.18.2/node_modules/knex/lib/client.js:110:11)
    at Knex (/home/vagrant/ghost/versions/2.18.2/node_modules/knex/lib/index.js:60:34)
    at getData (/usr/lib/node_modules/ghost-cli/lib/tasks/major-update/data.js:25:24)
    at Task.ui [as task] (/usr/lib/node_modules/ghost-cli/lib/tasks/major-update/ui.js:36:12)
    at Promise.resolve.then.then.skipped (/usr/lib/node_modules/ghost-cli/node_modules/listr/lib/task.js:167:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### What I've tried

* I've tried different node version, no luck
* I've tried update to different versions(2.0.0 ~ 2.18.2), no luck 

Please help me with this. 

Best regards.

**Comment by TonnyXu** [comment]
actually, I think it's a bug, so I reported as a bug. I did write as *please help me*, I realized that it's inappropriate, I've removed it. Leave it as pure bug report.

Also, I retried with clean install(new vagrant instance, new installation, new migration from 1x), it worked again.

So, it's not so reproducible, it's OK to close this.
