### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full.

### ISSUE THREAD

**Issue by simonbernard** [TryGhost/Ghost#10697]
### Issue Summary

I'm getting the following error around once in two weeks:

```
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /var/lib/ghost/versions/2.16.4/node_modules/knex/lib/client.js:340:13
    at tryCatcher (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/util.js:16:23)
    at /var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

I'm using Ghost 2.16.4 in the docker image from here: `https://hub.docker.com/_/ghost/` in standard database configuration (= SQLite). As said, the error occurs approx every 2 weeks. I am running multiple containers on one host. When the error occurs, quite a lot of them have the same problem. Restarting the container does not help, I have to restart the host.

Ghost does not recover by itself.

### To Reproduce

I don't know if a specific request is causing the problem. 

### Technical details:

* Ghost Version: 2.16.4
* Node Version: v8.15.1
* Browser/OS: on Mac, Firefox (but seems irrelevant)
* Database: SQLite3

Any help is greatly appreciated! Can I help out with any other information?
Thanks a lot!

**Comment by rishabhgrg** [comment]
Hey @simonbernard, the issue seems to be more specific to the particular docker setup and our Forum would be a right place to discuss a solution for it. If it turns out a specific issue in Ghost leading up to this, will be happy to reopen the issue here with more specific details. 😄 Thanks.

**Comment by mikeinboxlab** [comment]
@simonbernard we are running into this same issue on Heroku. Were you able to find the cause and solution?

**Comment by couchsoft** [comment]
@mikeinboxlab sorry, the issue just disappeared in my setup. Are you still running on 2.16? Maybe an update could help?
