### ISSUE TITLE
Sign-in Unknown Error

### ISSUE THREAD

**Issue by mariodian** [TryGhost/Ghost#10711]
I've recently updated to 2.21.0 and when I try to login to the administration `/ghost/api/v2/admin/session` throws `500 Internal Server Error` and there's also a red error message below the login box that says "Unknown error".

The server error log looks like this:

```
{  
   "name":"Log",
   "hostname":"<some hostname>",
   "pid":5385,
   "level":50,
   "req":{  
      "meta":{  
         "requestId":"284de190-67f2-11e9-a883-7b883ea92efa",
         "userId":null
      },
      "url":"/session",
      "method":"POST",
      "originalUrl":"/ghost/api/v2/admin/session",
      "params":{  

      },
      "headers":{  
         "host":"<some server>",
         "pragma":"no-cache",
         "cache-control":"no-cache",
         "origin":"https://<some server>",
         "app-pragma":"no-cache",
         "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
         "content-type":"application/json;charset=UTF-8",
         "accept":"text/plain, */*; q=0.01",
         "x-requested-with":"XMLHttpRequest",
         "x-ghost-version":"2.21",
         "referer":"https://<some server>/ghost/",
         "accept-encoding":"gzip, deflate, br",
         "accept-language":"en-US,en;q=0.9",
         "cookie":"**REDACTED**",
         "x-forwarded-proto":"https",
         "x-forwarded-for":"<some IP>",
         "x-forwarded-host":"<some server>",
         "x-forwarded-server":"<some server>",
         "connection":"Keep-Alive",
         "content-length":"68"
      },
      "query":{  

      }
   },
   "res":{  
      "_headers":{  
         "x-powered-by":"Express",
         "cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0",
         "content-type":"application/json; charset=utf-8",
         "content-length":"199",
         "etag":"W/\"c7-gS2eEoof/W3Ts73h5yBSlQyo5Vo\"",
         "vary":"Accept-Encoding"
      },
      "statusCode":500,
      "responseTime":"12ms"
   },
   "err":{  
      "id":"284f8f40-67f2-11e9-a883-7b883ea92efa",
      "domain":"https://<some server>",
      "code":"ER_BAD_FIELD_ERROR",
      "name":"InternalServerError",
      "statusCode":500,
      "level":"critical",
      "message":"Unknown error",
      "stack":"InternalServerError: Unknown error\n    at new InternalServerError (<some path>/versions/2.21.0/node_modules/ghost-ignition/lib/errors/index.js:77:23)\n    at Object.handleStoreError (<some path>/versions/2.21.0/core/server/web/shared/middlewares/api/spam-prevention.js:27:25)\n    at module.exports.<anonymous> (<some path>/versions/2.21.0/node_modules/express-brute/index.js:133:21)\n    at tryCatcher (<some path>/versions/2.21.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise.errorAdapter (<some path>/versions/2.21.0/node_modules/bluebird/js/release/nodeify.js:35:34)\n    at Promise._settlePromise (<some path>/versions/2.21.0/node_modules/bluebird/js/release/promise.js:566:21)\n    at Promise._settlePromise0 (<some path>/versions/2.21.0/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (<some path>/versions/2.21.0/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (<some path>/versions/2.21.0/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (<some path>/versions/2.21.0/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (<some path>/versions/2.21.0/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (<some path>/versions/2.21.0/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:120:23)\n\nError: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'\n    at Query.Sequence._packetToError (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (<some path>/versions/2.21.0/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (<some path>/versions/2.21.0/node_modules/mysql/lib/Connection.js:502:10)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (<some path>/versions/2.21.0/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (<some path>/versions/2.21.0/node_modules/mysql/lib/Connection.js:200:25)\n    at <some path>/versions/2.21.0/node_modules/knex/lib/dialects/mysql/index.js:161:18\n    at Promise._execute (<some path>/versions/2.21.0/node_modules/bluebird/js/release/debuggability.js:313:9)\n    at Promise._resolveFromExecutor (<some path>/versions/2.21.0/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (<some path>/versions/2.21.0/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL._query (<some path>/versions/2.21.0/node_modules/knex/lib/dialects/mysql/index.js:155:12)\n    at Client_MySQL.query (<some path>/versions/2.21.0/node_modules/knex/lib/client.js:206:17)\n    at <some path>/versions/2.21.0/node_modules/knex/lib/transaction.js:278:21\n    at tryCatcher (<some path>/versions/2.21.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (<some path>/versions/2.21.0/node_modules/bluebird/js/release/method.js:39:29)\n    at Client_MySQL.trxClient.query (<some path>/versions/2.21.0/node_modules/knex/lib/transaction.js:275:34)\n    at Runner.<anonymous> (<some path>/versions/2.21.0/node_modules/knex/lib/runner.js:155:36)\n    at Runner.tryCatcher (<some path>/versions/2.21.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Runner.query (<some path>/versions/2.21.0/node_modules/bluebird/js/release/method.js:15:34)\n    at <some path>/versions/2.21.0/node_modules/knex/lib/runner.js:61:21"
   },
   "msg":"Unknown error",
   "time":"2019-04-26T07:08:56.758Z",
   "v":0
}
```

Running Ghost with MySQL and Apache2 proxy.

My specs:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ apachectl -v
Server version: Apache/2.4.39 (Ubuntu)
Server built:   2019-04-02T20:30:26

$ mysql -V
mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Also, not sure if related, but I've manually deleted all the rows in the `sessions` table.

**Comment by mariodian** [comment]
I must have manually broken something. Please ignore.
