### ISSUE TITLE
Can't login to admin panel when ghost in subfolder

### ISSUE THREAD

**Issue by lordkada** [TryGhost/Ghost#10751]
Hi, I am trying to publish ghost behind nginx and served in a subfolder, but I am having problems when I need to login to the control panel. I am running ghost@2.22.1.

**BUT** if I downgrade to ghost to 2.2.0 (same configuration) everything works as expected.

Here some more details.

# Configurations

## config.json

"url" : "https://myhost.mydomain/blog"

## My nginx configuration

 ```
location ~/blog(/.*)  {
          proxy_pass http://127.0.0.1:2999$1;
          proxy_redirect off;
          proxy_set_header Host myhost.mydomain;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
    }

```

# Errors

The first thing I noticed when I open the login page is this error in the app logs ```Cannot read property 'origin' of undefined```:

```
2019-05-20T14:35:52.803591+00:00 app[web.1]: 
2019-05-20T14:35:52.803594+00:00 app[web.1]: Cannot read property 'origin' of undefined
2019-05-20T14:35:52.803610+00:00 app[web.1]: 
2019-05-20T14:35:52.803613+00:00 app[web.1]: Error ID:
2019-05-20T14:35:52.803614+00:00 app[web.1]: 91d4fef0-7b0c-11e9-a3e0-ad48e19ae3a5
2019-05-20T14:35:52.803616+00:00 app[web.1]: 
2019-05-20T14:35:52.803618+00:00 app[web.1]: ----------------------------------------
2019-05-20T14:35:52.803619+00:00 app[web.1]: 
2019-05-20T14:35:52.803621+00:00 app[web.1]: InternalServerError: Cannot read property 'origin' of undefined
2019-05-20T14:35:52.803623+00:00 app[web.1]: at new GhostError (/app/node_modules/ghost/core/server/lib/common/errors.js:10:26)
2019-05-20T14:35:52.803627+00:00 app[web.1]: at _private.prepareError (/app/node_modules/ghost/core/server/web/shared/middlewares/error-handler.js:43:19)
2019-05-20T14:35:52.803629+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2019-05-20T14:35:52.803630+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
2019-05-20T14:35:52.803632+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2019-05-20T14:35:52.803634+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-05-20T14:35:52.803635+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-05-20T14:35:52.803637+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803639+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
2019-05-20T14:35:52.803640+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2019-05-20T14:35:52.803642+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-05-20T14:35:52.803644+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-05-20T14:35:52.803646+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:635:15
2019-05-20T14:35:52.803648+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:260:14)
2019-05-20T14:35:52.803649+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:127:14)
2019-05-20T14:35:52.803651+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803653+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803654+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803656+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803658+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803659+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803661+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803662+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803664+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803666+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803667+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803669+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:135:13)
2019-05-20T14:35:52.803671+00:00 app[web.1]: at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
2019-05-20T14:35:52.803673+00:00 app[web.1]: 
2019-05-20T14:35:52.803674+00:00 app[web.1]: TypeError: Cannot read property 'origin' of undefined
2019-05-20T14:35:52.803676+00:00 app[web.1]: at cookieCsrfProtection (/app/node_modules/ghost/core/server/services/auth/session/middleware.js:82:22)
2019-05-20T14:35:52.803678+00:00 app[web.1]: at /app/node_modules/ghost/core/server/services/auth/session/middleware.js:112:13
2019-05-20T14:35:52.803680+00:00 app[web.1]: at session (/app/node_modules/express-session/index.js:195:71)
2019-05-20T14:35:52.803681+00:00 app[web.1]: at getSession (/app/node_modules/ghost/core/server/services/auth/session/middleware.js:48:12)
2019-05-20T14:35:52.803683+00:00 app[web.1]: at authenticate (/app/node_modules/ghost/core/server/services/auth/session/middleware.js:106:5)
2019-05-20T14:35:52.803685+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-20T14:35:52.803686+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2019-05-20T14:35:52.803688+00:00 app[web.1]: at authenticate (/app/node_modules/ghost/core/server/services/auth/api-key/admin.js:42:16)
2019-05-20T14:35:52.803695+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-20T14:35:52.803697+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2019-05-20T14:35:52.803699+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2019-05-20T14:35:52.803700+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-20T14:35:52.803702+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2019-05-20T14:35:52.803704+00:00 app[web.1]: at param (/app/node_modules/express/lib/router/index.js:354:14)
2019-05-20T14:35:52.803705+00:00 app[web.1]: at param (/app/node_modules/express/lib/router/index.js:365:14)
2019-05-20T14:35:52.803707+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
2019-05-20T14:35:52.803708+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-05-20T14:35:52.803710+00:00 app[web.1]: at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
2019-05-20T14:35:52.803712+00:00 app[web.1]: at router (/app/node_modules/express/lib/router/index.js:47:12)
2019-05-20T14:35:52.803719+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-20T14:35:52.803721+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-05-20T14:35:52.803723+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2019-05-20T14:35:52.803725+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-05-20T14:35:52.803726+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-05-20T14:35:52.803728+00:00 app[web.1]: at cacheControlHeaders (/app/node_modules/ghost/core/server/web/shared/middlewares/cache-control.js:32:9)
2019-05-20T14:35:52.803730+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-20T14:35:52.803732+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-05-20T14:35:52.803733+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
```

The login form is correctly displayed, but when I click the "sign in" button, I get an error and the server badly crashes (the post to ".../ghost/api/v2/admin/session" fails):

```
2019-05-20T14:39:22.249711+00:00 app[web.1]: /app/node_modules/ghost/core/server/services/auth/session/middleware.js:62
2019-05-20T14:39:22.250048+00:00 app[web.1]: req.session.user_id = req.user.id;
2019-05-20T14:39:22.250052+00:00 app[web.1]: ^
2019-05-20T14:39:22.250054+00:00 app[web.1]: 
2019-05-20T14:39:22.250057+00:00 app[web.1]: TypeError: Cannot set property 'user_id' of undefined
2019-05-20T14:39:22.250061+00:00 app[web.1]: at /app/node_modules/ghost/core/server/services/auth/session/middleware.js:62:29
2019-05-20T14:39:22.250063+00:00 app[web.1]: at session (/app/node_modules/express-session/index.js:195:71)
2019-05-20T14:39:22.250065+00:00 app[web.1]: at getSession (/app/node_modules/ghost/core/server/services/auth/session/middleware.js:48:12)
2019-05-20T14:39:22.250067+00:00 app[web.1]: at Object.createSession (/app/node_modules/ghost/core/server/services/auth/session/middleware.js:52:5)
2019-05-20T14:39:22.250069+00:00 app[web.1]: at /app/node_modules/ghost/core/server/api/v2/session.js:33:34
2019-05-20T14:39:22.250070+00:00 app[web.1]: at /app/node_modules/express-brute/index.js:60:9
2019-05-20T14:39:22.250072+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:61:11)
2019-05-20T14:39:22.258046+00:00 app[web.1]: 2019/05/20 14:39:22 [error] 104#0: *40 upstream prematurely closed connection while reading response header from upstream, client: 10.5.219.194, server: , request: "POST /blog/ghost/api/v2/admin/session HTTP/1.1", upstream: "http://127.0.0.1:2999/ghost/api/v2/admin/session", host: "stemawards-ghost.herokuapp.com", referrer: "https://stemawards-ghost.herokuapp.com/blog/ghost/"
2019-05-20T14:39:22.259445+00:00 app[web.1]: measure#nginx.service=0.362 request_id=6d79fc69-3eec-424b-af51-d06ab4d821ef
2019-05-20T14:39:22.262005+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-05-20T14:39:22.262368+00:00 app[web.1]: npm ERR! errno 1
2019-05-20T14:39:22.263801+00:00 app[web.1]: npm ERR! ghost-on-heroku@1.25.5 start: `node server.js`
2019-05-20T14:39:22.264046+00:00 app[web.1]: npm ERR! Exit status 1
2019-05-20T14:39:22.264321+00:00 app[web.1]: npm ERR!
2019-05-20T14:39:22.264543+00:00 app[web.1]: npm ERR! Failed at the ghost-on-heroku@1.25.5 start script.
2019-05-20T14:39:22.264783+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-20T14:39:22.269895+00:00 app[web.1]: 
2019-05-20T14:39:22.270113+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-05-20T14:39:22.270307+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-05-20T14_39_22_266Z-debug.log
2019-05-20T14:39:22.274629+00:00 app[web.1]: buildpack=nginx at=exit process=app
2019-05-20T14:39:22.339125+00:00 heroku[web.1]: State changed from up to crashed
```

Any idea?

**Comment by lordkada** [comment]
Assuming I don't know ghost and its architecture, I have peeked the code (middleware.js) and I think there're some weaknesses.

Look at this piece of code (rows [111](https://github.com/TryGhost/Ghost/blob/53b884ec2bdc126e98d6e7fca07a4699594fa702/core/server/services/auth/session/middleware.js#L111) and following):
```
        try {
            cookieCsrfProtection(req);
        } catch (err) {
            return next(err);
        }

        if (!req.session || !req.session.user_id) {
            req.user = null;
            return next();
        }
```

If you look at the cookieCsrfProtection() implementation, you see
```
const cookieCsrfProtection = (req) => {
    // If there is no origin on the session object it means this is a *new*
    // session, that hasn't been initialised yet. So we don't need CSRF protection
    if (!req.session.origin) {
        return;
    }
```

Shouldn't be better something like: `if (!req.session || !req.session.origin)`, like we have few rows after the invoking method in the initial snippet?

**Comment by allouis** [comment]
Hey @lordkada!

When `req.session` is undefined, it (usually) means that the `express-session` middleware couldn't match the current path with the path passed in (https://github.com/expressjs/session/blob/master/index.js#L194-L196)

Can you double check your config is loaded correctly, and maybe look at the output of this line: https://github.com/TryGhost/Ghost/blob/53b884ec2bdc126e98d6e7fca07a4699594fa702/core/server/services/auth/session/middleware.js#L42

As for explicitly checking `req.session` that might be a good idea, but I don't think it will fix anything, it will just silently continue as if there were no session. A better error message might be more helpful though :+1:

**Comment by lordkada** [comment]
A little update: I have tried to run both nginx & ghost locally and it works... 
It seems to be more related to my "production" environment (Heroku) and the way nginx talks to the ghost instance (proxy pass through https)!?!?
Need to investigate more...

**Comment by lordkada** [comment]
It definitively looks something related to my Heroku deployment... (nginx subfolder location/proxy_pass to ghost over ssl).

I think you may close this issue. 
Thank you for your support :-)

**Comment by allouis** [comment]
Thanks for the update @lordkada :relaxed: I'm gonna close this now (as I think it is specific to heroku), if you have more problems, open an issue and ping me, I'll do my best to help :ghost:

**Comment by Egrace** [comment]
@lordkada I have the same issue as you. If you are interested, my nginx setup is here: https://github.com/TryGhost/Ghost/issues/9982
Have you found a solution?

**Comment by Egrace** [comment]
I can't understand why simple html GET requests work fine but XHR requests to blog/ghost/api/v2/admin/users/me/?include=roles fails with undefined session.

**Comment by lordkada** [comment]
@Egrace unfortunately not. At the end I gave up and I am now serving the blog using a third level domain :-(

**Comment by kaiomagalhaes** [comment]
@egracens did you happen to have found a solution? I'm facing the same issue here

**Comment by egracens** [comment]
No, I have not solved it.
