### ISSUE TITLE
Setup breaks on MySQL setup

### ISSUE THREAD

**Issue by timscha** [TryGhost/Ghost#10761]
### Issue Summary

On a new setup of Ghost I got the following error.
```
Message: ER_ACCESS_DENIED_ERROR: Access denied for user 'ghost_dailytim'@'127.0.0.1' (using password: YES)
Help: Unknown database error
Suggestion: journalctl -u ghost_undefined -n 50

Debug Information:
    OS: Debian, v9.9
    Node Version: v10.15.3
    Ghost-CLI Version: 1.10.0
    Environment: production
    Command: 'ghost install'

Additional log info available in: /home/ghost-blogs/.ghost/logs/ghost-cli-debug-2019-05-27T20_12_05_977Z.log
```
I can confirm that the login details for the database are correct as I tried them on the terminal with the provided user details.

Logfile looks like this:

```
➜  htdocs journalctl -u ghost_undefined -n 50
-- Logs begin at Sat 2019-05-25 18:42:51 CEST, end at Mon 2019-05-27 22:13:09 CEST. --
May 27 22:12:04 hive node[18828]:     at _drainQueue (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/async.js:131:9)
May 27 22:12:04 hive node[18828]:     at Async._drainQueues (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/async.js:147:5)
May 27 22:12:04 hive node[18828]:     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/async.js:17:14)
May 27 22:12:04 hive node[18828]:     at runCallback (timers.js:705:18)
May 27 22:12:04 hive node[18828]:     at tryOnImmediate (timers.js:676:5)
May 27 22:12:04 hive node[18828]:     at processImmediate (timers.js:658:5)
May 27 22:12:04 hive node[18828]: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'ghost_dailytim'@'127.0.0.1' (using password: YES)
May 27 22:12:04 hive node[18828]:     at Handshake.Sequence._packetToError (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
May 27 22:12:04 hive node[18828]:     at Handshake.ErrorPacket (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
May 27 22:12:04 hive node[18828]:     at Protocol._parsePacket (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/Protocol.js:278:23)
May 27 22:12:04 hive node[18828]:     at Parser.write (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/Parser.js:76:12)
May 27 22:12:04 hive node[18828]:     at Protocol.write (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/Protocol.js:38:16)
May 27 22:12:04 hive node[18828]:     at Socket.<anonymous> (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/Connection.js:91:28)
May 27 22:12:04 hive node[18828]:     at Socket.<anonymous> (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/Connection.js:502:10)
May 27 22:12:04 hive node[18828]:     at Socket.emit (events.js:189:13)
May 27 22:12:04 hive node[18828]:     at addChunk (_stream_readable.js:284:12)
May 27 22:12:04 hive node[18828]:     at readableAddChunk (_stream_readable.js:265:11)
May 27 22:12:04 hive node[18828]:     at Socket.Readable.push (_stream_readable.js:220:10)
May 27 22:12:04 hive node[18828]:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
May 27 22:12:04 hive node[18828]:     --------------------
May 27 22:12:04 hive node[18828]:     at Protocol._enqueue (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/Protocol.js:144:48)
May 27 22:12:04 hive node[18828]:     at Protocol.handshake (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/protocol/Protocol.js:51:23)
May 27 22:12:04 hive node[18828]:     at Connection.connect (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/mysql/lib/Connection.js:118:18)
May 27 22:12:04 hive systemd[1]: Stopping Ghost systemd service for blog:...
May 27 22:12:04 hive node[18828]:     at _bluebird.default (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:82:18)
May 27 22:12:04 hive node[18828]:     at Promise._execute (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/debuggability.js:313:9)
May 27 22:12:04 hive node[18828]:     at Promise._resolveFromExecutor (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/promise.js:483:18)
May 27 22:12:04 hive node[18828]:     at new Promise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/promise.js:79:10)
May 27 22:12:04 hive node[18828]:     at Client_MySQL.acquireRawConnection (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:77:12
May 27 22:12:04 hive node[18828]:     at create (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/knex-migrator/node_modules/knex/lib/client.js:282:21)
May 27 22:12:04 hive node[18828]:     at tryPromise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/tarn/lib/Pool.js:366:22)
May 27 22:12:04 hive node[18828]:     at tryPromise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/tarn/lib/utils.js:57:20)
May 27 22:12:04 hive node[18828]:     at Promise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/tarn/lib/Pool.js:366:5)
May 27 22:12:04 hive node[18828]:     at Promise._execute (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/debuggability.js:313:9)
May 27 22:12:04 hive node[18828]:     at Promise._resolveFromExecutor (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/promise.js:483:18)
May 27 22:12:04 hive node[18828]:     at new Promise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/bluebird/js/release/promise.js:79:10)
May 27 22:12:04 hive node[18828]:     at callbackOrPromise (/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/node_modules/tarn/lib/Pool.js:357:10)
May 27 22:12:04 hive node[18828]:
May 27 22:12:04 hive node[18828]: events.js:174
May 27 22:12:04 hive node[18828]:       throw er; // Unhandled 'error' event
May 27 22:12:04 hive node[18828]:       ^
May 27 22:12:04 hive node[18828]: Error: EACCES: permission denied, open '/var/www/gb-dailytim-prod/htdocs/versions/2.23.0/content/logs/https___dailytim_de_production.error.log'
May 27 22:12:04 hive node[18828]: Emitted 'error' event at:
May 27 22:12:04 hive node[18828]:     at lazyFs.open (internal/fs/streams.js:272:12)
May 27 22:12:04 hive node[18828]:     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
May 27 22:12:05 hive node[18828]: /usr/lib/node_modules/ghost-cli/lib/process-manager.js:58
May 27 22:12:05 hive systemd[1]: ghost_undefined.service: Main process exited, code=exited, status=1/FAILURE
May 27 22:12:05 hive systemd[1]: Stopped Ghost systemd service for blog:.
```

### To Reproduce

1. Setup ghost dir and user
2. start ghost install, enter all details

### Technical details:

* Ghost Version: 2.23.0
* Node Version: 10.15.3
* Browser/OS: Chrome
* Database: MariaDB 10.3

**Comment by bird-in-hat** [comment]
Same for me.
Works when i override ENV database__connection__password for Docker, like 
`docker run -it -e database__connection__password="pass" container`
Strange.
