### ISSUE TITLE
Scheduling cause an InternalServerError

### ISSUE THREAD

**Issue by kaminskypavel** [TryGhost/Ghost#11145]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

**Hi Team!**
we've recently upgraded to 2.31 (and we love it)
our stack is using nginx (as a reverse proxy) on the server and we're runing ghost from it's official [docker image](https://hub.docker.com/_/ghost/)

everything is working great except the scheduling option which yield the following logs  

```
_Error ID:
    cafae0d0-dad1-11e9-b54c-dde50bb34d18

----------------------------------------

InternalServerError: The server has encountered an error.
    at new GhostError (/var/lib/ghost/versions/2.31.0/core/server/lib/common/errors.js:10:26)
    at request.catch (/var/lib/ghost/versions/2.31.0/core/server/adapters/scheduling/SchedulingDefault.js:349:30)
    at tryCatcher (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/2.31.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

HTTPError: Response code 301 (Moved Permanently)
    at EventEmitter.emitter.on (/var/lib/ghost/versions/2.31.0/node_modules/got/source/as-pro_
```

the nginx logs show also this call 
```logs
nginx.1    | <my site> 172.17.0.1 - - [20/Sep/2019:23:18:59 +0000] "PUT /ghost/api/v0.1/schedules/posts/5d85573bd59d65000127d103?client_id=ghost-scheduler&client_secret=<my secret> HTTP/1.1" 301 178 "-" "Ghost/2.31.0 (https://github.com/TryGhost/Ghost)"
```
also accessing the resource manually (with a browser) yield :
```json
{
"errors": [
{
"message": "Resource not found",
"errorType": "NotFoundError"
}
]
}
```
### To Reproduce

1. install ghost with docker 
```bash 
docker run -d --name my-ghost \
                        --restart always \
                        -p 3002:2368 \
                        -e 'VIRTUAL_HOST=<my domain>' \
                        -e 'VIRTUAL_PORT=3002' \
                        -e 'NODE_ENV=production' \
                        -e 'url=<my url>' \
                        ghost:2.31.0-alpine
```

2. configure nginx
```
    server {
        server_name         <your domain>;
        listen              80;
        location / {
            proxy_pass http://localhost:3002/;
        }
    }
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 2.31.0
* Node Version: v6.11.2
* Browser/OS: - 
* Database: SQLite Database

**Comment by kaminskypavel** [comment]
@kevinansfield , sorry I wasn't sure if it's a support request or a possible bug.
