### ISSUE TITLE
Restart after the upgrade is complete

### ISSUE THREAD

**Issue by QingShui23** [TryGhost/Ghost#11199]
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.15.0
    Ghost-CLI Version: 1.11.0
    Environment: production
    Command: 'ghost update'
Message: Could not communicate with Ghost
Suggestion: journalctl -u ghost_www-4zen-top -n 50
Stack: Error: Could not communicate with Ghost
    at Server.server.close (/usr/local/lib/node_modules/ghost-cli/lib/utils/port-polling.js:56:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1664:8)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by QingShui23** [comment]
ubuntu@VM-98-64-ubuntu:/var/www/ghost$ journalctl -u ghost_www-4zen-top -n 50
-- Logs begin at Fri 2019-10-04 11:30:25 CST, end at Fri 2019-10-04 11:40:38 CST. --
Oct 04 11:34:26 VM-98-64-ubuntu systemd[1]: Stopped Ghost systemd service for blog: www-4zen-top.
Oct 04 11:34:26 VM-98-64-ubuntu systemd[1]: Started Ghost systemd service for blog: www-4zen-top.
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]: /var/www/ghost/versions/2.31.1/node_modules/knex/lib/client.js:258
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:         return this.acquireRawConnection().then(async (connection) => {
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:                                                       ^
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]: SyntaxError: Unexpected token (
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at createScript (vm.js:56:10)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Object.runInThisContext (vm.js:97:10)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module._compile (module.js:549:28)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Object.Module._extensions..js (module.js:586:10)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module.load (module.js:494:32)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at tryModuleLoad (module.js:453:12)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Function.Module._load (module.js:445:3)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module.require (module.js:504:17)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at require (internal/module.js:20:19)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Object.<anonymous> (/var/www/ghost/versions/2.31.1/node_modules/knex/lib/knex.js:2:16)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module._compile (module.js:577:32)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Object.Module._extensions..js (module.js:586:10)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module.load (module.js:494:32)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at tryModuleLoad (module.js:453:12)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Function.Module._load (module.js:445:3)
Oct 04 11:34:27 VM-98-64-ubuntu node[3469]:     at Module.require (module.js:504:17)

**Comment by QingShui23** [comment]
i tryed run 'ghost setup systemd' fix it， 
result is good, it fixed now
