### ISSUE TITLE
Migration errror upgrading from 2.37.0 to 3.0.2

### ISSUE THREAD

**Issue by simonbernard** [TryGhost/Ghost#11350]
I have a problem upgrading my blog from v2.37.0 to the new v3.0.2. I am using SQLite as database backend.

Here is the message I got:

```
[2019-11-07 06:55:15] ERROR Cannot read property '1' of null
 Cannot read property '1' of null
 {"config":{"transaction":true},"name":"01-remove-user-ghost-auth-columns.js"}
"Error occurred while executing the following migration: 01-remove-user-ghost-auth-columns.js"
 Error ID:
     300
----------------------------------------
 MigrationScriptError: Cannot read property '1' of null
     at MigrationScriptError.KnexMigrateError (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/lib/errors.js:7:26)
     at new MigrationScriptError (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/lib/errors.js:25:26)
     at /var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/lib/index.js:1053:19
     at tryCatcher (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:547:31)
     at Promise._settlePromise (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:604:18)
     at Promise._settlePromise0 (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:649:10)
     at Promise._settlePromises (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:725:18)
     at _drainQueueStep (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:93:12)
     at _drainQueue (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:86:9)
     at Async._drainQueues (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:102:5)
     at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:15:14)
     at runCallback (timers.js:705:18)
     at tryOnImmediate (timers.js:676:5)
     at processImmediate (timers.js:658:5)
     at process.topLevelDomainCallback (domain.js:126:23)
 TypeError: Cannot read property '1' of null
     at SQLite3_DDL._doReplace (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:103:30)
     at columns.forEach.column (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:243:25)
     at Array.forEach (<anonymous>)
 [2019-11-07 06:54:50] ERROR Cannot read property '1' of null
     at SQLite3_DDL.<anonymous> (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:241:17)
     at SQLite3_DDL.tryCatcher (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
 Cannot read property '1' of null
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:547:31)
     at Promise._settlePromise (/var/lib/ghost/versions/3.0.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:604:18)

```

Can I help out with any additional information? Thanks for your support!

**Comment by gargol** [comment]
Hi @simonbernard! I was not able to reproduce this bug on my local instance running `SQLite 3.22.0` on Unbuntu 18.04. From the stack-trace, the closest I was able to narrow it down was the `getTableSql` in the `knex` library:
https://github.com/knex/knex/blob/48d8c7eb59525df47812047f9a30e785f9883633/lib/dialects/sqlite3/schema/ddl.js#L54-L64

But from function names that appear in the stack-track that doesn't seem to be right. Could you be more specific about your environemt: SQLite version, knex, knex-migrator version? Also, did you do any manual modifications to the table structure outside of normal ghost migrations in the past?
Thanks!

**Comment by simonbernard** [comment]
Yes, sure! I was able to reproduce this on multiple instances of ghost. I am using this docker image, where SQLite version is defined by Ghost itself: https://github.com/docker-library/ghost/blob/0d101bc60192416fddbbbaefcea3b91959101664/2/alpine/Dockerfile

I did never do any manual changes... 

Anything else that could help? Debug logging?

**Comment by gargol** [comment]
If you could produce some more detailed logs that would be super helpful. We don't support any docker images officially, think that might be a reason why this popped up the first time long after the 3.0 was out. 

I would recommend switching to 3.0 image first and ideally to the Debian distro (https://github.com/docker-library/ghost/tree/0d101bc60192416fddbbbaefcea3b91959101664/3/debian) as alpline is rarely tested.

**Comment by simonbernard** [comment]
Thanks! I will try this and come back with an update soon.

**Comment by gargol** [comment]
Awesome!

**Comment by simonbernard** [comment]
I tried to figure out what is the problem. It seems, that I can only upgrade the blogs to 3.0.2 if the default user Ghost still exists. When this user has been removed the migration fails with above message.

Are you able to reproduce it this way?

**Comment by gargol** [comment]
The default 'Ghost' user should always exist in the system it is not a hard requirement but something that is there to fall back to in different situations. But! I think it's worth looking into it just to make sure nothing unintentional is going on :)

**Comment by simonbernard** [comment]
OK, got your point. Just to mention it: this does not sound like I should keep the user:

![grafik](https://user-images.githubusercontent.com/6563486/68616671-cba6dc00-04c5-11ea-875b-60622458a4da.png)

**Comment by couchsoft** [comment]
@gargol Anything else I can provide to track down this issue? Would be happy to help!

**Comment by gargol** [comment]
@couchsoft would be great if you could find a reproducible state for this bug. Ideally a step by step instruction from installing 2.37.0 removing the Ghost user and then getting the same error. This would make verification and fixing the issue a breezy :smiley: Thanks!
