### ISSUE TITLE
Admin API Can't POST to /posts/ without cleaning up certain fields

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11461]
When using the API, there is an expectation that any data fetched should be possible to be sent back.

This is currently not the case for posts. 

## Reproduction Steps

This snippet should work with valid credentials:

```
const GhostAdminAPI = require('@tryghost/admin-api');
const api = new GhostAdminAPI({
    url,
    key,
    version: 'v2'
});
const allPosts = await api.posts.browse({limit: 10});
allPosts.map(async (post) => {
   // Edit one field here e.g. add a tag, find and replace content, etc
   return await api.posts.edit(post);
});
```

Currently, you get an error like:

```
There was an error { ValidationError: Validation error, cannot edit post.
    at makeRequest.catch (/Users/hannah/Sites/api-experiments/node_modules/@tryghost/admin-api/lib/index.js:304:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ValidationError',
  context: 'Validation failed for \'posts[0]\'',
  type: 'ValidationError',
  details:
   [ { keyword: 'additionalProperties',
       dataPath: '.posts[0]',
       schemaPath: '#/additionalProperties',
       params: { additionalProperty: 'uuid' },
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '.posts[0]',
       schemaPath: '#/additionalProperties',
       params: { additionalProperty: 'comment_id' },
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '.posts[0]',
       schemaPath: '#/additionalProperties',
       params: { additionalProperty: 'send_email_when_published' },
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '.posts[0]',
       schemaPath: '#/additionalProperties',
       params: { additionalProperty: 'email_subject' },
       message: 'should NOT have additional properties' } ],
  property: 'posts[0]',
  help: null,
  code: null,
  id: '21257850-1fef-11ea-bb64-d53f5ec37026' }
```

Note: 

uuid and comment_id are a problem in both v2 and v3
the 2x email fields are only a problem with v2

### Technical details:

* Ghost Version: master

**Comment by gargol** [comment]
With the above commits:
- `uuid` and `comment_id` were allowed in v2 and v3 requests
- `send_email_when_published` and `email_subject` were removed from API v2 responses
