### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by abdilra7eem** [TryGhost/Ghost#11708]
### Issue Summary

I get "Error 500 Maximum call stack size exceeded" when I try to open an article. I'm facing the problem on a publishing website with a very large number of collections (a very large routes.yaml).

Ghost version in use 3.12.1 pulled from this repo according to the instructions at: https://ghost.org/docs/install/source/.

The site works perfectly with a shorter routes.yaml file. I triple checked the routes file; it's valid, no errors whatsoever. There are no conflicts in collection rules, but they do have multiple filters each.

Here's an example of a collection:

> 
>   /palestine/g01/semester2/arabic/unit10/:
>     permalink: /palestine/g01/semester2/arabic/unit10/{slug}/
>     template: tag
>     filter: primary_tag:palestine+tag:g01+tag:semester2+tag:arabic+tag:unit10

Is there a maximum number of collections that work well ?

### Technical details:

* Ghost Version: 3.12.1
* Node Version: 10.19.0
* Browser/OS: Linux, Fedora 30
* Database: default ( SQLite ? )

**Comment by allouis** [comment]
Can you include the stack trace of the error from your server logs? This will help us find the problem, thanks!

FYI 

> This guide is for installing a local development copy of Ghost from source, **primarily for the purpose of modifying Ghost core**

(Emphasis added)

We recommend using the Ghost CLI for deploying to production :relaxed:

**Comment by abdilra7eem** [comment]
This is thr stack trace:

`Maximum call stack size exceeded

Error ID:
    56771c30-74e9-11ea-b969-55d68bad7013

----------------------------------------

InternalServerError: Maximum call stack size exceeded
    at new GhostError (/home/afakhouri/web-dev/cms/Ghost/core/server/lib/common/errors.js:10:26)
    at _private.prepareError (/home/afakhouri/web-dev/cms/Ghost/core/server/web/shared/middlewares/error-handler.js:52:19)
    at Layer.handle_error (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

RangeError: Maximum call stack size exceeded
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:635:15
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:260:14)
    at StaticRoutesRouter._prepareStaticRouteContext (/home/afakhouri/web-dev/cms/Ghost/core/frontend/services/routing/StaticRoutesRouter.js:124:9)
    at Layer.handle [as handle_request] (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:317:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:174:3)
    at StaticRoutesRouter (/home/afakhouri/web-dev/cms/Ghost/core/frontend/services/routing/ParentRouter.js:34:28)
    at Layer.handle [as handle_request] (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:317:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:635:15
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:260:14)
    at StaticRoutesRouter._prepareStaticRouteContext (/home/afakhouri/web-dev/cms/Ghost/core/frontend/services/routing/StaticRoutesRouter.js:124:9)
    at Layer.handle [as handle_request] (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:317:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:174:3)
    at StaticRoutesRouter (/home/afakhouri/web-dev/cms/Ghost/core/frontend/services/routing/ParentRouter.js:34:28)
    at Layer.handle [as handle_request] (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:317:13)
    at /home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/home/afakhouri/web-dev/cms/Ghost/node_modules/express/lib/router/index.js:275:10)`

The website is still in its development phase. I installed from source to stay up to date. When I deploy to production, I'll probably use the docker image.

**Comment by abdilra7eem** [comment]
I made another routes file with only one collection and a very large number of channels. The same problem occurs.

Then, I tried reducing the number of channels, and something interesting happened. At a certain number of routes, the post gives me the same error on the first few tried, but if I keep refreshing, it opens normally, then gives an error, then opens, then gives an error, until it starts to open normally. If I restart the server, The same thing happens, and I have to refresh several times until it shows the post again.

I concluded 2 things:
1. The same problem happens with different kinds of routes, not only with collections.
2. Ghost doesn't either work or fail. There's a situation where it both works and fails, and you can't know for sure until you try to open the post (reminds me of  Schrodinger's cat).

**Comment by abdilra7eem** [comment]
Another interesting finding: The place of the route in the routes.yaml file matters.
In the same routes.yaml, the same collection works when it's moves to the beginning of the routes file, but gives the error when it's moved near the end.

**Comment by abdilra7eem** [comment]
Any updates?

**Comment by JuliaBelokrinitskaya** [comment]
I'm having tha same issue. Large routes file. Many custom routes for landing pages. I was getting the same 500 error locally and on stage server in the blog articles and on amp versions of landing pages. Now I'm also getting the error on the newest landing pages. Seems like I cannot add custom routes anymore. I have 432 custom routes now in the routes.yaml + 14 collections + 1 taxonomy. Updated to ghost 4, but this didn't helped.

**Comment by ErisDS** [comment]
FYI we are tracking this concern as part of a larger concept for reworking routing. However, it would be really handy to have a file that reproduced this issue. Would be great if someone having this problem could share their routes.yaml file.

Thanks!
