### ISSUE TITLE
Ghost fails to restart after upgrading from 3.9.x to 3.15.3

### ISSUE THREAD

**Issue by magnolialogic** [TryGhost/Ghost#11812]
### Issue Summary

Ghost fails to restart after updating from 3.9.x to 3.15.3 on Ubuntu 18.04.4 LTS with node 12.16.3 with backtrace:

May 12 00:40:33 www systemd[1]: Started Ghost systemd service for blog: 
May 12 00:40:34 www node[1844]: - Inspecting operating system
May 12 00:40:34 www node[1844]: /var/www/ghost/versions/3.15.3/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
May 12 00:40:34 www node[1844]:       } catch {
May 12 00:40:34 www node[1844]:               ^
May 12 00:40:34 www node[1844]: SyntaxError: Unexpected token {
May 12 00:40:34 www node[1844]:     at createScript (vm.js:80:10)
May 12 00:40:34 www node[1844]:     at Object.runInThisContext (vm.js:139:10)
May 12 00:40:34 www node[1844]:     at Module._compile (module.js:616:28)
May 12 00:40:34 www node[1844]:     at Object.Module._extensions..js (module.js:663:10)
May 12 00:40:34 www node[1844]:     at Module.load (module.js:565:32)
May 12 00:40:34 www node[1844]:     at tryModuleLoad (module.js:505:12)
May 12 00:40:34 www node[1844]:     at Function.Module._load (module.js:497:3)
May 12 00:40:34 www node[1844]:     at Module.require (module.js:596:17)
May 12 00:40:34 www node[1844]:     at require (internal/module.js:11:18)
May 12 00:40:34 www node[1844]:     at Object.<anonymous> (/var/www/ghost/versions/3.15.3/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

### To Reproduce

1. Use `ghost update` to upgrade from 3.9.x to 3.15.3

Expected: after updating ghost starts without issue
Actual: `ghost update` upgrades install but stalls at `☴ Starting Ghost`, systemctl reports status `Active: failed (Result: start-limit-hit)`
### Technical details:

* Ghost Version: 3.15.3
* Node Version: 12.16.3
* Browser/OS: Ubuntu 18.04.4 LTS
* Database: mysql@5.7

**Comment by magnolialogic** [comment]
Fixed, my node version was 12.16.3 but nodejs was still on 8.x. Working after upgrading nodejs to 12.16.3 as well.
