### ISSUE TITLE
Error upgrading from 3.11.0 to 3.20.3

### ISSUE THREAD

**Issue by octopusthu** [TryGhost/Ghost#11938]
### Issue Summary

Error upgrading from 3.11.0 to 3.20.3. The upgrading process went well but the system failed to start after it. 

### To Reproduce

1. upgrade ghost-cli
```bash
npm install -g ghost-cli@latest
```
2. upgrade ghost
```bash
ghost upgrade
```

3. Ghost failed to restart. Output is as follows.

```log
Stopped Ghost systemd service for blog: 
Started Ghost systemd service for blog: 
/var/www/ghost/versions/3.20.3/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
} catch {
^
SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/www/ghost/versions/3.20.3/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

### Technical details:

* Node Version: v12.16.2
* Browser/OS: CentOS 7.8

**Comment by ErisDS** [comment]
This is not a bug, it is due to Ghost running with Node <v10. There are several posts on the forum discussing this:

https://forum.ghost.org/t/cannot-find-module-fs-extra-during-fresh-installation/4897
https://forum.ghost.org/t/attempt-to-upgrade-2-to-3-fails/13170/4

**Comment by octopusthu** [comment]
Changed the node binary referenced by systemd  to start ghost and the problem is solved. Thanks.
