### ISSUE TITLE
Error Upgrading from Ghost v3.2.0 to v3.31.3

### ISSUE THREAD

**Issue by bsberry** [TryGhost/Ghost#12170]
### Issue Summary
I ran `ghost update` on an instance running version 3.2.0 . The update proceeded apparently normally, but when I attempted to `ghost start` after the upgrade, it fails to start and logs this error:

```
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:                                                                  
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: Cannot remove permission(Read member signin urls) from role(Administrator) - permission does not exist                            
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: "OuterError: alter table `members_labels` add constraint `members_labels_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - UNKNOWN_CODE_PLEASE
_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible."           
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: Error ID:                                                                                                                                                                                Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     400                                                                                                                                                                                  
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: ----------------------------------------
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: RollbackError: Cannot remove permission(Read member signin urls) from role(Administrator) - permission does not exist
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at RollbackError.KnexMigrateError (/var/www/ghost/versions/3.31.3/node_modules/knex-migrator/lib/errors.js:7:26)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at new RollbackError (/var/www/ghost/versions/3.31.3/node_modules/knex-migrator/lib/errors.js:31:26)             
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at /var/www/ghost/versions/3.31.3/node_modules/knex-migrator/lib/index.js:440:23                                
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at tryCatcher (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/util.js:16:23)       
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/promise.js:547:31)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Promise._settlePromise (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/promise.js:604:18)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Promise._settlePromise0 (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/promise.js:649:10)          
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Promise._settlePromises (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/promise.js:725:18)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at _drainQueueStep (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/async.js:93:12)           
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at _drainQueue (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/async.js:86:9)                
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Async._drainQueues (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/async.js:102:5)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.31.3/node_modules/bluebird/js/release/async.js:15:14)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at processImmediate (internal/timers.js:456:21)                                                                                                                                      
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]: Error: Cannot remove permission(Read member signin urls) from role(Administrator) - permission does not exist                        
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at down (/var/www/ghost/versions/3.31.3/core/server/data/migrations/utils.js:122:23)
Sep 02 04:16:13 ghost-s-1vcpu-1gb-nyc3-01 node[29511]:     at async Object.down (/var/www/ghost/versions/3.31.3/core/server/data/migrations/utils.js:190:13)   
```
If I `ghost update --rollback` to v.3.2.0 the error goes away.

```
[ghost-mgr@ghost-s-1vcpu-1gb-nyc3-01] /var/www/ghost
$ uname -a
Linux ghost-s-1vcpu-1gb-nyc3-01 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[ghost-mgr@ghost-s-1vcpu-1gb-nyc3-01] /var/www/ghost
$ ghost --version
Ghost-CLI version: 1.14.1
Ghost version: 3.31.3 (at /var/www/ghost)
[ghost-mgr@ghost-s-1vcpu-1gb-nyc3-01] /var/www/ghost
$ node --version
v12.18.3
```

### To Reproduce

1. Upgrade from 3.2.0 to 3.31.3
2. Try to run ghost

### Technical details:

* Ghost Version: 3.31.3 (upgraded from 3.2.0
* Node Version: 12.18.3
* Browser/OS: No browser, Unbuntu 20.04
* Database: mysql

**Comment by ErisDS** [comment]
Can you please share the version of your MySQL database, whether it's standard MySQL or some flavour, and whether it's been upgraded?

Also, please share the full logs from your upgrade - this last piece is showing a rollback failing and indicates the true error is

```"OuterError: alter table `members_labels` add constraint `members_labels_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - UNKNOWN_CODE_PLEASE
_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible.```
