### ISSUE TITLE
No provider found for supplied URL. Oembed.

### ISSUE THREAD

**Issue by Sebubu** [TryGhost/Ghost#12389]
### Issue Summary

I am not able to embed `https://demo.ghost.io/welcome/` in my post. I have tried other Ghost websites but also failed. If I do, I get the following error.

```
[2020-11-20 10:07:20] ERROR "GET /ghost/api/v3/admin/oembed/?url=https%3A%2F%2Fdemo.ghost.io%2Fwelcome%2F&type=embed" 422 271ms

No provider found for supplied URL.

"https://demo.ghost.io/welcome/"

Error ID:
    2d9e7160-2b18-11eb-a6d4-b189c2d6827c

----------------------------------------

ValidationError: No provider found for supplied URL.
    at new ValidationError (/var/www/ghost/versions/3.38.2/node_modules/ghost-ignition/lib/errors/index.js:141:23)
    at unknownProvider (/var/www/ghost/versions/3.38.2/core/server/api/canary/oembed.js:81:27)
    at /var/www/ghost/versions/3.38.2/core/server/api/canary/oembed.js:257:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The issue looks similar to #11673 but my NodeJs version is up to date. Other embed types like Youtube work.
Not sure where the problem is exactly.

### To Reproduce

1. Run `ghost run`.
2. Try to embed `https://demo.ghost.io/welcome/` in a post.
3. See printed error.

I am running this on a newly installed Digital Ocean Ghost droplet.

### Technical details:

* OS: Ubuntu, v18.04.4 LTS
* Node Version: v12.19.1
* Ghost Version: 3.38.2
* Ghost-CLI Version: 1.15.2
* Environment: production
* Database: MySQL

**Comment by TSiege** [comment]
I'm noticing a similar problem with OEmbeds not working from Instagram. Mine is happening to me on the latest version of the ghost docker image `3.38`, but was happening on at least `3.35`. In early October I updated ghost from version `3.27` to `3.35`, which is when the problem started occurring. The Docker Image is using `node:12-buster-slim`. Might be related to not using the full version of Node, but locally in node v12 the URL class can parse instagram urls no problem.

```
Nov 24 01:42:27 PM  [2020-11-24 18:42:27] ERROR "GET /ghost/api/v3/admin/oembed/?url=https%3A%2F%2Fwww.instagram.com%2Fp%2FCH-sBOgp89w%2F&type=embed" 422 708ms
Nov 24 01:42:27 PM  
Nov 24 01:42:27 PM  No provider found for supplied URL.
Nov 24 01:42:27 PM  
Nov 24 01:42:27 PM  "https://www.instagram.com/p/CH-sBOgp89w/"
Nov 24 01:42:27 PM  
Nov 24 01:42:27 PM  Error ID:
Nov 24 01:42:27 PM      cce51ca0-2e84-11eb-9183-67b75f9122b3
Nov 24 01:42:27 PM  
Nov 24 01:42:27 PM  ----------------------------------------
Nov 24 01:42:27 PM  
Nov 24 01:42:27 PM  ValidationError: No provider found for supplied URL.
    at new ValidationError (/var/lib/ghost/versions/3.38.3/node_modules/ghost-ignition/lib/errors/index.js:141:23)
    at unknownProvider (/var/lib/ghost/versions/3.38.3/core/server/api/canary/oembed.js:81:27)
    at /var/lib/ghost/versions/3.38.3/core/server/api/canary/oembed.js:228:16
```

**Comment by kevinansfield** [comment]
> I'm noticing a similar problem with OEmbeds not working from Instagram.

Instagram won't work any more because Facebook killed open oembed support. They now require developer accounts and registered Facebook apps to be able to use their embed endpoints.

**Comment by TSiege** [comment]
@kevinansfield That's definitely a major headache for users. Is there any plans to readd support for instagram and facebook embeds using some sort of api token we can add to the ghost cms?

**Comment by TSiege** [comment]
Gotcha, thanks for the quick response

**Comment by sumew** [comment]
I'm seeing the same error, tried to embed youtube, github, twitter
Here's what I did 

- `docker run -d --name some-ghost -e url=http://localhost:3001 -p 3001:2368 ghost`
- Create a new post, tried to embed





```
Error ID:
    168b02e0-34eb-11eb-ad05-97d688681c62

----------------------------------------

ValidationError: No provider found for supplied URL.
    at new ValidationError (/var/lib/ghost/versions/3.39.0/node_modules/ghost-ignition/lib/errors/index.js:141:23)
    at unknownProvider (/var/lib/ghost/versions/3.39.0/core/server/api/canary/oembed.js:81:27)
    at fetchOembedData (/var/lib/ghost/versions/3.39.0/core/server/api/canary/oembed.js:124:16)
    at Object.query (/var/lib/ghost/versions/3.39.0/core/server/api/canary/oembed.js:250:20)
    at Object.query (/var/lib/ghost/versions/3.39.0/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versions/3.39.0/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/3.39.0/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/3.39.
```

**Comment by matthanley** [comment]
@sumew I'm unable to reproduce the issue with the sources you've mentioned. Could you confirm the version of the Ghost docker image you're using? (also note that the `ghost` Docker image is provided and maintained by the Docker community, and isn't an official Ghost image)

**Comment by sumew** [comment]
@matthanley I used the image [here](https://hub.docker.com/_/ghost). Where can I find the official image?
Here's the output of docker image inspect...
```
"Id": "sha256:9ebb9391dc1b07a6046799bc1abf2a1b85ed9e0e27ceef897441733a536f9023",
        "RepoTags": [
            "ghost:latest"
        ],
        "RepoDigests": [
            "ghost@sha256:ac3733fcec41534f9dd24a787625017954ff6c0c80a940623611dded80f5a40f"
        ]
...
```

**Comment by sghf** [comment]
@sumew : are you sure you container is able to access internet (or at least to resolve a domain name)?
Check routes and resolv.conf inside your Docker container.

**Comment by gustawdaniel** [comment]
I have the same error

```
http https://blog.gustawdaniel.com/ghost/api/v3/admin/oembed/\?url\=https%3A%2F%2Fgoofy-franklin-2f9df8.netlify.app\&type\=bookmark cookie:"ghost-admin-api-session=XXX"
```

```
HTTP/1.1 422 Unprocessable Entity
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Connection: keep-alive
Content-Length: 278
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Feb 2021 04:29:06 GMT
ETag: W/"116-48aR5nyqJjMMTY4+SHxExdS3tB8"
Server: nginx/1.14.0 (Ubuntu)
Vary: Accept-Encoding
X-Powered-By: Express

{
    "errors": [
        {
            "code": null,
            "context": "URL contains insufficient metadata. https://goofy-franklin-2f9df8.netlify.app",
            "details": null,
            "help": null,
            "id": "848b1f90-66a1-11eb-b214-e3495be70dea",
            "message": "Validation error, cannot read oembed.",
            "property": null,
            "type": "ValidationError"
        }
    ]
}
```

In browser:

![Screenshot from 2021-02-04 05-32-14](https://user-images.githubusercontent.com/16663028/106844974-2ff52300-66aa-11eb-8d92-53218a33766e.png)

In view

![Screenshot from 2021-02-04 05-32-35](https://user-images.githubusercontent.com/16663028/106845002-3daaa880-66aa-11eb-8e02-17025c5b823b.png)

But some links works correct

![Screenshot from 2021-02-04 05-33-08](https://user-images.githubusercontent.com/16663028/106845035-53b86900-66aa-11eb-8a8f-7d13c0b1e8d6.png)

**Comment by gustawdaniel** [comment]
How to debug:

In working case I have response

```
http https://blog.gustawdaniel.com/ghost/api/v3/admin/oembed/\?url\=https://www.bankier.pl/wiadomosc/Zlote-czasy-franka-jak-sie-zaczal-kredytowy-boom-2894462.html\&type\=bookmark cookie:xxx
```

with content:

```
HTTP/1.1 200 OK
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Connection: keep-alive
Content-Length: 812
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Feb 2021 04:38:26 GMT
ETag: W/"32c-xm8N8VXzwkTrLGnBfgxeRGIVvW0"
Server: nginx/1.14.0 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Express

{
    "metadata": {
        "author": "Michał Kisiel",
        "description": "Nagła kredytowa kariera szwajcarskiego franka sprawiła, że tysiące Polaków co najmniej raz w miesiącu z niepokojem zerkają na notowania. Popularność zobowiązań w helweckiej walucie była wynikiem zbiegu kilku okoliczności w określonym momencie gospodarczej historii Polski. Kredytobiorcy, którzy w poł…",
        "icon": "https://www.bankier.pl/favicon.ico",
        "publisher": "Bankier.pl",
        "thumbnail": "https://galeria.bankier.pl/p/7/4/2ce22f1888d615-thumb-2500.jpg",
        "title": "Złote czasy franka - jak się zaczął kredytowy boom?",
        "url": "https://www.bankier.pl/wiadomosc/Zlote-czasy-franka-jak-sie-zaczal-kredytowy-boom-2894462.html"
    },
    "type": "bookmark",
    "url": "https://www.bankier.pl/wiadomosc/Zlote-czasy-franka-jak-sie-zaczal-kredytowy-boom-2894462.html"
}
```

So probably on page: 

> https://goofy-franklin-2f9df8.netlify.app/

I need to add some metadata:

I added and now it works

![Screenshot from 2021-02-04 05-56-51](https://user-images.githubusercontent.com/16663028/106846689-a5162780-66ad-11eb-88de-4f7675763470.png)

I recommend to read:

https://css-tricks.com/essential-meta-tags-social-media/

How I fixed?

I added some meta tags:

```
  <meta name="description" content="Od 1995 są PLN, wcześniej były PLZ">
  <meta name="author" content="Daniel Gustaw">
  <meta name="publisher" content="Daniel Gustaw">

  <meta property="og:title" content="European Travel Destinations">
  <meta property="og:description" content="Offering tour packages for individuals or groups.">
  <meta property="og:image" content="http://euro-travel-example.com/thumbnail.jpg">
  <meta property="og:url" content="http://euro-travel-example.com/index.htm">
```

**Comment by ErisDS** [comment]
To address the original reporte issue - Ghost is not an oembed provider at present, instead you can use the bookmark card to create a nicely formatted link. 

I am not sure anything else here constitutes a bug but are either issues with other oembed providers or with individual environments @matthanley do you agree or is there something here you think warrants a fix?
