### ISSUE TITLE
RollbackError after 3.40.4 upgrade, application inaccessible

### ISSUE THREAD

**Issue by ivansieder** [TryGhost/Ghost#12510]
### Issue Summary

After running the upgrade to from 3.40.3 to 3.40.4 on the latest CLI version (1.15.3) and Node.js 14.15.4, the Application won't boot up anymore. Starting the application with `ghost run` returns the following error:

[2021-01-06 09:22:35] INFO Dropping composite index on email_recipients for [email_id, member_email]
[2021-01-06 09:22:36] ERROR alter table `email_recipients` add constraint `email_recipients_email_id_foreign` foreign key (`email_id`) references `emails` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'email_id' and referenced column 'id' in foreign key constraint 'email_recipients_email_id_foreign' are incompatible.

alter table `email_recipients` add constraint `email_recipients_email_id_foreign` foreign key (`email_id`) references `emails` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'email_id' and referenced column 'id' in foreign key constraint 'email_recipients_email_id_foreign' are incompatible.

"OuterError: update `members` set `email_count` = (SELECT COUNT(id) FROM email_recipients WHERE email_recipients.member_id = members.id), `email_opened_count` = (SELECT COUNT(id) FROM email_recipients WHERE email_recipients.member_id = members.id AND email_recipients.opened_at IS NOT NULL) - ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"

Error ID:
    400

Error Code: 
    UNKNOWN_CODE_PLEASE_REPORT

----------------------------------------

RollbackError: alter table `email_recipients` add constraint `email_recipients_email_id_foreign` foreign key (`email_id`) references `emails` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'email_id' and referenced column 'id' in foreign key constraint 'email_recipients_email_id_foreign' are incompatible.
    at RollbackError.KnexMigrateError (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/lib/errors.js:31:26)
    at /var/www/ghost/versions/3.40.4/node_modules/knex-migrator/lib/index.js:440:23
    at tryCatcher (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.40.4/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'email_id' and referenced column 'id' in foreign key constraint 'email_recipients_email_id_foreign' are incompatible.
    at Query.Sequence._packetToError (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/ghost/versions/3.40.4/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/client.js:169:17)
    at Runner.query (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/runner.js:248:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /var/www/ghost/versions/3.40.4/node_modules/knex-migrator/node_modules/knex/lib/runner.js:277:18
    at async down (/var/www/ghost/versions/3.40.4/core/server/data/migrations/versions/3.39/06-add-email-recipient-index.js:46:13)
    at async Object.down (/var/www/ghost/versions/3.40.4/core/server/data/migrations/utils.js:219:13)

### To Reproduce

1. Have a 3.40.3 installation
2. Upgrade to the latest version

### Technical details:

* Ghost Version: 3.40.4
* Node Version: 14.15.4
* Browser/OS: not relevant
* Database: Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

**Comment by ivansieder** [comment]
Issue seems to be burried inside the incompatible collation:
| ghost_prod   | email_recipients                       | email_id                   | utf8mb4            | utf8mb4_0900_ai_ci |
| ghost_prod   | emails                                 | id                         | utf8mb4            | utf8mb4_general_ci |

Temporary fixed with:
`mysql> alter table email_recipients convert to character set utf8mb4 collate utf8mb4_general_ci;`

**Comment by ErisDS** [comment]
Hi @ivansieder, sorry to hear you had trouble updating Ghost. However, this is an issue with your environment rather than a bug in Ghost and therefore considered a support request. Please see the comment here for more details: https://github.com/TryGhost/Ghost/issues/11625#issuecomment-644879046

**Comment by reubano** [comment]
I agree with @ivansieder this is definitely a bug.
