### ISSUE TITLE
Migrations error when upgrading to latest Ghost from ≤ 2.27

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12589]
### Issue Summary

Migrations fail to cleanly apply when migrating to the latest version of Ghost from ≤ 2.27. 

### To Reproduce

1. `nvm use 10`
1. `ghost install 2.27.0 --local`
1. `ghost update --local`
1. `ghost log`
1. 💥 Migrations failed

Due to https://github.com/TryGhost/knex-migrator/issues/241, the actual error is hidden behind another error, but this is what I could pull out:

```
[2021-02-01 14:05:32] ERROR Unable to update nested relation.

Unable to update nested relation.

{"key":"api_keys","tableName":"integrations","method":"setHasMany"}
"Error occurred while executing the following migration: 4-insert-scheduler-integration.js"

Error ID:
    8bf87500-6496-11eb-bc73-390e91e9acaf

Error Code:
    UPDATE_RELATION

----------------------------------------

MigrationScriptError: Unable to update nested relation.
    at MigrationScriptError.KnexMigrateError (/home/neo/code/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (/home/neo/code/knex-migrator/lib/errors.js:25:26)
    at /home/neo/code/knex-migrator/lib/index.js:1058:19

BookshelfRelationsError: Unable to update nested relation.
    at new BookshelfRelationsError (/home/neo/code/Ghost/node_modules/bookshelf-relations/errors.js:10:26)
    at /home/neo/code/Ghost/node_modules/bookshelf-relations/lib/relations.js:71:27
    at tryCatcher (/home/neo/code/Ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/neo/code/Ghost/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/neo/code/Ghost/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/neo/code/Ghost/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/neo/code/Ghost/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/neo/code/Ghost/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/neo/code/Ghost/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/neo/code/Ghost/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/neo/code/Ghost/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

Error: insert into `api_keys` (`created_at`, `created_by`, `id`, `integration_id`, `last_seen_at`, `last_seen_version`, `role_id`, `secret`, `type`, `updated_at`, `updated_by`, `user_id`) values ('2021-02-01 14:05:32.108', '1', '60180aacdcb8702d79ec3a96', '60180aacdcb8702d79ec3a95', NULL, NULL, '60180aacdcb8702d79ec3a93', '6f0450302e583204e1b5b3c7dfd23cc425f0f5d3ea77039820d54a7ee8b6d57e', 'admin', '2021-02-01 14:05:32.108', '1', NULL) - SQLITE_ERROR: table api_keys has no column named user_id
```

### Technical details:

* Ghost Version: `2.27.0` -> `3.41.2`
* Node Version: `v10.18.0`
* Browser/OS: N/A
* Database: SQLite

**Comment by ErisDS** [comment]
I'm assuming it works fine if you upgrade to 2.38.3 first? i.e. with our policy of supporting upgrading from the latest version in your stream this is ok?

I do think however that there is a small piece of work needed in Ghost CLI to enforce the upgrade to the latest version-in-stream first that's been lost.

**Comment by daniellockyer** [comment]
@ErisDS Can confirm - I just tested `2.27` -> `2.38.3` -> `3.41.8` and it LGTM 👍🏻

**Comment by matthanley** [comment]
Updating docs with the correct update policy is tracked in https://github.com/TryGhost/Team/issues/499
