### ISSUE TITLE
Ghost crashes when Mailgun is misconfigured

### ISSUE THREAD

**Issue by rozhok** [TryGhost/Ghost#12610]
### Issue Summary

If Mailgun misconfigured, for instance, domain is set incorrectly, Ghost will silently crash after trying to send any email.

### To Reproduce

0. Go to Admin -> Labs -> Members
1. Type https://mailgun.endpoint in "Mailgun domain" setting
2. Try to send any test email

ER: Ghost won't crash and print "Error while sending email using Mailgun: wrong configuration" to log.

AR: Ghost crashes with no meaningful exception in logs:
```
TypeError: Cannot read property 'id' of undefined
    at /var/lib/ghost/versions/3.41.3/core/server/services/bulk-email/mailgun.js:109:30
    at Request.callback (/var/lib/ghost/versions/3.41.3/node_modules/async/dist/async.js:4617:26)
    at IncomingMessage.<anonymous> (/var/lib/ghost/versions/3.41.3/node_modules/mailgun-js/lib/request.js:331:19)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I've set full Mailgun endpoint instead of only domain part by mistake and spent a good hour trying to figure out what's wrong.

### Technical details:

* Ghost Version: 3.41.3
* Node Version: 12.20.1
* Browser/OS: Any
* Database: SQLite

**Comment by matthanley** [comment]
Closed by https://github.com/TryGhost/Ghost/pull/12718
