### ISSUE TITLE
Unexpected string in JSON at position 159

### ISSUE THREAD

**Issue by diazepan** [TryGhost/Ghost#12772]
When I tried to update from the 3.42.2 version to the 4.0.1 version, I get this error

Stack: SyntaxError: Unexpected string in JSON at position 159
    at JSON.parse (<anonymous>)
    at checkUsage (/var/www/ghost/versions/4.0.1/node_modules/gscan/lib/checks/080-helper-usage.js:12:38)
    at /var/www/ghost/versions/4.0.1/node_modules/gscan/lib/checker.js:34:24
    at tryCatcher (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/4.0.1/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by naz** [comment]
@diazepan what's the contents of your theme's `package.json` file? It seems like the file is not there or the JSON formatting in the file is broken.
