### ISSUE TITLE
Error upgrading from 4.1.0 to 4.4.0

### ISSUE THREAD

**Issue by tmlmt** [TryGhost/Ghost#12947]
I get the following error message when trying to upgrade from 4.1.0 to 4.4.0:

```
✔ Fetched release notes
✔ Downloading and updating Ghost to v4.4.0
+ sudo systemctl stop ghost_myblog-com
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
+ sudo systemctl start ghost_myblog-com
+ sudo systemctl stop ghost_myblog-com
✖ Restarting Ghost
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: alter table `members_products` add constraint `members_products_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_products_member_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 02-add-members-products-table.js
Suggestion: journalctl -u ghost_myblog-com -n 50

Debug Information:
    OS: Ubuntu, v20.04.2 LTS
    Node Version: v10.19.0
    Ghost Version: 4.4.0
    Ghost-CLI Version: 1.16.3
    Environment: production
    Command: 'ghost update'

```
Here is the relevant extract from `journalctl -u ghost_myblog-com -n 100`
```
May 09 11:54:05 udoo systemd[1]: Started Ghost systemd service for blog: myblog-com.
May 09 11:54:08 udoo node[815634]: - Inspecting operating system
May 09 11:54:12 udoo node[815663]: [2021-05-09 09:54:12] INFO Ghost is running in production...
May 09 11:54:12 udoo node[815663]: [2021-05-09 09:54:12] INFO Your site is now available on https://myblog.com/
May 09 11:54:12 udoo node[815663]: [2021-05-09 09:54:12] INFO Ctrl+C to shut down
May 09 11:54:12 udoo node[815663]: [2021-05-09 09:54:12] INFO Ghost server started in 3.52s
May 09 11:54:13 udoo node[815663]: [2021-05-09 09:54:13] INFO Bootstrap client was closed.
May 09 11:54:13 udoo node[815663]: [2021-05-09 09:54:13] WARN Database state requires migration.
May 09 11:54:15 udoo node[815663]: [2021-05-09 09:54:15] INFO Creating database backup
May 09 11:54:16 udoo node[815663]: [2021-05-09 09:54:16] INFO Database backup written to: /var/www/blog/content/data/blog.ghost.2021-05-09-09-54-16.json
May 09 11:54:16 udoo node[815663]: [2021-05-09 09:54:16] INFO Fixing incorrect mrr_delta in members_paid_subscription_events table
May 09 11:54:16 udoo node[815663]: [2021-05-09 09:54:16] INFO Adding table: products
May 09 11:54:16 udoo node[815663]: [2021-05-09 09:54:16] INFO Adding table: members_products
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] INFO Skipping rollback of members_signup_access setting. Does not exist.
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] INFO Dropping table: members_products
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] INFO Dropping table: products
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] INFO Reverting mrr_delta to old value in members_paid_subscription_events table
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] ERROR alter table `members_products` add constraint `members_products_member_id_foreign` foreign key (`member_id`) references `members`>
May 09 11:54:17 udoo node[815663]: 
May 09 11:54:17 udoo node[815663]: alter table `members_products` add constraint `members_products_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - >
May 09 11:54:17 udoo node[815663]: {"config":{"transaction":false},"name":"02-add-members-products-table.js"}
May 09 11:54:17 udoo node[815663]: "Error occurred while executing the following migration: 02-add-members-products-table.js"
May 09 11:54:17 udoo node[815663]: Error ID:
May 09 11:54:17 udoo node[815663]:     300
May 09 11:54:17 udoo node[815663]: Error Code: 
May 09 11:54:17 udoo node[815663]:     UNKNOWN_CODE_PLEASE_REPORT
May 09 11:54:17 udoo node[815663]: ----------------------------------------
May 09 11:54:17 udoo node[815663]: MigrationScriptError: alter table `members_products` add constraint `members_products_member_id_foreign` foreign key (`member_id`) references `members` (`id`>
May 09 11:54:17 udoo node[815663]:     at MigrationScriptError.KnexMigrateError (/var/www/blog/versions/4.4.0/node_modules/knex-migrator/lib/errors.js:7:26)
May 09 11:54:17 udoo node[815663]:     at new MigrationScriptError (/var/www/blog/versions/4.4.0/node_modules/knex-migrator/lib/errors.js:25:26)
May 09 11:54:17 udoo node[815663]:     at /var/www/blog/versions/4.4.0/node_modules/knex-migrator/lib/index.js:1055:19
May 09 11:54:17 udoo node[815663]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 11:54:17 udoo node[815663]: Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_products_member_id_foreign' a>
May 09 11:54:17 udoo node[815663]:     at Query.Sequence._packetToError (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
May 09 11:54:17 udoo node[815663]:     at Query.ErrorPacket (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
May 09 11:54:17 udoo node[815663]:     at Protocol._parsePacket (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/Protocol.js:291:23)
May 09 11:54:17 udoo node[815663]:     at Parser._parsePacket (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/Parser.js:433:10)
May 09 11:54:17 udoo node[815663]:     at Parser.write (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/Parser.js:43:10)
May 09 11:54:17 udoo node[815663]:     at Protocol.write (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/Protocol.js:38:16)
May 09 11:54:17 udoo node[815663]:     at Socket.<anonymous> (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/Connection.js:88:28)
May 09 11:54:17 udoo node[815663]:     at Socket.<anonymous> (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/Connection.js:526:10)
May 09 11:54:17 udoo node[815663]:     at Socket.emit (events.js:315:20)
May 09 11:54:17 udoo node[815663]:     at addChunk (internal/streams/readable.js:309:12)
May 09 11:54:17 udoo node[815663]:     at readableAddChunk (internal/streams/readable.js:284:9)
May 09 11:54:17 udoo node[815663]:     at Socket.Readable.push (internal/streams/readable.js:223:10)
May 09 11:54:17 udoo node[815663]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
May 09 11:54:17 udoo node[815663]:     --------------------
May 09 11:54:17 udoo node[815663]:     at Protocol._enqueue (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/protocol/Protocol.js:144:48)
May 09 11:54:17 udoo node[815663]:     at Connection.query (/var/www/blog/versions/4.4.0/node_modules/mysql/lib/Connection.js:198:25)
May 09 11:54:17 udoo node[815663]:     at /var/www/blog/versions/4.4.0/node_modules/knex/lib/dialects/mysql/index.js:134:18
May 09 11:54:17 udoo node[815663]:     at new Promise (<anonymous>)
May 09 11:54:17 udoo node[815663]:     at Client_MySQL._query (/var/www/blog/versions/4.4.0/node_modules/knex/lib/dialects/mysql/index.js:128:12)
May 09 11:54:17 udoo node[815663]:     at Client_MySQL.query (/var/www/blog/versions/4.4.0/node_modules/knex/lib/client.js:168:17)
May 09 11:54:17 udoo node[815663]:     at Runner.query (/var/www/blog/versions/4.4.0/node_modules/knex/lib/runner.js:151:36)
May 09 11:54:17 udoo node[815663]:     at Runner.queryArray (/var/www/blog/versions/4.4.0/node_modules/knex/lib/runner.js:248:31)
May 09 11:54:17 udoo node[815663]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 11:54:17 udoo node[815663]:     at async /var/www/blog/versions/4.4.0/node_modules/knex/lib/runner.js:277:18
May 09 11:54:17 udoo node[815663]:     at async Object.up (/var/www/blog/versions/4.4.0/core/server/data/migrations/utils.js:239:13)
May 09 11:54:17 udoo node[815663]: 
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost is shutting down
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost has shut down
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Your site is now offline
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost was running for a few seconds
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] INFO Bootstrap client was closed.
May 09 11:54:17 udoo systemd[1]: Stopping Ghost systemd service for blog: myblog-com...
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost is shutting down
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost has shut down
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Your site is now offline
May 09 11:54:17 udoo node[815663]: [2021-05-09 09:54:17] WARN Ghost was running for a few seconds
May 09 11:54:18 udoo node[815634]: /usr/local/npm/lib/node_modules/ghost-cli/lib/process-manager.js:46
May 09 11:54:18 udoo node[815634]:         throw error;
May 09 11:54:18 udoo node[815634]:         ^
May 09 11:54:18 udoo node[815634]: {
May 09 11:54:18 udoo node[815634]:   message: "Ghost was able to start, but errored during boot with: alter table `members_products` add constraint `members_products_member_id_foreign` foreign>
May 09 11:54:18 udoo node[815634]: }
May 09 11:54:18 udoo systemd[1]: ghost_myblog-com.service: Main process exited, code=exited, status=1/FAILURE
May 09 11:54:18 udoo systemd[1]: ghost_myblog-com.service: Failed with result 'exit-code'.
May 09 11:54:18 udoo systemd[1]: Stopped Ghost systemd service for blog: myblog-com.
```

**Comment by tmlmt** [comment]
Solved using @jebarjonet's fix found here (https://forum.ghost.org/t/unable-to-upgrade-ghost-from-v4-2-0-to-v4-3-0-cascade-unknown-code-please-report/22086/56), in case it helps someone landing on this page: 
My ghost MySQL database and its tables were all with the new default MySQL 8.0 collation utf8mb4_0900_ai_ci. Shouldn't

**Comment by fadyosman** [comment]
If anyone reached this page when trying to fix their ghost installation, it's not easy as it requires changing the collation and will result in some conflicts if done manually.

The quickest way I was able to use is to export the database using PHP my admin as a SQL file, then replace all the collations with `utf8mb4_0900_ai_ci`, I used find and replace all in my text editor to replace the conflicting collation with `utf8mb4_0900_ai_ci`.

After that remove all the tables and re-import the file.

Note: use this suggestion at your own risk as you can see one of the steps is deleting all the tables so make sure to backup.
