### ISSUE TITLE
TypeError `allNotifications.forEach is not a function` when opening admin panel dashboard

### ISSUE THREAD

**Issue by coditva** [TryGhost/Ghost#12963]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
When opening the dashboard for my blog, I'm getting this error in the `content/logs/XXX_production.error.log` file:

```
TypeError: allNotifications.forEach is not a function
    at Notifications.fetchAllNotifications (/home/coditva/coditva/versions/4.5.0/core/server/services/notifications/notifications.js:26:26)
    at Notifications.browse (/home/coditva/coditva/versions/4.5.0/core/server/services/notifications/notifications.js:42:37)
    at Object.query (/home/coditva/coditva/versions/4.5.0/core/server/api/canary/notifications.js:11:34)
    at Object.query (/home/coditva/coditva/versions/4.5.0/core/server/api/shared/pipeline.js:156:24)
    at /home/coditva/coditva/versions/4.5.0/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)a/versions/4.5.0/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/coditva/coditva/versions/4.5.0/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

Looking into the source, I could find this is because of [this line](https://github.com/TryGhost/Ghost/blob/e9b21fdbd1a19259e8ab55b782668f3b147c72ad/core/server/services/notifications/notifications.js#L26).
I'm not sure if this just need to be checked for safe access or should this not happen at all (which could indicate a problem elsewhere). If it's just a matter of adding a safe check, do let me know. I'll be happy to send a PR. :)

_Nothing is breaking as such, but reporting here just in case._

### To Reproduce

1. Open `{{blogURL}}/ghost`.
2. `tail` the logs file (`content/logs/XXX_production.error.log`) to find this error.

### Technical details:

* Ghost Version: 4.5.0
* Node Version: v12.22.1
* Browser/OS: Linux
* Database: MySQL (version, not sure; will have to check but I don't think it's related)

**Comment by naz** [comment]
Related to https://github.com/TryGhost/Ghost/issues/13088, and has been closed through https://github.com/TryGhost/Ghost/commit/b5fb439ae74d2efe970f16567073ad07c320d84f
