### ISSUE TITLE
Attempt to create or modify table without primary key: ghost_production.benefits

### ISSUE THREAD

**Issue by xoxoxo** [TryGhost/Ghost#13138]
### Issue Summary

After upgrading ghost from 4.8.3 i get this error

from db:
`Attempt to create or modify table without primary key: ghost_production.benefits`

from ghost installation:

```

[2021-07-13 07:23:47] ERROR create table `benefits` (`id` varchar(24) not null, `name` varchar(191) not null, `slug` varchar(191) not null, `created_at` datetime not null, `updated_at` datetime null) default character set utf8mb4 - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

create table `benefits` (`id` varchar(24) not null, `name` varchar(191) not null, `slug` varchar(191) not null, `created_at` datetime not null, `updated_at` datetime null) default character set utf8mb4 - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

{"config":{"transaction":false},"name":"02-add-benefits-table.js"}
"Error occurred while executing the following migration: 02-add-benefits-table.js"

Error ID:
    300

Error Code: 
    UNKNOWN_CODE_PLEASE_REPORT

----------------------------------------

InternalServerError: create table `benefits` (`id` varchar(24) not null, `name` varchar(191) not null, `slug` varchar(191) not null, `created_at` datetime not null, `updated_at` datetime null) default character set utf8mb4 - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
    at DatabaseStateManager.makeReady (/var/www/ghost/versions/4.9.4/core/server/data/db/state-manager.js:98:32)
    at async initDatabase (/var/www/ghost/versions/4.9.4/core/boot.js:57:5)
    at async bootGhost (/var/www/ghost/versions/4.9.4/core/boot.js:320:9)

MigrationScriptError: create table `benefits` (`id` varchar(24) not null, `name` varchar(191) not null, `slug` varchar(191) not null, `created_at` datetime not null, `updated_at` datetime null) default character set utf8mb4 - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
    at MigrationScriptError.KnexMigrateError (/var/www/ghost/versions/4.9.4/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (/var/www/ghost/versions/4.9.4/node_modules/knex-migrator/lib/errors.js:25:26)
    at /var/www/ghost/versions/4.9.4/node_modules/knex-migrator/lib/index.js:1055:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
    at Query.Sequence._packetToError (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at TLSSocket.ondata (internal/streams/readable.js:726:22)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/ghost/versions/4.9.4/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/ghost/versions/4.9.4/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/var/www/ghost/versions/4.9.4/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/var/www/ghost/versions/4.9.4/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/var/www/ghost/versions/4.9.4/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/var/www/ghost/versions/4.9.4/node_modules/knex/lib/runner.js:248:31)
    at /var/www/ghost/versions/4.9.4/node_modules/knex/lib/runner.js:38:25
    at /var/www/ghost/versions/4.9.4/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.up (/var/www/ghost/versions/4.9.4/core/server/data/migrations/utils.js:239:13)

```

### To Reproduce

1. Update ghost from 4.8.3 to 4.9.4

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

OS: Ubuntu, v20.04.2 LTS
Node Version: v14.17.1
Ghost Version: 4.9.4
Ghost-CLI Version: 1.17.3

**Comment by ErisDS** [comment]
Can you please provide the technical details of your database setup? You've deleted the most important line from the issue template 🙈

**Comment by xoxoxo** [comment]
AH yes sorry I am using Digitalocean managed database - MySQL 8.

@ErisDS

**Comment by xoxoxo** [comment]
similar if i connect to new db/cluster

```
Message: Ghost was able to start, but errored during boot with: create table `migrations_lock` (`lock_key` varchar(191) not null, `locked` boolean default '0', `acquired_at` datetime null, `released_at` datetime null) default character set utf8mb4 - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
```

**Comment by xoxoxo** [comment]
in this post https://forum.ghost.org/t/digitalocean-database-connection/20504 its mentioned that primary keys are fixed mi 4.0 but i could not to make it work.
I managed to create a new ghost website using older dump i believe from 4.3.3 and then installing ghost 4.8.3. Seems like something happened between 4.8.3 and newest one.

so seems like bot new website and upgrading to 4.9.3 is broken. Also creating new website from eg. 4.8.3 is also broken. Well only if someone is using a digitalocean cluster. Which kinda sucks.

**Comment by xoxoxo** [comment]
bump

**Comment by matthanley** [comment]
This issue is being tracked over in the knex-migrator repo: https://github.com/TryGhost/knex-migrator/issues/251
