### ISSUE TITLE
Login/Signup via email fails after updating to v4.15: "Sorry, something went wrong. Please try again."

### ISSUE THREAD

**Issue by avimanyu786** [TryGhost/Ghost#13353]
### Issue Summary

Since updating to Ghost 4.15 from 4.13, login/signup via email no longer works. Possibly on v4.14 too. We're using Mailgun. The only workaround we had was to revert to 4.13 to make it work again.

### To Reproduce

1. Update Ghost from version 4.13 to 4.15.
2. Enter email to log in to Ghost blog. 
3. Click on "SEND LOGIN LINK".

The issue is similar to https://github.com/TryGhost/Ghost/issues/7847. The logs reveal "_Failed to send email. Reason: Invalid login: 535 Authentication failed._":

```
[2021-09-22 14:18:30] ERROR Failed to send email. Reason: Invalid login: 535 Authentication failed.

Failed to send email. Reason: Invalid login: 535 Authentication failed.

"Please see https://ghost.org/docs/config/#mail for instructions on configuring email."

Error ID:
f5eeafd0-1baf-11ec-a6b5-3f6b787399fb

Error Code:
EAUTH

----------------------------------------

EmailError: Failed to send email. Reason: Invalid login: 535 Authentication failed.
at createMailError (/var/lib/ghost/versions/4.15.0/core/server/services/mail/GhostMailer.js:59:12)
at GhostMailer.sendMail (/var/lib/ghost/versions/4.15.0/core/server/services/mail/GhostMailer.js:119:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async GhostMailer.send (/var/lib/ghost/versions/4.15.0/core/server/services/mail/GhostMailer.js:105:26)
at async MagicLink.sendMagicLink (/var/lib/ghost/versions/4.15.0/node_modules/@tryghost/magic-link/lib/MagicLink.js:62:22)
at async RouterController.sendMagicLink (/var/lib/ghost/versions/4.15.0/node_modules/@tryghost/members-api/lib/controllers/router.js:248:17)

Error: Invalid login: 535 Authentication failed
at SMTPConnection._formatError (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
at SMTPConnection._actionAUTHComplete (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
at SMTPConnection.<anonymous> (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:540:26)
at SMTPConnection._processResponse (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
at SMTPConnection._onData (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
at TLSSocket.SMTPConnection._onSocketData (/var/lib/ghost/versions/4.15.0/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
at TLSSocket.emit (events.js:400:28)
at addChunk (internal/streams/readable.js:290:12)
at readableAddChunk (internal/streams/readable.js:265:9)
at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Current Technical details:

* Ghost Version: 4.13.0
* Node Version: 14.17.6
* Database: MariaDB 10.5.3
* Docker Version: 20.10.7
* Browser/OS: Firefox 92(client side)/Ubuntu 20.04 Server

**Comment by aprosvetova** [comment]
I confirm this. We also use mailgun and get these errors on Ghost v4.15.0.

**Comment by aprosvetova** [comment]
I'm pretty sure [this commit](https://github.com/TryGhost/Ghost/commit/93e4b2eafd18bc8e4c17924e0824e73617e7940c) is the reason.

**Comment by avimanyu786** [comment]
Thanks @aprosvetova! Hope it gets resolved soon.

**Comment by daniellockyer** [comment]
Hey all! 👋🏻 I believe this would be fixed with [a commit](https://github.com/TryGhost/Ghost/commit/20870aa2faaef57526daa3eb15e429fef3739cf6) in 4.15.1, so please update using Ghost-CLI. If the issue still persists, provide your logs and we'll do our best to fix it. 🙂

**Comment by avimanyu786** [comment]
It was indeed Mailgun relevant (subscription renewal). Everything's working again now on the latest version.
