### ISSUE TITLE
Cannot read property 'product' of undefined

### ISSUE THREAD

**Issue by mnlttt** [TryGhost/Ghost#13741]
### Issue Summary

Cannot get member list when accessing `/ghost/#/members` after upgrading from a previous 4.x version (I'm really sorry but I do not remember which one).

### Steps to Reproduce

1. Go into `https://example.com/ghost/#/members`

### Ghost Version

4.22.1

### Node.js Version

14.18.1

### How did you install Ghost?

ghost-cli un ubuntu 20

### Database type

MySQL 5.7

### Relevant log / error output

```shell
[2021-11-13 16:06:43] ERROR "GET /ghost/api/canary/admin/members/" 500 47ms

NAME: InternalServerError
MESSAGE: Cannot read property 'product' of undefined

level: normal

InternalServerError: Cannot read property 'product' of undefined
    at _private.prepareError (/var/www/ghost/versions/4.22.1/core/server/web/shared/middlewares/error-handler.js:91:19)
    at Layer.handle_error (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/4.22.1/node_modules/express/lib/router/route.js:127:14)
    at /var/www/ghost/versions/4.22.1/core/server/api/shared/http.js:124:17
    at tryCatcher (/var/www/ghost/versions/4.22.1/node_modules/bluebird/js/release/util.js:16:23)

TypeError: Cannot read property 'product' of undefined
    at /var/www/ghost/versions/4.22.1/node_modules/@tryghost/members-api/lib/services/member-bread.js:54:88
    at Array.map (<anonymous>)
    at MemberBREADService.attachSubscriptionsToMember (/var/www/ghost/versions/4.22.1/node_modules/@tryghost/members-api/lib/services/member-bread.js:54:67)
    at /var/www/ghost/versions/4.22.1/node_modules/@tryghost/members-api/lib/services/member-bread.js:320:18
    at Array.map (<anonymous>)
    at MemberBREADService.browse (/var/www/ghost/versions/4.22.1/node_modules/@tryghost/members-api/lib/services/member-bread.js:319:30)
    at async Object.query (/var/www/ghost/versions/4.22.1/core/server/api/canary/members.js:62:26)
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
@mnlttt Could you please share the output of `select * from migrations;` run on your Ghost database? That should help us determine which version you migrated from, and will hopefully help us to replicate the issue!

**Comment by mnlttt** [comment]
@allouis sadly I can't because I deleted the whole server, but I can tell you that I ran an update with the `--force` flag, most likely it was that the reason for these missed migrations. Is there a cli command to run unstarted migrations?

**Comment by allouis** [comment]
Ah okay - that's a shame - so have you completely erased your database? 

I don't think this error is due to missing migrations, but with incorrect Stripe data in the database - I'm looking at a fix for it, but we'd like to try and replicate the issue to determine the exact cause.

**Comment by mnlttt** [comment]
Are migrations included when you export your data? That's everything that's left.

<img width="439" alt="CleanShot 2021-11-26 at 09 11 22@2x" src="https://user-images.githubusercontent.com/37709016/143548232-f5f65814-502d-4d78-8d77-6ac65d6765ef.png">

**Comment by allouis** [comment]
Closed via https://github.com/TryGhost/Members/commit/7f872adb0f8bd085b36039131599de067aef2dd0 and https://github.com/TryGhost/Ghost/commit/c55a138a58937d912b74747aa54abef1b724f536
