### ISSUE TITLE
ghost install local fails with `EBUSY: resource busy or locked, rmdir 'versions\4.34.3`

### ISSUE THREAD

**Issue by sirredbeard** [TryGhost/Ghost#14100]
### Issue Summary

`versions\4.34.3` is still busy or locked when Ghost CLI attempts to remove it when installing with 'ghost install local --no-prompt' causing the installation to fail.

### Steps to Reproduce

1. Install Docker on Windows, either Docker Desktop or manually downloading dockerd.exe and installing as a Windows service.
2. Create a Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2022 as installer
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]
RUN Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing "https://nodejs.org/dist/latest-v14.x/node-v14.19.0-win-x64.zip"
RUN Expand-Archive "nodejs.zip" -DestinationPath "C:\\"
RUN Rename-Item "C:\\node-v14.19.0-win-x64" c:\nodejs

FROM mcr.microsoft.com/windows/nanoserver:1803
USER ContainerAdministrator
WORKDIR C:\\nodejs
COPY --from=installer C:\\nodejs\\ .
RUN SETX PATH C:\\nodejs
RUN npm install ghost-cli@latest -g
RUN mkdir C:\\ghost
WORKDIR C:\\ghost
RUN ghost install local --no-prompt --verbose
```
3. In the directory of your Dockerfile, run `docker build -t ghost .`
4. A local ghost installation should install in the Windows Container.

### Ghost Version

4.34.3

### Node.js Version

14.19.0

### How did you install Ghost?

Windows 11

### Database type

SQLite3

### Relevant log / error output

```shell
An error occurred.
Message: 'EBUSY: resource busy or locked, rmdir 'versions\4.34.3''

Stack: Error: EBUSY: resource busy or locked, rmdir 'versions\4.34.3'
    at Object.rmdirSync (fs.js:916:10)
    at rmdirSync (C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:264:13)
    at rimrafSync (C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:26)
    at rmdirSync (C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:269:7)
    at Object.rimrafSync [as removeSync] (C:\nodejs\node_modules\ghost-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\nodejs\node_modules\ghost-cli\lib\commands\install.js:152:44
    at Array.map (<anonymous>)
    at InstallCommand.cleanInstallDirectory (C:\nodejs\node_modules\ghost-cli\lib\commands\install.js:152:29)
    at InstallCommand.run (C:\nodejs\node_modules\ghost-cli\lib\commands\install.js:80:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function._run (C:\nodejs\node_modules\ghost-cli\lib\command.js:190:13)
Code: EBUSY
Path: versions\4.34.3

[16:03:52] Installing dependencies [failed]
[16:03:52] → stdout maxBuffer exceeded
[16:03:52] Downloading and installing Ghost v4.34.3 [failed]
[16:03:52] → stdout maxBuffer exceeded
Debug Information:
    OS: , v10.0.17134
    Node Version: v14.19.0
    Ghost-CLI Version: 1.18.1
    Environment: development
    Command: 'ghost install local --no-prompt --verbose'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sirredbeard** [comment]
I can no longer reproduce. (ㆆ_ㆆ)
