### ISSUE TITLE
Query Error: unexpected character in filter at char 7

### ISSUE THREAD

**Issue by reinismu** [TryGhost/Ghost#14279]
### Issue Summary

Updated my blog from v3.{most up to date} to v4.37.0 and now this error shows up in logs. Blog itself still works fine.

I use MariaDB

### Steps to Reproduce

Take v3 blog and update to v4.37.0

### Ghost Version

v4.37.0

### Node.js Version

Using docker. so same as there

### How did you install Ghost?

Docker

### Database type

Other

### Relevant log / error output

```shell
: Query Error: unexpected character in filter at char 7
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/4.37.0/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:66:23)
(tags:[]+id:-)+type:post
-------^
Expecting 'NULL'
, 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'
    at Parser.parser.parseError (/var/lib/ghost/versions/4.37.0/node_modules/@nexes/nql-lang/dist/parser.js:328:12)
    at Parser.parse (/var/lib/ghost/versions/4.37.0/node_modules/@nexes/
nql-lang/dist/parser.js:245:22)
    at Object.exports.parse (/var/lib/ghost/versions/4.37.0/node_modules/@nexes/nql-lang/lib/nql.js:18:44)
    at Object.api.parse (/var/lib/ghost/versions/4.37.0/node_modules/@nexes/nql/lib/nql.js:15:31)
    at Object.a
pi.querySQL (/var/lib/ghost/versions/4.37.0/node_modules/@nexes/nql/lib/nql.js:49:44)
    at Builder.<anonymous> (/var/lib/ghost/versions/4.37.0/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:63:24)
    at Object.query (/var/lib/ghost/v
ersions/4.37.0/node_modules/bookshelf/lib/helpers.js:164:14)
    at Child.query (/var/lib/ghost/versions/4.37.0/node_modules/bookshelf/lib/model.js:1387:22)
    at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/4.37.0/node_modules/@tryghost
/bookshelf-filter/lib/bookshelf-filter.js:56:22)
    at Function.getFilteredCollection (/var/lib/ghost/versions/4.37.0/core/server/models/base/plugins/filtered-collection.js:13:32)
    at Function.findPage (/var/lib/ghost/versions/4.37.0/core/server/mod
els/base/plugins/crud.js:73:41)
    at Object.query (/var/lib/ghost/versions/4.37.0/core/server/api/canary/posts-public.js:37:32)
    at Object.query (/var/lib/ghost/versions/4.37.0/core/server/api/shared/pipeline.js:156:24)
    at /var/lib/ghost/versi
ons/4.37.0/core/server/api/shared/pipeline.js:243:35
    at tryCatcher (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/rele
ase/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/promise.js:649:10)

    at Promise._settlePromises (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost
/versions/4.37.0/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/4.37.0/node_modules/bluebird/js/release/async.js:102:5)"},"msg":"Error parsing filter","time":"2022-03-08T06:25:03.592Z","v":0}
{"name":"Log","hostname":"0f8093ff3bf9","pid":1,"level":50,"err":{"id":"7dd10f30-9ea8-11ec-ad54-0d75a1389bf2","domain":"https://examle.lv","code":null,"name":"BadRequestError","statusCode":400,"level":"normal","message":"Error parsing filter","stack":"Error
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
What theme are you using? Did you also update the theme to a v4 compatible version?

**Comment by reinismu** [comment]
I used the Casper before, but I switched to Ruby.

Ye now that I check my other blog that is using liebling it doesn't produce such error.

Seems like the issue is in Ruby theme

**Comment by ErisDS** [comment]
Definitely a Ruby theme issue.

`(tags:[]+id:-)+type:post` is not a valid filter as there are no values. Seems like they've done this in the wrong place.

**Comment by cathysarisky** [comment]
This error is still present, and a specific problem with the ruby theme.  If someone has a moment, please point me at the right place to file this bug.

**Comment by cathysarisky** [comment]
I just downloaded the latest version of Ruby and this problem is no longer there.  Anyone seeing the same problem might want to download a NEW copy of Ruby.  My old copy did exactly the behavior described above.
