### ISSUE TITLE
Failed migration on update to 4.40.0

### ISSUE THREAD

**Issue by leifurhauks** [TryGhost/Ghost#14343]
### Issue Summary

On updating to version 4.40.0, this database migration failed: https://github.com/TryGhost/Ghost/blob/main/core/server/data/migrations/versions/4.40/2022-03-07-14-37-add-members-cancel-events-table.js

Log output is below.

This occurred initially on an update from 4.36.2 to 4.40.0. I had run `ghost doctor` before the update. After the update failed, I instead updated, successfully, to 4.39.0. Subsequently, attempting to update to 4.40.0 reproduced the same error.

I encountered the same problem on a second ghost blog hosted on the same VPS. 

Ghost-CLI version:
```
$ ghost version
Ghost-CLI version: 1.17.3
Ghost version: 4.39.0 (at ****************)
```

MySQL version:
```
$ mysqld --version
/usr/sbin/mysqld  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))
```

### Steps to Reproduce

1. Using Ghost-CLI, run `ghost update 4.40.0`. The error occurred while updating from 4.36.2 or from 4.39.0. 

### Ghost Version

4.40.0 (on update)

### Node.js Version

v14.19.1

### How did you install Ghost?

Ghost-CLI on Ubuntu 20.04 (updated from a previous Ubuntu LTS release), VPS on DigitalOcean

### Database type

MySQL 8

### Relevant log / error output

```shell
Mar 18 19:25:05 ghost node[195117]: [2022-03-18 23:25:05] INFO Bootstrap client was closed.
Mar 18 19:27:24 ghost systemd[1]: Stopping Ghost systemd service for blog: ***************...
Mar 18 19:27:24 ghost node[195117]: [2022-03-18 23:27:24] WARN Ghost is shutting down
Mar 18 19:27:24 ghost node[195117]: [2022-03-18 23:27:24] WARN Ghost has shut down
Mar 18 19:27:24 ghost node[195117]: [2022-03-18 23:27:24] WARN Your site is now offline
Mar 18 19:27:24 ghost node[195117]: [2022-03-18 23:27:24] WARN Ghost was running for 2 minutes
Mar 18 19:27:24 ghost systemd[1]: ghost_***************.service: Succeeded.
Mar 18 19:27:24 ghost systemd[1]: Stopped Ghost systemd service for blog: ***************.
Mar 18 19:27:24 ghost systemd[1]: Started Ghost systemd service for blog: ***************.
Mar 18 19:27:25 ghost node[195552]: - Inspecting operating system
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Ghost is running in production...
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Your site is now available on https://********************
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Ctrl+C to shut down
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Ghost server started in 0.531s
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Bootstrap client was closed.
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] WARN Database state requires migration.
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Creating database backup
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Database backup written to: ********************************************************************************
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Running migrations.
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Backfilling the members.last_seen_at column from members_login_events.
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Adding products.visibility column
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] WARN Removing products.visible column - skipping as table is correct
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Updating free products to visible
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Updating 1 products to visible, 60948e60936fe947a10efd6d
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Adding table: members_cancel_events
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Rolling back: alter table `members_cancel_events` add constraint `members_cancel_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_cancel_events_member_id_foreign' are incompatible..
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Dropping table: members_cancel_events
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Updating portal_products to ["60948e60936fe947a10efd6d","621000fc8bfe3e41f2b1dbdb"]
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Updating portal_plans to ["monthly","yearly"]
Mar 18 19:27:26 ghost node[195583]: [2022-03-18 23:27:26] INFO Removing products.visibility column
Mar 18 19:27:27 ghost node[195583]: [2022-03-18 23:27:27] WARN Removing products.visible column - skipping as table is correct
Mar 18 19:27:27 ghost node[195583]: [2022-03-18 23:27:27] INFO Rolling back the backfilling of the members.last_seen_at column from members_login_events.
Mar 18 19:27:27 ghost node[195583]: [2022-03-18 23:27:27] INFO Rollback was successful.
Mar 18 19:27:27 ghost node[195583]: [2022-03-18 23:27:27] ERROR alter table `members_cancel_events` add constraint `members_cancel_events_me
mber_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced col
umn 'id' in foreign key constraint 'members_cancel_events_member_id_foreign' are incompatible.
Mar 18 19:27:27 ghost node[195583]: 
Mar 18 19:27:27 ghost node[195583]: alter table `members_cancel_events` add constraint `members_cancel_events_member_id_foreign` foreign key
 (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key cons
traint 'members_cancel_events_member_id_foreign' are incompatible.
Mar 18 19:27:27 ghost node[195583]: {"config":{"transaction":false},"name":"2022-03-07-14-37-add-members-cancel-events-table.js"}
Mar 18 19:27:27 ghost node[195583]: "Error occurred while executing the following migration: 2022-03-07-14-37-add-members-cancel-events-tabl
e.js"
Mar 18 19:27:27 ghost node[195583]: Error ID:
Mar 18 19:27:27 ghost node[195583]:     300
Mar 18 19:27:27 ghost node[195583]: ----------------------------------------
Mar 18 19:27:27 ghost node[195583]: MigrationScriptError: alter table `members_cancel_events` add constraint `members_cancel_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_cancel_events_member_id_foreign' are incompatible.
Mar 18 19:27:27 ghost node[195583]:     at DatabaseStateManager.makeReady (****************/versions/4.40.0/core/server/data/db/state-manager.js:95:32)
Mar 18 19:27:27 ghost node[195583]:     at MigrationScriptError.KnexMigrateError (****************/versions/4.40.0/node_modules/knex-migrator/lib/errors.js:7:26)
Mar 18 19:27:27 ghost node[195583]:     at new MigrationScriptError (****************/versions/4.40.0/node_modules/knex-migrator/lib/errors.js:25:26)
Mar 18 19:27:27 ghost node[195583]:     at ****************/versions/4.40.0/node_modules/knex-migrator/lib/index.js:1032:19
Mar 18 19:27:27 ghost node[195583]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Mar 18 19:27:27 ghost node[195583]: Error: alter table `members_cancel_events` add constraint `members_cancel_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_cancel_events_member_id_foreign' are incompatible.
Mar 18 19:27:27 ghost node[195583]:     at Packet.asError (****************/versions/4.40.0/node_modules/mysql2/lib/packets/packet.js:728:17)
Mar 18 19:27:27 ghost node[195583]:     at Query.execute (****************/versions/4.40.0/node_modules/mysql2/lib/commands/command.js:29:26)
Mar 18 19:27:27 ghost node[195583]:     at Connection.handlePacket (****************/versions/4.40.0/node_modules/mysql2/lib/connection.js:456:32)
Mar 18 19:27:27 ghost node[195583]:     at PacketParser.onPacket (****************/versions/4.40.0/node_modules/mysql2/lib/connection.js:85:12)
Mar 18 19:27:27 ghost node[195583]:     at PacketParser.executeStart (****************/versions/4.40.0/node_modules/mysql2/lib/packet_parser.js:75:16)
Mar 18 19:27:27 ghost node[195583]:     at Socket.<anonymous> (****************/versions/4.40.0/node_modules/mysql2/lib/connection.js:92:25)
Mar 18 19:27:27 ghost node[195583]:     at Socket.emit (events.js:400:28)
Mar 18 19:27:27 ghost node[195583]:     at addChunk (internal/streams/readable.js:293:12)
Mar 18 19:27:27 ghost node[195583]:     at readableAddChunk (internal/streams/readable.js:267:9)
Mar 18 19:27:27 ghost node[195583]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Mar 18 19:27:27 ghost node[195583]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by leifurhauks** [comment]
I just noticed that there is a more recent version of Ghost-CLI. I will try with the latest Ghost-CLI and report back.

**Comment by leifurhauks** [comment]
Repeated the update with Ghost-CLI version 1.18.2, the result was the same.

**Comment by leifurhauks** [comment]
Also, in case it helps, this is the output for `SHOW CREATE TABLE members` in MySQL:
```sql
  members | CREATE TABLE `members` (
  `id` varchar(24) COLLATE utf8mb4_general_ci NOT NULL,
  `uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email` varchar(191) COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `note` varchar(2000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `geolocation` varchar(2000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `subscribed` tinyint(1) DEFAULT '1',
  `created_at` datetime NOT NULL,
  `created_by` varchar(24) COLLATE utf8mb4_general_ci NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by` varchar(24) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email_open_rate` int unsigned DEFAULT NULL,
  `email_count` int unsigned NOT NULL DEFAULT '0',
  `email_opened_count` int unsigned NOT NULL DEFAULT '0',
  `status` varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'free',
  `last_seen_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `members_email_unique` (`email`),
  UNIQUE KEY `members_uuid_unique` (`uuid`),
  KEY `members_email_open_rate_index` (`email_open_rate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

**Comment by ErisDS** [comment]
This is due to your ubuntu upgrade also upgrading you from mysql 5 -> 8.

Please check out our FAQ page: https://ghost.org/docs/faq/troubleshooting-mysql-database/

If you have further questions about resolving the problem please ask on the forum :)
