### ISSUE TITLE
Ghost Application Doesn't Save Any Settings Once Saved, then Reentering Page

### ISSUE THREAD

**Issue by GSY-PI** [TryGhost/Ghost#14341]
### Issue Summary

When applying settings text or uploading an asset like logo, it displays on the page after clicking save. Once entering the page the change is lost.

### Steps to Reproduce

Change any setting, click and reload the page.

### Ghost Version

4.39.1

### Node.js Version

v16.14.0

### How did you install Ghost?

Self Hosted, Ubuntu 20 with Openlitespeed Proxy

### Database type

MySQL 5.7

### Browser & OS version

Server version: 10.3.34-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

### Relevant log / error output

```shell
// ERROR LOGS

tack":"ValidationError: Unknown setting: show_share_links.\n    at CustomThemeSettingsService.updateSettings (/home/rrblog-ghost/versions/4.39.1/node_modules/@tryghost/custom-theme-settings-service/lib/service.js:66:19)\n    at Object.query (/home/rrblog-ghost/versions/4.39.1/core/server/api/canary/custom-theme-settings.js:19:51)\n    at Object.query (/home/rrblog-ghost/versions/4.39.1/core/server/api/shared/pipeline.js:156:24)\n    at /home/rrblog-ghost/versions/4.39.1/core/server/api/shared/pipeline.js:243:35\n    at tryCatcher (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (node:internal/timers:466:21)"},"msg":"Unknown setting: show_share_links.","time":"2022-03-18T18:48:55.684Z","v":0}
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":50,"req":{"meta":{"requestId":"ee3d14bb-b02c-4c55-8490-706e248a06d2","userId":"1"},"url":"/custom_theme_settings/","method":"PUT","originalUrl":"/ghost/api/admin/custom_theme_settings/","params":{},"headers":{"host":"revrebel.blog","content-type":"application/json; charset=utf-8","accept":"application/json, text/javascript, */*; q=0.01","accept-version":"v4","x-requested-with":"XMLHttpRequest","app-pragma":"no-cache","accept-language":"en-US,en;q=0.9","accept-encoding":"gzip","origin":"https://revrebel.blog","content-length":"762","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15","referer":"https://revrebel.blog/ghost/","x-ghost-version":"4.39","cookie":"**REDACTED**","x-forwarded-host":"revrebel.blog","x-forwarded-proto":"https","x-forwarded-for":"68.7.130.10"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"https://revrebel.blog","vary":"Origin, Accept-Encoding","content-type":"application/json; charset=utf-8","content-length":"249","etag":"W/\"f9-1VsOzLopMkZF893OXGNcHp/q/IA\""},"statusCode":422,"responseTime":"104ms"},"err":{"id":"1350d540-a6ec-11ec-a267-3d9cafe30c1b","domain":"https://revrebel.blog","code":null,"name":"ValidationError","statusCode":422,"level":"normal","message":"Unknown setting: show_share_links.","stack":"ValidationError: Unknown setting: show_share_links.\n    at CustomThemeSettingsService.updateSettings (/home/rrblog-ghost/versions/4.39.1/node_modules/@tryghost/custom-theme-settings-service/lib/service.js:66:19)\n    at Object.query (/home/rrblog-ghost/versions/4.39.1/core/server/api/canary/custom-theme-settings.js:19:51)\n    at Object.query (/home/rrblog-ghost/versions/4.39.1/core/server/api/shared/pipeline.js:156:24)\n    at /home/rrblog-ghost/versions/4.39.1/core/server/api/shared/pipeline.js:243:35\n    at tryCatcher (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues (/home/rrblog-ghost/versions/4.39.1/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (node:internal/timers:466:21)"},"msg":"Unknown setting: show_share_links.","time":"2022-03-18T18:49:00.824Z","v":0}
nodejs% 



e":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"8e701b31-fdaa-4e89-91f2-763078aec9a1","userId":null},"url":"/","method":"POST","originalUrl":"/","params":{},"headers":{"host":"revrebel.blog","accept":"text/plain","content-type":"text/html;charset=utf-8">
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"7a20c1ce-749b-4c31-9dc1-762bf6eb1e7d","userId":null},"url":"/size/w600/2022/03/-RR-BLOG-by-REVREBEL-5.png","method":"GET","originalUrl":"/content/images/size/w600/2022/03/-RR-BLOG-by-REVREBEL-5.png","param>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"296ae266-c5eb-4d83-8f9b-746f445b65d7","userId":"1"},"url":"/settings/","method":"PUT","originalUrl":"/ghost/api/admin/settings/","params":{},"headers":{"host":"revrebel.blog","content-type":"application/js>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"afbb2200-f889-44b7-8661-a1edb1aea0e0","userId":"1"},"url":"/custom_theme_settings/","method":"PUT","originalUrl":"/ghost/api/admin/custom_theme_settings/","params":{},"headers":{"host":"revrebel.blog","con>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"526d2bcb-8683-4455-a560-30dc4e6c25ed","userId":null},"url":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","method":"GET","originalUrl":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"910d0137-aae0-43d2-9995-7fc7690174ec","userId":null},"url":"/?v=1647629908575","method":"GET","originalUrl":"/?v=1647629908575","params":{},"headers":{"host":"revrebel.blog","accept":"text/html,application>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"4ff2258f-d82e-490b-8791-e8087fd314a2","userId":null},"url":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","method":"GET","originalUrl":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"4e271113-9c7e-47a6-bc3b-202bba8d327f","userId":"1"},"url":"/settings/","method":"PUT","originalUrl":"/ghost/api/admin/settings/","params":{},"headers":{"host":"revrebel.blog","content-type":"application/js>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"f8aff34e-e56a-45c4-9f5b-b872f8380ad9","userId":null},"url":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","method":"GET","originalUrl":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"183d7ccb-17bc-46c9-be4f-7084820d7970","userId":"1"},"url":"/products/62321a1d6a408a4a233eff7a/","method":"PUT","originalUrl":"/ghost/api/admin/products/62321a1d6a408a4a233eff7a/","params":{"id":"62321a1d6a>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"00d33a29-8e23-4c4f-8462-a278a5085c57","userId":"1"},"url":"/images/upload/","method":"POST","originalUrl":"/ghost/api/admin/images/upload/","params":{},"headers":{"host":"revrebel.blog","content-type":"mul>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"3df80cc7-5096-4b7f-87e8-7f2546b160e7","userId":null},"url":"/2022/03/icon-circle-white-3.png","method":"GET","originalUrl":"/content/images/2022/03/icon-circle-white-3.png","params":{},"headers":{"host":"r>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"553ed798-ee2e-4335-817c-e2df02a7313c","userId":"1"},"url":"/settings/","method":"PUT","originalUrl":"/ghost/api/admin/settings/","params":{},"headers":{"host":"revrebel.blog","content-type":"application/js>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"905f07e8-e08a-4e8d-92c4-9fc0b852d6b8","userId":null},"url":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","method":"GET","originalUrl":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"e93b93e2-d7f0-4e6a-b8d0-adb20a69844e","userId":null},"url":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","method":"GET","originalUrl":"/content/images/11lm42jZKDWAwoP8uKF8ap_ZVJzYV2CnL.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"dcfd6bd5-c195-4a2a-b11c-2d2eeae944ff","userId":"1"},"url":"/settings/","method":"PUT","originalUrl":"/ghost/api/admin/settings/","params":{},"headers":{"host":"revrebel.blog","content-type":"application/js>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"c40a59c1-c260-4d7b-8a0d-1f2be217fdc3","userId":"1"},"url":"/products/62321a1d6a408a4a233eff7a/","method":"PUT","originalUrl":"/ghost/api/admin/products/62321a1d6a408a4a233eff7a/","params":{"id":"62321a1d6a>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"bfdfc885-599d-458d-a42f-5540a9e33ed9","userId":"1"},"url":"/custom_theme_settings/","method":"GET","originalUrl":"/ghost/api/admin/custom_theme_settings/","params":{},"headers":{"host":"revrebel.blog","con>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"1c1e0da0-94ac-4629-8e52-7ebd53e6a151","userId":null},"url":"/","method":"POST","originalUrl":"/","params":{},"headers":{"host":"revrebel.blog","accept":"text/plain","content-type":"text/html;charset=utf-8">
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"cf9a8fc1-c1f1-4d39-a0d9-1cd9d24b3251","userId":null},"url":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","method":"GET","originalUrl":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"2cedadf3-3435-42ff-b160-fccaf749eecf","userId":null},"url":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","method":"GET","originalUrl":"/content/images/1jzj8sG1LkUU6hVvo1c1WN2O9YQXMcuwv.png","head>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"bba542e5-a888-48a9-8c95-af5a6dcb1eaa","userId":null},"url":"/","method":"GET","originalUrl":"/","params":{},"headers":{"host":"revrebel.blog","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWe>
{"name":"Log","hostname":"nodejs.revrebel.cloud","pid":836677,"level":30,"req":{"meta":{"requestId":"64d4bbd9-cbdc-4a3f-8ec1-08ceea149c69","userId":null},"url":"/favicon.ico","method":"GET","originalUrl":"/favicon.ico","params":{},"headers":{"host":"revrebel.blog","user-agent":"Mozilla/5.0 (Windows NT 10.>

// config.production.json

{
  "url": "https://revrebel.blog",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "REMOVE FOR POST,
      "user": "REMOVE FOR POST",
      "password": REMOVE FOR POST",
      "database": "rrblogdb"
    }
  },
  "mail": {
    "transport": "SMTP",
    "options": {
      "service": "Mailgun",
      "host": "smtp.mailgun.org",
      "port": 587,
      "auth": {
        "user": "REMOVE FOR POST",
        "pass": "REMOVED FOR PSOT"
      }
    }
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "privacy": {
    "useTinfoil": true
  },
  "imageOptimization": {
    "resize": false
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/home/rrblog-ghost/content"
  }
}


// OPENLITESPEED PROXY VCONF

docRoot                   /$VH_ROOT/current/
vhDomain                  blog.revrebel.io
vhAliases                 www.blog.revrebel.io
enableGzip                1
enableIpGeo               1

errorlog $VH_ROOT/logs/rrblog-error.log {
  useServer               0
  logLevel                DEBUG
  rollingSize             10m
  keepDays                120
  compressArchive         1
}

accesslog $VH_ROOT/logs/revrebel.io.access_log {
  useServer               0
  logFormat               "%h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i""
  logHeaders              5
  rollingSize             10M
  keepDays                30
  compressArchive         1
}

index  {
  useServer               0
  indexFiles              index.html, index.php, index.js
}

errorpage 404 {
  url                     /home/.error_pages/404.html
}

errorpage 403 {
  url                     /home/.error_pages/403.html
}

errorpage 502 {
  url                     /home/.error_pages/502.html
}

accessControl  {
  allow                   *
}

extprocessor blog {
  type                    proxy
  address                 0.0.0.0:2368
  maxConns                500
  initTimeout             30
  retryTimeout            3
  respBuffer              0
}

context / {
  type                    proxy
  handler                 blog

  accessControl  {
    allow                 *
  }
  addDefaultCharset       on
  defaultCharsetCustomized utf-8
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  logLevel                9
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/revrebel.blog/privkey.pem
  certFile                /etc/letsencrypt/live/revrebel.blog/fullchain.pem
  certChain               1
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling          1
  ocspRespMaxAge          86400
}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by GSY-PI** [comment]
The issue seems to be with the remote SQL server, when I use a local SQL server with the same settings except localhost there are no issues. But when using a remote sql connection the issue reappears.
