### ISSUE TITLE
SSL profile must be an object, instead it's a boolean.

### ISSUE THREAD

**Issue by fisheyemh** [TryGhost/Ghost#14362]
### Issue Summary

Hi,
i'm running ghost on a docker image on azure, we updated to the latest image from ghost docker hub, and i get this error:

**SSL profile must be an object, instead it's a boolean**

```
2022-03-22T14:03:58.730522383Z [2022-03-22 14:03:58] [36mINFO[39m Ghost is running in development...
2022-03-22T14:03:58.733007298Z [2022-03-22 14:03:58] [36mINFO[39m Listening on: 0.0.0.0:2368
2022-03-22T14:03:58.734204806Z [2022-03-22 14:03:58] [36mINFO[39m Url configured as: https://test.******.it/
2022-03-22T14:03:58.735335913Z [2022-03-22 14:03:58] [36mINFO[39m Ctrl+C to shut down
2022-03-22T14:03:58.739018136Z [2022-03-22 14:03:58] [36mINFO[39m Ghost server started in 1.159s
2022-03-22T14:03:59.050766991Z [2022-03-22 14:03:59] [31mERROR[39m SSL profile must be an object, instead it's a boolean
2022-03-22T14:03:59.050818491Z [31m
2022-03-22T14:03:59.050824391Z [31mSSL profile must be an object, instead it's a boolean[39m
2022-03-22T14:03:59.050828591Z
2022-03-22T14:03:59.050832291Z [33m"Unknown database error"[39m
2022-03-22T14:03:59.050836291Z
2022-03-22T14:03:59.050839991Z [1m[37mError ID:[39m[22m
2022-03-22T14:03:59.050843891Z     [90m500[39m
2022-03-22T14:03:59.050847691Z
2022-03-22T14:03:59.050851191Z [90m----------------------------------------[39m
2022-03-22T14:03:59.050855091Z
2022-03-22T14:03:59.050858591Z [90mDatabaseError: SSL profile must be an object, instead it's a boolean
2022-03-22T14:03:59.050868691Z     at DatabaseStateManager.getState (/var/lib/ghost/versions/4.39.1/core/server/data/db/state-manager.js:64:32)
2022-03-22T14:03:59.050873191Z     at DatabaseError.KnexMigrateError (/var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/lib/errors.js:7:26)
2022-03-22T14:03:59.050876991Z     at new DatabaseError (/var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/lib/errors.js:55:26)
2022-03-22T14:03:59.050880691Z     at /var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/lib/database.js:56:19
2022-03-22T14:03:59.050884591Z     at async DatabaseStateManager.getState (/var/lib/ghost/versions/4.39.1/core/server/data/db/state-manager.js:40:13)
2022-03-22T14:03:59.050888492Z     at async DatabaseStateManager.makeReady (/var/lib/ghost/versions/4.39.1/core/server/data/db/state-manager.js:73:25)
2022-03-22T14:03:59.050892192Z     at async initDatabase (/var/lib/ghost/versions/4.39.1/core/boot.js:60:5)
2022-03-22T14:03:59.050895892Z     at async bootGhost (/var/lib/ghost/versions/4.39.1/core/boot.js:394:9)
2022-03-22T14:03:59.050899592Z
2022-03-22T14:03:59.050903192Z TypeError: SSL profile must be an object, instead it's a boolean
2022-03-22T14:03:59.050906992Z     at new ConnectionConfig (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/lib/connection_config.js:135:15)
2022-03-22T14:03:59.050910692Z     at Object.exports.createConnection (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/index.js:10:35)
2022-03-22T14:03:59.050914392Z     at /var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:64:38
2022-03-22T14:03:59.050928492Z     at new Promise (<anonymous>)
2022-03-22T14:03:59.050932592Z     at Client_MySQL2.acquireRawConnection (/var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:63:12)
2022-03-22T14:03:59.050936492Z     at create (/var/lib/ghost/versions/4.39.1/node_modules/knex-migrator/node_modules/knex/lib/client.js:290:39)[39m
2022-03-22T14:03:59.050940492Z [39m
2022-03-22T14:03:59.054405314Z [2022-03-22 14:03:59] [35mWARN[39m Ghost is shutting down
2022-03-22T14:03:59.061860060Z [2022-03-22 14:03:59] [35mWARN[39m Ghost has shut down
2022-03-22T14:03:59.063893773Z [2022-03-22 14:03:59] [35mWARN[39m Ghost was running for a few seconds
```

On my development.config.json the ssl is set to true like it's told in the ghost docs under database configuration, but it seems this option is no longer valid, i already tried to pass this object under ssl:
```
"ssl": {
	"rejectUnauthorized": true
	}
```

but then i get another error:

```
2022-03-22T14:16:38.189229477Z [2022-03-22 14:16:38] [36mINFO[39m Ghost is running in development...
2022-03-22T14:16:38.192009762Z [2022-03-22 14:16:38] [36mINFO[39m Listening on: 0.0.0.0:2368
2022-03-22T14:16:38.193449306Z [2022-03-22 14:16:38] [36mINFO[39m Url configured as: https://test.******.it/
2022-03-22T14:16:38.194494138Z [2022-03-22 14:16:38] [36mINFO[39m Ctrl+C to shut down
2022-03-22T14:16:38.198184052Z [2022-03-22 14:16:38] [36mINFO[39m Ghost server started in 1.318s
2022-03-22T14:16:39.331890759Z [2022-03-22 14:16:39] [35mWARN[39m Database state requires migration.
2022-03-22T14:16:39.433188269Z events.js:377
2022-03-22T14:16:39.433216869Z       throw er; // Unhandled 'error' event
2022-03-22T14:16:39.433221569Z       ^
2022-03-22T14:16:39.433224969Z
2022-03-22T14:16:39.433228169Z Error: read ECONNRESET
2022-03-22T14:16:39.433231669Z     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2022-03-22T14:16:39.433235169Z Emitted 'error' event on Connection instance at:
2022-03-22T14:16:39.433238569Z     at Connection._notifyError (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/lib/connection.js:236:12)
2022-03-22T14:16:39.433243969Z     at Connection._handleFatalError (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/lib/connection.js:167:10)
2022-03-22T14:16:39.433247369Z     at Connection._handleNetworkError (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/lib/connection.js:180:10)
2022-03-22T14:16:39.433250769Z     at TLSSocket.<anonymous> (/var/lib/ghost/versions/4.39.1/node_modules/mysql2/lib/connection.js:350:14)
2022-03-22T14:16:39.433259769Z     at TLSSocket.emit (events.js:400:28)
2022-03-22T14:16:39.433262969Z     at TLSSocket._tlsError (_tls_wrap.js:897:8)
2022-03-22T14:16:39.433266269Z     at TLSSocket.emit (events.js:400:28)
2022-03-22T14:16:39.433269569Z     at emitErrorNT (internal/streams/destroy.js:106:8)
2022-03-22T14:16:39.433272869Z     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
2022-03-22T14:16:39.433276169Z     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
2022-03-22T14:16:39.433279469Z   errno: -104,
2022-03-22T14:16:39.433282669Z   code: 'ECONNRESET',
2022-03-22T14:16:39.433285969Z   syscall: 'read',
2022-03-22T14:16:39.433289469Z   fatal: true
2022-03-22T14:16:39.433292769Z }
```

This is my development config file
```

{
  "paths": {
	"contentPath": "/var/lib/ghost/content/"
  },

  "database": {
	"client": "mysql",
        "connection": {
            "host": "***.mysql.database.azure.com",
            "port": 3306,
            "user": "***@****",
            "password": "*****",
            "database": "*****",
	    "ssl": true
        }
  },
  "logging": {
	"transports": ["stdout"]
  }
}

```

Thank in advance for the help!

### Steps to Reproduce

1. Pull latest docker image
2. Run it connected to a mySQL server with "ssl" : true

### Ghost Version

4.39.1

### Node.js Version

node:14-alpine3.14

### How did you install Ghost?

It's running as a docker container

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by fisheyemh** [comment]
Hey @ErisDS I'm quite sure this is a bug, i followed your documentation, it says that azure database for mysql is in Mozilla RDS trusted sources and to use a boolean value true. But that isn't working it looks like a bug to me, if it's not then maybe there's something missing in the docs. May you please take a second to reconsider?

**Comment by fisheyemh** [comment]
@daniellockyer Glad to be helpful, thanks for the help.

**Comment by jmaitrehenry** [comment]
You can also use `ssl: {minVersion: 'TLSv1.2'}` if you do not want to put the CA.

**Comment by Babug01** [comment]
I'm getting this issue with ghost version v5.60.0 in azure
Attached logs for reference:
[ghost_error.txt](https://github.com/TryGhost/Ghost/files/12446783/ghost_error.txt)

These are the configuration i have passed as part of app service settings
    // Ghost-specific settings
    NODE_ENV: 'production'
    GHOST_CONTENT: containerMountPath
    paths__contentPath: containerMountPath
    privacy_useUpdateCheck: 'false'
    url: siteUrl
    database__client: 'mysql'
    database__connection__host: databaseHostFQDN
    database__connection__user: databaseLogin
    database__connection__password: '@Microsoft.KeyVault(SecretUri=${databasePasswordSecretUri})'
    database__connection__database: databaseName
    database__connection__ssl: 'true'
    database__connection__ssl_minVersion: 'TLSv1.2'


Is this issue fixed on any version of the ghost?
