### ISSUE TITLE
Can not run any ghost4 images under linux docker

### ISSUE THREAD

**Issue by stamepicmorg** [TryGhost/Ghost#14492]
## My compose config

````
  mysql8-native:
    container_name: mysql8-native
    hostname: mysql8-native
    image: mysql:8
    ports:
        - "0.0.0.0:3308:3306"
    volumes:
      - /mnt/docker/database/shared/mysql8.0/etc/mysql/my.cnf:/etc/mysql/my.cnf
      - /mnt/docker/database/shared/mysql8.0/var/lib/mysql:/var/lib/mysql
      - /mnt/docker/database/shared/mysql8.0/var/log/mysql:/var/log/mysql
      - /mnt/docker/database/shared/mysql8.0/var/lib/mysql-files:/var/lib/mysql-files
    restart: always
    environment:
      INIT_TOKUDB: 1
      MYSQL_ROOT_PASSWORD: password
    tmpfs:
      - /tmp

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    restart: always
    privileged: true
    ports:
      - 2368:2368
    depends_on:
      - mysql8-native
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql8-native
      database__connection__database: ghost
      database__connection__user: ghost
      database__connection__password: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://news.antinomy-collective.org
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: production
    volumes:
      - /mnt/docker/services/shared/ghost:/var/lib/ghost/content
````

## Error log
`````
[2022-04-16 16:46:46] ERROR (Code: -97)

(Code: -97)

"There was an error starting your server."
 "Please use the error code above to search for a solution."

 Error ID:
     cd9d5850-bda4-11ec-a989-9d00a94dc17e

 ----------------------------------------

 InternalServerError: (Code: -97)
     at Server.<anonymous> (/var/lib/ghost/versions/4.41.3/core/server/ghost-server.js:116:34)
     at Server.emit (events.js:400:28)
     at emitErrorNT (net.js:1358:8)
     at processTicksAndRejections (internal/process/task_queues.js:82:21)

 [2022-04-16 16:46:46] WARN Ghost is shutting down
 [2022-04-16 16:46:46] WARN Ghost has shut down
 [2022-04-16 16:46:46] WARN Your site is now offline
 [2022-04-16 16:46:46] WARN Ghost was running for a few seconds
`````

### Steps to Reproduce

1. `docker -v` is `Docker version 20.10.10, build b485636`
2. `Debian GNU/Linux 11 (bullseye)`
3. `docker-compose -v` is `Docker Compose version v2.4.1`
4. apply my config

### Ghost Version

any 4

### Node.js Version

bundled in docker image

### How did you install Ghost?

cause ghost is cool

### Database type

MySQL 8

### Browser & OS version

not depent

### Relevant log / error output

```shell
[2022-04-16 16:46:46] ERROR (Code: -97)

(Code: -97)

"There was an error starting your server."
 "Please use the error code above to search for a solution."

 Error ID:
     cd9d5850-bda4-11ec-a989-9d00a94dc17e

 ----------------------------------------

 InternalServerError: (Code: -97)
     at Server.<anonymous> (/var/lib/ghost/versions/4.41.3/core/server/ghost-server.js:116:34)
     at Server.emit (events.js:400:28)
     at emitErrorNT (net.js:1358:8)
     at processTicksAndRejections (internal/process/task_queues.js:82:21)

 [2022-04-16 16:46:46] WARN Ghost is shutting down
 [2022-04-16 16:46:46] WARN Ghost has shut down
 [2022-04-16 16:46:46] WARN Your site is now offline
 [2022-04-16 16:46:46] WARN Ghost was running for a few seconds
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by stamepicmorg** [comment]
help please...

a tried some versions of `4` ghost. and `-alpine` versions too. Now, I'am using `ghost3` but i want to use `v4` or `v5` after release.

thank you.

**Comment by stamepicmorg** [comment]
very strange support. seriously? i cant to run your engine in docker. and you answered that it is not a bug?

a cant install any 4.x versions. come on.

**Comment by stamepicmorg** [comment]
@matthanley help please?

**Comment by ErisDS** [comment]
@stamepicmorg The docker images are provided by docker & the docker community, they are not provided or maintained by us. See https://hub.docker.com/_/ghost. Meanwhile, we do not provide support via GitHub, please use our [forum](https://forum.ghost.org).
