### ISSUE TITLE
Cannot send emails

### ISSUE THREAD

**Issue by 5factor** [TryGhost/Ghost#14854]
### Issue Summary

I get the following error when attempting to publish a post + email subscribers:
`
InternalServerError: Unexpected visibility value "[object Promise]". Use one of the valid: "members", "paid".
`

The post is visible to all members with no additional settings applied.

<img width="368" alt="Screen Shot 2022-05-17 at 6 36 45 PM" src="https://user-images.githubusercontent.com/53883918/168923983-6cfab906-07a5-46d5-987a-9c335561fa26.png">

<img width="571" alt="Screen Shot 2022-05-17 at 6 36 59 PM" src="https://user-images.githubusercontent.com/53883918/168924002-e0ebe944-f186-4525-9486-f25272882804.png">

### Steps to Reproduce

Publish post + send to subscribers

### Ghost Version

4.47.3

### Node.js Version

v16.5.0

### How did you install Ghost?

Ubuntu 20.04 LTS x64 | 2vcpu, 4gb ram, installed with ghost CLI

### Database type

MySQL 8

### Relevant log / error output

```shell
InternalServerError: Unexpected visibility value "[object Promise]". Use one of the valid: "members", "paid".
    at /var/www/baseplate/versions/4.47.3/node_modules/@tryghost/job-manager/lib/job-manager.js:110:35
    at sendEmailJob (/var/www/baseplate/versions/4.47.3/core/server/services/mega/mega.js:406:15)
    at transformEmailRecipientFilter (/var/www/baseplate/versions/4.47.3/core/server/services/mega/mega.js:182:19)
    at getEmailMemberRows (/var/www/baseplate/versions/4.47.3/core/server/services/mega/mega.js:433:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createSegmentedEmailBatches (/var/www/baseplate/versions/4.47.3/core/server/services/mega/mega.js:497:22)
    at async /var/www/baseplate/versions/4.47.3/core/server/services/mega/mega.js:379:33
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Thanks for the report! This was already fixed and released in [4.47.4](https://github.com/TryGhost/Ghost/releases/tag/v4.47.4)
