### ISSUE TITLE
Upgrade from 4.41.0 to 4.47.4, database upgrade fails

### ISSUE THREAD

**Issue by iamdoubz** [TryGhost/Ghost#14860]
### Issue Summary

When performing a standard upgrade, the database upgrade fails resulting in a 502 and infinite server restart.

### Steps to Reproduce

1. Upgrade using the standard `ghost upgrade`
2. Restart service `sudo service ghost restart`
3. Check log files `sudo journalctl -fu ghost`

### Ghost Version

4.47.4

### Node.js Version

14.19.1

### How did you install Ghost?

Ubuntu 20.04 and `sudo npm install -g ghost-cli@latest && ghost install`

### Database type

MySQL 5.7

### Browser & OS version

MariaDB 10.3.34

### Relevant log / error output

```shell
iamdoubz@computer:/var/www/ghost$ sudo journalctl -fu ghost
May 18 11:21:49 computer systemd[1]: blog.service: Main process exited, code=exited, status=1/FAILURE
May 18 11:21:49 computer systemd[1]: blog.service: Failed with result 'exit-code'.
May 18 11:21:49 computer systemd[1]: blog.service: Scheduled restart job, restart counter is at 59.
May 18 11:21:49 computer systemd[1]: Stopped Ghost systemd service for blog: blog-my-domain.
May 18 11:21:49 computer systemd[1]: Started Ghost systemd service for blog: blog-my-domain.
May 18 11:21:50 computer node[1931950]: - Inspecting operating system
May 18 11:21:50 computer node[1931950]: Love open source? We’re hiring Node.js Engineers to work on Ghost full-time.
May 18 11:21:50 computer node[1931950]: https://careers.ghost.org/product-engineer-node-js
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Ghost is running in production...
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Your site is now available on https://blog.my.domain/
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Ctrl+C to shut down
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Ghost server started in 0.351s
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] WARN Database state requires migration.
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Creating database backup
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Database backup written to: /var/www/ghost/content/data/firstname-lastname.ghost.2022-05-18-16-21-50.json
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Running migrations.
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Dropping nullable: newsletters.created_at
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Rolling back: alter table `newsletters` modify  `created_at` datetime not null default 'NULL' - Invalid default value for 'created_at'.
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] INFO Setting nullable: newsletters.created_at
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] ERROR alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
May 18 11:21:50 computer node[1931976]:
May 18 11:21:50 computer node[1931976]: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
May 18 11:21:50 computer node[1931976]: "OuterError: alter table `newsletters` modify  `created_at` datetime not null default 'NULL' - Invalid default value for 'created_at'"
May 18 11:21:50 computer node[1931976]: Error ID:
May 18 11:21:50 computer node[1931976]:     400
May 18 11:21:50 computer node[1931976]: Error Code:
May 18 11:21:50 computer node[1931976]:     ER_INVALID_DEFAULT
May 18 11:21:50 computer node[1931976]: ----------------------------------------
May 18 11:21:50 computer node[1931976]: RollbackError: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
May 18 11:21:50 computer node[1931976]:     at DatabaseStateManager.makeReady (/var/www/ghost/versions/4.47.4/core/server/data/db/state-manager.js:95:32)
May 18 11:21:50 computer node[1931976]:     at RollbackError.KnexMigrateError (/var/www/ghost/versions/4.47.4/node_modules/knex-migrator/lib/errors.js:7:26)
May 18 11:21:50 computer node[1931976]:     at new RollbackError (/var/www/ghost/versions/4.47.4/node_modules/knex-migrator/lib/errors.js:31:26)
May 18 11:21:50 computer node[1931976]:     at KnexMigrator.migrate (/var/www/ghost/versions/4.47.4/node_modules/knex-migrator/lib/index.js:418:31)
May 18 11:21:50 computer node[1931976]:     at async DatabaseStateManager.makeReady (/var/www/ghost/versions/4.47.4/core/server/data/db/state-manager.js:86:17)
May 18 11:21:50 computer node[1931976]:     at async initDatabase (/var/www/ghost/versions/4.47.4/core/boot.js:69:5)
May 18 11:21:50 computer node[1931976]:     at async bootGhost (/var/www/ghost/versions/4.47.4/core/boot.js:414:9)
May 18 11:21:50 computer node[1931976]: Error: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
May 18 11:21:50 computer node[1931976]:     at Packet.asError (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/packets/packet.js:728:17)
May 18 11:21:50 computer node[1931976]:     at Query.execute (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/commands/command.js:29:26)
May 18 11:21:50 computer node[1931976]:     at Connection.handlePacket (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/connection.js:456:32)
May 18 11:21:50 computer node[1931976]:     at PacketParser.onPacket (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/connection.js:85:12)
May 18 11:21:50 computer node[1931976]:     at PacketParser.executeStart (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/packet_parser.js:75:16)
May 18 11:21:50 computer node[1931976]:     at Socket.<anonymous> (/var/www/ghost/versions/4.47.4/node_modules/mysql2/lib/connection.js:92:25)
May 18 11:21:50 computer node[1931976]:     at Socket.emit (events.js:400:28)
May 18 11:21:50 computer node[1931976]:     at addChunk (internal/streams/readable.js:293:12)
May 18 11:21:50 computer node[1931976]:     at readableAddChunk (internal/streams/readable.js:267:9)
May 18 11:21:50 computer node[1931976]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
May 18 11:21:50 computer node[1931976]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
May 18 11:21:50 computer node[1931976]:
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] WARN Ghost is shutting down
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] WARN Ghost has shut down
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] WARN Your site is now offline
May 18 11:21:50 computer node[1931976]: [2022-05-18 16:21:50] WARN Ghost was running for a few seconds
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by iamdoubz** [comment]
Sorry I didn't look at open issues! That is my mistake.
