### ISSUE TITLE
Validation error, cannot edit setting. Please enter a valid email address

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#15226]
### Issue Summary

`Validation error, cannot edit setting. Please enter a valid email address` - Getting this Warning Message while making any changes, Updates and Edits in Ghost admin settings page

Already someone Reported this error about in Forum - <https://forum.ghost.org/t/validation-error-cannot-edit-setting-please-enter-a-valid-email-address/31665>

![Screenshot from 2022-08-06 19-34-01](https://user-images.githubusercontent.com/10300271/184471725-7760bc07-4afd-4051-87d8-6b0bcc367620.png)

### Steps to Reproduce

- Restart Ghost - No fix
- Force Update - No fix
- Restart MySQL and Server Reboot - No fix
- Adding dummy staff with full privilege - No fix
- 
This issue occurs only on the Site Settings page
rest things on the Dashboard work well

- website settings
- Members
- Advanced

Test My Production site locally on my system
Facing this same issue on localhost too
error log same as I Provided

seems Issue on `bluebird Promise()`

### Ghost Version

5.8.0

### Node.js Version

v16.16.0

### How did you install Ghost?

VPS Server with Ubuntu 18.04 - install via Ghost CLI and Nginx Server

### Database type

MySQL 8

### Browser & OS version

Ubuntu 18.04 LTS

### Relevant log / error output

```shell
NAME: ValidationError
MESSAGE: Please enter a valid email address.

level: normal

ValidationError: Please enter a valid email address.
    at /var/www/example.com/versions/5.8.0/core/server/api/endpoints/utils/validators/input/settings.js:56:39
    at arrayEach (/var/www/example.com/versions/5.8.0/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/var/www/example.com/versions/5.8.0/node_modules/lodash/lodash.js:9410:14)
    at Object.edit (/var/www/example.com/versions/5.8.0/core/server/api/endpoints/utils/validators/input/settings.js:17:11)
    at docNameMethod (/var/www/example.com/versions/5.8.0/core/server/api/shared/validators/handle.js:61:74)
    at /var/www/example.com/versions/5.8.0/node_modules/@tryghost/promise/lib/sequence.js:10:31
    at tryCatcher (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/www/example.com/versions/5.8.0/node_modules/bluebird/js/release/async.js:93
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Are you able to access your database and run the following query? 

```
SELECT `key`, `value` from settings where `key` in ('members_support_address', 'members_from_address');
```

**Comment by mskian** [comment]
```sh
mysql> SELECT `key`, `value` from settings where `key` in ('members_support_address', 'members_from_address');
+-------------------------+-------+
| key                     | value |
+-------------------------+-------+
| members_support_address | NULL  |
+-------------------------+-------+
1 row in set (0.01 sec)
```

**Comment by ErisDS** [comment]
I don't know how you've reached this state (and I don't think it's worth looking into unless a lot of people experience it) but that value should be a string, not NULL.

The following will update the value back to the default:

```
UPDATE settings set `value` = 'noreply' where `key` = 'members_support_address';
```

**Comment by mskian** [comment]
yes, no clue how it happens maybe recent MYSQL 5.6 to 8 may causes this issue 

Now if Fixed

**Comment by ErisDS** [comment]
Excellent, thanks for letting us know.

**Comment by olivrg** [comment]
I'm currently experiencing this exact issue after upgrading to the latest Ghost. 
I'm also not able to access the database with this command: 
`SELECT `key`, `value` from settings where `key` in ('members_support_address', 'members_from_address');`

Any help?

**Comment by mskian** [comment]
@olivrg 

- Log into MYSQL Database

```sh
sudo mysql -u root -D <ghost_site_database_name> -p
```

- Run this Query

```sh
SELECT `key`, `value` from settings where `key` in ('members_support_address', 'members_from_address');
```
- if the same output comes as i posted above then run this query to fix

```sh
UPDATE settings set `value` = 'noreply' where `key` = 'members_support_address';
```

**Comment by olivrg** [comment]
Thank you, @mskian 👍
