### ISSUE TITLE
Unable to delete post with nested comment

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Ghost#15252]
### Issue Summary

Whenever you try to delete a post that has a comment and a reply to that comment, an internal server error occurs:

`Internal server error, cannot delete post. Cannot set properties of undefined (setting 'message')`

### Steps to Reproduce

1. Create a new blog post and publish it
2. Leave a comment on that blog post
3. Reply to that comment
4. Attempt to delete the blog post

### Ghost Version

5.9.4

### Node.js Version

16.16

### How did you install Ghost?

Ubuntu 20.04.4 LTS

### Database type

MySQL 8

### Relevant log / error output

```shell
{"name":"Log","hostname":"example","pid":696855,"level":50,"req":{"meta":{"requestId":"07055caf-c581-4d77-81a3-01f7055c77c7","userId":"1"},"url":"/posts/62fdbbfb752fb6a221f26e9d/","method":"DELETE","originalUrl":"/ghost/api/admin/posts/62fdbbfb752fb6a221f26e9d/","params":{},"headers":{"host":"blog.example.org","cf-ipcountry":"US","cdn-loop":"cloudflare","accept-encoding":"gzip","x-forwarded-for":"**REDACTED**","cf-ray":"**REDACTED**","x-forwarded-proto":"https, https","cf-visitor":"{\"scheme\":\"https\"}","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"5.9","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36","content-type":"application/json; charset=UTF-8","sec-gpc":"1","origin":"https://blog.example.org","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://blog.example.org/ghost/","accept-language":"en-US,en;q=0.9,de;q=0.8","cf-connecting-ip":"**REDACTED**","cookie":"**REDACTED**","x-forwarded-host":"blog.example.org"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"https://blog.example.org","vary":"Origin, Accept-Encoding","content-type":"application/json; charset=utf-8","content-length":"286","etag":"W/\"11e-JGRxNJsjDWlG04oL0DLfIS39Z7M\""},"statusCode":500,"responseTime":"70ms"},"err":{"id":"eec45ac0-1eab-11ed-8676-618ce3f5ed56","domain":"https://blog.example.org","code":null,"name":"InternalServerError","statusCode":500,"level":"critical","message":"Cannot set properties of undefined (setting 'message')","stack":"TypeError: Cannot set properties of undefined (setting 'message')\n    at module.exports.prepareError (/var/www/blog.example.org/versions/5.9.4/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:79:19)\n    at ErrorCtor (/var/www/blog.example.org/versions/5.9.4/node_modules/create-error/create-error.js:29:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","hideStack":false},"msg":"Cannot set properties of undefined (setting 'message')","time":"2022-08-18T04:12:11.248Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I have confirmed this bug. Replies are comments with a self-referencing `parent_id` and that foreign key is missing an ON DELETE directive.

As an aside, the error message shown here is utter BS 🙈 It's an error coming from Bookshelf's error handler, completely masking the underlying problem. I have a fix for this part prepared, but it changes the error so that the underlying SQL error is displayed:

```
[ghost] Error: delete from `posts` where `id` = '62e927c57c3023a1878ebd86' - Cannot delete or update a parent row: a foreign key constraint fails (`ghost_dev`.`comments`, CONSTRAINT `comments_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `comments` (`id`))
[ghost]     at module.exports.prepareError (/Users/hannah/Sites/Ghost/ghost/mw-error-handler/lib/mw-error-handler.js:79:19)
[ghost]     at Packet.asError (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/packets/packet.js:728:17)
[ghost]     at Query.execute (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/commands/command.js:29:26)
[ghost]     at Connection.handlePacket (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/connection.js:456:32)
[ghost]     at PacketParser.onPacket (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/connection.js:85:12)
[ghost]     at PacketParser.executeStart (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/packet_parser.js:75:16)
[ghost]     at Socket.<anonymous> (/Users/hannah/Sites/Ghost/node_modules/mysql2/lib/connection.js:92:25)
[ghost]     at Socket.emit (node:events:526:28)
[ghost]     at addChunk (node:internal/streams/readable:315:12)
[ghost]     at readableAddChunk (node:internal/streams/readable:289:9)
[ghost]     at Socket.Readable.push (node:internal/streams/readable:228:10)
[ghost]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

This is useful for fixing the issue, but not ideal to ship without a fix for the constraint.

**Comment by ErisDS** [comment]
Fix for the main bug is in - the fix for the error message is coming after the release.

**Comment by ryansechrest** [comment]
Wonderful! This beats me having to delete the comments in reverse order via SQL. 🙈 Thank you, @ErisDS
