### ISSUE TITLE
Getting JavaScript Syntax Error if Native Comments are enabled

### ISSUE THREAD

**Issue by paulknulst** [TryGhost/Ghost#15428]
### Issue Summary

I have found a reproducible error that happens if I enable native comments on my blog.

For testing purposes I created a dev environment for my [blog](www.knulst.de) at [dev-www.knulst.de](https://dev-www.knulst.de) on which I try different features before I apply them.

If I enable native comments I got several JavaScript error within the Chrome/FireFox/Opera Dev console:
![image](https://user-images.githubusercontent.com/5755794/190899339-53b452a1-c99e-4adf-ac6a-9e981825e147.png)

I have Ghost running in a Docker Environment with a Traefik Reverse Proxy

### Steps to Reproduce

1. Activate Casper/Liebling Theme
2. Enable Native comments
3. Switch to a Post containing native comments feature

### Ghost Version

 5.14.1

### Node.js Version

node:16-bullseye-slim

### How did you install Ghost?

Installed using Docker Container from Docker Hub (latest)

### Database type

MySQL 8

### Browser & OS version

Opera, Firefox, Chrome

### Relevant log / error output

```shell
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.@babel/runtime/helpers/interopRequireDefault @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_handshake @ contentscript.js:1
i @ contentscript.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
y.uncork @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.@babel/runtime/helpers/interopRequireDefault @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.@babel/runtime/helpers/interopRequireDefault @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_handshake @ contentscript.js:1
i @ contentscript.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
y.uncork @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.@babel/runtime/helpers/interopRequireDefault @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/modules/mv3.utils @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
w @ inpage.js:1
(anonymous) @ inpage.js:1
y.write @ inpage.js:1
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
_write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
middleware @ inpage.js:1
(anonymous) @ inpage.js:17
_runMiddleware @ inpage.js:17
_runAllMiddleware @ inpage.js:17
await in _runAllMiddleware (async)
_processRequest @ inpage.js:17
_handle @ inpage.js:17
handle @ inpage.js:17
r.sendSiteMetadata @ inpage.js:1
await in r.sendSiteMetadata (async)
e @ inpage.js:1
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
w @ inpage.js:1
(anonymous) @ inpage.js:1
y.write @ inpage.js:1
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
_write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
middleware @ inpage.js:1
(anonymous) @ inpage.js:17
_runMiddleware @ inpage.js:17
_runAllMiddleware @ inpage.js:17
await in _runAllMiddleware (async)
_processRequest @ inpage.js:17
_handle @ inpage.js:17
handle @ inpage.js:17
r.sendSiteMetadata @ inpage.js:1
await in r.sendSiteMetadata (async)
e @ inpage.js:1
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
2admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
App.js:203 Error parsing event data SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at App.js:200:29
(anonymous) @ App.js:203
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
admin-auth.min.js:1 SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at admin-auth.min.js:1:365
(anonymous) @ admin-auth.min.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 4 more frames
admin-auth.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'action')
    at admin-auth.min.js:1:516
```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by paulknulst** [comment]
One important addition:
- It only happens if I am logged in to Ghost not if I use a private tab,

**Comment by ErisDS** [comment]
I get the same, it's caused by the react dev tools extension for me - could be a different extension for you, but essentially something is posting non-JSON content to all the iframes.

This is just creating console noise, there's no actual problem. We need to stop logging this case to the console, if the message can't be parsed as JSON then it didn't come from Ghost :)

**Comment by paulknulst** [comment]
But there are also errors if you do a lighthouse test.

For example, this site: [https://www.knulst.de/7-tricks-to-improve-home-office-productivity/](https://www.knulst.de/7-tricks-to-improve-home-office-productivity/)

gives:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

which is logged to the console. See lighthouse report: [https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.knulst.de%2F7-tricks-to-improve-home-office-productivity%2F&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.knulst.de%2F7-tricks-to-improve-home-office-productivity%2F&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

**Comment by ErisDS** [comment]
Yes, that's the request to see if you are logged in returning "nope". Again it's showing a visible error but nothing is actually wrong. There is no broken functionality.

**Comment by paulknulst** [comment]
I know and understand that it is not broken. I only want to inform you that these "errors" are logged to the console which should normally not be the case. As I understand it is expected behavior as I am not currently logged in and cannot comment until I log into the website.
I only want to get rid of the console.log :)

Feel free to close this issue.
