### ISSUE TITLE
Crash on Upgrade to 5.21.0

### ISSUE THREAD

**Issue by iBotPeaches** [TryGhost/Ghost#15727]
### Issue Summary

Vising any page in Admin that results in listing posts, crashes.

### Steps to Reproduce

1. Upgraded to 5.21.0 (MariaDB)
2. Visited Admin Panel

### Ghost Version

5.21.0

### Node.js Version

16.x

### How did you install Ghost?

Source

### Database type

Other

### Browser & OS version

Chrome

### Relevant log / error output

```shell
"err":{
      "id":"f666d1b0-577f-11ed-853a-91052f8bcbb2",
      "domain":"",
      "code":"ER_BAD_FIELD_ERROR",
      "name":"BadRequestError",
      "statusCode":400,
      "level":"normal",
      "message":"Could not understand request.",
      "stack":"Error: select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`status` = 'draft' and `posts`.`type` = 'post') order by CASE WHEN posts.status = 'scheduled' THEN 1 WHEN posts.status = 'draft' THEN 2 ELSE 3 END ASC,CASE WHEN posts.status != 'draft' THEN posts.published_at END DESC,posts.updated_at DESC,posts.id DESC limit 30 - Unknown column 'posts.id' in 'where clause'\n    at /var/www/connor/blog/versions/5.21.0/node_modules/@tryghost/bookshelf-pagination/lib/bookshelf-pagination.js:259:27\n    at Packet.asError (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/var/www/connor/blog/versions/5.21.0/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "hideStack":false
   },
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by iBotPeaches** [comment]
Wait. This is my fault for using MariaDB.

This is not an issue when I moved to mysql8.
