### ISSUE TITLE
Migration failed update from 5.19.3 to 5.22.1

### ISSUE THREAD

**Issue by nik-nazarov** [TryGhost/Ghost#15743]
### Issue Summary

Can't update ghost from 5.19.3 to 5.22.1. 
Migration failed. 

### Steps to Reproduce

1. Change docker image to new version 5.22.1
2. Trying to start ghost with new version and get the error. 

### Ghost Version

5.19.3

### Node.js Version

v16.18.0

### How did you install Ghost?

helm chart

### Database type

MySQL 8 (AWS RDS)

### Relevant log / error output

```shell
[2022-11-01 10:01:50] INFO Ghost is running in production...
[2022-11-01 10:01:50] INFO Your site is now available on https://blog.***.com/
[2022-11-01 10:01:50] INFO Ctrl+C to shut down
[2022-11-01 10:01:50] INFO Ghost server started in 1.689s
[2022-11-01 10:01:50] WARN Database state requires migration.
[2022-11-01 10:01:51] INFO Creating database backup
[2022-11-01 10:01:51] INFO Database backup written to: /var/lib/ghost/content/data/***com.ghost.2022-11-01-10-01-51.json
[2022-11-01 10:01:51] INFO Running migrations.
[2022-11-01 10:01:51] INFO Dropping nullable: subscriptions.tier_id
[2022-11-01 10:01:51] INFO Rolling back: alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'.
[2022-11-01 10:01:51] INFO Rollback was successful.
[2022-11-01 10:01:51] ERROR alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'

alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'

{"config":{"transaction":true},"name":"2022-10-18-05-39-drop-nullable-tier-id.js"}
"Error occurred while executing the following migration: 2022-10-18-05-39-drop-nullable-tier-id.js"

Error ID:
    300

Error Code: 
    ER_FK_COLUMN_CANNOT_CHANGE

----------------------------------------

Error: alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'
    at /var/lib/ghost/versions/5.22.1/node_modules/knex-migrator/lib/index.js:1032:19
    at Packet.asError (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/lib/ghost/versions/5.22.1/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

[2022-11-01 10:01:51] WARN Ghost is shutting down
[2022-11-01 10:01:51] WARN Ghost has shut down
[2022-11-01 10:01:51] WARN Your site is now offline
[2022-11-01 10:01:51] WARN Ghost was running for a few seconds


```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Please can you connect to your DB and run `SELECT @@sql_mode` and share the output?

**Comment by nik-nazarov** [comment]
Hi @ErisDS, sure

```sql
NO_ENGINE_SUBSTITUTION
```

**Comment by ErisDS** [comment]
> The default SQL mode in MySQL 8.0 includes these modes: [ONLY_FULL_GROUP_BY](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_only_full_group_by), [STRICT_TRANS_TABLES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_strict_trans_tables), [NO_ZERO_IN_DATE](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_in_date), [NO_ZERO_DATE](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date), [ERROR_FOR_DIVISION_BY_ZERO](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_error_for_division_by_zero), and [NO_ENGINE_SUBSTITUTION](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_engine_substitution).
- From https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html

Ghost expects the default sql mode, and **requires** NO_STRICT_TRANS_TABLES

I'll leave this open for the time being to:

1. Get this documented
2. Look at catching these errors and instead throwing something more specific like "Incorrect SQL Mode, STRICT_TRANS_TABLES is required.

If anyone would like to take on 2 that would be awesome.

**Comment by nik-nazarov** [comment]
@ErisDS thank you for your reply, I've just update sql_mode to default value and now it works!

**Comment by samrap** [comment]
@ErisDS @nik-nazarov  can you clarify what actually needs to be done here? 

Our database is on RDS and I can't set the global sql mode. Have to pin to version 5.19.3 for the time being.

**Comment by nik-nazarov** [comment]
@samrap sure, you need to update sql_mode parameter in parameters groups that is attached to your RDS instance. 
![image](https://user-images.githubusercontent.com/86673860/199617886-3695fc37-4901-4ea6-aeee-57736ba950f4.png)

**Comment by samrap** [comment]
@nik-nazarov Brilliant! Thank you

**Comment by danquack** [comment]
There was a foreign key relationship on the products table:
```
SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'ghost'; 

...
| subscriptions                          | tier_id           | subscriptions_tier_id_foreign                               | products                               | id                     |
```

Where the product table had the key as NOT NULL:
```
show create table products;
CREATE TABLE `products` (
  `id` varchar(24) NOT NULL,
  ...
```

To fix this I disabled the foreign key check and then altered the table:
```
mysql> SET FOREIGN_KEY_CHECKS = 0;
Query OK, 0 rows affected (0.07 sec)

mysql>  alter table `subscriptions` modify  `tier_id` varchar(24) not null;
Query OK, 0 rows affected (0.22 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> SET FOREIGN_KEY_CHECKS = 1;
Query OK, 0 rows affected (0.07 sec)
```

It appears this is the commit that caused the change https://github.com/TryGhost/Ghost/commit/3858f255b9f6a0fa8e65f73959adf1682c4b129e, not sure how the schema migrations are validated, but this at least can get folks up and running until a patch goes in.

**Comment by ErisDS** [comment]
@danquack to be transparent I've hidden your comment as your approach to fixing this is a hack around the problem. There is not going to be a patch to change Ghost to use a non-default SQL mode.  

The docs have now been updated: https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_fk_column_cannot_change

If anyone wants to take on the work of improving the error message for these cases to make the error clearer and point to the docs, that'd be great as this issue only affects self-hosters who have a non-default SQL mode & I understand it can be difficult to find the source of the problem from the current error.
