### ISSUE TITLE
Cannot dismiss Ghost v5 upgrade notification in Ghost v4

### ISSUE THREAD

**Issue by seanhamlin** [TryGhost/Ghost#15802]
### Issue Summary

Spotted in the logs, I am unable to actually dismiss the Ghost v5 upgrade notification, so every page load there is a nag.

I am not wanting to upgrade to Ghost v5 right now due to the MySQL v8 requirement.

### Steps to Reproduce

1. Dismiss the Ghost v5 notification at the top
2. See error in logs
3. Refresh the page, the notification comes back

### Ghost Version

4.48.7

### Node.js Version

16

### How did you install Ghost?

Alpine Linux

### Database type

MySQL 5.7

### Browser & OS version

Chrome 107 and Mac OSX 12.5.1

### Relevant log / error output

```shell
[2022-11-10 20:21:58] ERROR "DELETE /ghost/api/admin/notifications/130f7c24-113a-4768-a698-12a8b3422e81/" 422 28ms

Value in notifications should be an array.

Error ID:
    538f13c0-6135-11ed-8ecd-0920c835b0cb

----------------------------------------

ValidationError: Value in notifications should be an array.
    at /var/lib/ghost/versions/4.48.7/core/server/api/canary/utils/validators/input/settings.js:47:35
    at arrayEach (/var/lib/ghost/versions/4.48.7/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/var/lib/ghost/versions/4.48.7/node_modules/lodash/lodash.js:9410:14)
    at Object.edit (/var/lib/ghost/versions/4.48.7/core/server/api/canary/utils/validators/input/settings.js:28:11)
    at docNameMethod (/var/lib/ghost/versions/4.48.7/core/server/api/shared/validators/handle.js:61:74)
    at /var/lib/ghost/versions/4.48.7/node_modules/@tryghost/promise/lib/sequence.js:10:31
    at tryCatcher (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/4.48.7/node_modules/bluebird/js/release/async.js:86:9)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there, thank you so much for the detailed bug report.

That validation error does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

Whilst here, just want to clarify that 4.x is EOL on 31st Jan.

**Comment by neerajkrbansal1996** [comment]
Hi @ErisDS ,

If no one is working on this issue, I would love to take this issue!

**Comment by ErisDS** [comment]
@neerajkrbansal1996 PRs are always welcome - especially for issues marked with the `help wanted` label like this one.

**Comment by farhan787** [comment]
@ErisDS I used below resources to do my local dev setup. How do I install an older version of Ghost for my dev environment? 

1. [Install from source](https://ghost.org/docs/install/source/) - followed this primarily
2. [Contributing Docs](https://ghost.org/docs/contributing/)
3. [Contributing GitHub Guide](https://github.com/TryGhost/Ghost/blob/3d989eba2371235d41468f7699a08e46fc2b1e87/.github/CONTRIBUTING.md)

Default version is 5+ that is running on my setup.
