### ISSUE TITLE
Posts do not load in admin interface after upgrade to v5.22.10

### ISSUE THREAD

**Issue by ladvoc** [TryGhost/Ghost#15815]
### Issue Summary

After upgrading to v5.22.10, I can not longer access posts through the admin interface. When clicking on "Posts" (or any of the sub-links) in the sidebar, I receive a 400 error. All other sections appear to be working as expected. I have included the full log entry for the bad request.

<img width="944" alt="screenshot" src="https://user-images.githubusercontent.com/3182119/201542835-9c33d602-2f33-4a49-a733-45bebf166ccf.png">

### Steps to Reproduce

1. Upgrade from v5.22.5 to v5.22.10
2. Access the admin interface
3. Click on "Posts"

### Ghost Version

v5.22.10

### Node.js Version

v16.16.0

### How did you install Ghost?

Custom installation on FreeBSD

### Database type

MySQL 8

### Relevant log / error output

```shell
[2022-11-13 20:19:42] ERROR "GET /ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=30&page=1&filter=status%3A%5Bdraft%2Cscheduled%2Cpublished%2Csent%5D" 400 16ms

NAME: BadRequestError
CODE: ER_BAD_FIELD_ERROR
MESSAGE: Could not understand request.

level: normal

Error: select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`status` in ('draft', 'scheduled', 'published', 'sent') and `posts`.`type` = 'post') order by CASE WHEN posts.status = 'scheduled' THEN 1 WHEN posts.status = 'draft' THEN 2 ELSE 3 END ASC,CASE WHEN posts.status != 'draft' THEN posts.published_at END DESC,posts.updated_at DESC,posts.id DESC limit 30 - Unknown column 'posts.id' in 'where clause'
    at /home/pi/installation/versions/5.22.10/node_modules/@tryghost/bookshelf-pagination/lib/bookshelf-pagination.js:259:27
    at Packet.asError (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/pi/installation/versions/5.22.10/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by dmaglia** [comment]
I have the same issue, but showing a 404 instead of the 400 error. Updated from v5.16.0 to v5.22.6. Running `ghost doctor` results in no issues.

**Comment by ErisDS** [comment]
Please see the docs on [troubleshooting mysql issues](https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_bad_field_error)
