### ISSUE TITLE
[Portal] Failed to initialize

### ISSUE THREAD

**Issue by jiangjiali** [TryGhost/Ghost#15904]
### Issue Summary

[Portal] Failed to initialize: TypeError: Cannot read properties of undefined (reading 'includes')

### Steps to Reproduce

Open Home Page
https://www.jiangjiali.com/

### Ghost Version

4.x

### Node.js Version

16

### How did you install Ghost?

default

### Database type

MySQL 8

### Browser & OS version

Google

### Relevant log / error output

```shell
[Portal] Failed to initialize: TypeError: Cannot read properties of undefined (reading 'includes')
    at Li (portal.min.js:1:244782)
    at portal.min.js:1:370914
    at u (portal.min.js:1:144114)
    at Generator.<anonymous> (portal.min.js:1:145451)
    at Generator.throw (portal.min.js:1:144477)
    at S (portal.min.js:1:150106)
    at l (portal.min.js:1:150345)
(anonymous) @ portal.min.js:1
u @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
S @ portal.min.js:1
l @ portal.min.js:1
Promise.then (async)
S @ portal.min.js:1
a @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
value @ portal.min.js:1
vl @ portal.min.js:1
Ds @ portal.min.js:1
n.unstable_runWithPriority @ portal.min.js:1
Wi @ portal.min.js:1
Is @ portal.min.js:1
bs @ portal.min.js:1
hs @ portal.min.js:1
ec @ portal.min.js:1
(anonymous) @ portal.min.js:1
ws @ portal.min.js:1
ac @ portal.min.js:1
n.render @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
(anonymous) @ portal.min.js:1
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by jiangjiali** [comment]
原来是我的 portal.min.js 版本问题。我换回 1.x 版本就可行了。
