### ISSUE TITLE
Ghost upgrade - migration error

### ISSUE THREAD

**Issue by bird-in-hat** [TryGhost/Ghost#15922]
### Issue Summary

Can not upgrade to latest ghost version - get migration error

I use mysql database. And ghost image 5.12-alpine 
```
    "database": {
        "client": "mysql",
        "connection": {
            "database": "",
            "host": "",
            "port": 3306,
            "password": "",
            "user": "",
            "ssl": "Amazon RDS"
        }
    },
```

### Steps to Reproduce

Used image ghost:5.12-alpine with mysql8 database.
`docker run --restart=always -p 3001:2368 -v /home/ubuntu/ghost:/var/lib/ghost/content -it ghost:5.12-alpine`

Upgrade to image ghost:5.24.2-alpine (or ghost:5.23-alpine - same error)
`docker run --restart=always -p 3001:2368 -v /home/ubuntu/ghost:/var/lib/ghost/content -it ghost:5.24.2-alpine`

### Ghost Version

5.12

### Node.js Version

16.18.1

### How did you install Ghost?

docker, alpine

### Database type

MySQL 8

### Browser & OS version

terminal

### Relevant log / error output

```shell
[2022-12-02 10:45:05] INFO Ghost is running in production...
[2022-12-02 10:45:05] INFO Your site is now available on https://<site>/
[2022-12-02 10:45:05] INFO Ctrl+C to shut down
[2022-12-02 10:45:05] INFO Ghost server started in 2.191s
[2022-12-02 10:45:06] WARN Database state requires migration.
[2022-12-02 10:45:07] INFO Creating database backup
[2022-12-02 10:45:07] INFO Database backup written to: /var/lib/ghost/content/data/site.ghost.2022-12-02-10-45-07.json
[2022-12-02 10:45:07] INFO Running migrations.
[2022-12-02 10:45:07] INFO Renaming members.bio to members.expertise
[2022-12-02 10:45:07] INFO Adding posts.lexical column
[2022-12-02 10:45:07] INFO Adding setting: email_track_clicks
[2022-12-02 10:45:07] INFO Adding table: post_revisions
[2022-12-02 10:45:07] WARN Skipping migration - noop
[2022-12-02 10:45:07] WARN Skipping migration - noop
[2022-12-02 10:45:07] INFO Adding members_created_events.referrer_source column
[2022-12-02 10:45:08] INFO Adding members_created_events.referrer_medium column
[2022-12-02 10:45:08] INFO Adding members_created_events.referrer_url column
[2022-12-02 10:45:08] INFO Adding members_subscription_created_events.referrer_source column
[2022-12-02 10:45:08] INFO Adding members_subscription_created_events.referrer_medium column
[2022-12-02 10:45:08] INFO Adding members_subscription_created_events.referrer_url column
[2022-12-02 10:45:08] INFO Dropping table: members_link_click_events
[2022-12-02 10:45:08] INFO Dropping table: link_redirects
[2022-12-02 10:45:08] INFO Adding table: redirects
[2022-12-02 10:45:08] INFO Adding table: members_click_events
[2022-12-02 10:45:08] INFO Set email_track_clicks to true (current email_track_opens value)
[2022-12-02 10:45:08] INFO Adding emails.track_clicks column
[2022-12-02 10:45:08] INFO Adding products.monthly_price column
[2022-12-02 10:45:09] INFO Adding products.yearly_price column
[2022-12-02 10:45:09] INFO Adding products.currency column
[2022-12-02 10:45:09] INFO Updating 1 Tiers with price and currency information
[2022-12-02 10:45:09] INFO Adding table: subscriptions
[2022-12-02 10:45:09] INFO Adding table: members_feedback
[2022-12-02 10:45:09] INFO Adding newsletters.feedback_enabled column
[2022-12-02 10:45:09] INFO Dropping nullable: subscriptions.tier_id
[2022-12-02 10:45:09] INFO Rolling back: alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'.
[2022-12-02 10:45:09] INFO Removing newsletters.feedback_enabled column
[2022-12-02 10:45:09] INFO Dropping table: members_feedback
[2022-12-02 10:45:10] INFO Dropping table: subscriptions
[2022-12-02 10:45:10] INFO Removing currency and price information for all tiers
[2022-12-02 10:45:10] INFO Removing products.currency column
[2022-12-02 10:45:10] INFO Removing products.yearly_price column
[2022-12-02 10:45:10] INFO Removing products.monthly_price column
[2022-12-02 10:45:10] INFO Removing emails.track_clicks column
[2022-12-02 10:45:10] INFO Dropping table: members_click_events
[2022-12-02 10:45:10] INFO Dropping table: redirects
[2022-12-02 10:45:10] INFO Adding table: link_redirects
[2022-12-02 10:45:10] INFO Adding table: members_link_click_events
[2022-12-02 10:45:10] INFO Removing members_subscription_created_events.referrer_url column
[2022-12-02 10:45:10] INFO Removing members_subscription_created_events.referrer_medium column
[2022-12-02 10:45:10] INFO Removing members_subscription_created_events.referrer_source column
[2022-12-02 10:45:11] INFO Removing members_created_events.referrer_url column
[2022-12-02 10:45:11] INFO Removing members_created_events.referrer_medium column
[2022-12-02 10:45:11] INFO Removing members_created_events.referrer_source column
[2022-12-02 10:45:11] WARN Skipping migration - noop
[2022-12-02 10:45:11] WARN Skipping migration - noop
[2022-12-02 10:45:11] INFO Dropping table: post_revisions
[2022-12-02 10:45:11] INFO Dropping setting: email_track_clicks
[2022-12-02 10:45:11] INFO Removing posts.lexical column
[2022-12-02 10:45:11] INFO Renaming members.expertise back to members.bio
[2022-12-02 10:45:11] INFO Rollback was successful.
[2022-12-02 10:45:11] ERROR alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'

alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'

{"config":{"transaction":true},"name":"2022-10-18-05-39-drop-nullable-tier-id.js"}
"Error occurred while executing the following migration: 2022-10-18-05-39-drop-nullable-tier-id.js"

Error ID:
    300

Error Code:
    ER_FK_COLUMN_CANNOT_CHANGE

----------------------------------------

Error: alter table `subscriptions` modify  `tier_id` varchar(24) not null  - Cannot change column 'tier_id': used in a foreign key constraint 'subscriptions_tier_id_foreign'
    at /var/lib/ghost/versions/5.23.0/node_modules/knex-migrator/lib/index.js:1032:19
    at Packet.asError (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/packet_parser.js:75:16)
    at TLSSocket.<anonymous> (/var/lib/ghost/versions/5.23.0/node_modules/mysql2/lib/connection.js:360:25)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

[2022-12-02 10:45:11] WARN Ghost is shutting down
[2022-12-02 10:45:11] WARN Ghost has shut down
[2022-12-02 10:45:11] WARN Your site is now offline
[2022-12-02 10:45:11] WARN Ghost was running for a few seconds
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by bird-in-hat** [comment]
Here are latest migration applied

<img width="739" alt="Снимок экрана 2022-12-02 в 15 03 03" src="https://user-images.githubusercontent.com/14351922/205278585-e5385d0f-6108-4c87-a041-017f091400b1.png">

**Comment by bird-in-hat** [comment]
Sorry for duplication! 

#15743
