### ISSUE TITLE
I get "Unexpected token '.'" when updating Ghost to v4.48.9

### ISSUE THREAD

**Issue by dozieogbo** [TryGhost/Ghost#16032]
### Issue Summary

I get "Unexpected token '.'" when updating Ghost to v4.48.9

### Steps to Reproduce

1. Install Ghost v4.48.2
2. Upgrade using `ghost update v4`

### Ghost Version

4.48.9

### Node.js Version

12.13.1

### How did you install Ghost?

Ghost Cli - Ubuntu 18

### Database type

MySQL 5.7

### Relevant log / error output

```shell
[2022-12-20 07:37:56] ERROR Unexpected token '.'

Unexpected token '.'
Error ID:
    387e83e0-8039-11ed-a6be-d54a8dd285ca
----------------------------------------
/var/www/***/versions/4.48.9/node_modules/bookshelf-relations/lib/utils/
    at bootGhost (/var/www/***/versions/4.48.9/core/boot.js:463:32)
    return obj?.id ? {id: obj.id} : {};
               ^
SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/***/versions/4.48.9/node_modules/bookshelf-relations/lib/
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/***/versions/4.48.9/node_modules/bookshelf-relations/index.
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Node 12 has been EOL since 30 Apr 2022 & Ghost v4.x is EOL on 31st Jan 2023. CLI should be telling you that your Node version is out of date - what version of the CLI do you have?

The solution is to upgrade to at least Node 14, you also need to prepare to upgrade Ghost.
