### ISSUE TITLE
Getting SQL Query error when I try to open statistics

### ISSUE THREAD

**Issue by SBajonczak** [TryGhost/Ghost#16274]
### Issue Summary

When I try to click on the stats Icon like the first here:

![image](https://user-images.githubusercontent.com/18240989/218841533-1338f749-907c-4c03-bf8e-803dfb197577.png)

I get a SQL error displayed and a (nice) 500 Server Error message.

```
Internal server error, cannot read post. An unexpected error occurred, please try again. select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`type` = 'post' and `posts`.`status` in ('draft', 'published', 'scheduled', 'sent')) and `posts`.`id` = '63e9183c4e062f0001c304ea' limit 1 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`k` as (select `member_id` from `members_subscription_created_events` where post' at line 1
```

### Steps to Reproduce

1. Go to the Posts
2. Click on one statistic Icon on any post that will be send through the newsletter

### Ghost Version

5.33.8

### Node.js Version

comes with the docker version

### How did you install Ghost?

Docker Image

### Database type

MySQL 5.7

### Browser & OS version

Edge / Chrome / Firefox

### Relevant log / error output

```shell
2023-02-14T19:44:59.617309059Z [2023-02-14 19:44:59] [31mERROR[39m "GET /ghost/api/admin/posts/63e9183c4e062f0001c304ea/?formats=mobiledoc%2Clexical&include=tags%2Cauthors%2Cauthors.roles%2Cemail%2Ctiers%2Cnewsletter%2Ccount.conversions%2Ccount.clicks%2Csentiment%2Ccount.positive_feedback%2Ccount.negative_feedback" [31m500[39m 70ms
2023-02-14T19:44:59.617347360Z [31m
2023-02-14T19:44:59.617353060Z [31mAn unexpected error occurred, please try again.[39m
2023-02-14T19:44:59.617357160Z
2023-02-14T19:44:59.617361760Z [37m"select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`type` = 'post' and `posts`.`status` in ('draft', 'published', 'scheduled', 'sent')) and `posts`.`id` = '63e9183c4e062f0001c304ea' limit 1 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`k` as (select `member_id` from `members_subscription_created_events` where post' at line 1"[39m
2023-02-14T19:44:59.617383060Z
2023-02-14T19:44:59.617386960Z [1m[37mError ID:[39m[22m
2023-02-14T19:44:59.617390560Z [90m10dda760-aca0-11ed-9ec5-ef16445495fc[39m
2023-02-14T19:44:59.617394460Z
2023-02-14T19:44:59.617397860Z [1m[37mError Code: [39m[22m
2023-02-14T19:44:59.617401460Z [90mUNEXPECTED_ERROR[39m
2023-02-14T19:44:59.617404960Z
2023-02-14T19:44:59.617408460Z [90m----------------------------------------[39m
2023-02-14T19:44:59.617411960Z
2023-02-14T19:44:59.617416560Z [90mError: select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`type` = 'post' and `posts`.`status` in ('draft', 'published', 'scheduled', 'sent')) and `posts`.`id` = '63e9183c4e062f0001c304ea' limit 1 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`k` as (select `member_id` from `members_subscription_created_events` where post' at line 1
2023-02-14T19:44:59.617422660Z at module.exports.prepareError (/var/lib/ghost/versions/5.33.8/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:92:19)
2023-02-14T19:44:59.617426660Z at Packet.asError (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/packets/packet.js:728:17)
2023-02-14T19:44:59.617430360Z at Query.execute (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/commands/command.js:29:26)
2023-02-14T19:44:59.617434060Z at Connection.handlePacket (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/connection.js:487:32)
2023-02-14T19:44:59.617437560Z at PacketParser.onPacket (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/connection.js:94:12)
2023-02-14T19:44:59.617441160Z at PacketParser.executeStart (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/packet_parser.js:75:16)
2023-02-14T19:44:59.617444960Z at Socket.<anonymous> (/var/lib/ghost/versions/5.33.8/node_modules/mysql2/lib/connection.js:101:25)
2023-02-14T19:44:59.617451660Z at Socket.emit (node:events:513:28)
2023-02-14T19:44:59.617455360Z at addChunk (node:internal/streams/readable:315:12)
2023-02-14T19:44:59.617459060Z at readableAddChunk (node:internal/streams/readable:289:9)
2023-02-14T19:44:59.617462660Z at Socket.Readable.push (node:internal/streams/readable:228:10)
2023-02-14T19:44:59.617466361Z at TCP.onStreamRead (node:internal/stream_base_commons:190:23)[39m
2023-02-14T19:44:59.617470061Z [39m
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi @SBajonczak - MySQL 5.7 is not a supported database for Ghost v5, and I believe this error is related to that. Please follow the instructions here: https://ghost.org/docs/faq/supported-databases/

**Comment by SBajonczak** [comment]
Okay thx, I will upgrade my Database to Version 8.0 then. Thanks for the information. Hopfully it will work :)
