### ISSUE TITLE
Error in "npm install" command and storage adapter installation

### ISSUE THREAD

**Issue by antonioalia7** [TryGhost/Ghost#16317]
### Issue Summary

Trying to install the google drive storage adapter I encountered this error:

npm ERROR! ERESOLVE queues
npm ERROR! ERESOLVE unable to resolve dependency tree
npm ERROR!
npm ERROR! While solving: ghost@5.34.0
npm ERROR! Found: knex@2.4.2
npm ERROR! node_modules/knex
npm ERROR! knex@"2.4.2" from the root project
npm ERROR!
npm ERROR! Could not resolve dependency:
npm ERROR! peer knex@"> 0.8 < 2.1" from mock-knex@0.4.9
npm ERROR! node_modules/mock-knex
npm ERROR! dev mock-knex@"TryGhost/mock-knex#8ecb8c227bf463c991c3d820d33f59efc3ab9682" from the root project
npm ERROR!
npm ERROR! Fix the upstream dependency conflict, or retry
npm ERROR! this command with --force or --legacy-peer-deps
npm ERROR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERROR!
npm ERROR!
npm ERROR! For a full report see:
npm ERROR! /home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-eresolve-report.txt

npm ERROR! A complete log of this run can be found in:
npm ERROR! /home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-debug-0.log

Actually the problem is not the google drive storage adapter. But something in the ghost installation.

If I try to navigate to the current folder and give the command "npm install" the error is always the same.

### Steps to Reproduce

1. cd var/www/ghostfolder/current
2. npm install

### Ghost Version

5.31.1

### Node.js Version

18.14.0

### How did you install Ghost?

AlphaVPS and Ubuntu 22.04

### Database type

MySQL 8

### Relevant log / error output

```shell
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.3.1
2 info using node@v18.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 9ms
6 timing config:load:builtin Completed in 9ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/var/www/andreasainato/versions/5.34.0/.npmrc Completed in 0ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/home/antonio/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 22ms
17 timing npm:load:configload Completed in 22ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:/home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-
26 verbose logfile /home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 33ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 3458ms
36 timing idealTree:userRequests Completed in 0ms
37 silly idealTree buildDeps
38 silly fetch manifest @tryghost/adapter-cache-redis@file:components/tryghost-adapter-cache-redis-5.34.0.tgz
39 silly fetch manifest @tryghost/adapter-manager@file:components/tryghost-adapter-manager-5.34.0.tgz
40 silly fetch manifest @tryghost/api-framework@file:components/tryghost-api-framework-5.34.0.tgz
41 silly fetch manifest @tryghost/api-version-compatibility-service@file:components/tryghost-api-version-compatibility-service-5.34.0.tgz
42 silly fetch manifest @tryghost/audience-feedback@file:components/tryghost-audience-feedback-5.34.0.tgz
43 silly fetch manifest @tryghost/bootstrap-socket@file:components/tryghost-bootstrap-socket-5.34.0.tgz
44 silly fetch manifest @tryghost/constants@file:components/tryghost-constants-5.34.0.tgz
45 silly fetch manifest @tryghost/custom-theme-settings-service@file:components/tryghost-custom-theme-settings-service-5.34.0.tgz
46 silly fetch manifest @tryghost/data-generator@file:components/tryghost-data-generator-5.34.0.tgz
47 silly fetch manifest @tryghost/domain-events@file:components/tryghost-domain-events-5.34.0.tgz
48 silly fetch manifest @tryghost/dynamic-routing-events@file:components/tryghost-dynamic-routing-events-5.34.0.tgz
49 silly fetch manifest @tryghost/email-analytics-provider-mailgun@file:components/tryghost-email-analytics-provider-mailgun-5.34.0.tgz
50 silly fetch manifest @tryghost/email-analytics-service@file:components/tryghost-email-analytics-service-5.34.0.tgz
51 silly fetch manifest @tryghost/email-content-generator@file:components/tryghost-email-content-generator-5.34.0.tgz
52 silly fetch manifest @tryghost/email-service@file:components/tryghost-email-service-5.34.0.tgz
53 silly fetch manifest @tryghost/email-suppression-list@file:components/tryghost-email-suppression-list-5.34.0.tgz
54 silly fetch manifest @tryghost/express-dynamic-redirects@file:components/tryghost-express-dynamic-redirects-5.34.0.tgz
55 silly fetch manifest express@4.18.2
56 http fetch GET 200 https://registry.npmjs.org/express 188ms (cache revalidated)
57 silly fetch manifest @tryghost/html-to-plaintext@file:components/tryghost-html-to-plaintext-5.34.0.tgz
58 silly fetch manifest @tryghost/importer-revue@file:components/tryghost-importer-revue-5.34.0.tgz
59 silly fetch manifest @tryghost/job-manager@file:components/tryghost-job-manager-5.34.0.tgz
60 silly fetch manifest @tryghost/link-redirects@file:components/tryghost-link-redirects-5.34.0.tgz
61 silly fetch manifest @tryghost/link-replacer@file:components/tryghost-link-replacer-5.34.0.tgz
62 silly fetch manifest @tryghost/link-tracking@file:components/tryghost-link-tracking-5.34.0.tgz
63 silly fetch manifest @tryghost/magic-link@file:components/tryghost-magic-link-5.34.0.tgz
64 silly fetch manifest @tryghost/mailgun-client@file:components/tryghost-mailgun-client-5.34.0.tgz
65 silly fetch manifest @tryghost/member-attribution@file:components/tryghost-member-attribution-5.34.0.tgz
66 silly fetch manifest @tryghost/member-events@file:components/tryghost-member-events-5.34.0.tgz
67 silly fetch manifest @tryghost/members-api@file:components/tryghost-members-api-5.34.0.tgz
68 silly fetch manifest @tryghost/members-csv@file:components/tryghost-members-csv-5.34.0.tgz
69 silly fetch manifest @tryghost/members-events-service@file:components/tryghost-members-events-service-5.34.0.tgz
70 silly fetch manifest @tryghost/members-importer@file:components/tryghost-members-importer-5.34.0.tgz
71 silly fetch manifest @tryghost/members-offers@file:components/tryghost-members-offers-5.34.0.tgz
72 silly fetch manifest @tryghost/members-ssr@file:components/tryghost-members-ssr-5.34.0.tgz
73 silly fetch manifest @tryghost/members-stripe-service@file:components/tryghost-members-stripe-service-5.34.0.tgz
74 silly fetch manifest @tryghost/milestone-emails@file:components/tryghost-milestone-emails-5.34.0.tgz
75 silly fetch manifest @tryghost/minifier@file:components/tryghost-minifier-5.34.0.tgz
76 silly fetch manifest @tryghost/mw-api-version-mismatch@file:components/tryghost-mw-api-version-mismatch-5.34.0.tgz
77 silly fetch manifest @tryghost/mw-cache-control@file:components/tryghost-mw-cache-control-5.34.0.tgz
78 silly fetch manifest @tryghost/mw-error-handler@file:components/tryghost-mw-error-handler-5.34.0.tgz
79 silly fetch manifest @tryghost/mw-session-from-token@file:components/tryghost-mw-session-from-token-5.34.0.tgz
80 silly fetch manifest @tryghost/mw-vhost@file:components/tryghost-mw-vhost-5.34.0.tgz
81 silly fetch manifest @tryghost/oembed-service@file:components/tryghost-oembed-service-5.34.0.tgz
82 silly fetch manifest @tryghost/package-json@file:components/tryghost-package-json-5.34.0.tgz
83 silly fetch manifest @tryghost/security@file:components/tryghost-security-5.34.0.tgz
84 silly fetch manifest @tryghost/session-service@file:components/tryghost-session-service-5.34.0.tgz
85 silly fetch manifest @tryghost/settings-path-manager@file:components/tryghost-settings-path-manager-5.34.0.tgz
86 silly fetch manifest @tryghost/staff-service@file:components/tryghost-staff-service-5.34.0.tgz
87 silly fetch manifest @tryghost/stats-service@file:components/tryghost-stats-service-5.34.0.tgz
88 silly fetch manifest @tryghost/tags-public@file:components/tryghost-tags-public-5.34.0.tgz
89 silly fetch manifest @tryghost/tiers@file:components/tryghost-tiers-5.34.0.tgz
90 silly fetch manifest @tryghost/update-check-service@file:components/tryghost-update-check-service-5.34.0.tgz
91 silly fetch manifest @tryghost/verification-trigger@file:components/tryghost-verification-trigger-5.34.0.tgz
92 silly fetch manifest @tryghost/webmentions@file:components/tryghost-webmentions-5.34.0.tgz
93 silly fetch manifest @playwright/test@1.30.0
94 http fetch GET 200 https://registry.npmjs.org/@playwright%2ftest 1942ms (cache revalidated)
95 silly fetch manifest @tryghost/express-test@0.13.0
96 http fetch GET 200 https://registry.npmjs.org/@tryghost%2fexpress-test 1902ms (cache revalidated)
97 silly fetch manifest @tryghost/webhook-mock-receiver@0.2.3
98 http fetch GET 200 https://registry.npmjs.org/@tryghost%2fwebhook-mock-receiver 1942ms (cache revalidated)
99 silly fetch manifest @types/common-tags@1.8.1
100 http fetch GET 200 https://registry.npmjs.org/@types%2fcommon-tags 1259ms (cache revalidated)
101 silly fetch manifest c8@7.12.0
102 http fetch GET 200 https://registry.npmjs.org/c8 306ms (cache revalidated)
103 silly fetch manifest cli-progress@3.11.2
104 http fetch GET 200 https://registry.npmjs.org/cli-progress 259ms (cache revalidated)
105 silly fetch manifest cssnano@5.1.14
106 http fetch GET 200 https://registry.npmjs.org/cssnano 43ms (cache revalidated)
107 silly fetch manifest postcss@8.4.21
108 http fetch GET 200 https://registry.npmjs.org/postcss 265ms (cache revalidated)
109 silly fetch manifest expect@^29.0.0
110 http fetch GET 200 https://registry.npmjs.org/expect 45ms (cache revalidated)
111 silly fetch manifest html-validate@7.13.2
112 http fetch GET 200 https://registry.npmjs.org/html-validate 940ms (cache revalidated)
113 silly fetch manifest jest@^25.1 || ^26 || ^27.1 || ^28.1.3 || ^29.0.3
114 http fetch GET 200 https://registry.npmjs.org/jest 883ms (cache revalidated)
115 silly fetch manifest node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0
116 http fetch GET 200 https://registry.npmjs.org/node-notifier 56ms (cache revalidated)
117 silly fetch manifest jest-diff@^25.1 || ^26 || ^27.1 || ^28.1.3 || ^29.0.3
118 http fetch GET 200 https://registry.npmjs.org/jest-diff 41ms (cache revalidated)
119 silly fetch manifest jest-snapshot@^25.1 || ^26 || ^27.1 || ^28.1.3 || ^29.0.3
120 http fetch GET 200 https://registry.npmjs.org/jest-snapshot 33ms (cache revalidated)
121 silly fetch manifest inquirer@8.2.5
122 http fetch GET 200 https://registry.npmjs.org/inquirer 264ms (cache revalidated)
123 silly fetch manifest jwks-rsa@3.0.1
124 http fetch GET 200 https://registry.npmjs.org/jwks-rsa 278ms (cache revalidated)
125 silly fetch manifest mocha@10.2.0
126 http fetch GET 200 https://registry.npmjs.org/mocha 73ms (cache revalidated)
127 silly fetch manifest mocha-slow-test-reporter@0.1.2
128 http fetch GET 200 https://registry.npmjs.org/mocha-slow-test-reporter 947ms (cache revalidated)
129 silly fetch manifest mock-knex@TryGhost/mock-knex#8ecb8c227bf463c991c3d820d33f59efc3ab9682
130 http fetch GET 200 https://codeload.github.com/TryGhost/mock-knex/tar.gz/8ecb8c227bf463c991c3d820d33f59efc3ab9682 232ms (cache revalidated)
131 timing arborist:ctor Completed in 1ms
132 silly fetch manifest knex@2.4.2
133 http fetch GET 200 https://registry.npmjs.org/knex 268ms (cache revalidated)
134 silly fetch manifest knex@> 0.8 < 2.1
135 timing idealTree Completed in 17328ms
136 timing command:install Completed in 17337ms
137 verbose stack Error: unable to resolve dependency tree
137 verbose stack     at [failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1380:25)
137 verbose stack     at [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1346:34)
137 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
137 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
137 verbose stack     at async Promise.all (index 1)
137 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:156:5)
137 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:146:5)
137 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
138 verbose cwd /var/www/andreasainato/versions/5.34.0
139 verbose Linux 5.2.0
140 verbose node v18.14.0
141 verbose npm  v9.3.1
142 error code ERESOLVE
143 error ERESOLVE unable to resolve dependency tree
144 error
145 error While resolving: ^[[1mghost^[[22m@^[[1m5.34.0^[[22m
145 error Found: ^[[1mknex^[[22m@^[[1m2.4.2^[[22m^[[2m^[[22m
145 error ^[[2mnode_modules/knex^[[22m
145 error   ^[[1mknex^[[22m@"^[[1m2.4.2^[[22m" from the root project
145 error
145 error Could not resolve dependency:
145 error ^[[35mpeer^[[39m ^[[1mknex^[[22m@"^[[1m> 0.8 < 2.1^[[22m" from ^[[1mmock-knex^[[22m@^[[1m0.4.9^[[22m^[[2m^[[22m
145 error ^[[2mnode_modules/mock-knex^[[22m
145 error   ^[[33mdev^[[39m ^[[1mmock-knex^[[22m@"^[[1mTryGhost/mock-knex#8ecb8c227bf463c991c3d820d33f59efc3ab9682^[[22m" from the root project
145 error
145 error Fix the upstream dependency conflict, or retry
145 error this command with --force or --legacy-peer-deps
145 error to accept an incorrect (and potentially broken) dependency resolution.
146 error
146 error
146 error For a full report see:
146 error /home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-eresolve-report.txt
147 verbose exit 1
148 timing npm Completed in 17394ms
149 verbose unfinished npm timer reify 1677074664034
150 verbose unfinished npm timer reify:loadTrees 1677074664037
151 verbose unfinished npm timer idealTree:buildDeps 1677074667496
152 verbose unfinished npm timer idealTree:#root 1677074667497
153 verbose code 1
154 error A complete log of this run can be found in:
154 error     /home/antonio/.npm/_logs/2023-02-22T14_04_23_984Z-debug-0.log
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@antonioalia7 This is a limitation of `npm`, but we also recommend using `yarn` for Ghost. `mock-knex` is a devDependency so you shouldn't be installing it for production anyway.
