### ISSUE TITLE
Got “Invalid token” in Admin API Token authentication even with the token generated by the Bash (cURL) sample code in Doc.

### ISSUE THREAD

**Issue by GavinCnod** [TryGhost/Ghost#16313]
### Issue Summary

Got “Invalid token” in Admin API Token authentication even with the token generated by the Bash (cURL) sample code in Doc.

### Steps to Reproduce

1. Have a Docker installation of Ghost on my server. with "-e NODE_ENV=development" parameter. the website and the admin pages runs fine.
2. Setting a CUSTOM INTEGRATIONS and got the Admin API Key.
3. Write some code in Java of my own Content Mgt app follow the guide of Docs (not only the Split Key to ID and Secret, but also Decode the Hexdecimal Secret). but when using GET/POST /admin/post/ API got error as follow.
4. Even use the Sample Bash Code on Doc (https://ghost.org/docs/admin-api/#token-authentication) to generate JWT Token, also get the following error.
`{
-"errors": [
-{
"message": "Invalid token",
"context": null,
"type": "BadRequestError",
"details": null,
"property": null,
"help": null,
"code": "INVALID_JWT",
"id": "5c91e460-b27b-11ed-b16a-f7290cb584e9",
"ghostErrorCode": null
}
]
}`

Any other info:
1. I tried the /admin/site/ API, which is a unauthenticated, read-only endpoint, and IT RUNs FINE as excepted.
2. I tried switch Accept-Version from v3.0 to v4.0 to v5.0, but nothing change.
3. I tried rewrite the Token Generation logics and use different Java Library but didnot work.
4. I tried to use the Sample code in Doc, still cannot work.
5. Even tried to generate Token in jwt.io, still cannot work.

### Ghost Version

5.34

### Node.js Version

12.12.9

### How did you install Ghost?

By Docker with "-e NODE_ENV=development" parameter

### Database type

SQLite3

### Relevant log / error output

```shell
some logs form Docker Logs
`
[2023-02-22 06:37:19] INEO "GET /ghost/assets/vendor-253d6527ca6353855164ef65f896f762.js"200 11502ms[2023-02-22 06:37:21] INEO "GET /ghost/assets/chunk.616.18lelad6c33f0bec7a65.js" 200 13334ms[2023-02-22 06:37:22] ERROR "GET /ghost/api/admin/posts/" 400 2ms
Invalid token
Error ID:
5c9le460-b27b-1led-b16a-f7290cb584e9
Error Code:
INVALID JWT
BadRequestError: Invalid token
at authenticatelithloken (/var/lib/ghost/versions/5,34.0/core/server/services/auth/api-key/admin.js:96:21)
at authenticate (/var/lib/ghost/versions/5,34.0/core/server/services/auth/api-key/admin,js:63:12)
at layer.handle las handle reguest) (/var/lib/ghost/versions/5.34.0/node modules/express/lib/router/layer.js:95:5)
at next (/var/lib/ghost/versions/5.34.0/node modules/express/lib/router/route.js:144:13)
at Route.dispatch (/var/lib/ghost/versions/5.34.0/node modules/express/lib/router/route.js:114:3)
at layer.handle [las handle request) (/var/lib/ghost/versions/5.34.0/node modules/express/lib/router/layer.js:95:5)
at /var/lib/ghost/versions/5,34.0/node modules/express/lib/router/index.js:284:15
at Function,process params (/var/lib/ghost/versions/5,34.0/node modules/express/lib/router/index,js:346:12)
at next (/var/lib/ghost/versions/5.34.0/node modules/express/lib/router/index.js:280:10)
at /var/lib/ghost/versions/5.34.0/node modules/cors/lib/index.js:228:13
at corsOotionsDelegate (/var/lib/chost/versions/5,34.0/core/server/web/api/middleware/cors.is:73:16)
at corsMiddleware (/var/lib/ghost/versions/5.34.0/node modules/cors/lib/index.js:204:7)
at layer.handle las handle request  /var/lib/ghost/versions/5,34.0/node modulesexpress/lib/router/layer.ja;95:5
at trim prefix (/var/lib/ghost/versions/5,34.0/node modules/express/lib/router/index.js:328:13)
at /var/lib/ghost/versions/5.34.0/node modules/express/lib/router/index,is:286:9
at Eunction,process params (/var/lib/ghost/versions/5,34.0/node modules/express/lib/router/index,js:346:12)
`
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@GavinCnod I've labelled this a support request as it belongs on the forum, but the Bash example listed [here](https://ghost.org/docs/admin-api/#token-authentication) also works as-is for me, just by replacing the Admin API key.
