### ISSUE TITLE
Handlebars helper for assets errors when input is SafeString

### ISSUE THREAD

**Issue by monkeysees** [TryGhost/Ghost#16332]
### Issue Summary

Try to compute asset path with `asset` helper and passing `(concat "some" "string")` as input i.e. check `{{asset (concat 'some' 'string'}}`. It will error with `[error.hbs] path.match is not a function`.

Relevant lines of code:
https://github.com/TryGhost/Ghost/blob/c667620d8f2e32c96fe376ad0f3dabc79488532a/ghost/core/core/frontend/helpers/asset.js#L28
https://github.com/TryGhost/Ghost/blob/c667620d8f2e32c96fe376ad0f3dabc79488532a/ghost/core/core/frontend/meta/asset-url.js#L16
https://github.com/TryGhost/Ghost/blob/c667620d8f2e32c96fe376ad0f3dabc79488532a/ghost/core/core/frontend/helpers/concat.js#L7

### Steps to Reproduce

`{{asset (concat 'some' 'string'}}` produces error regardless of the concatenated string provided. The reason is that asset helper expect plain strings as input but `(concat …)` produces `SafeString` object which results in the above error.

### Ghost Version

5.35.1-alpine (https://hub.docker.com/_/ghost)

### Node.js Version

Comes with https://hub.docker.com/_/ghost

### How did you install Ghost?

https://hub.docker.com/_/ghost

### Relevant log / error output

```shell
TypeError: path.match is not a function
      at getAssetUrl (core/frontend/meta/asset-url.js:16:14)
      at Object.asset (core/frontend/helpers/asset.js:40:9)
      at Object.wrapper (/home/monkeysees/ghost-git/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
      at Object.eval [as main] (eval at createFunctionContext (/home/monkeysees/ghost-git/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:123)
      at main (/home/monkeysees/ghost-git/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
      at ret (/home/monkeysees/ghost-git/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
      at ret (/home/monkeysees/ghost-git/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by monkeysees** [comment]
I’ll be happy to work on a PR.

**Comment by daniellockyer** [comment]
@monkeysees We'd welcome a PR to fix this 🙂
