### ISSUE TITLE
Test Failures on Fresh Clone 

### ISSUE THREAD

**Issue by a-amir01** [TryGhost/Ghost#16679]
### Issue Summary

yarn test results in test failures - updated with the latest commit e6f9fce99abd4e3cba06a35e21aed8920ccd7db3
- @tryghost/slack-notifications:test
- @tryghost/stats-service:test

### Steps to Reproduce

yarn global add knex-migrator ember-cli
git clone --recurse-submodules git@github.com:TryGhost/Ghost && cd Ghost
yarn setup
yarn test

### Ghost Version

5.44

### Node.js Version

v16.19.1

### How did you install Ghost?

Local Install 

### Database type

SQLite3

### Browser & OS version

MacBook Pro 13" 2 GHz Quad-Core Intel Core i5

### Relevant log / error output

```shell
1) SlackNotifications
              notifyMilestoneReceived
                Sends a notification to Slack for achieved ARR Milestone - no meta:
       
             AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
       
         assert(sendStub.calledWith(expectedResult, 'https://slack-webhook.example') === true)
       
             + expected - actual
       
             -false
             +true
             
             at Context.<anonymous> (test/SlackNotifications.test.js:104:13)

1) MembersStatsService
              getCountHistory
                Always returns at least one value:
       
             AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
       
       {
         comped: 3,
         date: '2000-01-09',
         free: 2,
         paid: 1,
         paid_canceled: 0,
         paid_subscribed: 0
       }
       
       should loosely deep-equal
       
       {
         comped: 3,
         date: '2000-01-10',
         free: 2,
         paid: 1,
         paid_canceled: 0,
         paid_subscribed: 0
       }
             + expected - actual
       
              {
                "comped": 3
             -  "date": "2000-01-09"
             +  "date": "2000-01-10"
                "free": 2
                "paid": 1
                "paid_canceled": 0
                "paid_subscribed": 0
             
             at Context.<anonymous> (test/lib/members.test.js:132:20)
       
         2) MembersStatsService
              getCountHistory
                Passes paid_subscribers and paid_canceled:
       
             AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
       
       [
         {
           comped: 3,
           date: '2000-01-09',
           free: 2,
           paid: 1,
           paid_canceled: 0,
           paid_subscribed: 0
         }
       ]
       
       should loosely deep-equal
       
       [
         {
           comped: 0,
           date: '2000-01-09',
           free: 0,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 3,
           date: '2000-01-10',
           free: 2,
           paid: 1,
           paid_canceled: 3,
           paid_subscribed: 4
         }
       ]
             + expected - actual
       
              [
                {
             -    "comped": 3
             +    "comped": 0
                  "date": "2000-01-09"
             -    "free": 2
             -    "paid": 1
             +    "free": 0
             +    "paid": 0
                  "paid_canceled": 0
                  "paid_subscribed": 0
                }
             +  {
             +    "comped": 3
             +    "date": "2000-01-10"
             +    "free": 2
             +    "paid": 1
             +    "paid_canceled": 3
             +    "paid_subscribed": 4
             +  }
              ]
             
             at Context.<anonymous> (test/lib/members.test.js:163:20)
       
         3) MembersStatsService
              getCountHistory
                Correctly resolves deltas:
       
             AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
       
       [
         {
           comped: 4,
           date: '2000-01-08',
           free: 3,
           paid: 1,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 4,
           date: '2000-01-09',
           free: 3,
           paid: 2,
           paid_canceled: 1,
           paid_subscribed: 2
         }
       ]
       
       should loosely deep-equal
       
       [
         {
           comped: 1,
           date: '2000-01-08',
           free: 1,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 1,
           date: '2000-01-09',
           free: 1,
           paid: 1,
           paid_canceled: 1,
           paid_subscribed: 2
         },
         {
           comped: 4,
           date: '2000-01-10',
           free: 3,
           paid: 2,
           paid_canceled: 3,
           paid_subscribed: 4
         }
       ]
             + expected - actual
       
              [
                {
             -    "comped": 4
             +    "comped": 1
                  "date": "2000-01-08"
             -    "free": 3
             -    "paid": 1
             +    "free": 1
             +    "paid": 0
                  "paid_canceled": 0
                  "paid_subscribed": 0
                }
                {
             -    "comped": 4
             +    "comped": 1
                  "date": "2000-01-09"
             -    "free": 3
             -    "paid": 2
             +    "free": 1
             +    "paid": 1
                  "paid_canceled": 1
                  "paid_subscribed": 2
                }
             +  {
             +    "comped": 4
             +    "date": "2000-01-10"
             +    "free": 3
             +    "paid": 2
             +    "paid_canceled": 3
             +    "paid_subscribed": 4
             +  }
              ]
             
             at Context.<anonymous> (test/lib/members.test.js:211:20)
       
         4) MembersStatsService
              getCountHistory
                Correctly handles negative numbers:
       
             AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
       
       [
         {
           comped: 0,
           date: '2000-01-07',
           free: 101,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 4,
           date: '2000-01-08',
           free: 103,
           paid: 1,
           paid_canceled: 1,
           paid_subscribed: 2
         },
         {
           comped: 4,
           date: '2000-01-09',
           free: 3,
           paid: 2,
           paid_canceled: 1,
           paid_subscribed: 2
         }
       ]
       
       should loosely deep-equal
       
       [
         {
           comped: 0,
           date: '2000-01-07',
           free: 1,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 1,
           date: '2000-01-08',
           free: 3,
           paid: 0,
           paid_canceled: 1,
           paid_subscribed: 2
         },
         {
           comped: 1,
           date: '2000-01-09',
           free: 0,
           paid: 1,
           paid_canceled: 1,
           paid_subscribed: 2
         },
         {
           comped: 4,
           date: '2000-01-10',
           free: 3,
           paid: 2,
           paid_canceled: 3,
           paid_subscribed: 4
         }
       ]
             + expected - actual
       
              [
                {
                  "comped": 0
                  "date": "2000-01-07"
             -    "free": 101
             +    "free": 1
                  "paid": 0
                  "paid_canceled": 0
                  "paid_subscribed": 0
                }
                {
             -    "comped": 4
             +    "comped": 1
                  "date": "2000-01-08"
             -    "free": 103
             +    "free": 3
             +    "paid": 0
             +    "paid_canceled": 1
             +    "paid_subscribed": 2
             +  }
             +  {
             +    "comped": 1
             +    "date": "2000-01-09"
             +    "free": 0
                  "paid": 1
                  "paid_canceled": 1
                  "paid_subscribed": 2
                }
                {
                  "comped": 4
             -    "date": "2000-01-09"
             +    "date": "2000-01-10"
                  "free": 3
                  "paid": 2
             -    "paid_canceled": 1
             -    "paid_subscribed": 2
             +    "paid_canceled": 3
             +    "paid_subscribed": 4
                }
              ]
             
             at Context.<anonymous> (test/lib/members.test.js:274:20)
       
         5) MembersStatsService
              getCountHistory
                Ignores events in the future:
       
             AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
       
       [
         {
           comped: 3,
           date: '2000-01-08',
           free: 1,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 3,
           date: '2000-01-09',
           free: 2,
           paid: 1,
           paid_canceled: 0,
           paid_subscribed: 1
         }
       ]
       
       should loosely deep-equal
       
       [
         {
           comped: 0,
           date: '2000-01-08',
           free: 0,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 0
         },
         {
           comped: 0,
           date: '2000-01-09',
           free: 0,
           paid: 0,
           paid_canceled: 0,
           paid_subscribed: 1
         },
         {
           comped: 3,
           date: '2000-01-10',
           free: 2,
           paid: 1,
           paid_canceled: 3,
           paid_subscribed: 4
         }
       ]
             + expected - actual
       
              [
                {
             -    "comped": 3
             +    "comped": 0
                  "date": "2000-01-08"
             -    "free": 1
             +    "free": 0
                  "paid": 0
                  "paid_canceled": 0
                  "paid_subscribed": 0
                }
                {
             -    "comped": 3
             +    "comped": 0
                  "date": "2000-01-09"
             -    "free": 2
             -    "paid": 1
             +    "free": 0
             +    "paid": 0
                  "paid_canceled": 0
                  "paid_subscribed": 1
                }
             +  {
             +    "comped": 3
             +    "date": "2000-01-10"
             +    "free": 2
             +    "paid": 1
             +    "paid_canceled": 3
             +    "paid_subscribed": 4
             +  }
              ]
             
             at Context.<anonymous> (test/lib/members.test.js:347:20)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by a-amir01** [comment]
Even when I download https://github.com/TryGhost/Ghost/releases/tag/v5.44.0
Do 
yarn setup 
yarn test
I get the same failure. 
The code for the tests haven't changed in months. What am I doing wrong here ?

**Comment by a-amir01** [comment]
Please help, this is still happening with the latest update from upstream

**Comment by daniellockyer** [comment]
@a-amir01 That's strange! I don't get those errors locally nor in CI.

**Comment by a-amir01** [comment]
Hmm could it be the node version I am running ? 
node: v16.19.1

The only thing I'm doing is 
```
git clone --recurse-submodules [git@github.com](mailto:git@github.com):TryGhost/Ghost && cd Ghost
yarn setup
yarn test
```

**Comment by a-amir01** [comment]
@daniellockyer here is a video running yarn test on the latest version 

Steps: 
wget https://github.com/TryGhost/Ghost/archive/refs/tags/v5.46.1.zip
unzip v5.46.1.zip
cd Ghost-5.46.1
yarn && yarn workspace ghost run setup (essentially yarn setup without the git init part)
yarn test

Node Version: v16.13.0

https://user-images.githubusercontent.com/15374718/236050564-018ddedb-8024-4eae-8e49-ebfececacdc7.MP4

**Comment by a-amir01** [comment]
@allouis awesome! the timezone fixed the issue. I am now getting a different test failure.

```
ghost-admin:test
Launcher Chrome not found. Not installed?
```

Is there something extra I need to setup for headless chrome ?

**Comment by a-amir01** [comment]
Since I have the project forked, there are some pre-validations before you can push your changes to the forked origin. 
So `git push origin main` will fail because of those test failures. Is there a way to force the timezone ?

**Comment by hemri** [comment]
Hi all, I am in CST timezone and I got the same errors related to timezones as reported here. This PR that attempts to make the code independant on the system timezone: https://github.com/TryGhost/Ghost/pull/17013
thanks for your review/comments in advance.
