### ISSUE TITLE
Mail error message shown, even though message was sent

### ISSUE THREAD

**Issue by creyD** [TryGhost/Ghost#16851]
### Issue Summary

Ghost shows "Error sending email! Error sending email: Failed to send email. Reason: Sending failed. Please check your email settings and resend the invitation." as a banner and also in the console log, even though the message was sent successfully. I am using a mailgun config and hosting ghost in a docker container.

### Steps to Reproduce

1. Setup mailgun configuration
2. Invite a user
3. Error message appears

### Ghost Version

5.49.0

### Node.js Version

v16.20.0

### How did you install Ghost?

Custom Docker Compose

### Database type

MySQL 8

### Relevant log / error output

```shell
ghost_app    | [2023-05-23 21:15:01] ERROR "POST /ghost/api/admin/invites/" 500 132ms
ghost_app    | 
ghost_app    | Error sending email: Failed to send email. Reason: Sending failed. Please check your email settings and resend the invitation.
ghost_app    | 
ghost_app    | "Please see https://ghost.org/docs/config/#mail for instructions on configuring email."
ghost_app    | 
ghost_app    | Error ID:
ghost_app    |     e0ea2360-f9ae-11ed-bd2e-c9968c393f20
ghost_app    | 
ghost_app    | ----------------------------------------
ghost_app    | 
ghost_app    | Error: Sending failed
ghost_app    |     at createMailError (/var/lib/ghost/versions/5.49.0/core/server/services/mail/GhostMailer.js:68:12)
ghost_app    |     at DirectMailer.<anonymous> (/var/lib/ghost/versions/5.49.0/node_modules/nodemailer-direct-transport/lib/direct-transport.js:157:41)
ghost_app    |     at DirectMailer.<anonymous> (/var/lib/ghost/versions/5.49.0/node_modules/nodemailer-direct-transport/lib/direct-transport.js:228:30)
ghost_app    |     at DirectMailer.<anonymous> (/var/lib/ghost/versions/5.49.0/node_modules/nodemailer-direct-transport/lib/direct-transport.js:326:28)
ghost_app    |     at Object.onceWrapper (node:events:628:26)
ghost_app    |     at SMTPConnection.emit (node:events:513:28)
ghost_app    |     at SMTPConnection._onError (/var/lib/ghost/versions/5.49.0/node_modules/smtp-connection/lib/smtp-connection.js:518:10)
ghost_app    |     at SMTPConnection._actionGreeting (/var/lib/ghost/versions/5.49.0/node_modules/smtp-connection/lib/smtp-connection.js:893:14)
ghost_app    |     at SMTPConnection._processResponse (/var/lib/ghost/versions/5.49.0/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
ghost_app    |     at SMTPConnection._onData (/var/lib/ghost/versions/5.49.0/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
ghost_app    |     at Socket.emit (node:events:513:28)
ghost_app    |     at addChunk (node:internal/streams/readable:315:12)
ghost_app    |     at readableAddChunk (node:internal/streams/readable:289:9)
ghost_app    |     at Socket.Readable.push (node:internal/streams/readable:228:10)
ghost_app    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by creyD** [comment]
So it is not a bug that ghost shows it can't send mails while it in fact can. Didn't read that in the docs anywhere...
