### ISSUE TITLE
Type error within hash function during setting up 

### ISSUE THREAD

**Issue by nishp77** [TryGhost/Ghost#16918]
### Issue Summary

I was trying to setup the docker container with mysql both are latest, version 5.49 of Ghost. It threw an error that there was an invalid type argument for hashing function SHA1 within mysql2 package. I have defined the password as string but somehow it assumes it's a number therefore some type issue. I'm attaching the pic of the error

![image](https://github.com/TryGhost/Ghost/assets/35785259/983e7df5-3d97-4e5b-8579-222b1d18c8e2)

### Steps to Reproduce

1. Get the latest mysql and ghost(5.49)
2. Try to run the compose file with:- 

version: '3.3'

services:
  blog:
    image: ghost:latest
    restart: always
    volumes:
      - ~/data/content:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: '1877'
      database__connection__database: ghost
      url: https://ghost.justarandomdev.com
      NODE_ENV: production

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1877'
      MYSQL_DATABASE: ghost
      MYSQL_USER: user
      MYSQL_PASSWORD: '1877'

### Ghost Version

5.49.2

### Node.js Version

16.20.0

### How did you install Ghost?

Using portainer with docker on linux

### Database type

MySQL 8

### Relevant log / error output

```shell
[2023-06-02 01:52:43] INFO Ghost is running in production...
blog_1      | [2023-06-02 01:52:43] INFO Your site is now available on https://ghost.justarandomdev.com/
blog_1      | [2023-06-02 01:52:43] INFO Ctrl+C to shut down
blog_1      | [2023-06-02 01:52:43] INFO Ghost server started in 1.219s
blog_1      | node:internal/crypto/hash:109
blog_1      |     throw new ERR_INVALID_ARG_TYPE(
blog_1      |     ^
blog_1      | 
blog_1      | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1877)
blog_1      |     at new NodeError (node:internal/errors:387:5)
blog_1      |     at Hash.update (node:internal/crypto/hash:109:11)
blog_1      |     at sha1 (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/auth_41.js:31:8)
blog_1      |     at Object.token [as calculateToken] (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/auth_41.js:57:18)
blog_1      |     at new HandshakeResponse (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/packets/handshake_response.js:28:26)
blog_1      |     at ClientHandshake.sendCredentials (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/commands/client_handshake.js:71:31)
blog_1      |     at ClientHandshake.handshakeInit (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/commands/client_handshake.js:162:12)
blog_1      |     at ClientHandshake.execute (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/commands/command.js:45:22)
blog_1      |     at Connection.handlePacket (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/connection.js:489:32)
blog_1      |     at PacketParser.onPacket (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/connection.js:94:12)
blog_1      |     at PacketParser.executeStart (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/packet_parser.js:75:16)
blog_1      |     at Socket.<anonymous> (/var/lib/ghost/versions/5.49.2/node_modules/mysql2/lib/connection.js:101:25)
blog_1      |     at Socket.emit (node:events:513:28)
blog_1      |     at addChunk (node:internal/streams/readable:315:12)
blog_1      |     at readableAddChunk (node:internal/streams/readable:289:9)
blog_1      |     at Socket.Readable.push (node:internal/streams/readable:228:10) {
blog_1      |   code: 'ERR_INVALID_ARG_TYPE'
blog_1      | }
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by nishp77** [comment]
I was looking at the code found it was within core folder that's using mysql2 however it's not using the latest module

**Comment by daniellockyer** [comment]
This seems to be due to the fact that ` database__connection__password: '1877'` becomes a number, and mysql2 doesn't like that. It's quite niche but we can probably workaround it, so a PR would be welcome 🙂
