### ISSUE TITLE
ARM64 Make NodeJS Error node-gyp rebuild

### ISSUE THREAD

**Issue by danielehrhardt** [TryGhost/Ghost#16936]
### Issue Summary

If i try to install Ghost on a Arm64 Server ghost install in the www directory i get a make error:

```
Building locally ...

> re2@1.18.0 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.0 | linux | arm64
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.16.0/node-v18.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ghost/.cache/node-gyp/18.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ghost/.cache/node-gyp/18.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ghost/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:10:17)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:54:21)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:69:33)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:80:22
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
gyp ERR! System Linux 5.15.0-73-generic
gyp ERR! command "/usr/bin/node" "/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.7
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.7>
npm notice Run `npm install -g npm@9.6.7` to update!
npm notice 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.16.0

> re2@1.18.0 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.0 | linux | arm64
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ghost/.cache/node-gyp/18.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ghost/.cache/node-gyp/18.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ghost/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:10:17)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:54:21)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:69:33)
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/which/which.js:80:22
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/newsletter.codext.de/versions/5.50.0/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
gyp ERR! System Linux 5.15.0-73-generic
gyp ERR! command "/usr/bin/node" "/var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/newsletter.codext.de/versions/5.50.0/node_modules/re2
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

```

### Steps to Reproduce

1. Setup Hetzner Arm64 Server
2. Run steps: https://ghost.org/docs/install/ubuntu/
3. ghost install

### Ghost Version

1.24.0

### Node.js Version

18

### How did you install Ghost?

arm64 ubuntu

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kiraitachi** [comment]
This is actually an issue for me too. It seems its related to nodejs18 not supporting arm64. Nodejs16 seems to work.
