### ISSUE TITLE
DB migration failure on donation_payments_events in 5.57.2

### ISSUE THREAD

**Issue by major** [TryGhost/Ghost#17584]
### Issue Summary

After updating to 5.57.2 via a new Docker image, my Ghost blog was unresponsive in the browser. Once I logged in, I saw there was a failed database migration due to a foreign key in `donation_payments_events`. (Full output in the log output section)

I downgraded back to 5.55.2 and Ghost is operating normally again.

### Steps to Reproduce

1. Was running 5.55.2 via Docker
2. Updated docker container to 5.57.2
3. After Ghost restarted, the database migration failed and Ghost's admin console was unresponsive.

### Ghost Version

5.57.2

### Node.js Version

Unsure

### How did you install Ghost?

Docker image

### Database type

MySQL 8

### Relevant log / error output

```shell
[2023-08-03 11:10:16] INFO Adding members.email_disabled column
[2023-08-03 11:10:16] INFO Setting email_disabled to true for all members that have their email on the suppression list
[2023-08-03 11:10:16] INFO Setting nullable: stripe_products.product_id
[2023-08-03 11:10:16] INFO Adding table: donation_payment_events
[2023-08-03 11:10:16] INFO Rolling back: alter table `donation_payment_events` add constraint `donation_payment_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete SET NULL - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'donation_payment_events_member_id_foreign' are incompatible..
[2023-08-03 11:10:16] INFO Dropping table: donation_payment_events
[2023-08-03 11:10:16] INFO Dropping nullable:  stripe_products.product_id with foreign keys disabled
[2023-08-03 11:10:16] INFO Setting email_disabled to false for all members
[2023-08-03 11:10:16] INFO Removing members.email_disabled column
[2023-08-03 11:10:16] INFO Rollback was successful.
[2023-08-03 11:10:16] ERROR alter table `donation_payment_events` add constraint `donation_payment_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete SET NULL - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'donation_payment_events_member_id_foreign' are incompatible.

alter table `donation_payment_events` add constraint `donation_payment_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete SET NULL - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'donation_payment_events_member_id_foreign' are incompatible.
{"config":{"transaction":false},"name":"2023-07-27-11-47-49-create-donation-events.js"}
"Error occurred while executing the following migration: 2023-07-27-11-47-49-create-donation-events.js"
Error ID:
    300
Error Code: 
    ER_FK_INCOMPATIBLE_COLUMNS
----------------------------------------
Error: alter table `donation_payment_events` add constraint `donation_payment_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete SET NULL - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'donation_payment_events_member_id_foreign' are incompatible.
    at /var/lib/ghost/versions/5.57.2/node_modules/knex-migrator/lib/index.js:1032:19
    at Packet.asError (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/lib/ghost/versions/5.57.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by major** [comment]
My current `members` table today as it exists in MySQL:

```
mysql> describe members;
+------------------------------+---------------+------+-----+---------+-------+
| Field                        | Type          | Null | Key | Default | Extra |
+------------------------------+---------------+------+-----+---------+-------+
| id                           | varchar(24)   | NO   | PRI | NULL    |       |
| uuid                         | varchar(36)   | YES  | UNI | NULL    |       |
| email                        | varchar(191)  | NO   | UNI | NULL    |       |
| status                       | varchar(50)   | NO   |     | free    |       |
| name                         | varchar(191)  | YES  |     | NULL    |       |
| expertise                    | varchar(191)  | YES  |     | NULL    |       |
| note                         | varchar(2000) | YES  |     | NULL    |       |
| geolocation                  | varchar(2000) | YES  |     | NULL    |       |
| enable_comment_notifications | tinyint(1)    | NO   |     | 1       |       |
| email_count                  | int unsigned  | NO   |     | 0       |       |
| email_opened_count           | int unsigned  | NO   |     | 0       |       |
| email_open_rate              | int unsigned  | YES  | MUL | NULL    |       |
| last_seen_at                 | datetime      | YES  |     | NULL    |       |
| last_commented_at            | datetime      | YES  |     | NULL    |       |
| created_at                   | datetime      | NO   |     | NULL    |       |
| created_by                   | varchar(24)   | NO   |     | NULL    |       |
| updated_at                   | datetime      | YES  |     | NULL    |       |
| updated_by                   | varchar(24)   | YES  |     | NULL    |       |
+------------------------------+---------------+------+-----+---------+-------+
18 rows in set (0.00 sec)
```

**Comment by daniellockyer** [comment]
Hey @major - did you update your DB from MySQL 5 to 8 recently? I believe this is due to mismatched collations and not a bug within Ghost itself as we're not seeing this elsewhere

**Comment by major** [comment]
@daniellockyer Thanks for the reply. I did switch weeks ago. Is there a guide for getting these collations corrected?

**Comment by major** [comment]
@daniellockyer For what it's worth, I ran through [some steps](https://dnsmichi.at/2022/06/01/ghost-v5-upgrade-with-mysql-8-collation-migration-in-docker-compose/) to change the collation on my tables and that seems to have fixed it.

```
[2023-08-09 12:47:39] INFO Ghost server started in 0.994s
[2023-08-09 12:47:39] WARN Database state requires migration.
[2023-08-09 12:47:40] INFO Creating database backup
[2023-08-09 12:47:40] INFO Database backup written to ...
[2023-08-09 12:47:40] INFO Running migrations.
[2023-08-09 12:47:40] INFO Adding members.email_disabled column
[2023-08-09 12:47:40] INFO Setting email_disabled to true for all members that have their email on the suppression list
[2023-08-09 12:47:40] INFO Setting nullable: stripe_products.product_id
[2023-08-09 12:47:40] INFO Adding table: donation_payment_events
[2023-08-09 12:47:40] INFO Adding setting: donations_currency
[2023-08-09 12:47:40] INFO Adding setting: donations_suggested_amount
[2023-08-09 12:47:40] INFO Database is in a ready state.
[2023-08-09 12:47:40] INFO Ghost database ready in 2.087s
```

**Comment by daniellockyer** [comment]
Great! 

We do mention collations here: https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_cant_create_table-with-_foreign-key-constraint-is-incorrectly-formed_, but this now seems to be a different error code. I'll see if we can add this to the docs so it's more searchable
