### ISSUE TITLE
@partial-block works, but throws errors

### ISSUE THREAD

**Issue by richardpickett** [TryGhost/Ghost#17914]
### Issue Summary

Partial blocks are fully supported by handlebars and ghost (it displays as expected), yet it throws errors whenever the theme using `@partial-block` is uploaded or ghost starts and that theme is the current theme.

Additionally the error is shown in the Ghost dashboard.

Handlebars documentation on partial blocks: https://handlebarsjs.com/guide/partials.html#partial-blocks

The error thrown:

```
Error ID:
    aaa99960-484c-11ee-bbd7-3f8b55bc8265

Details:
    checkedVersion: 5.x
    name:           casper-custom
    path:           /var/lib/ghost/content/themes/casper-custom
    version:        5.4.4
    errors: 
      - 
        fatal:    false
        level:    error
        rule:     Unknown global helper used
        details:  A global helper was detected that is not supported by this version of Ghost. Check the <a href="https://ghost.org/docs/themes/helpers/" target=_blank>helpers documentation</a> for further information.
        failures: 
          - 
            ref:     partials/parts/text-column-with-video-column.hbs
            message: {{@partial-block}} is not a known global
          - 
            ref:     partials/parts/text-column-with-video-column.hbs
            message: {{@partial-block}} is not a known global
        code:     GS120-NO-UNKNOWN-GLOBALS
    warnings: 
      (empty array)

----------------------------------------

ThemeValidationError: The currently active theme "casper-custom" has errors, but will still work.
    at Object.getThemeValidationError (/var/lib/ghost/versions/5.59.1/core/server/services/themes/validate.js:142:12)
    at Object.module.exports.loadAndActivate (/var/lib/ghost/versions/5.59.1/core/server/services/themes/activate.js:30:35)
    at async initServicesForFrontend (/var/lib/ghost/versions/5.59.1/core/boot.js:192:5)
    at async bootGhost (/var/lib/ghost/versions/5.59.1/core/boot.js:501:31)
```

### Steps to Reproduce

1. Create a block as seen in the Handlebars documentation in your theme.
2. Upload the theme.

Expected behavior: no error would be thrown.

### Ghost Version

5.59.1

### Node.js Version

v16.20.2

### How did you install Ghost?

I'm using the docker image

### Database type

MySQL 8

### Browser & OS version

N/A

### Relevant log / error output

```shell
Error ID:
    aaa99960-484c-11ee-bbd7-3f8b55bc8265

Details:
    checkedVersion: 5.x
    name:           casper-custom
    path:           /var/lib/ghost/content/themes/casper-custom
    version:        5.4.4
    errors: 
      - 
        fatal:    false
        level:    error
        rule:     Unknown global helper used
        details:  A global helper was detected that is not supported by this version of Ghost. Check the <a href="https://ghost.org/docs/themes/helpers/" target=_blank>helpers documentation</a> for further information.
        failures: 
          - 
            ref:     partials/parts/text-column-with-video-column.hbs
            message: {{@partial-block}} is not a known global
          - 
            ref:     partials/parts/text-column-with-video-column.hbs
            message: {{@partial-block}} is not a known global
        code:     GS120-NO-UNKNOWN-GLOBALS
    warnings: 
      (empty array)

----------------------------------------

ThemeValidationError: The currently active theme "casper-custom" has errors, but will still work.
    at Object.getThemeValidationError (/var/lib/ghost/versions/5.59.1/core/server/services/themes/validate.js:142:12)
    at Object.module.exports.loadAndActivate (/var/lib/ghost/versions/5.59.1/core/server/services/themes/activate.js:30:35)
    at async initServicesForFrontend (/var/lib/ghost/versions/5.59.1/core/boot.js:192:5)
    at async bootGhost (/var/lib/ghost/versions/5.59.1/core/boot.js:501:31)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by zendyani** [comment]
Hi there,
Is it possible to have more details, after forking Casper theme [here](git@github.com:zendyani/Casper-test.git) 
and added a partial block I didn't see the errors.
You can check the code I added #https://github.com/zendyani/Casper-test/commit/58a7a9e925d7e1555b1db93c138fe27ef645ef2b
Any help to trigger the error is welcome.
Thanks

**Comment by richardpickett** [comment]
My code uses it like this:

`{{{@partial-block}}}
`
