### ISSUE TITLE
Image uploads fail because sharp isn't installed [ARMv7]

### ISSUE THREAD

**Issue by XChikuX** [TryGhost/Ghost#17935]
### Issue Summary

I checked the node_modules folder. I am running 2 different individual instances of ghost both at 5.60.

One of them is running on aarch64 while the other is on a 32bit version of alpine.

I can confirm there is no sharp folder on the armv7 attempt.

Are we planning on ever supporting this? I assume this is closely linked with #293 , #308

```
/var/lib/ghost/versions/5.60.0 # npm --version
8.19.4
/var/lib/ghost/versions/5.60.0 # node --version
v16.20.2
```

### Steps to Reproduce

Just try to upload images on a armv7 with the `ghost:alpine` docker image

### Ghost Version

5.60

### Node.js Version

v16.20.2

### How did you install Ghost?

Alpine docker image for 

### Database type

SQLite3

### Relevant log / error output

```shell
[2023-09-01 20:27:41] ERROR "POST /blog/ghost/api/admin/images/upload/" 500 98ms

Sharp wasn't installed

Error ID:
    0044bbc0-4906-11ee-a235-f737a40a4d9e

Error Code:
    SHARP_INSTALLATION

----------------------------------------

Error: Cannot find module 'sharp'
    at Object.resizeFromPath (/var/lib/ghost/versions/5.60.0/node_modules/@tryghost/image-transform/lib/transform.js:127:31)
Require stack:
- /var/lib/ghost/versions/5.60.0/node_modules/@tryghost/image-transform/lib/transform.js
- /var/lib/ghost/versions/5.60.0/node_modules/@tryghost/image-transform/index.js
- /var/lib/ghost/versions/5.60.0/core/frontend/helpers/img_url.js
- /var/lib/ghost/versions/5.60.0/core/frontend/services/helpers/registry.js
- /var/lib/ghost/versions/5.60.0/core/frontend/services/helpers/index.js
- /var/lib/ghost/versions/5.60.0/core/frontend/services/apps/proxy.js
- /var/lib/ghost/versions/5.60.0/core/frontend/services/apps/loader.js
- /var/lib/ghost/versions/5.60.0/core/frontend/services/apps/index.js
- /var/lib/ghost/versions/5.60.0/core/bridge.js
- /var/lib/ghost/versions/5.60.0/core/server/services/route-settings/RouteSettings.js
- /var/lib/ghost/versions/5.60.0/core/server/services/route-settings/index.js
- /var/lib/ghost/versions/5.60.0/core/boot.js
- /var/lib/ghost/versions/5.60.0/ghost.js
- /var/lib/ghost/versions/5.60.0/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.resizeFromPath (/var/lib/ghost/versions/5.60.0/node_modules/@tryghost/image-transform/lib/transform.js:125:9)
    at Object.query (/var/lib/ghost/versions/5.60.0/core/server/api/endpoints/images.js:36:38)
    at Object.query (/var/lib/ghost/versions/5.60.0/node_modules/@tryghost/api-framework/lib/pipeline.js:158:24)
    at /var/lib/ghost/versions/5.60.0/node_modules/@tryghost/api-framework/lib/pipeline.js:252:35
    at async /var/lib/ghost/versions/5.60.0/node_modules/@tryghost/api-framework/lib/http.js:64:28
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
It seems Sharp does not ship prebuilt binaries for ARMv7 as per https://github.com/lovell/sharp/releases/tag/v0.32.5

Our recommended + supported stack does not include ARMv7, so I'm going to close this issue, but I'd suggest asking the Sharp maintainers if they can add prebuilds for that architecture 🙂
