### ISSUE TITLE
Duplicate Entry inserting into `permissions` when starting from Backup

### ISSUE THREAD

**Issue by K1D77A** [TryGhost/Ghost#18386]
### Issue Summary

Hi, 
I dumped the mysql database used for an instance of Ghost that we were using in preproduction. I am now trying to use that dumped database for our new deployment which is using the Ghost Alpine docker container. 
I have mysql running locally (not in a container). 
But when I attempt to launch the container it complains about a duplicate entry and crashes.
Thanks. 

### Steps to Reproduce

Dump database from original 
Load database into mysql that new docker based deployment will use
launch through docker

### Ghost Version

Ghost docker current

### Node.js Version

Whatever is in the ghost docker

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Relevant log / error output

```shell
ghost_1  | [2023-09-27 19:18:02] INFO Removing posts.twitter_description column
ghost_1  | [2023-09-27 19:18:02] INFO Removing posts.twitter_title column
ghost_1  | [2023-09-27 19:18:02] INFO Removing posts.twitter_image column
ghost_1  | [2023-09-27 19:18:02] INFO Removing posts.og_description column
ghost_1  | [2023-09-27 19:18:02] INFO Removing posts.og_title column
ghost_1  | [2023-09-27 19:18:03] INFO Removing posts.og_image column
ghost_1  | [2023-09-27 19:18:03] INFO Removing posts.codeinjection_foot column
ghost_1  | [2023-09-27 19:18:03] INFO Removing posts.codeinjection_head column
ghost_1  | [2023-09-27 19:18:03] INFO Removing posts.custom_excerpt column
ghost_1  | [2023-09-27 19:18:03] INFO Rollback was successful.
ghost_1  | [2023-09-27 19:18:03] ERROR insert into `permissions` (`action_type`, `created_at`, `created_by`, `id`, `name`, `object_type`, `updated_at`, `updated_by`) values ('download', CURRENT_TIMESTAMP, 1, '65147feabf53f60001a38534', 'Upload redirects', 'redirect', CURRENT_TIMESTAMP, 1) - Duplicate entry 'Upload redirects' for key 'permissions.permissions_name_unique'
ghost_1  | 
ghost_1  | insert into `permissions` (`action_type`, `created_at`, `created_by`, `id`, `name`, `object_type`, `updated_at`, `updated_by`) values ('download', CURRENT_TIMESTAMP, 1, '65147feabf53f60001a38534', 'Upload redirects', 'redirect', CURRENT_TIMESTAMP, 1) - Duplicate entry 'Upload redirects' for key 'permissions.permissions_name_unique'
ghost_1  | 
ghost_1  | {"config":{"transaction":true},"name":"1-add-permissions-redirect.js"}
ghost_1  | "Error occurred while executing the following migration: 1-add-permissions-redirect.js"
ghost_1  | 
ghost_1  | Error ID:
ghost_1  |     300
ghost_1  | 
ghost_1  | Error Code: 
ghost_1  |     ER_DUP_ENTRY
ghost_1  | 
ghost_1  | ----------------------------------------
ghost_1  | 
ghost_1  | MigrationScriptError: insert into `permissions` (`action_type`, `created_at`, `created_by`, `id`, `name`, `object_type`, `updated_at`, `updated_by`) values ('download', CURRENT_TIMESTAMP, 1, '65147feabf53f60001a38534', 'Upload redirects', 'redirect', CURRENT_TIMESTAMP, 1) - Duplicate entry 'Upload redirects' for key 'permissions.permissions_name_unique'
ghost_1  |     at DatabaseStateManager.makeReady (/var/lib/ghost/versions/4.48.9/core/server/data/db/state-manager.js:95:32)
ghost_1  |     at MigrationScriptError.KnexMigrateError (/var/lib/ghost/versions/4.48.9/node_modules/knex-migrator/lib/errors.js:7:26)
ghost_1  |     at new MigrationScriptError (/var/lib/ghost/versions/4.48.9/node_modules/knex-migrator/lib/errors.js:25:26)
ghost_1  |     at /var/lib/ghost/versions/4.48.9/node_modules/knex-migrator/lib/index.js:1032:19
ghost_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ghost_1  | 
ghost_1  | Error: insert into `permissions` (`action_type`, `created_at`, `created_by`, `id`, `name`, `object_type`, `updated_at`, `updated_by`) values ('download', CURRENT_TIMESTAMP, 1, '65147feabf53f60001a38534', 'Upload redirects', 'redirect', CURRENT_TIMESTAMP, 1) - Duplicate entry 'Upload redirects' for key 'permissions.permissions_name_unique'
ghost_1  |     at Packet.asError (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/packets/packet.js:728:17)
ghost_1  |     at Query.execute (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/commands/command.js:29:26)
ghost_1  |     at Connection.handlePacket (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/connection.js:456:32)
ghost_1  |     at PacketParser.onPacket (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/connection.js:85:12)
ghost_1  |     at PacketParser.executeStart (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/packet_parser.js:75:16)
ghost_1  |     at Socket.<anonymous> (/var/lib/ghost/versions/4.48.9/node_modules/mysql2/lib/connection.js:92:25)
ghost_1  |     at Socket.emit (events.js:400:28)
ghost_1  |     at addChunk (internal/streams/readable.js:293:12)
ghost_1  |     at readableAddChunk (internal/streams/readable.js:267:9)
ghost_1  |     at Socket.Readable.push (internal/streams/readable.js:206:10)
ghost_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
ghost_1  |
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by K1D77A** [comment]
hold up on checking on this

**Comment by K1D77A** [comment]
My fault!!! For some reason the default docker container in the examples is alpine-4...

**Comment by agentzhao** [comment]
@K1D77A hey I'm currently facing the same issue after importing my database from mariadb. May I know how you fixed it?
