### ISSUE TITLE
Upgrade from 5.66.1 to 5.67.0 fails

### ISSUE THREAD

**Issue by ReyKoxha** [TryGhost/Ghost#18490]
### Issue Summary

The update fails with the following error:

```
ERROR alter table `recommendation_click_events` add constraint `recommendation_click_events_recommendation_id_foreign` foreign key (`recommendation_id`) references `recommendations` (`id`) on delete CASCADE - Referencing column 'recommendation_id' and referenced column 'id' in foreign key constraint 'recommendation_click_events_recommendation_id_foreign' are incompatible.

alter table `recommendation_click_events` add constraint `recommendation_click_events_recommendation_id_foreign` foreign key (`recommendation_id`) references `recommendations` (`id`) on delete CASCADE - Referencing column 'recommendation_id' and referenced column 'id' in foreign key constraint 'recommendation_click_events_recommendation_id_foreign' are incompatible.
```

Output of ghost run
```
{"config":{"transaction":false},"name":"2023-09-12-11-22-10-add-recommendation-click-events-table.js"}
"Error occurred while executing the following migration: 2023-09-12-11-22-10-add-recommendation-click-events-table.js"

Error ID:
    300

Error Code:
    ER_FK_INCOMPATIBLE_COLUMNS

----------------------------------------

Error: alter table `recommendation_click_events` add constraint `recommendation_click_events_recommendation_id_foreign` foreign key (`recommendation_id`) references `recommendations` (`id`) on delete CASCADE - Referencing column 'recommendation_id' and referenced column 'id' in foreign key constraint 'recommendation_click_events_recommendation_id_foreign' are incompatible.
    at /home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/knex-migrator/lib/index.js:1032:19
    at Packet.asError (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/gbr/hirschmann-koxha.de/blog/versions/5.67.0/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Steps to Reproduce

ghost update from an older version

### Ghost Version

5.67.0

### Node.js Version

18.7

### How did you install Ghost?

Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This is due to an issue with your MySQL setup - https://ghost.org/docs/faq/troubleshooting-mysql-database/
