### ISSUE TITLE
Mailgun dependency is limitive

### ISSUE THREAD

**Issue by aug2uag** [TryGhost/Ghost#20599]
### Issue Summary

Mailgun puts arbitrary limits on email transactions, I've found them to be unreliable and their service is unreasonable. I think having a hard dependency on Mailgun is hurting the Ghost ecosystem. There should be support for other services including AWS SES.

### Steps to Reproduce

1. In the past year, I've only been able to send 4 emails
2. Ghost logs show the error to be "Mailgun Error 420: Domain m.xxx.com is not allowed to send: recipient limit exceeded, try again after Fri, 12 Jul 2024 06:52:45 UTC" on an attempt to send to 26 recipients

### Ghost Version

5.87.1

### Node.js Version

18.20.4

### How did you install Ghost?

Ubuntu LTS

### Database type

MySQL 5.7

### Relevant log / error output

```shell
EmailError: status code 420: Domain m.xxx.com is not allowed to send: recipient limit exceeded, try again after Fri, 12 Jul 2024 06:52:45 UTC
    at BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:621:32)
    at MailgunEmailProvider.send (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/MailgunEmailProvider.js:148:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendingService.send (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/SendingService.js:117:16)
    at async response.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:434:24)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:600:30)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.sendBatch (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:433:30)
    at async runNext (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:370:21)
    at async Promise.all (index 0)
    at async BatchSendingService.sendBatches (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:378:9)
    at async BatchSendingService.sendEmail (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:213:9)
    at async BatchSendingService.emailJob (/var/www/xxx.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:158:13)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by aug2uag** [comment]
Mailgun is abusive, I've been paying them $35 or so per month, had no issues before changing the Mailgun account for admin reasons, and they are actively/knowingly denying services. After requesting for support the error now is `EmailError: Forbidden: Domain m.xxx.com is not allowed to send large batches yet`

<img width="1115" alt="Screenshot 2024-07-12 at 10 15 02 AM" src="https://github.com/user-attachments/assets/61eb3f89-c26d-42a5-8da5-fe4a2ac74943">

<img width="1056" alt="Screenshot 2024-07-12 at 10 09 14 AM" src="https://github.com/user-attachments/assets/2b288da5-a99c-4c2a-aae4-315e78f18fd7">

<img width="1073" alt="Screenshot 2024-07-12 at 10 09 28 AM" src="https://github.com/user-attachments/assets/ee20a5fc-0c02-4035-91a2-a15aaccc3be9">

<img width="1056" alt="Screenshot 2024-07-12 at 10 09 44 AM" src="https://github.com/user-attachments/assets/81670c43-94e8-4381-831b-705eb0834857">

**Comment by aug2uag** [comment]
Mailgun is truly a nightmare, over the past several months many hours were spent on diagnosing why emails weren't being sent with changes in themes and upgrades and such, only to find out there was a running limit (max 9 addresses in bulk send, while I needed a whopping 26 emails to be dispatched) on the ability to send emails.

Initially, we tried customer support for help, but instead of helping they put another type of restriction on the account:

`EmailError: Forbidden: Domain m.iconic99s.com is not allowed to send large batches yet`

I then contacted Sinch directly and finally got on the phone with a tech support rep named Hector. After describing my situation he said he'd need me to respond to his email and as long as my responses were legit that the limit would be removed. I thought the issue was resolved:

<img width="1174" alt="Screenshot 2024-07-12 at 5 21 46 PM" src="https://github.com/user-attachments/assets/48a3eea0-307b-446c-bbab-5334299f8896">
<img width="1171" alt="Screenshot 2024-07-12 at 5 22 19 PM" src="https://github.com/user-attachments/assets/ca1c08fa-d3f2-4364-ac54-6d2ad967ba89">

I didn't hear back all day, so I figured to try and send an email. On trying to send an email, I got this in the logs:

```
EmailError: Forbidden: Domain m.iconic99s.com is not allowed to send: Account Terminated
    at BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:621:32)
    at MailgunEmailProvider.send (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/MailgunEmailProvider.js:148:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendingService.send (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/SendingService.js:117:16)
    at async response.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:434:24)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:600:30)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.sendBatch (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:433:30)
    at async runNext (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:370:21)
    at async Promise.all (index 0)
    at async BatchSendingService.sendBatches (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:378:9)
    at async BatchSendingService.sendEmail (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:213:9)
    at async BatchSendingService.emailJob (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:158:13)
    at async /var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/job-manager/lib/JobManager.js:244:25
    at async JobManager.worker (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/job-manager/lib/JobManager.js:16:22)
    ```

I paid more than $500 to Mailgun for this, and I'm more upset that my ability to reach and grow an audience is in the hands of such a company. If there's no trivial fix for swapping Mailgun for SES then I'm going to be blocked from using an otherwise very effective tech for my needs.

**Comment by aug2uag** [comment]
Mailgun is truly a nightmare, over the past several months many hours were spent on diagnosing why emails weren't being sent with changes in themes and upgrades and such, only to find out there was a running limit (max 9 addresses in bulk send, while I needed a whopping 26 emails to be dispatched) on the ability to send emails.

Initially, we tried customer support for help, but instead of helping they put another type of restriction on the account:

`EmailError: Forbidden: Domain m.iconic99s.com is not allowed to send large batches yet`

I then contacted Sinch directly and finally got on the phone with a tech support rep named Hector. After describing my situation he said he'd need me to respond to his email and as long as my responses were legit that the limit would be removed. I thought the issue was resolved:

<img width="1173" alt="Screenshot 2024-07-12 at 5 33 58 PM" src="https://github.com/user-attachments/assets/b00e228d-0694-43a4-974c-5a4d16bc7f18">
<img width="1169" alt="Screenshot 2024-07-12 at 5 34 54 PM" src="https://github.com/user-attachments/assets/518d4e01-0007-4c1f-93db-5862ef334001">


I didn't hear back all day, so I figured to try and send an email. On trying to send an email, I got this in the logs:

```
EmailError: Forbidden: Domain m.iconic99s.com is not allowed to send: Account Terminated
    at BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:621:32)
    at MailgunEmailProvider.send (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/MailgunEmailProvider.js:148:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendingService.send (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/SendingService.js:117:16)
    at async response.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:434:24)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:600:30)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.retryDb (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:635:20)
    at async BatchSendingService.sendBatch (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:433:30)
    at async runNext (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:370:21)
    at async Promise.all (index 0)
    at async BatchSendingService.sendBatches (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:378:9)
    at async BatchSendingService.sendEmail (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:213:9)
    at async BatchSendingService.emailJob (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/email-service/lib/BatchSendingService.js:158:13)
    at async /var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/job-manager/lib/JobManager.js:244:25
    at async JobManager.worker (/var/www/iconic99s.com/htdocs/versions/5.87.1/node_modules/@tryghost/job-manager/lib/JobManager.js:16:22)
    ```

I paid more than $500 to Mailgun for this, and I'm more upset that my ability to reach and grow an audience is in the hands of such a company. If there's no trivial fix for swapping Mailgun for SES then I'm going to be blocked from using an otherwise very effective tech for my needs.

**Comment by sam-lord** [comment]
The issue you're having has been covered in the forum before, you'll need to contact Mailgun if you're experiencing throttling on your account: https://forum.ghost.org/t/problem-with-mailgun-newsletter/23942.

**Comment by sam-lord** [comment]
I've marked this as a feature request so you get the link to the forum if you want to leave a feature request to be able to use alternative bulk email providers.
