### ISSUE TITLE
Ghost Doctor should check for 'vips' on Freebsd

### ISSUE THREAD

**Issue by philmb3487** [TryGhost/Ghost#21275]
### Issue Summary

I installed ghost on my freebsd VPS (because why not? freebsd is one of the most common OS in the server space), and it mostly works, but there are issues.

Image upload in particular fails. Reading the error log, I see this uses 'sharp', which does not ship a binary for freebsd. Per documentation,

https://sharp.pixelplumbing.com/install

Means Ghost depends on 'vips' on Freebsd, and therefore it would be very helpful to check for it as a dependency in either 'doctor' or even before 'ghost start'.

### Steps to Reproduce

1. install ghost on freebsd
2. observe your image upload does not work

### Ghost Version

5.96.0

### Node.js Version

v20.15.1

### How did you install Ghost?

'ghost install' on freebsd 14.1

### Database type

MySQL 8

### Relevant log / error output

```shell
{"name":"Log","hostname":"vultr.guest","pid":16882,"level":50,"version":"5.96.0","req":{"meta":{"requestId":"eb9dace4-363c-4787-97f7-5021ed0d8c4e","userId":"1"},"url":"/images/upload/","method":"POST","originalUrl":"/ghost/api/admin/images/upload/","params":{},"headers":{"host":"philmb.com","x-forwarded-proto":"https","x-real-ip":"96.9.79.116","x-forwarded-for":"96.9.79.116","connection":"close","content-length":"695767","x-ghost-version":"5.96","sec-ch-ua-platform":"\"Linux\"","sec-ch-ua":"\"Chromium\";v=\"129\", \"Not=A?Brand\";v=\"8\"","app-pragma":"no-cache","sec-ch-ua-mobile":"?0","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","accept":"text/plain, */*; q=0.01","content-type":"multipart/form-data; boundary=----WebKitFormBoundaryNARduyS2YvAHBH7E","origin":"https://philmb.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://philmb.com/ghost/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","cookie":"**REDACTED**"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","content-version":"v5.96","vary":"Accept-Version, Origin, Accept-Encoding","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"https://philmb.com","content-type":"application/json; charset=utf-8","content-length":"317","etag":"W/\"13d-gYNDPJC/bNoZl09YGrIoedvhxik\""},"statusCode":400,"responseTime":"35ms"},"err":{"id":"50710510-86ed-11ef-ab6f-ad02a6cbff45","domain":"https://philmb.com","code":null,"name":"BadRequestError","statusCode":400,"level":"normal","message":"Image processing failed","context":"\"Sharp wasn't installed\"","help":"\"Please verify that the image is valid\"","stack":"BadRequestError: Image processing failed\n    at Object.query (/usr/local/www/philmb.com/versions/5.96.0/core/server/api/endpoints/images.js:43:27)\n    at async getResponse (/usr/local/www/philmb.com/versions/5.96.0/node_modules/@tryghost/api-framework/lib/pipeline.js:259:34)\n    at async ImplWrapper (/usr/local/www/philmb.com/versions/5.96.0/node_modules/@tryghost/api-framework/lib/pipeline.js:264:30)\n    at async Http (/usr/local/www/philmb.com/versions/5.96.0/node_modules/@tryghost/api-framework/lib/http.js:70:28)","hideStack":false},"msg":"Image processing failed","time":"2024-10-10T09:52:08.676Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by philmb3487** [comment]
So this will be ignored? Sad to see this is how the Ghost team operates.
