### ISSUE TITLE
Dynamic routing accepts only YAML, but not YML

### ISSUE THREAD

**Issue by sm-samax** [TryGhost/Ghost#21560]
### Issue Summary

I tried to upload my routes.yml to a production configured ghost instance and I got `Please select a valid YAML file to import.`.
After some research I figured out that the problem was the file extension, so after I renamed it from `routes.yml` to `routes.yaml` it worked. 

Why I'm writing this then?

Because the default routes in Ghost is in `yml` format and the common sense dictates to follow this example. It's just a small thing, but one can lose time with it.

### Steps to Reproduce

1. On a production ghost instance
2. Go to  hostname/ghost/#/settings/labs
3. Beta features > Routes > Upload routes file
4. Select a file with `.yml` ending

### Ghost Version

5.96.1 (ghost:5.96.1-alpine image)

### Node.js Version

It's included with the docker image

### How did you install Ghost?

On Debian 12 via Docker

### Database type

MySQL 5.7

### Browser & OS version

Firefox

### Relevant log / error output

```shell
[2024-11-07 08:39:32] INFO Updating incoming recommendations on boot

[2024-11-07 08:40:11] INFO [Recommendations] Updating recommendations metadata

[2024-11-07 08:40:19] ERROR "POST /ghost/api/admin/settings/routes/yaml/" 415 22ms

Please select a valid YAML file to import.

Error ID:

    eb8c1470-9ce3-11ef-89d3-2d4682878da5

----------------------------------------

UnsupportedMediaTypeError: Please select a valid YAML file to import.

    at uploadValidation (/var/lib/ghost/versions/5.96.1/core/server/web/api/middleware/upload.js:212:25)

    at Layer.handle [as handle_request] (/var/lib/ghost/versions/5.96.1/node_modules/express/lib/router/layer.js:95:5)

    at next (/var/lib/ghost/versions/5.96.1/node_modules/express/lib/router/route.js:149:13)

    at /var/lib/ghost/versions/5.96.1/core/server/web/api/middleware/upload.js:94:9

    at Immediate._onImmediate (/var/lib/ghost/versions/5.96.1/node_modules/multer/lib/make-middleware.js:53:37)

    at process.processImmediate (node:internal/timers:478:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
From your title, this is by design, but from your description, there might be a bug/docs issue 😁 

> Because the default routes in Ghost is in yml format and the common sense dictates to follow this example. It's just a small thing, but one can lose time with it.

Which default routes are you referring to?

**Comment by sm-samax** [comment]
I see now that in the docker image it's indeed `yaml`. I copied the `routes.yml` from `/content/settings/` of a localy installed ghost instance and it caused the confusion.

Thank you for the feedback. :)
