### ISSUE TITLE
NPM Module is not working when using a custom config file

### ISSUE THREAD

**Issue by rchrd2** [TryGhost/Ghost#4757]
Works:
```
var path = require('path');
var ghost = require('ghost');
ghost().then(function (ghostServer) {
  ghostServer.start();
});
```
Does not work:
```
ghost({
    config: path.join(__dirname, 'config.js')
}).then(function (ghostServer) {
    ghostServer.start();
});
```
config.js is exactly the same as the config sample.
The error is:
```
Possibly unhandled Error
    at Error.ValidationError (/src/blog/node_modules/ghost/core/server/errors/validation-error.js:6:18)
    at /src/blog/node_modules/ghost/core/server/data/validation/index.js:117:35
    at process._tickDomainCallback (node.js:463:13)
From previous event:
    at Function.Promise$All [as all] (/src/blog/node_modules/ghost/node_modules/bluebird/js/main/promise.js:202:12)
    at Events.triggerThen (/src/blog/node_modules/ghost/node_modules/bookshelf/node_modules/trigger-then/trigger-then.js:66:23)
    at Events.triggerThen (/src/blog/node_modules/ghost/node_modules/bookshelf/node_modules/trigger-then/trigger-then.js:51:37)
    at null.<anonymous> (/src/blog/node_modules/ghost/node_modules/bookshelf/lib/model.js:212:19)
From previous event:
    at Function.Promise$Bind [as bind] (/src/blog/node_modules/ghost/node_modules/bluebird/js/main/promise.js:274:9)
    at _.extend.save (/src/blog/node_modules/ghost/node_modules/bookshelf/lib/model.js:176:20)
    at /src/blog/node_modules/ghost/core/server/models/settings.js:145:74
    at forOwn (/src/blog/node_modules/ghost/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/src/blog/node_modules/ghost/node_modules/lodash/dist/lodash.js:3302:9)
    at /src/blog/node_modules/ghost/core/server/models/settings.js:137:15
From previous event:
    at Function.ghostBookshelf.Model.ghostBookshelf.Model.extend.findAll (/src/blog/node_modules/ghost/core/server/models/base.js:225:67)
    at Function.ghostBookshelf.Model.extend.populateDefaults (/src/blog/node_modules/ghost/core/server/models/settings.js:133:21)
    at config.load.then.then.then.then.then.then.then.then.then.express.static.mime.define.application/font-woff (/src/blog/node_modules/ghost/core/server/index.js:155:32)
From previous event:
    at Function.Promise$All [as all] (/src/blog/node_modules/ghost/node_modules/bluebird/js/main/promise.js:202:12)
```
package.json
```
{
  "name": "blog",
  "version": "0.0.0",
  "description": "blog.rchrd.net",
  "main": "index.js",
  "dependencies": {
    "ghost": "0.5.7"
  },
  "devDependencies": {},
  "scripts": {
    "start": "node index",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Richard Caceres",
  "license": "ISC"
}
```

Am I missing something? I followed the instructions on in the wiki (https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-npm-module).

**Comment by rchrd2** [comment]
Sorry to bother, because I found the solution. It was noted at the bottom of the wiki page.
>>> NOTE: If you change the location of the content/ directory Ghost expects to find the same directory structure that exists in the module. To get started copy the default content directory structure as the basis for your custom content/ location.
