### ISSUE TITLE
Problem with non-latin domains

### ISSUE THREAD

**Issue by garbageek** [TryGhost/Ghost#4838]
I am trying to start blog on ccTLD non-latin domain "кулік.укр".  But when I add domain name to config.js it causes an issue:

ERROR: Your site url in config.js is invalid. 
 http://кулік.укр 
 Please make sure this is a valid url before restarting 
 Error: Your site url in config.js is invalid.
    at ConfigManager.validate (/var/www/kulik/core/server/config/index.js:320:25)
    at /var/www/kulik/core/server/config/index.js:233:29
    at tryCatch1 (/var/www/kulik/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/var/www/kulik/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/var/www/kulik/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/var/www/kulik/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAtPostResolution (/var/www/kulik/node_modules/bluebird/js/main/promise.js:335:10)
    at Async._consumeFunctionBuffer (/var/www/kulik/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/var/www/kulik/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickDomainCallback (node.js:463:13) 

When I change url to converted analog it causes issue again:

ERROR: Your site url in config.js is invalid. 
 http://xn--j1aac5a4g.xn--j1amh 
 Please make sure this is a valid url before restarting 
 Error: Your site url in config.js is invalid.
    at ConfigManager.validate (/var/www/kulik/core/server/config/index.js:320:25)
    at /var/www/kulik/core/server/config/index.js:233:29
    at tryCatch1 (/var/www/kulik/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/var/www/kulik/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/var/www/kulik/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/var/www/kulik/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAtPostResolution (/var/www/kulik/node_modules/bluebird/js/main/promise.js:335:10)
    at Async._consumeFunctionBuffer (/var/www/kulik/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/var/www/kulik/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickDomainCallback (node.js:463:13) 

Is it possible to fix this issue. Thanks

**Comment by halfdan** [comment]
Hi there,
that seems to be an issue with the validator module we are using. I opened an issue there and provided [a fix](https://github.com/chriso/validator.js/pull/352). Hopefully this can make it into the next release of Ghost.

**Comment by garbageek** [comment]
Thanks
