### ISSUE TITLE
Bug: no root key ('setup') provided

### ISSUE THREAD

**Issue by panchr** [TryGhost/Ghost#5037]
I am trying to use Ghost as an `npm` module alongside an existing expressjs app.

I have all of the configuration working correctly and everything loads fine, but I run into an issue when trying to setup the blog. On `domain.com/blog/ghost/setup`, once I submit, I get the following error:

`No root key ('setup') provided.`

This is the output of the process:

```
ERROR: No root key ('setup') provided.
 
 Error
    at Error.BadRequestError (/var/www/domain.com/web/node_modules/ghost/core/server/errors/bad-request-error.js:6:18)
    at Object.utils.checkObject (/var/www/domain.com/web/node_modules/ghost/core/server/api/utils.js:20:45)
    at authentication.isSetup.then.then.setupUser.name (/var/www/domain.com/web/node_modules/ghost/core/server/api/authentication.js:201:26)
    at tryCatch1 (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromises (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/async.js:40:14) 

ERROR: No root key ('setup') provided.
 
 Error
    at Error.BadRequestError (/var/www/domain.com/web/node_modules/ghost/core/server/errors/bad-request-error.js:6:18)
    at Object.utils.checkObject (/var/www/domain.com/web/node_modules/ghost/core/server/api/utils.js:20:45)
    at authentication.isSetup.then.then.setupUser.name (/var/www/domain.com/web/node_modules/ghost/core/server/api/authentication.js:201:26)
    at tryCatch1 (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromises (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/var/www/domain.com/web/node_modules/ghost/node_modules/bluebird/js/main/async.js:40:14)
```

**Comment by ErisDS** [comment]
Hi @panchr, sorry that this isn't working too well for you.

I think this sounds like a configuration or setup issue, rather than a bug. There are quite a lot of people using the npm module, and if it just plain wasn't working I think we'd have more reports. I recommend using the [forum](https://ghost.org/forum) or perhaps dropping by IRC and chatting someone through your setup so they can help you debug it?

If it does turn out I'm wrong and there's a bug to fix, we can reopen this.

**Comment by tylerlindell** [comment]
@panchr did you find a solution? I am having the same.

changing app.use(bodyParser.urlencoded({ extended: false })); to true fixed it for me.


Thanks to the post here: https://ghost.org/forum/bugs-suggestions/18275-hitting-error-no-root-key-setup-provided-when-trying-to-set-up-blog/

**Comment by maddenf** [comment]
I am having the same issue and the solution by tylerlindell didn't work.  Ghost version is 0.11.3.

I'm running Ghost on top of an existing Express app on /blog.  It works great for the most part.  However, trying to run the initial user setup and after entering everything in step two, I get this same error message:  no root key ('setup') provided
