### ISSUE TITLE
'Incorrect datetime value' error when using MySQL

### ISSUE THREAD

**Issue by keesun** [TryGhost/Ghost#5050]
my environment: `Ghost v0.5.10`, `MySQL v5.6.16`, `Node.js v0.10.34`

When I tried to update user information like changing name or sometime, then I got the error:

```
ERROR: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2015-03-18T02:14:41.000Z' for column 'created_at' at row 1

 Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2015-03-18T02:14:41.000Z' for column 'created_at' at row 1
    at Query.Sequence._packetToError (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
    at Query.ErrorPacket (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/Protocol.js:202:24)
    at Parser.write (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/Connection.js:72:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    --------------------
    at Protocol._enqueue (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/protocol/Protocol.js:110:48)
    at Connection.query (/Users/naver/apps/ghost-0.5.10/node_modules/mysql/lib/Connection.js:165:25)
    at /Users/naver/apps/ghost-0.5.10/node_modules/knex/lib/dialects/mysql/runner.js:42:16
    at tryCatch2 (/Users/naver/apps/ghost-0.5.10/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Users/naver/apps/ghost-0.5.10/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Users/naver/apps/ghost-0.5.10/node_modules/bluebird/js/main/promise.js:84:37)
    at Runner_MySQL.<anonymous> (/Users/naver/apps/ghost-0.5.10/node_modules/knex/lib/dialects/mysql/runner.js:41:10)
    at tryCatch1 (/Users/naver/apps/ghost-0.5.10/node_modules/bluebird/js/main/util.js:45:21)
    at Runner_MySQL._query (/Users/naver/apps/ghost-0.5.10/node_modules/bluebird/js/main/promise.js:201:25)
    at Runner_MySQL.<anonymous> (/Users/naver/apps/ghost-0.5.10/node_modules/knex/lib/runner.js:125:15)
```

Please help me out. Except this error, creating and updating posts work well.

**Comment by ErisDS** [comment]
Hi @keesun, sorry to hear you're having trouble.

Although I've seen this problem before with other software, I've never seen it reported with Ghost before, and I can't find anyone reporting it to [bookshelf](https://github.com/tgriesser/bookshelf/search?utf8=%E2%9C%93&q=ER_TRUNCATED_WRONG_VALUE) or [knex](https://github.com/tgriesser/knex/search?q=ER_TRUNCATED_WRONG_VALUE&type=Issues&utf8=%E2%9C%93) either. 

Not sure specifically why this is happening to you, but it may be to do with your specific version of MySQL. 

The fix is to first locate your `my.cnf` file (often somewhere like `/usr/local/my.cnf /etc/my.cnf /etc/mysql/my.cnf /usr/local/etc/my.cnf ~/.my.cnf`).

Then, inside of that file remove `STRICT_TRANS_TABLES` from the sql-mode line, and restart MySQL. All should then be fine.

I don't think there's an issue here for us to fix. Perhaps we [ought to be using timestamp](https://github.com/mozilla/chronicle/issues/100) rather than datetime fields, however as it should be easily fixable with a config change, unless we get lots of people running into this I don't think it needs looking into at this stage. Therefore, I'm going to close this for now - and if we get more reports we can reopen.

**Comment by keesun** [comment]
@ErisDS Thanks for your comment. I can fix the problem as you said.

**Comment by chengcheng222e** [comment]
@ErisDS  Thanks for your. I've fixed the problem too.
