### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by Julyyq** [TryGhost/Ghost#5112]
I follow the instructions but get the following error, and can't get any useful information through Google.

        $ grunt init
        Loading "Gruntfile.js" tasks...ERROR
        >> Error: ENOENT, no such file or directory '.npmignore'
        Warning: Task "init" not found. Use --force to continue.
        Error: Task "init" not found.
            at Task.run (/Users/Allen/swift-tricks.cn/node_modules/grunt/lib/util/task.js:179:28)
            at /Users/Allen/swift-tricks.cn/node_modules/grunt/lib/grunt.js:161:39
            at Array.forEach (native)
            at Object.grunt.tasks (/Users/Allen/swift-tricks.cn/node_modules/grunt/lib/grunt.js:161:9)
            at Object.module.exports [as cli] (/Users/Allen/swift-tricks.cn/node_modules/grunt/lib/grunt/cli.js:38:9)
            at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
            at Module._compile (module.js:460:26)
            at Object.Module._extensions..js (module.js:478:10)
            at Module.load (module.js:355:32)
            at Function.Module._load (module.js:310:12)

        Aborted due to warnings.

My ghost version is v0.5.10. Does anyone have the same problem?

**Comment by ErisDS** [comment]
Hi @Julyyq This happens if you try to run the grunt tasks on a pre-built version of Ghost. The zip files do not contain the source files, only the built files, so there is no need for grunt tasks.

**Comment by rickarubio** [comment]
:+1: thanks @ErisDS this helped me out tonight as well.

**Comment by Cahl-Dee** [comment]
Hey Guys. I installed from the pre-built version of Ghost. When I try to run `npm start --production` I get the "ERROR: Javascript files have not been built." error message. Documentation indicates this means I need to run grunt.... circular logic here. 

Any ideas?
