### ISSUE TITLE
{{ghost_head}} not working on error page in Ghost 0.6.0

### ISSUE THREAD

**Issue by franklouwers** [TryGhost/Ghost#5146]
The theme I currently use, has a custom 404 error template in error.hbs. It uses the {{ghost_head}} helper in the template. This worked fine in all 0.5.x versions

After upgrading to 0.6.0 however, I get the following error when browsing to a non-existing page:

    ERROR: [error.hbs] Cannot read property '0' of undefined
     Error whilst rendering error page
     Error template has an error
     TypeError: [error.hbs] Cannot read property '0' of undefined
        at Object.ghost_head (/Users/frank/src/openminds/frank/ghostblog/core/server/helpers/ghost_head.js:269:31)
        at Object.<anonymous> (/Users/frank/src/openminds/frank/ghostblog/core/server/helpers/index.js:60:28)
        at Function.Waiter.resolve (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/async.js:83:3)
        at Object.<anonymous> (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:394:18)
        at Object.eval (eval at <anonymous> (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:11:166)
        at ret (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
        at ret (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)
        at renderTemplate (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:481:13)
        at render (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:529:5)
        at renderIt (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:591:18)

(Forum thread: https://ghost.org/forum/installation/18712-ghost_head-not-allowed-in-error-hbs-after-upgrading-to-0-6-0/)

**Comment by ErisDS** [comment]
@franklouwers thanks for the bug report, we'll get it fixed up :)

**Comment by cobbspur** [comment]
PR inbound https://github.com/TryGhost/Ghost/pull/5149

**Comment by jgentes** [comment]
So others can google this issue based on the text on the error page:
```
Oops, seems there is an error in the error template.

Encountered the error:

[default.hbs] Cannot read property '0' of undefined

whilst trying to render an error page for the error:

404
Page Not Found
```
