### ISSUE TITLE
ERROR: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by frdmn** [TryGhost/Ghost#5187]
I'm using https://github.com/dockerfile/ghost and since a couple of days I can't run the container anymore.

It crashes because of the error stated in the title:

```bash
$ docker run --name="docker-ghost" -p 8091:2368 -v /tmp/docker-ghost:/ghost-override dockerfile/ghost
> ghost@0.6.2 start /ghost
> node index


ERROR: Arguments to path.join must be strings

 TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at Object.<anonymous> (/ghost-override/config.js:18:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at ConfigManager.readFile (/ghost/core/server/config/index.js:321:12)
    at ConfigManager.validate (/ghost/core/server/config/index.js:336:23)
```

Any ideas?

**Comment by halfdan** [comment]
Ghost is having trouble reading your config. Make sure that it doesn't have any syntax errors.

**Comment by frdmn** [comment]
@halfdan it's the default configuration :/

**Comment by jaswilli** [comment]
As mentioned above, this is a problem with `config.js` (it appears as though it's the `path.join` in the `database` block).  Something you've got going on in your environment or in `config.js` is causing node's `path.join` to blow up.

There's not really much we can do about that so I'm going to close this for now.  If you find out more information that points to it being an issue with Ghost please let us know.

**Comment by frdmn** [comment]
Thanks @jaswilli, will do!
