### ISSUE TITLE
Event related potential leak in tests

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5373]
There is a warning output by some of our tests, mostly functional/route tests I think, about a possible EventEmitter memory leak. 

This only happens on the node 0.12 and io.js tests, not node 0.10.

Not sure if it's really something to worry about. I guess it's because event listeners are never removed, but I had a quick go at trying to automatically remove them and that didn't seem to help.

```
 Frontend Routing
(node) warning: possible EventEmitter memory leak detected. 11 tag.added listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at TagsMapGenerator._.extend.bindEvents (/home/travis/build/TryGhost/Ghost/core/server/data/xml/sitemap/tag-generator.js:23:25)
    at /home/travis/build/TryGhost/Ghost/core/server/data/xml/sitemap/base-generator.js:32:25
    at tryCatcher (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/TryGhost/Ghost/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 tag.edited listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by acburdine** [comment]
of note: https://github.com/nodejs/node-v0.x-archive/issues/5108
