### ISSUE TITLE
Cannot find module '../../../package.json'

### ISSUE THREAD

**Issue by axsuul** [TryGhost/Ghost#5394]
```
% npm start                                                                                                                                                           

> ghost@0.6.4 start /srv/ghost
> node index


module.js:340
    throw err;
          ^
Error: Cannot find module '../../../package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/ghost/server/config/index.js:18:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/ghost/server/api/index.js:8:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.6.4 start: `node index`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ghost@0.6.4 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/ghost/npm-debug.log
```

Any ideas?

**Comment by ErisDS** [comment]
Hi @axsuul, sorry to hear you're having trouble. GitHub is where we track issues with the software, it isn't the right place for support. We have a [slack](https://ghost.org/slack) community, or alternatively you could use [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog) if you prefer.
