### ISSUE TITLE
ERROR: Object function (){ parent.apply(this, arguments); } has no method 'findPage'

### ISSUE THREAD

**Issue by balintant** [TryGhost/Ghost#5803]
I've just updated Ghost on my blog to 0.7 and it throws the following stack instead of starting up.

```
ERROR: Object function (){ parent.apply(this, arguments); } has no method 'findPage'

 TypeError: Object function (){ parent.apply(this, arguments); } has no method 'findPage'
    at modelQuery (/var/webhosts/balintant/blog/core/server/api/posts.js:50:38)
    at runTask (/var/webhosts/balintant/blog/core/server/utils/pipeline.js:8:24)
    at /var/webhosts/balintant/blog/core/server/utils/pipeline.js:15:32
    at tryCatcher (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/util.js:24:31)
    at ReductionPromiseArray._promiseFulfilled (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/reduce.js:107:18)
    at Promise._settlePromiseAt (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/promise.js:535:26)
    at Promise._settlePromises (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/var/webhosts/balintant/blog/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by ErisDS** [comment]
Hi @balintant, sorry to hear you're having trouble. If you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!

**Comment by jakedahn** [comment]
@balintant did you ever fix your issue?

I ran into this same thing, and it was because I unarchived the new version over the old one and some old crufty files were left over. To fix it I deleted the core directory and re-unarchived.

**Comment by ErisDS** [comment]
@jakedahn deleting the `core` folder is a key step in the upgrade process: http://support.ghost.org/how-to-upgrade/. I've updated the troubleshooting guide on that page to cover this error as it seems to be common.

**Comment by balintant** [comment]
@jakedahn, I simply exported the data, replaced with a fresh Ghost instance and restored the data. Or I think I did something like that. (Who remembers that far?)
