### ISSUE TITLE
meta_description fails inside next_post block helper (async helpers cannot be nested)

### ISSUE THREAD

**Issue by ArekSredzki** [TryGhost/Ghost#5850]
The meta_description helper will fail in an ugly manner if used in the nextPrev block helper.
Being able to use it here is very useful, as one can then select what text is used to promote other articles.
However, if one tries to use it here then an async error occurs which creates multiple ugly problems on the page.

Here's the error:

```
ERROR: Can't set headers after they are sent. 
 registerAsyncThemeHelper: ghost_head 
 
 Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:154:12)
    at fn (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:934:10)
    at _stackRenderer (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/hbs.js:524:9)
    at Waiter.callback (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/hbs.js:501:7)
    at Waiter.resolve (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/async.js:43:12)
    at /Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/async.js:84:15
    at /Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/core/server/helpers/index.js:64:13
    at tryCatcher (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17) 

Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:154:12)
    at fn (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express/lib/response.js:934:10)
    at _stackRenderer (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/hbs.js:524:9)
    at Waiter.callback (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/hbs.js:501:7)
    at Waiter.resolve (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/async.js:43:12)
    at /Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/express-hbs/lib/async.js:84:15
    at /Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/core/server/helpers/index.js:64:13
    at tryCatcher (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/areksredzki/Dropbox/dev/env/current/web/envoy/ghost/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by ErisDS** [comment]
This is, at the moment, an expected behaviour of the way the various helpers in Ghost work. The next and previous helpers are asynchronous and so are the meta_title and meta_description helpers.

Asynchronous helpers cannot be nested inside each other. 

I realise this provides a real limitation, but it is non-trivial to fix. There are ongoing attempts to look at this inside of express-hbs where the limitation lives: https://github.com/barc/express-hbs/issues/56.

In the meantime, the main thing we can do here is provide a better error message.

**Comment by mcsekar** [comment]
I am facing the same issue mentioned above.
    ERROR: Can't set headers after they are sent.
 registerAsyncThemeHelper: ghost_head

 Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:700:10)
    at ServerResponse.send (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:154:12)
    at fn (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:934:10)
    at _stackRenderer (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\hbs.js:524:9)
    at Waiter.callback (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\hbs.js:501:7)
    at Waiter.resolve (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\async.js:43:12)
    at C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\async.js:84:15
    at C:\Ghost\ghost-0.7.1\core\server\helpers\index.js:64:13
    at tryCatcher (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:177:16)
    at Async._drainQueues (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:700:10)
    at ServerResponse.send (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:154:12)
    at fn (C:\Ghost\ghost-0.7.1\node_modules\express\lib\response.js:934:10)
    at _stackRenderer (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\hbs.js:524:9)
    at Waiter.callback (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\hbs.js:501:7)
    at Waiter.resolve (C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\async.js:43:12)
    at C:\Ghost\ghost-0.7.1\node_modules\express-hbs\lib\async.js:84:15
    at C:\Ghost\ghost-0.7.1\core\server\helpers\index.js:64:13
    at tryCatcher (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:177:16)
    at Async._drainQueues (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Ghost\ghost-0.7.1\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

And string  __aSyNcId_<_fbaEDzWj__ is displayed in the page.



Please Help.
