### ISSUE TITLE
Unable to upgrade ghost with postgresql

### ISSUE THREAD

**Issue by yanntech** [TryGhost/Ghost#5891]
Hi,

I'm unable to upgrade ghost from 0.6.4 to 0.7.
My ghost config: ghost 0.6.4 with official docker image and PostgreSQL.

My error message in debug mode (debug: true in databases):

```
Migrations: Database upgrade required from version 003 to 004
Migrations: Creating database backup
{ __cid: '__cid1',
  sql: 'select * from information_schema.tables where table_name = $1',
  bindings: [ 'settings' ],
  output: [Function] }
{ __cid: '__cid2',


var _       = require('lodash'),
  sql: 'SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' and table_name not like \'pg_%\'',


var _       = require('lodash'),
  method: 'raw',
  bindings: [] }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [ 'databaseVersion', 'currentVersion' ],
  sql: 'select "value" from "settings" where "key" = $1 or "key" = $2' }
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'title', 1 ],
  sql: 'select "settings".* from "settings" where "settings"."key" = $1 limit $2' }
Migrations: Database backup written to: /var/lib/ghost/content/data/snip.ghost.2015-09-28.json
{ __cid: '__cid2',
  sql: 'SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' and table_name not like \'pg_%\'',
  method: 'raw',
  bindings: [] }
Migrations: Running migrations
Migrations: Creating table: posts
{ __cid: '__cid1',
  sql: 'create table "posts" ("id" serial primary key, "uuid" varchar(36) not null, "title" varchar(150) not null, "slug" varchar(150) not null, "markdown" text null, "html" text null, "image" text null, "featured" boolean not null default \'0\', "page" boolean not null default \'0\', "status" varchar(150) not null default \'draft\', "language" varchar(6) not null default \'en_US\', "meta_title" varchar(150) null, "meta_description" varchar(200) null, "author_id" integer not null, "created_at" timestamptz not null, "created_by" integer not null, "updated_at" timestamptz null, "updated_by" integer null, "published_at" timestamptz null, "published_by" integer null)',
  bindings: [] }

ERROR: relation "posts" already exists

 error: relation "posts" already exists
    at Connection.parseE (/usr/src/ghost/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/usr/src/ghost/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/usr/src/ghost/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

Regards

**Comment by jberkus** [comment]
See dicussion on related PR.  There's an easy fix for this, but we need to figure out if we want the easy fix.
