### ISSUE TITLE
grunt init in stable branch from git fails on module 'lodash-node/modern/objects/assign'

### ISSUE THREAD

**Issue by lazzarello** [TryGhost/Ghost#5977]
The following is the output after running `grunt init`. I don't know much about this project's workflow. I'm going to try the archived release but I thought this would be a decent report since searching for keyword "lodash" gives zero results for open bugs.

```
$ node --version
v0.10.13
```

```
Running "shell:ember:dev" (shell) task

module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash-node/modern/objects/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lazzarello/src/series-digital/ghost/core/client/node_modules/ember-cli/node_modules/core-object/core-object.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Warning: Command failed: 
module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash-node/modern/objects/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lazzarello/src/series-digital/ghost/core/client/node_modules/ember-cli/node_modules/core-object/core-object.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
 Use --force to continue.

Aborted due to warnings.
```

Last three commits from my repo

```
commit f91f3edaf2a8bb7becdf74258d71e2bce4d2226e
Author: Hannah Wolfe <erisds@gmail.com>
Date:   Mon Sep 28 08:11:36 2015 +0100

    Adding shrinkwrap file for stable

commit fe9c10a67c5e79dbd2fcd7ccb350c0ef653e02c4
Merge: 9f605e3 f8caa1f
Author: Hannah Wolfe <erisds@gmail.com>
Date:   Mon Sep 28 08:10:58 2015 +0100

    Merge branch 'master' @ 0.7.1 into stable

commit f8caa1f09142af3076758df192a62fb349c2f804
Author: Hannah Wolfe <erisds@gmail.com>
Date:   Sun Sep 27 14:36:14 2015 +0100

    Version bump to 0.7.1
```

**Comment by ErisDS** [comment]
Hi @lazzarello, sorry to hear you're having trouble. 

This sounds very much like `npm install` didn't complete successfully for you - note that in Ghost, `npm install` runs twice - once when you run it in the root dir, and once as part of `grunt init`. Looks like at least one of these didn't work (very common esp on older versions of npm) and you're missing a dependency as a result. It's not a bug or issue with the stable branch itself.

If you pop by our [slack](https://ghost.org/slack) team you can get help debugging what's going wrong for you in your environment.

**Comment by saurabhvalsangkar** [comment]
I am using docker set up and facing exact same issue. Tried re-installing npm multiple times but no help...

Can you provide any pointers?

Cannot find module 'lodash-node/modern/objects/assign'
