### ISSUE TITLE
after setup can not login

### ISSUE THREAD

**Issue by bangbang93** [TryGhost/Ghost#6043]
in page "/ghost/setup/two/"
I setup with email&password&etc
after that I got a 401 error

here is log
```
125.121.71.226 - - [04/Nov/2015:10:17:11 +0000] "GET /ghost/signin/ HTTP/1.0" 302 70 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:22 +0000] "GET /ghost/setup/ HTTP/1.0" 200 4098 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:22 +0000] "GET /ghost/vendor.min.css?v=cd7ff6a24c HTTP/1.0" 200 5985 "http://ww.cofactories.com/ghost/setup/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:22 +0000] "GET /ghost/ghost.min.css?v=cd7ff6a24c HTTP/1.0" 200 90259 "http://ww.cofactories.com/ghost/setup/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:22 +0000] "GET /ghost/ghost.min.js?v=cd7ff6a24c HTTP/1.0" 200 584228 "http://ww.cofactories.com/ghost/setup/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:22 +0000] "GET /ghost/vendor.min.js?v=cd7ff6a24c HTTP/1.0" 200 1484643 "http://ww.cofactories.com/ghost/setup/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:17:26 +0000] "GET /ghost/api/v0.1/authentication/setup/ HTTP/1.0" 200 28 "http://ww.cofactories.com/ghost/setup/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:18:02 +0000] "POST /ghost/api/v0.1/authentication/setup/ HTTP/1.0" 201 448 "http://ww.cofactories.com/ghost/setup/two/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
125.121.71.226 - - [04/Nov/2015:10:18:02 +0000] "POST /ghost/api/v0.1/authentication/token HTTP/1.0" 401 73 "http://ww.cofactories.com/ghost/setup/two/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36"
```
and  error
```
ERROR: Access denied. 
 
 Error
    at Error.UnauthorizedError (/home/nodejs/www/core/server/errors/unauthorized-error.js:6:18)
    at authenticate (/home/nodejs/www/core/server/middleware/auth.js:95:50)
    at Strategy.strategy.success (/home/nodejs/www/node_modules/passport/lib/middleware/authenticate.js:194:18)
    at verified (/home/nodejs/www/node_modules/passport-oauth2-client-password/lib/strategy.js:50:10)
    at then (/home/nodejs/www/core/server/middleware/auth-strategies.js:21:32)
    at tryCatcher (/home/nodejs/www/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/nodejs/www/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/nodejs/www/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/nodejs/www/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/nodejs/www/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/nodejs/www/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17) 
```

I used clipboard ,so I can't input wrong password.And I had use email to reset password.According to log ,the reset was successfully but I still can't login .

I'm using MySQL for database

**Comment by kevinansfield** [comment]
Hi @bangbang93, which version of Ghost are you using?

**Comment by bangbang93** [comment]
0.7.1
latest master branch ,I cloned seval hours ago

**Comment by kevinansfield** [comment]
Ok, this issue may be related to #6034 which I'll be looking into today.

Do you have anything in local storage? It's accessible under the Resources tab in Web Inspector.

**Comment by bangbang93** [comment]
{ghost:session: "{"authenticated":{}}"}

only this 
no cookies or session storage

**Comment by ErisDS** [comment]
@kevinansfield should this be resolved now?

**Comment by kevinansfield** [comment]
@ErisDS I believe so, I'm not aware of any other issues in this area. Maybe worth closing unless we get any further reports?

**Comment by ErisDS** [comment]
Cool, closing as fixed. Will reopen if there's evidence to the contrary :wink:

**Comment by chinakids** [comment]
me too,version is 0.11
