### ISSUE TITLE
Error: terminating connection due to administrator command

### ISSUE THREAD

**Issue by Fredric** [TryGhost/Ghost#6081]
Hi. I recently added a ghost CMS installation to heroku and my server crashes several times a day with this error. Its the postgres module and it seems to drop connection initiated from the database side. 

Could these kind of errors be catched and not throw an exception?. (Try catch) ?

    2015-11-16T13:31:39.528996+00:00 app[web.1]: events.js:72
    2015-11-16T13:31:39.529393+00:00 app[web.1]:         throw er; // Unhandled 'error' event
    2015-11-16T13:31:39.529398+00:00 app[web.1]:               ^
    2015-11-16T13:31:39.529430+00:00 app[web.1]: error: terminating connection due to administrator command
    2015-11-16T13:31:39.529432+00:00 app[web.1]:     at Connection.parseE (/app/node_modules/ghost/node_modules/pg/lib/connection.js:534:11)
    2015-11-16T13:31:39.529433+00:00 app[web.1]:     at Connection.parseMessage (/app/node_modules/ghost/node_modules/pg/lib/connection.js:361:17)
    2015-11-16T13:31:39.529434+00:00 app[web.1]:     at CleartextStream.<anonymous> (/app/node_modules/ghost/node_modules/pg/lib/connection.js:105:22)
    2015-11-16T13:31:39.529435+00:00 app[web.1]:     at CleartextStream.emit (events.js:95:17)
    2015-11-16T13:31:39.529435+00:00 app[web.1]:     at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    2015-11-16T13:31:39.529436+00:00 app[web.1]:     at CleartextStream.emit (events.js:92:17)
    2015-11-16T13:31:39.529437+00:00 app[web.1]:     at emitReadable_ (_stream_readable.js:427:10)
    2015-11-16T13:31:39.529437+00:00 app[web.1]:     at _stream_readable.js:420:7
    2015-11-16T13:31:39.529438+00:00 app[web.1]:     at process._tickDomainCallback (node.js:492:13)
    2015-11-16T13:31:39.529439+00:00 app[web.1]:     at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)
    2015-11-16T13:31:39.570531+00:00 app[web.1]: 
    2015-11-16T13:31:39.589640+00:00 app[web.1]: npm ERR! Additional logging details can be found in:
    2015-11-16T13:31:39.589799+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
    2015-11-16T13:31:39.590169+00:00 app[web.1]: npm ERR! not ok code 0
    2015-11-16T13:31:39.581093+00:00 app[web.1]: npm ERR! ghost-on-heroku@0.7.0 start: `node server.js`
    2015-11-16T13:31:39.581368+00:00 app[web.1]: npm ERR! Exit status 8
    2015-11-16T13:31:39.581669+00:00 app[web.1]: npm ERR! 
    2015-11-16T13:31:39.581844+00:00 app[web.1]: npm ERR! Failed at the ghost-on-heroku@0.7.0 start script.
    2015-11-16T13:31:39.582767+00:00 app[web.1]: npm ERR! This is most likely a problem with the ghost-on-heroku package,
    2015-11-16T13:31:39.582955+00:00 app[web.1]: npm ERR! not with npm itself.
    2015-11-16T13:31:39.583082+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
    2015-11-16T13:31:39.583221+00:00 app[web.1]: npm ERR!     node server.js
    2015-11-16T13:31:39.583369+00:00 app[web.1]: npm ERR! You can get their info via:
    2015-11-16T13:31:39.583525+00:00 app[web.1]: npm ERR!     npm owner ls ghost-on-heroku
    2015-11-16T13:31:39.583709+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
    2015-11-16T13:31:39.583906+00:00 app[web.1]: npm ERR! System Linux 3.13.0-63-generic
    2015-11-16T13:31:39.584100+00:00 app[web.1]: npm ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start" "--production"
    2015-11-16T13:31:39.584296+00:00 app[web.1]: npm ERR! cwd /app
    2015-11-16T13:31:39.584487+00:00 app[web.1]: npm ERR! node -v v0.10.40
    2015-11-16T13:31:39.584696+00:00 app[web.1]: npm ERR! npm -v 1.4.28
    2015-11-16T13:31:39.584879+00:00 app[web.1]: npm ERR! code ELIFECYCLE
    2015-11-16T13:31:39.589320+00:00 app[web.1]: npm ERR! 
    2015-11-16T13:31:40.573194+00:00 heroku[web.1]: State changed from up to crashed
    2015-11-16T13:31:40.562840+00:00 heroku[web.1]: Process exited with status 1

Not a very impressive up-time. :( 
![stats](https://cloud.githubusercontent.com/assets/437287/11183840/4689ae80-8c74-11e5-97e7-d7271fe3a736.png)

**Comment by ErisDS** [comment]
Sorry to hear you're having trouble. Going to close this as you found our #help channel on slack. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
