### ISSUE TITLE
can't install on Win7, nodev4.2.3, npm2.14.10

### ISSUE THREAD

**Issue by tomByrer** [TryGhost/Ghost#6218]
### System

Win7-64, Node installed with [nodist](https://github.com/marcelklehr/nodist) (nvm clone for windows)

### CLI output:

```bash
E:\client\Tim\ghost> nodist
  (x64)
> nodev4.2.3  (global)

E:\client\Tim\ghost> npm -v
2.14.10

E:\client\Tim\ghost> npm install --production

> ghost@0.7.2 preinstall E:\client\Tim\ghost
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

semver@5.0.3 node_modules\semver
module.js:339
    throw err;
    ^

Error: Cannot find module './core/server/utils/startup-check.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:578:27
    at doNTCallback0 (node.js:419:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\p\\n\\nodist\\v-x64\\nodev4.2.3\\node.exe" "C:\\p\\n\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.10
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.7.2 preinstall: `npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ghost@0.7.2 preinstall script 'npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\client\Tim\ghost\npm-debug.log
```

### npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\p\\n\\nodist\\v-x64\\nodev4.2.3\\node.exe',
1 verbose cli   'C:\\p\\n\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--production' ]
2 info using npm@2.14.10
3 info using node@v4.2.3
4 verbose readDependencies loading dependencies from E:\client\Tim\ghost\package.json
5 verbose readDependencies npm-shrinkwrap.json is overriding dependencies
6 info shrinkwrap file "E:\\client\\Tim\\ghost\\npm-shrinkwrap.json"
7 verbose readDependencies returned deps { abbrev: '1.0.7',
7 verbose readDependencies returned deps   bcryptjs: 'https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.3.0.tgz',
7 verbose readDependencies returned deps   bluebird: 'https://registry.npmjs.org/bluebird/-/bluebird-2.10.2.tgz',
7 verbose readDependencies returned deps   'body-parser': 'https://registry.npmjs.org/body-parser/-/body-parser-1.14.1.tgz',
7 verbose readDependencies returned deps   bookshelf: 'https://registry.npmjs.org/bookshelf/-/bookshelf-0.7.9.tgz',
7 verbose readDependencies returned deps   busboy: 'https://registry.npmjs.org/busboy/-/busboy-0.2.11.tgz',
7 verbose readDependencies returned deps   bytes: '2.1.0',
7 verbose readDependencies returned deps   chalk: 'https://registry.npmjs.org/chalk/-/chalk-1.1.1.tgz',
7 verbose readDependencies returned deps   cheerio: 'https://registry.npmjs.org/cheerio/-/cheerio-0.19.0.tgz',
7 verbose readDependencies returned deps   compression: 'https://registry.npmjs.org/compression/-/compression-1.6.0.tgz',
7 verbose readDependencies returned deps   'connect-slashes': 'https://registry.npmjs.org/connect-slashes/-/connect-slashes-1.3.1.tgz',
7 verbose readDependencies returned deps   'content-type': '1.0.1',
7 verbose readDependencies returned deps   'cookie-session': 'https://registry.npmjs.org/cookie-session/-/cookie-session-1.2.0.tgz',
7 verbose readDependencies returned deps   downsize: 'https://registry.npmjs.org/downsize/-/downsize-0.0.8.tgz',
7 verbose readDependencies returned deps   express: 'https://registry.npmjs.org/express/-/express-4.13.3.tgz',
7 verbose readDependencies returned deps   'express-hbs': 'https://registry.npmjs.org/express-hbs/-/express-hbs-0.8.4.tgz',
7 verbose readDependencies returned deps   'extract-zip': 'https://registry.npmjs.org/extract-zip/-/extract-zip-1.1.1.tgz',
7 verbose readDependencies returned deps   'fs-extra': 'https://registry.npmjs.org/fs-extra/-/fs-extra-0.24.0.tgz',
7 verbose readDependencies returned deps   'ghost-gql': '0.0.3',
7 verbose readDependencies returned deps   glob: 'https://registry.npmjs.org/glob/-/glob-5.0.15.tgz',
7 verbose readDependencies returned deps   'html-to-text': 'https://registry.npmjs.org/html-to-text/-/html-to-text-1.3.2.tgz',
7 verbose readDependencies returned deps   'http-errors': '1.3.1',
7 verbose readDependencies returned deps   'iconv-lite': '0.4.12',
7 verbose readDependencies returned deps   inherits: '2.0.1',
7 verbose readDependencies returned deps   ini: '1.3.4',
7 verbose readDependencies returned deps   intl: 'https://registry.npmjs.org/intl/-/intl-1.0.0.tgz',
7 verbose readDependencies returned deps   'intl-messageformat': 'https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.1.0.tgz',
7 verbose readDependencies returned deps   istanbul: 'https://registry.npmjs.org/istanbul/-/istanbul-0.4.1.tgz',
7 verbose readDependencies returned deps   jsonpath: 'https://registry.npmjs.org/jsonpath/-/jsonpath-0.2.0.tgz',
7 verbose readDependencies returned deps   knex: 'https://registry.npmjs.org/knex/-/knex-0.7.3.tgz',
7 verbose readDependencies returned deps   lodash: 'https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz',
7 verbose readDependencies returned deps   'mime-types': '2.1.7',
7 verbose readDependencies returned deps   minimist: '1.1.3',
7 verbose readDependencies returned deps   mocha: '2.3.4',
7 verbose readDependencies returned deps   moment: 'https://registry.npmjs.org/moment/-/moment-2.10.6.tgz',
7 verbose readDependencies returned deps   morgan: 'https://registry.npmjs.org/morgan/-/morgan-1.6.1.tgz',
7 verbose readDependencies returned deps   mysql: 'https://registry.npmjs.org/mysql/-/mysql-2.1.1.tgz',
7 verbose readDependencies returned deps   'node-uuid': 'https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.3.tgz',
7 verbose readDependencies returned deps   nodemailer: 'https://registry.npmjs.org/nodemailer/-/nodemailer-0.7.1.tgz',
7 verbose readDependencies returned deps   nopt: '3.0.6',
7 verbose readDependencies returned deps   oauth2orize: 'https://registry.npmjs.org/oauth2orize/-/oauth2orize-1.0.1.tgz',
7 verbose readDependencies returned deps   'on-finished': '2.3.0',
7 verbose readDependencies returned deps   'on-headers': '1.0.1',
7 verbose readDependencies returned deps   once: 'https://registry.npmjs.org/once/-/once-1.1.1.tgz',
7 verbose readDependencies returned deps   passport: 'https://registry.npmjs.org/passport/-/passport-0.3.0.tgz',
7 verbose readDependencies returned deps   'passport-http-bearer': 'https://registry.npmjs.org/passport-http-bearer/-/passport-http-bearer-1.0.1.tgz',
7 verbose readDependencies returned deps   'passport-oauth2-client-password': 'https://registry.npmjs.org/passport-oauth2-client-password/-/passport-oauth2-client-password-0.1.2.tgz',
7 verbose readDependencies returned deps   'passport-strategy': '1.0.0',
7 verbose readDependencies returned deps   'path-match': 'https://registry.npmjs.org/path-match/-/path-match-1.2.3.tgz',
7 verbose readDependencies returned deps   pg: 'https://registry.npmjs.org/pg/-/pg-4.1.1.tgz',
7 verbose readDependencies returned deps   request: 'https://registry.npmjs.org/request/-/request-2.65.0.tgz',
7 verbose readDependencies returned deps   rss: 'https://registry.npmjs.org/rss/-/rss-1.2.0.tgz',
7 verbose readDependencies returned deps   semver: '5.0.3',
7 verbose readDependencies returned deps   'showdown-ghost': 'https://registry.npmjs.org/showdown-ghost/-/showdown-ghost-0.3.6.tgz',
7 verbose readDependencies returned deps   sqlite3: 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.1.tgz',
7 verbose readDependencies returned deps   statuses: '1.2.1',
7 verbose readDependencies returned deps   'type-is': '1.6.9',
7 verbose readDependencies returned deps   unidecode: 'https://registry.npmjs.org/unidecode/-/unidecode-0.1.7.tgz',
7 verbose readDependencies returned deps   unpipe: '1.0.0',
7 verbose readDependencies returned deps   'utils-merge': '1.0.0',
7 verbose readDependencies returned deps   validator: 'https://registry.npmjs.org/validator/-/validator-4.1.0.tgz',
7 verbose readDependencies returned deps   xml: 'https://registry.npmjs.org/xml/-/xml-1.0.0.tgz' }
8 verbose install where, deps [ 'E:\\client\\Tim\\ghost',
8 verbose install   [ 'abbrev',
8 verbose install     'bcryptjs',
8 verbose install     'bluebird',
8 verbose install     'body-parser',
8 verbose install     'bookshelf',
8 verbose install     'busboy',
8 verbose install     'bytes',
8 verbose install     'chalk',
8 verbose install     'cheerio',
8 verbose install     'compression',
8 verbose install     'connect-slashes',
8 verbose install     'content-type',
8 verbose install     'cookie-session',
8 verbose install     'downsize',
8 verbose install     'express',
8 verbose install     'express-hbs',
8 verbose install     'extract-zip',
8 verbose install     'fs-extra',
8 verbose install     'ghost-gql',
8 verbose install     'glob',
8 verbose install     'html-to-text',
8 verbose install     'http-errors',
8 verbose install     'iconv-lite',
8 verbose install     'inherits',
8 verbose install     'ini',
8 verbose install     'intl',
8 verbose install     'intl-messageformat',
8 verbose install     'istanbul',
8 verbose install     'jsonpath',
8 verbose install     'knex',
8 verbose install     'lodash',
8 verbose install     'mime-types',
8 verbose install     'minimist',
8 verbose install     'mocha',
8 verbose install     'moment',
8 verbose install     'morgan',
8 verbose install     'mysql',
8 verbose install     'node-uuid',
8 verbose install     'nodemailer',
8 verbose install     'nopt',
8 verbose install     'oauth2orize',
8 verbose install     'on-finished',
8 verbose install     'on-headers',
8 verbose install     'once',
8 verbose install     'passport',
8 verbose install     'passport-http-bearer',
8 verbose install     'passport-oauth2-client-password',
8 verbose install     'passport-strategy',
8 verbose install     'path-match',
8 verbose install     'pg',
8 verbose install     'request',
8 verbose install     'rss',
8 verbose install     'semver',
8 verbose install     'showdown-ghost',
8 verbose install     'sqlite3',
8 verbose install     'statuses',
8 verbose install     'type-is',
8 verbose install     'unidecode',
8 verbose install     'unpipe',
8 verbose install     'utils-merge',
8 verbose install     'validator',
8 verbose install     'xml' ] ]
9 verbose install where, peers [ 'E:\\client\\Tim\\ghost', [] ]
10 verbose installManyTop reading for lifecycle E:\client\Tim\ghost\package.json
11 info preinstall ghost@0.7.2
12 verbose unsafe-perm in lifecycle true
13 info ghost@0.7.2 Failed to exec preinstall script
14 verbose stack Error: ghost@0.7.2 preinstall: `npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\p\n\nodist\bin\node_modules\npm\lib\utils\lifecycle.js:214:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\p\n\nodist\bin\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ghost@0.7.2
16 verbose cwd E:\client\Tim\ghost
17 error Windows_NT 6.1.7601
18 error argv "C:\\p\\n\\nodist\\v-x64\\nodev4.2.3\\node.exe" "C:\\p\\n\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
19 error node v4.2.3
20 error npm  v2.14.10
21 error code ELIFECYCLE
22 error ghost@0.7.2 preinstall: `npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`
22 error Exit status 1
23 error Failed at the ghost@0.7.2 preinstall script 'npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"'.
23 error This is most likely a problem with the ghost package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"
23 error You can get their info via:
23 error     npm owner ls ghost
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ckousik** [comment]
I'm having the same issue. I installed some of the dependencies manually.... 
now when I run grunt init it doesn't run ember build and I get the same JavaScript files not built error when I run npm start

**Comment by BarryThePenguin** [comment]
You both might want to have a read of the following

http://support.ghost.org/supported-node-versions/

Particularly the bit where it mentions disabling the version check

http://support.ghost.org/supported-node-versions/#disable-the-version-check

**Comment by BarryThePenguin** [comment]
Whelp! Even using `GHOST_NODE_VERSION_CHECK=false` I couldn't get ghost installed...

**Comment by ErisDS** [comment]
I'm sorry this got missed - it's not a regular or reproducible issue - it's a problem particular to your machine / environment. There's a troubleshooting guide here: http://support.ghost.org/troubleshooting/.

As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
