### ISSUE TITLE
Error: Cannot find module './lib/main' when try to upgrade to latest Ghost version

### ISSUE THREAD

**Issue by alicoding** [TryGhost/Ghost#6262]
```

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/main'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/ghost/node_modules/intl-messageformat/index.js:5:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/ghost/core/server/i18n.js:7:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I'm using node version `4.2.0` and followed digitalocean guide for upgrade.

**Comment by alicoding** [comment]
Went through the upgrade guide again and it's now working.

**Comment by fjaguero** [comment]
Hi @alicoding, what was the problem? I'm having the same issue.

**Comment by alicoding** [comment]
@fjaguero I honestly have no idea why it was throwing the error, but once I follow the guide from start again and it was working fine.

**Comment by kevinansfield** [comment]
@fjaguero It sounds like npm had some issues when installing, unfortunately it's not always the most reliable and can fail silently. We have a troubleshooting guide that details some steps to try and get an install working again - http://support.ghost.org/troubleshooting/

**Comment by fjaguero** [comment]
@kevinansfield Thanks, I will have a double-check of each item. It may be the free memory issue.
