### ISSUE TITLE
{{ghost_head}} throwing errors when used in errors.hbs

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6289]
The errors.hbs template which can be provided with a Ghost theme is used to render both 404 and 500 errors. As this file can be used to render server-side error information, it *should* not extend a layout file using all the fancy helpers from the default.hbs template because if the error affects any of those systems, the error page won't be able to render. For this reason, the error template [provided as an example](https://github.com/TryGhost/Ghost/blob/master/core/server/views/user-error.hbs) is a minimal template.

Many theme developers don't realise this (it's not documented) and so many themes have error.hbs files which extend the default.hbs. As a result, helpers like `{{ghost_head}}` get called. Whilst that is not ideal, these helpers should cope.

At the moment, `{{ghost_head}}` throws errors when called from the error template. This is just one of them, I've seen the same error for 'slug', and 'published_at', I think the error depends on what the url structure is when the error happens as ghost_head tries to do some work.

```
ERROR: Cannot read property 'description' of undefined 
 registerAsyncThemeHelper: ghost_head 
 
 TypeError: Cannot read property 'description' of undefined
    at initMetaData (/Users/hannah/Ghost/Ghost/core/server/helpers/ghost_head.js:133:48)
    at Promise.props.then.then.api.settings.read.key (/Users/hannah/Ghost/Ghost/core/server/helpers/ghost_head.js:317:28)
    at tryCatcher (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13) 
```

This error prevents the page from being rendered, Ghost hangs, and the user sees this:

![](http://puu.sh/mklU3.png)

Navigating to another page will work, Ghost doesn't fully crash, but this is very far from ideal. The quick fix here is to make sure that ghost_head doesn't try to do anything for the error page (meta data isn't needed here) for the longer term, #6186 talks about refactoring ghost_head completely.

**Comment by ErisDS** [comment]
Closed by #6298
