### ISSUE TITLE
Access denied from url when trying to access admin using google chrome

### ISSUE THREAD

**Issue by paragasu** [TryGhost/Ghost#6312]
Access denied from url when trying to access admin using google chrome.

### Issue summary
login via /ghost/signin using google chrome Version 47.0.2526.80 (64-bit) will give error

    Access Denied from url: blog.myblog.com. Please use the url configured in config.js.

No problem if login using firefox.

### Step to reproduce
1. Download latest stable v0.7.4 from ghost.org/download .
2. Start the ghost server in production mode.
3. Open google chrome and type blogurl.com/admin.

### Technical details
* Ghost  v0.7.4 
* Google Chrome v47.0.2526.80
* npm v3.5.3
* node v4.2.4
* Server Os - Debian 8 Jessie 3.16.0-4-amd64
* Client Os - Debian 8 Jessie 3.16.0-4-amd64
* Database sqlite3

**Comment by ErisDS** [comment]
Hi @paragasu the error you're reporting should have had a lot more information underneath it, including an explanation and a link to the documentation explaining what's wrong. They should read:

`You have attempted to access your Ghost admin panel from a url that does not appear in config.js.
For information on how to fix this, please read http://support.ghost.org/config/#url.`

Do you not see that output in your environment?

**Comment by paragasu** [comment]
Hi ErisDs,

Well, at first i suspect the error related to the config file.   
The weird part is **i can login normally without problem if i use Firefox browser**. 
If the config file is not good, i should not be able to login in Firefox.

The issue currently **only appear on my google chrome browser**. It is tested on two computer so far (the other computer running on the latest ubuntu linux).

The error is visible on the login page in google chrome. On the console, the error is this one,

    ERROR: Access Denied from url: blog.myblog.com. Please use the url configured in config.js. 
     You have attempted to access your Ghost admin panel from a url that does not appear in config.js. 
     For information on how to fix this, please read http://support.ghost.org/config/#url. 
    Error
        at Error.UnauthorizedError (/home/myblog/ghost/core/server/errors/unauthorized-error.js:6:18)
        at authenticate (/home/myblog/ghost/core/server/middleware/auth.js:130:29)
        at Strategy.strategy.success (/home/myblog/ghost/node_modules/passport/lib/middleware/authenticate.js:194:18)
        at verified (/home/myblog/ghost/node_modules/passport-oauth2-client-password/lib/strategy.js:50:10)
        at then (/home/myblog/ghost/core/server/middleware/auth-strategies.js:21:32)
        at tryCatcher (/home/myblog/ghost/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/myblog/ghost/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/home/myblog/ghost/node_modules/bluebird/js/main/promise.js:581:18)
        at Async._drainQueue (/home/myblog/ghost/node_modules/bluebird/js/main/async.js:128:12)
       at Async._drainQueues (/home/myblog/ghost/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues [as _onImmediate] (/home/myblog/ghost/node_modules/bluebird/js/main/async.js:15:14)
       at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by ErisDS** [comment]
Hi @paragasu, I understand now why you only saw the first part of the message. We need to improve our UI messaging to also be clearer. 

> If the config file is not good, i should not be able to login in Firefox.

Browsers are all different, particularly in terms of how they manage security. 

The documentation at http://support.ghost.org/config/#url should have explained how to fix the issue, if not let me know and I'll try to improve the documentation.

**Comment by madhuraraju** [comment]
So why does this error only occur from a chrome browser and not from firefox or safari? 
I don't get a "Access Denied from url: www.mydomain.com. Please use the url configured in config.js." from safari or firefox. Have you been able to diagnose the problem?

**Comment by ErisDS** [comment]
Unfortunately, it's not possible to diagnose exactly what might be causing this unless people who see it  provide the relevant details. That is the url configuration in config.js and the URL they're using to access the admin panel. 

We have a  #help channel in our [slack](https://ghost.org/slack) team for getting help & support with your specific setup.
