### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by mnzt** [TryGhost/Ghost#6476]
```
ERROR: [index.hbs] Cannot read property 'fn' of undefined 
 Rendering Error Page 
 Ghost caught a processing error in the middleware layer. 
 TypeError: [index.hbs] Cannot read property 'fn' of undefined
    at Object.foreach (/home/ubuntu/workspace/blog.nerdping.com/core/server/helpers/foreach.js:18:21)
    at Object.eval (eval at createFunctionContext (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:194)
    at ret (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at renderTemplate (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:481:13)
    at render (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:529:5)
    at renderIt (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:591:18)
    at /home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:601:11
    at _returnLayouts (/home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:138:7)
    at /home/ubuntu/workspace/blog.nerdping.com/node_modules/express-hbs/lib/hbs.js:149:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3) 
```

Using version 0.7.6, trying to setup `default.hbs`, and running into this error in custom themeing within dev mode. Directory structure:

```
├── assets
│   ├── css
│   ├── fonts
│   ├── images
│   └── js
├── default.hbs
├── index.hbs
├── package.json
├── partials
│   ├── footer.hbs
│   └── header.hbs
└── post.hbs
```

Index 'imports' default via: `{{!< default}}` on line 1.

**Comment by mnzt** [comment]
I omitted a parameter from the foreach by mistake. However, the error should be a little clearer imho.
