### ISSUE TITLE
page_url: Cannot read data property of undefined

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost#6719]
### Issue Summary

Since this morning I get the following error on my home page:

![screenshot_2016-04-14_10-54-29](https://cloud.githubusercontent.com/assets/175080/14523628/f595afec-0234-11e6-9576-12529704b1bd.png)

I downloaded the ghost source and running the latest master in development mode, I get a little more information:

```
TypeError: [index.hbs] Cannot read property 'data' of undefined
    at Object.page_url (/home/jon/source/ghost/core/server/helpers/page_url.js:18:41)
    at Object.eval (eval at createFunctionContext (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:14:166)
    at ret (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.templates.execute (/home/jon/source/ghost/core/server/helpers/template.js:23:42)
    at Object.pagination (/home/jon/source/ghost/core/server/helpers/pagination.js:34:21)
    at Object.eval (eval at createFunctionContext (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:8:185)
    at ret (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/home/jon/source/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at renderTemplate (/home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:481:13)
    at render (/home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:529:5)
    at renderIt (/home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:591:18)
    at /home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:601:11
    at _returnLayouts (/home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:138:7)
    at /home/jon/source/ghost/node_modules/express-hbs/lib/hbs.js:149:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I'm still not sure if this is an issue with my theme but since it has been working I'm creating an issue. This happens in my `pagination.hbs` partial:

```
<script type="text/javascript">
    // set the values that we'll use in the bootstrap-pagination.js file
    {{!if there is no value for the variable, display a 0}}
    prev = {{#if prev}}{{prev}}{{else}}0{{/if}};
    pages = {{#if pages}}{{pages}}{{else}}0{{/if}};
    page = {{#if page}}{{page}}{{else}}0{{/if}};
    next = {{#if next}}{{next}}{{else}}0{{/if}};
    pageUrl = '{{page_url}}';
    pageUrlPrev = '{{page_url prev}}';
    pageUrlNext = '{{page_url next}}';
    pageUrlFirst = '{{page_url 1}}';
    pageUrlLast = '{{page_url pages}}';
</script>
<nav class="text-center">
  <ul class="pagination bootstrap-pagination">
  </ul>
</nav>
```

This template required some javascript defined in `default.hbs` to generate the pagination correctly. I've not included that because if I remove `{{pagination}}` from `index.hbs` the page loads fine. It seems that `options` in `ghost/core/server/helpers/pagination.js` is now undefined.

In version 0.7.8 (stable branch) it works fine.

### Technical details:

* Ghost Version: latest master (commit: 8b53308f10bcc151e4d0addea97803f7e178f043)
* Node Version: v4.4.0
* Browser/OS: Iceweasel and Chromium
* Database: Whatever npm start uses

Sorry I can't be of more help since I'm at work.

**Comment by ErisDS** [comment]
Hey @jonblack - seems you're on Ghost(Pro) and got early-upgraded :wink: 

The issue here is that the `{{page_url}}` helper is not intended to be called without being passed a page to output. It looks like you're using it to get the base URL which is surely identical to doing `{{page_url 1}}` ? The quick fix here for you would be to change that line to `{{page_url 1}}`.

The fact that it's causing such a serious error should probably be addressed - we're discussing it but in the meantime this is how to resolve it.

**Comment by jonblack** [comment]
Thanks for the quick reply. You're right that I need to pass the page number.
