### ISSUE TITLE
Upgraded to 0.8.0, sqlite3 error

### ISSUE THREAD

**Issue by dalanmiller** [TryGhost/Ghost#6902]
### Issue Summary

While in the my `ghost` directory, I can run `npm start --production` and it loads just fine. However when I restart my `supervisord` conf, it fails to load correctly: 
```
> ghost@0.8.0 start /user/ghost
> node index

Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/user/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usert/ghost/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Client._driver (/user/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:37:12)
    at Client.initializeDriver (/user/ghost/node_modules/knex/lib/client.js:162:26)
    at Client (/user/ghost/node_modules/knex/lib/client.js:41:10)
    at Client_SQLite3 (/user/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:23:10)
    at new Client (/user/ghost/node_modules/knex/lib/util/make-client.js:15:18)
    at Knex (/user/ghost/node_modules/knex/lib/index.js:26:19)
    at Object.<anonymous> (/user/ghost/core/server/data/db/connection.js:33:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.get [as knex] (/user/ghost/core/server/data/db/index.js:7:36)
    at Object.<anonymous> (/user/ghost/core/server/models/base/index.js:28:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Here is my supervisor conf
```
[program:ghost]
command = npm start --production
directory = /user/ghost
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/ghost.log
stderr_logfile = /var/log/supervisor/ghost_err.log
environment = NODE_ENV="production"
```

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.2.6
* Browser/OS: Ubuntu 14.04
* Database: sqlite3

**Comment by ErisDS** [comment]
Hi @dalanmiller, sorry to hear you're having trouble. 

> Error: Cannot find module '/user/ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node'

Means that the sqlite3 binary that is needed cannot be found. This suggests to me that perhaps the node version is different between when you run on the cli vs with supervisor? Were you perhaps using nave or nvm?

Running `npm install sqlite3` again, providing the cli version of node is the same as the service will use, will install a new binary.

I'm going to close this issue as it is not an issue with the software, but with your particular installation. If you need further help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel.

**Comment by dalanmiller** [comment]
Thanks @ErisDS !

**Comment by dalanmiller** [comment]
To anyone who finds this issue later down the line. If you use `nvm` I couldn't find a canonized way to install a system-wide version of Node which would be usable by `supervisor`. What I eventually did was just provide the direct path to the `nvm` installed version of `node` that I want to use for Ghost. 

Here is my `supervisor` config for Ghost:

```
[program:ghost]
command = /user/.nvm/v4.2.6/bin/node index --production
directory = /user/ghost
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/ghost.log
stderr_logfile = /var/log/supervisor/ghost_err.log
environment = NODE_ENV="production"
```

This is somewhat borrowed originally from here - http://ahmed.amayem.com/running-a-node-js-app-ghost-in-the-background-continuously-with-supervisor-supervisord/

**Comment by ErisDS** [comment]
Thanks for the update 👍
