### ISSUE TITLE
Invalid refresh token leading to unsupported database operation

### ISSUE THREAD

**Issue by enceladus** [TryGhost/Ghost#6944]
### Issue Summary

Ghost is inserting null byte characters (0x00) into text fields in a Postgres database, which is unsupported. This seems to be happening when a refresh token is invalid. But I'm not sure why I'm getting an invalid refresh token in the first place.

### Steps to Reproduce

I'm using Ghost as a middle ware in an Express app [as described here](http://rogerstringer.com/2015/09/07/ghost-express-middleware/).

I installed Ghost via NPM, and followed that guide exactly. 

When I get to http://localhost:3000/blog/ghost/ for the setup, I create a user, and then click the button "Last Step: Invite Your Team," which results in a HTTP 500 response to this request:

    GET http://localhost:3000/blog/ghost/api/v0.1/settings/?type=blog%2Ctheme%2Cprivate 

Checking my logs, I get:

```
ERROR: Invalid refresh token. 
 
 Error
    at Error.NoPermissionError (node_modules/ghost/core/server/errors/no-permission-error.js:6:18)
    at then (node_modules/ghost/core/server/middleware/oauth.js:14:25)
    at null.<anonymous> (node_modules/loopback/node_modules/continuation-local-storage/context.js:76:17)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (node_modules/ghost/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:15:14)
    at Immediate._onImmediate (node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
    at processImmediate [as _immediateCallback] (timers.js:368:17) 

POST /blog/ghost/api/v0.1/authentication/token 403 28.650 ms - 81
GET /blog/ghost/api/v0.1/authentication/setup/ 200 16.389 ms - 28
POST /blog/ghost/api/v0.1/authentication/setup/ 201 583.899 ms - 500
POST /blog/ghost/api/v0.1/authentication/token 200 291.766 ms - -
error: invalid byte sequence for encoding "UTF8": 0x00
    at Connection.parseE (node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    at TCP.onread (node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
```

(changed paths for readability — all paths are relative to the application's base directory)

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.2.0
* Browser/OS: Chrome/OSX
* Database: PostgreSQL 9.5.2

**Comment by ErisDS** [comment]
Hi @enceladus, I'm sorry that this issue has gone so long without a reply. 

With the combination of using Ghost as an npm module & postgres you have kind of hit the jackpot in terms of going off the beaten path! 

Particularly, when it comes to postgres, there's no longer any regular contributors who are familiar with it and up for debugging these issues. For this reason, we're going to be dropping support for postgres in Ghost 1.0 and focusing our efforts on optimising Ghost for MySQL. 

If you managed to figure out what caused it, or wanted to submit a patch to the `lts` branch for Ghost v0.11 that would be very welcome. Otherwise I think it's best if we close this issue now.
