### ISSUE TITLE
Unable to delete a user, causes all subsequent db requests to fail

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7137]
### Issue Summary

When attempting to delete a user who has posts I'm seeing a 500 Internal Server Error, all subsequent API requests also return a 500 error.

### Steps to Reproduce

1. Ensure you have a user who has authored some posts
2. Sign out and sign in as a user who has permissions to delete users
3. Select the user from step 1 in the Team page then click the cog icon and select "Delete User"
4. Click "Delete"

At this point I see a long spinner which eventually results in the 500 error and this message in the app log:

```
ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
 
 InternalServerError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Error.InternalServerError (/Users/kevinansfield/code/ghost/Ghost/core/server/errors/internal-server-error.js:6:18)
    at null.<anonymous> (/Users/kevinansfield/code/ghost/Ghost/core/server/models/post.js:661:23)
From previous event:
    at Function.destroyByAuthor (/Users/kevinansfield/code/ghost/Ghost/core/server/models/post.js:660:19)
    at Function.tryCatcher (/Users/kevinansfield/code/ghost/Ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Function.destroyByAuthor (/Users/kevinansfield/code/ghost/Ghost/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/kevinansfield/code/ghost/Ghost/core/server/api/users.js:397:39
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/knex/lib/transaction.js:38:20
    at processImmediate [as _immediateCallback] (timers.js:383:17) 

DELETE /ghost/api/v0.1/users/7/ 500 60093.195 ms - 167
```

Any requests after this point have a similar response.

In case it's particular to my database state, [here's a copy of my sqlite db](https://cl.ly/3d0Y1r170u02)

### Technical details:

* Ghost Version: master
* Database: sqlite

**Comment by kirrg001** [comment]
This bug exists also in `0.8.0`.

**Comment by kirrg001** [comment]
The bug only exists when using `sqlite`.
