### ISSUE TITLE
validation-error.js error?

### ISSUE THREAD

**Issue by wangqiliang** [TryGhost/Ghost#7164]
### Issue Summary

I was try to update ghost 0.9.0-beta1 to ghost-0.9.0 .

### Steps to Reproduce
0.  copy gost-0.9.0/core to the directory of the website
1.  rm -rf node_modules
2.  npm install --production
3.  node index

### 4. ERROR OCCURED!
```
ERROR: Value in [settings.uuid] exceeds maximum length of 36 characters.

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:88:43)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Validation (isUUID) failed for uuid

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:189:35)
    at /home/ghost/node_modules/lodash/index.js:2874:23
    at /home/ghost/node_modules/lodash/index.js:3073:15
    at baseForOwn (/home/ghost/node_modules/lodash/index.js:2046:14)
    at /home/ghost/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3346:13)
    at validate (/home/ghost/core/server/data/validation/index.js:175:7)
    at each (/home/ghost/core/server/data/validation/index.js:94:60)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Value in [settings.key] exceeds maximum length of 150 characters.

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:88:43)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Value in [settings.type] exceeds maximum length of 150 characters.

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:88:43)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Validation (isIn) failed for type

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:189:35)
    at /home/ghost/node_modules/lodash/index.js:2874:23
    at /home/ghost/node_modules/lodash/index.js:3073:15
    at baseForOwn (/home/ghost/node_modules/lodash/index.js:2046:14)
    at /home/ghost/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3346:13)
    at validate (/home/ghost/core/server/data/validation/index.js:175:7)
    at each (/home/ghost/core/server/data/validation/index.js:94:60)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Value in [settings.created_by] is not an integer.

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:101:43)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: Value in [settings.updated_by] is not an integer.

 Error
    at Error.ValidationError (/home/ghost/core/server/errors/validation-error.js:6:18)
    at each (/home/ghost/core/server/data/validation/index.js:101:43)
    at arrayEach (/home/ghost/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/ghost/node_modules/lodash/index.js:3345:13)
    at Object.validateSchema (/home/ghost/core/server/data/validation/index.js:59:7)
    at validate (/home/ghost/core/server/models/settings.js:79:27)
    at then (/home/ghost/core/server/models/base/index.js:86:29)
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/ghost/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.4.7
* Browser/OS: CentOS 7
* Database:  MariaDB 5.5.47

I consider it a database Migration error.

**Comment by acburdine** [comment]
@wangqiliang sorry to hear you're having trouble!

Would you mind swinging by our [slack channel](https://ghost.org/slack)? We can provide better support there for this 😄  If it is actually a bug with Ghost we can reopen this.

**Comment by manusajith** [comment]
@wangqiliang Did you manage to fix the issue, I just stumbled upon the same thing and was wondering how you managed to fixed it ?

**Comment by ErisDS** [comment]
I'm going to wager a guess that this comes from trying to use utf8mb4 encoding. This is not currently supported.
