### ISSUE TITLE
Downloading a large theme causes an error

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7266]
When trying to download a theme with a lot of files (E.g. with a bunch of development-related files like node-modules), I see the following error:

```
ERROR: stdout maxBuffer exceeded 
 
 Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20) 
```

### Steps to Reproduce

Example file:
[casper-with-nodemodules.zip](https://github.com/TryGhost/Ghost/files/436178/casper-with-nodemodules.zip)

1. Add this theme to your content/themes directory 
2. Attempt to download it

**Comment by ErisDS** [comment]
It also occurs to me that the current implementation of download won't work on any machine that doesn't have `zip` installed, which is Windows + many linux distros.

I have a working JavaScript implementation using `node-archiver`, but it's really slow, even with a simple theme. 

I'm not sure if we can find a faster implementation, or if we're going to need to create some sort of UI to show that something is happening whilst the file is generated.

**Comment by ErisDS** [comment]
Wait... it's not slow!! I had a bug where I was downloading the entire theme directory rather than just one theme 👯 

Given that, it actually wasn't that slow at all, and it successfully zipped up 50mb of themes & theme zips. Sooo I guess that's a good test for robustness 😁
