### ISSUE TITLE
Broken admin UI: Version mismatch with ghost npm module instance

### ISSUE THREAD

**Issue by krokofant** [TryGhost/Ghost#7286]
### Issue Summary

The main site works but the admin interface is broken and an error is produced:
`ERROR: Request for version 0.9 does not match current version 0.10.`

### Steps to Reproduce

1. create new project folder
2. `npm install ghost express`
3. add `config.example.json` from ghost v0.10.0
4. `node index.js`
5. go to `http://localhost:2368/admin`

#### index.js
```javascript
var ghost = require('ghost'),
    express = require('express'),
    parentApp = express();

ghost().then(function (ghostServer) {
    parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);
    ghostServer.start(parentApp);
});
```

### Technical details:

* Ghost Version: 0.10.0 via npm
* Node Version: 4.5 LTS
* Browser/OS: WIndows 10 x64, Google Chrome v52
* Database: PG or sqlite

#### log
```
Migrations: Creating tables...
Migrations: Creating table: posts
Migrations: Creating table: users
Migrations: Creating table: roles
Migrations: Creating table: roles_users
Migrations: Creating table: permissions
Migrations: Creating table: permissions_users
Migrations: Creating table: permissions_roles
Migrations: Creating table: permissions_apps
Migrations: Creating table: settings
Migrations: Creating table: tags
Migrations: Creating table: posts_tags
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: client_trusted_domains
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Creating table: subscribers
Migrations: Running fixture populations
Migrations: Creating owner
Ghost is running in development...
Listening on 127.0.0.1:2368
Url configured as: http://localhost:2368
Ctrl+C to shut down
GET /ghost/img/ghosticon.jpg 200 8.099 ms - 2499
GET / 200 207.515 ms - -
GET /assets/js/jquery.fitvids.js?v=b509dbeb97 200 4.311 ms - -
GET /assets/css/screen.css?v=b509dbeb97 200 4.538 ms - -
GET /assets/js/index.js?v=b509dbeb97 200 4.215 ms - -
GET /ghost/ 302 10.995 ms - 70
GET /ghost/setup/ 200 1926.452 ms - -
GET /ghost/vendor.css?v=b509dbeb97 200 6.638 ms - -
GET /ghost/ghost.css?v=b509dbeb97 200 5.145 ms - -
GET /ghost/ghost.js?v=b509dbeb97 200 1.179 ms - -
GET /ghost/vendor.js?v=b509dbeb97 200 2.849 ms - -

ERROR: Request for version 0.9 does not match current version 0.10.

 Error
    at Error.VersionMismatchError (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\ghost\core\server\errors\version-mismatch-error.js:6:18)
    at checkVersionMatch (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\ghost\core\server\middleware\api\version-match.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\express\lib\router\index.js:271:10)
    at module.exports (C:\Users\krok\Documents\GitHub\ghost-0-10-test\node_modules\ghost\core\server\middleware\maintenance.js:12:5)
```

**Comment by kirrg001** [comment]
hey @krokofant Sorry to hear you are having trouble.
We have published a new npm version (`0.10.0-rc1`), this should fix your issue (i've tested it).
You can reopen this issue, if you still have problems.
