### ISSUE TITLE
Migration error:

### ISSUE THREAD

**Issue by sp90** [TryGhost/Ghost#7349]
### Issue Summary

This is a basic migration issue when i start the project

### Steps to Reproduce

1. node index.js

### Error output:

```
Migrations: Creating database backup

ERROR: undefined is not a function 
 
 TypeError: undefined is not a function
    at settingsFilter (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:215:37)
    at getSettingsResult (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:357:44)
    at /root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:372:24
    at tryCatcher (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17) 

Unhandled rejection TypeError: undefined is not a function
    at settingsFilter (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:215:37)
    at /root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

Unhandled rejection TypeError: undefined is not a function
    at settingsFilter (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:215:37)
    at /root/live/test-ghost/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/live/test-ghost/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

Migrations: Database backup written to: /root/live/test-ghost/content/data/ghost.2016-09-09.json
Migrations: Migration required from 006 to 007
Migrations: No tasks found for version
Migrations: Updating database to 007
Migrations: Running fixture updates
Skipping Migrations: rolling back because of: undefined
```

### Technical details:

* Ghost Version: 0.9.0 -> 0.10.1
* Node Version: 0.12.7
* Browser/OS: ...
* Database: sqlite 3.1.4

**Comment by ErisDS** [comment]
Hi there @sp90. That looks like the same problem as reported in #7336. You can also find a workaround there :)
