### ISSUE TITLE
Upgrading from 0.10.1 to 0.11

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Ghost#7392]
I am trying to upgrade Ghost from 0.10.1 to 0.11. I have removed `node_modules` before doing this upgrade.

I get the following error:

```
npm WARN cannot run in wd ghost@0.11.0 node core/server/utils/npm/preinstall.js (wd=/var/www/ghost)

> jsonpath@0.2.6 postinstall /var/www/ghost/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


Killed
```

nodejs version - v4.5.0

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'stop', '--production' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose stack Error: missing script: stop
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /var/www/ghost
6 error Linux 3.13.0-85-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "stop" "--production"
8 error node v4.5.0
9 error npm  v2.15.9
10 error missing script: stop
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Any idea on what went wrong?

**Comment by ErisDS** [comment]
Hi @akshaybabloo, sorry you're having trouble. This is an npm/server issue rather than a Ghost issue - your server is running out of memory. Please see the replies here for possible solutions: https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what

If you have questions or need more help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by akshaybabloo** [comment]
Figured it out. There was a problem while copying `core` directory.
