### ISSUE TITLE
after setup can not login

### ISSUE THREAD

**Issue by chinakids** [TryGhost/Ghost#7408]
Just like #6043 ，but I do not see any solutions

```
ERROR: Client Authentication Failed
 Client credentials were not valid
 For information on how to fix this, please read http://api.ghost.org/docs/client-authentication.


ERROR: Access denied.

 Error
    at Error.UnauthorizedError (/home/admin/polymerization-wiki/target/polymerization-wiki/core/server/errors/unauthorized-error.js:6:18)
    at authenticate (/home/admin/polymerization-wiki/target/polymerization-wiki/core/server/middleware/auth.js:74:50)
    at allFailed (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/passport/0.3.2/passport/lib/middleware/authenticate.js:98:18)
    at attempt (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/passport/0.3.2/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/passport/0.3.2/passport/lib/middleware/authenticate.js:284:9)
    at verified (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/passport-oauth2-client-password/0.1.2/passport-oauth2-client-password/lib/strategy.js:49:32)
    at then (/home/admin/polymerization-wiki/target/polymerization-wiki/core/server/middleware/auth-strategies.js:24:24)
    at tryCatcher (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/admin/polymerization-wiki/target/polymerization-wiki/node_modules/.npminstall/bluebird/2.11.0/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:490:17)
```

**Comment by chinakids** [comment]
version 0.11

**Comment by chinakids** [comment]
on my other server is normal,i think i need help..wow

**Comment by ErisDS** [comment]
Hi @chinakids, sorry to hear you're having trouble. 

It seems like something went wrong during your installation process, but it's not possible for us to debug this without more information.

As mentioned in the readme & contrib guide, if you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
