### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by tim-steele** [TryGhost/Ghost#7433]
*UPDATE:* I changed to 0.11.0 version of Ghost and this error disappeared.

In Mac OS X, when trying to start Ghost as an NPM module following [these instructions](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-npm-module) - I am seeing a SQLite issue. I have SQLite and it is working running. Has anyone else seen this error with Ghost?

Node: 4.4.7
Ghost: 1.0.0-alpha.1

```
Knex:warning` - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - Error: SQLITE_CANTOPEN: unable to open database file
Unhandled rejection Error: Pool was destroyed
    at Pool._destroyPool (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/node_modules/pool2/lib/pool.js:560:20)
    at Pool.<anonymous> (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/node_modules/pool2/lib/pool.js:474:18)
    at Pool.<anonymous> (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/node_modules/pool2/lib/pool.js:517:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Client.acquireConnection (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/client.js:216:12)
    at /Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/runner.js:137:23
From previous event:
    at /Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/runner.js:136:35
From previous event:
    at Runner.ensureConnection (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/runner.js:135:26)
    at Runner.run (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/runner.js:29:31)
    at SchemaBuilder.Target.then (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/knex/lib/interface.js:26:43)
    at Object.getDatabaseVersion (/Users/tsteele/Sites/academy/academy/node_modules/ghost/core/server/data/schema/versioning.js:26:48)
    at Object.bootUp (/Users/tsteele/Sites/academy/academy/node_modules/ghost/core/server/data/schema/bootup.js:8:10)
    at /Users/tsteele/Sites/academy/academy/node_modules/ghost/core/server/index.js:80:19
    at tryCatcher (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._filter (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/tsteele/Sites/academy/academy/node_modules/ghost/node_modules/bluebird/js/release/promise.js:431:57)
```

**Comment by kirrg001** [comment]
Hey @tim-steele Sorry to hear you are having trouble.

Someone had this problem in the past, see https://github.com/TryGhost/Ghost/issues/1568
I assume this is a local problem, so will close this issue.

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
