### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by zhangyanglogin** [TryGhost/Ghost#7449]
when i run " npm start --production",the ghost is not running.have this error:

```
> ghost@0.10.1 start /root/ghost
> node index

WARNING: Ghost is attempting to use a direct method to send email.
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.


ERROR: Cannot read property 'zone' of undefined

 TypeError: Cannot read property 'zone' of undefined
    at Object.isTimezone (/root/ghost/core/server/data/validation/index.js:42:21)
    at Object.validator.(anonymous function) [as isTimezone] (/root/ghost/core/server/data/validation/index.js:28:19)
    at each (/root/ghost/core/server/data/validation/index.js:188:39)
    at /root/ghost/node_modules/.3.10.1@lodash/index.js:2874:23
    at /root/ghost/node_modules/.3.10.1@lodash/index.js:3073:15
    at baseForOwn (/root/ghost/node_modules/.3.10.1@lodash/index.js:2046:14)
    at /root/ghost/node_modules/.3.10.1@lodash/index.js:3043:18
    at Function.<anonymous> (/root/ghost/node_modules/.3.10.1@lodash/index.js:3346:13)
    at validate (/root/ghost/core/server/data/validation/index.js:175:7)
    at Object.validateSettings (/root/ghost/core/server/data/validation/index.js:123:52)
    at then (/root/ghost/core/server/models/settings.js:80:31)
    at tryCatcher (/root/ghost/node_modules/.3.4.6@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/root/ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/root/ghost/node_modules/.3.4.6@bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/root/ghost/node_modules/.3.4.6@bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/ghost/node_modules/.3.4.6@bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

> Technical details:
> Ghost Version: 0.11
> Ghost Version: 0.10.1

**Comment by kevinansfield** [comment]
Hey @zhangyanglogin, sorry to hear you're having issues 😞 Unfortunately we can't provide support here on Github - we use it exclusively for tracking bugs and on-going development. If you swing by the #help channel on [our slack team](https://ghost.org/slack) you can get support from the community to help diagnose your install issue. If it turns out there is an actual bug then we can re-open this issue.

**Comment by aid414944** [comment]
You can try change fourth line text, from "moment = require('moment')" to "moment = require('moment-timezone')" in /ghost/core/server/data/validation/index.js file.

**Comment by LeoAnd95** [comment]
Thanks a lot
