### ISSUE TITLE
Upgrading from 0.11.0 to 0.11.2

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Ghost#7578]
I was trying to upgrade Ghost 0.11.0 to Ghost 0.11.2, it seems to install well, but when I do `npm start --production` I get the following error:

```
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/var/www/ghost/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/ghost/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Client_SQLite3._driver (/var/www/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/var/www/ghost/node_modules/knex/lib/client.js:211:26)
    at Client_SQLite3.Client (/var/www/ghost/node_modules/knex/lib/client.js:105:10)
    at new Client_SQLite3 (/var/www/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
    at Knex (/var/www/ghost/node_modules/knex/lib/index.js:60:34)

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--production"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.11.2 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ghost@0.11.2 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ghost/npm-debug.log
```

here is the debug file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start', '--production' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ghost@0.11.2
6 info start ghost@0.11.2
7 verbose unsafe-perm in lifecycle true
8 info ghost@0.11.2 Failed to exec start script
9 verbose stack Error: ghost@0.11.2 start: `node index`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ghost@0.11.2
11 verbose cwd /var/www/ghost
12 error Linux 4.4.0-38-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--production"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error ghost@0.11.2 start: `node index`
17 error Exit status 1
18 error Failed at the ghost@0.11.2 start script 'node index'.
18 error This is most likely a problem with the ghost package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ghost
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ghost
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

It looks like there seems to be an error in `npm WARN cannot run in wd ghost@0.11.2 node core/server/utils/npm/preinstall.js (wd=/var/www/ghost)` while installing.

**Comment by akshaybabloo** [comment]
#7575 seems to have the same problem.

**Comment by kirrg001** [comment]
Hey @akshaybabloo Sorry to hear you are having trouble.
But can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
