### ISSUE TITLE
TMPDir Error

### ISSUE THREAD

**Issue by alexkadis** [TryGhost/Ghost#7741]
### Issue Summary

Hosted at [A Small Orange,](https://asmallorange.com/) on shared Linux GNU.

When installing Ghost, or updating to the latest version, an error occurs:
```node
/home/user/ghost/node_modules/multer/node_modules/mkdirp/index.js:90
                    throw err0;
                          ^
Error: EACCES, permission denied '/root/tmp'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Function.sync (/home/user/ghost/node_modules/multer/node_modules/mkdirp/index.js:71:13)
    at new DiskStorage (/home/user/ghost/node_modules/multer/storage/disk.js:21:12)
    at module.exports (/home/user/ghost/node_modules/multer/storage/disk.js:65:10)
    at new Multer (/home/user/ghost/node_modules/multer/index.js:15:20)
    at multer (/home/user/ghost/node_modules/multer/index.js:92:12)
    at Object.<anonymous> (/home/user/ghost/core/server/middleware/index.js:45:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/user/ghost/core/server/index.js:24:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

### Steps to Reproduce

1. [Follow ASO's instructions here](https://kb.asmallorange.com/customer/en/portal/articles/1603398-install-or-update-ghost) on installing/updating Ghost.
2. Receive the error above from Passenger 

### Workaround
1. Edit .htaccess, add these lines:
```apache
SetEnv TMPDIR /home/user/ghost/tmp # Force Ghost to use the local tmp directory
SetEnv GHOST_NODE_VERSION_CHECK false # Once fix is done above, Ghost complains that Node is the wrong version (it isn't), so override that error.
```

My full .htaccess for reference:
```apache
RewriteEngine off

PassengerEnabled on
PassengerAppRoot /home/user/ghost
SetEnv NODE_ENV production
SetEnv NODE_PATH /usr/lib/node_modules
SetEnv TMPDIR /home/user/ghost/tmp
SetEnv GHOST_NODE_VERSION_CHECK false
```

### Technical details:

* Ghost Version: v0.11.3
* Node Version: 6.9.1
* Browser/OS: Linux/GNU
* Database: MySQL

**Comment by kirrg001** [comment]
Hey @alexkadis Sorry to hear you are having trouble.

This does not look like a Ghost issue. 

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
