### ISSUE TITLE
Ghost v0.11.3 cannot start 

### ISSUE THREAD

**Issue by ryanivanka** [TryGhost/Ghost#7745]
### Issue Summary

I'm using Redhat to install ghost, npm 3.9.6, nodejs 4.2.0. 
My enviroment using openshift container, with ghost and nodejs supported. I have a ghost 0.9.0 running successfully on node 0.10.0 on same env. But after 0.11.3 version, it throw exception when starts.

But node start will have exception.

### Steps to Reproduce
download ghost 0.11.3 version, npm install --production, and node index, 

Here comes the exception from bluebird:

```
 ERROR: _.toPairs is not a function 
 
 TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at getSettingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:357:44)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:372:24
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17) 
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Migrations: Database backup written to: /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/content/data/ghost.2016-11-22.json
Migrations: Migration required from 006 to 007
Migrations: No tasks found for version
Migrations: Updating database to 007
Migrations: Running fixture updates
Skipping Migrations: rolling back because of: undefined
Migrations: Creating database backup
ERROR: _.toPairs is not a function 
 
 TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at getSettingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:357:44)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:372:24
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17) 
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Migrations: Database backup written to: /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/content/data/ghost.2016-11-22.json
Migrations: Migration required from 006 to 007
Migrations: No tasks found for version
Migrations: Updating database to 007
Migrations: Running fixture updates
Skipping Migrations: rolling back because of: undefined
Migrations: Creating database backup
ERROR: _.toPairs is not a function 
 
 TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at getSettingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:357:44)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:372:24
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17) 
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Unhandled rejection TypeError: _.toPairs is not a function
    at settingsFilter (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:112:35)
    at settingsResult (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:215:37)
    at /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/core/server/api/settings.js:361:28
    at tryCatcher (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Migrations: Database backup written to: /var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/content/data/ghost.2016-11-22.json
Migrations: Migration required from 006 to 007
Migrations: No tasks found for version
Migrations: Updating database to 007
Migrations: Running fixture updates
Skipping Migrations: rolling back because of: undefined
Unhandled rejection Error: ENOENT: no such file or directory, scandir '/var/lib/openshift/5834779789f5cf76f8000103/app-root/runtime/repo/content/themes'
    at Error (native)
```

### Technical details:

* Ghost Version: 0.11.3
* Node Version:4.2.0
* Browser/OS: Redhat on openshift
* Database: mysql

**Comment by acburdine** [comment]
@ryanivanka This is due to a npm install issue.

The fix for it is to remove your node modules folder and reinstall - `rm -rf node_modules && npm install --production`

If you have further issues please visit our [slack channel](https://ghost.org/slack). Thanks! 😄

**Comment by ryanivanka** [comment]
I ```rm -rf node_modules && npm install --production``` already, but still met this issue. And since slack channel requires a email with @ghost.org, I'm not invited in Ghost group, so I cannot post there.
