### ISSUE TITLE
Unauthorized issue and many 404 error when changing theme and enable public API on ghost 0.11.3

### ISSUE THREAD

**Issue by ryanivanka** [TryGhost/Ghost#7756]
I don't have invitation on slack for ghost group, so I have to post here. 

### Issue Summary

After I update my ghost to latest 0.11.3, I keep seeing error message in admin page showing page not found, and get 404 error for each /ghost/api/v0.1/* api.

Please go to this link for screenshot: [image](http://ryanivanka.info/content/images/2016/11/Screen-Shot-2016-11-30-at-11-55-29.png)

### Steps to Reproduce

1. login ghost admin page
2. enable public api in lab tab
3. update theme and try to active the theme
4. add a post also get 404 response.

Log for unauthorized:

```
45.34.23.99 - - [30/Nov/2016:04:51:50 +0000] "POST /ghost/api/v0.1/settings/ HTTP/1.1" 404 14 "http://latestghost-ryanivanka.rhcloud.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
ERROR: Client Authentication Failed 
 Client credentials were not provided 
 For information on how to fix this, please read http://api.ghost.org/docs/client-authentication. 
ERROR: Access denied. 
 
 Error
    at Error.UnauthorizedError (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/core/server/errors/unauthorized-error.js:6:18)
    at authenticateClient (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/core/server/middleware/auth.js:55:42)
    at Layer.handle [as handle_request] (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/layer.js:95:5)
    at /var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:271:10)
    at checkVersionMatch (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/core/server/middleware/api/version-match.js:17:5)
    at Layer.handle [as handle_request] (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/node_modules/express/lib/router/index.js:271:10)
    at module.exports (/var/lib/openshift/583e48bc2d52715594000064/app-root/runtime/repo/node_modules/ghost/core/server/middleware/maintenance.js:12:5) 
45.34.23.99 - - [30/Nov/2016:04:52:45 +0000] "GET /ghost/api/v0.1/settings/ HTTP/1.1" 401 73 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"

```

Logs for 404 error:

```
45.34.23.99 - - [30/Nov/2016:04:57:54 +0000] "POST /ghost/api/v0.1/posts/2/?include=tags HTTP/1.1" 404 14 "http://latestghost-ryanivanka.rhcloud.com/ghost/editor/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
45.34.23.99 - - [30/Nov/2016:04:57:59 +0000] "POST /ghost/api/v0.1/uploads/ HTTP/1.1" 200 66 "http://latestghost-ryanivanka.rhcloud.com/ghost/editor/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
45.34.23.99 - - [30/Nov/2016:04:58:00 +0000] "GET /content/images/2016/11/Screen-Shot-2016-11-30-at-11.55.29-1.png HTTP/1.1" 200 227040 "http://latestghost-ryanivanka.rhcloud.com/ghost/editor/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
45.34.23.99 - - [30/Nov/2016:04:58:02 +0000] "POST /ghost/api/v0.1/posts/2/?include=tags HTTP/1.1" 404 14 "http://latestghost-ryanivanka.rhcloud.com/ghost/editor/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
```
### Technical details:

* Ghost Version: 0.11.3
* Node Version: 3.9.6
* Browser: Mac os
* OS: Ghost is deployed on Redhat
* Database: mysql

**Comment by kirrg001** [comment]
Hey @ryanivanka . This does not sound like a Ghost bug. Sounds more like an update issue.

Can you follow our [update instructions](http://support.ghost.org/how-to-upgrade/)?
Ensure you always keep a backup of your database. If this turns out to be an actual issue with Ghost this issue can be reopened.
