### ISSUE TITLE
Bug: Password authentication failed for PostgreSQL

### ISSUE THREAD

**Issue by ChasonTang** [TryGhost/Ghost#7815]
### Issue Summary
After upgrading node version 6.0,the Ghost failed with authentication error.
Here is message I got(in production):
```
ERROR: password authentication failed for user "ghost" 
 
 error: password authentication failed for user "ghost"
    at Connection.parseE (/home/ghost/node_modules/.4.1.1@pg/lib/connection.js:534:11)
    at Connection.parseMessage (/home/ghost/node_modules/.4.1.1@pg/lib/connection.js:361:17)
    at TLSSocket.<anonymous> (/home/ghost/node_modules/.4.1.1@pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
```
### Steps to Reproduce

1. config.js
```
database: {
        client: 'pg',
        connection: {
                host     : 'localhost',
                user     : 'ghost',
                password : 'ghost',
                database : 'ghost',
                charset  : 'utf8',
                ssl      : true
        },
}
```
2. `npm install`
3. got error in development mode
```
error: password authentication failed for user "ghost"
    at Connection.parseE (/Users/ChasonTang/Downloads/Ghost/node_modules/.4.1.1@pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/ChasonTang/Downloads/Ghost/node_modules/.4.1.1@pg/lib/connection.js:361:17)
    at TLSSocket.<anonymous> (/Users/ChasonTang/Downloads/Ghost/node_modules/.4.1.1@pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.7@bluebird/js/release/debuggability.js:397:19)
    at Function.Promise.attempt.Promise.try (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.7@bluebird/js/release/method.js:29:9)
    at Runner.ensureConnection (/Users/ChasonTang/Downloads/Ghost/node_modules/.0.12.5@knex/lib/runner.js:197:34)
    at Runner.run (/Users/ChasonTang/Downloads/Ghost/node_modules/.0.12.5@knex/lib/runner.js:47:42)
    at SchemaBuilder.Target.then (/Users/ChasonTang/Downloads/Ghost/node_modules/.0.12.5@knex/lib/interface.js:35:43)
    at Object.getDatabaseVersion (/Users/ChasonTang/Downloads/Ghost/core/server/data/schema/versioning.js:26:48)
    at /Users/ChasonTang/Downloads/Ghost/core/server/index.js:86:27
    at tryCatcher (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/ChasonTang/Downloads/Ghost/node_modules/.3.4.6@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

### Resolution

I found same issue in https://github.com/tgriesser/knex/issues/1371, This is the problem in pg, so just upgrade pg dependency to 4.5.5,it's ok

### Technical details

* Ghost Version: 0.11.3
* Client OS: macOS10.12
* Server OS: CentOS7.3
* Node Version: 6.9.1(Server), 6.9.2(Client)
* Browser: Chome
* Database: PostgreSQL 9.5.2

**Comment by ChasonTang** [comment]
pg upgrade to latest version(6.1.2) is ok

**Comment by acburdine** [comment]
@ChasonTang the reason it hasn't been updated is afaik because there hasn't been demand for it, and in the 1.0 alpha series of builds for Ghost we dropped support for postgresql altogether (see the reasoning [here](https://dev.ghost.org/dropping-support-for-postgresql/)).

If you want - you should just be able to manually upgrade postgres on your installation of Ghost by using `npm install --save pg@latest`. However, I'm going to close this unless there's enough reason to update it, and even then it would only be for the LTS releases of Ghost.

**Comment by ErisDS** [comment]
A PR to upgrade pg on the `lts` branch would be welcomed 😉

**Comment by ChasonTang** [comment]
i got it.A PR will make.
