### ISSUE TITLE
Facing problem while switching from Native to WebView in appium

### ISSUE THREAD

**Issue by ankitgupta0304** [TryGhost/Ghost#7828]
While switching to WebView Appium are unable to find the element:

[debug] [ADB] Running '/Users/ankit.gupta04/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","fb04e45f","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 30075 pkg: com.xxx.main!
[debug] [AndroidDriver] from: u0_a271,30075,331,2182724,268720,ffffffff,00000000,S,com.xxx.main
[debug] [AndroidDriver] returning process name: com.xxx.main
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.xxx.main"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.xxx.main"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.xxx.main'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.3\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.xxx.main","androidUseRunningApp":true,"androidDeviceSerial":"fb04e45f"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fd1d1a28b919c2842c7fc0a72a5ca27e","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"55.0.2883.91","webStorageEnabled":true}}
[debug] [Chromedriver] Changed state to 'online'
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/context 200 1976 ms - 76 
[HTTP] --> GET /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["dc49fb82-611b-4a61-95dc-e1231815c1f5"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_com.xxx.main"
[HTTP] <-- GET /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/context 200 6 ms - 99 
WEBVIEW_com.xxx.main
Switched to WEBVIEW_com.xxx.main
[HTTP] --> GET /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["dc49fb82-611b-4a61-95dc-e1231815c1f5"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_com.xxx.main"
[HTTP] <-- GET /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/context 200 7 ms - 99 
WEBVIEW_com.xxx.main
[HTTP] --> POST /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/element {"using":"xpath","value":"//div[@class='address-section']//p[contains(text(),'blastandroid')]"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/element] to [POST http://127.0.0.1:8000/wd/hub/session/fd1d1a28b919c2842c7fc0a72a5ca27e/element] with body: {"using":"xpath","value":"//div[@class='address-section']//p[contains(text(),'blastandroid')]"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fd1d1a28b919c2842c7fc0a72a5ca27e","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@class='address-section']//p[contains(text(),'blastandroid')]\"}\n  (Session info: chrome=55.0.2883.91)\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.3 x86_64)"}}
[JSONWP Proxy] Replacing sessionId fd1d1a28b919c2842c7fc0a72a5ca27e with dc49fb82-611b-4a61-95dc-e1231815c1f5
[HTTP] <-- POST /wd/hub/session/dc49fb82-611b-4a61-95dc-e1231815c1f5/element 200 332 ms - 394 
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='address-section']//p[contains(text(),'blastandroid')]"}
  (Session info: chrome=55.0.2883.91)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 349 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'AnkitGupta04.local', ip: '10.20.86.78', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_101'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.xxx.main, app=/Users/ankit.gupta04/Documents/Automation/xxx-ios-automation/TestSnapdealAutomation/app/xxx-universal-debug6.2.5.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=fb04e45f, platform=LINUX, deviceUDID=fb04e45f, appActivity=com.xxx.ui.material.activity.MaterialMainActivity, desired={appPackage=com.xxx.main, app=/Users/ankit.gupta04/Documents/Automation/xxx-ios-automation/TestxxxAutomation/app/Snapdeal-universal-debug6.2.5.apk, appActivity=com.xxx.ui.material.activity.MaterialMainActivity, newCommandTimeout=60000, platformVersion=5.1.5, browserName=, platformName=Android, udid=fb04e45f, deviceName=MI}, newCommandTimeout=60000, platformVersion=5.0.2, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, platformName=Android, udid=fb04e45f}]
Session ID: dc49fb82-611b-4a61-95dc-e1231815c1f5
*** Element info: {Using=xpath, value=//div[@class='address-section']//p[contains(text(),'blastandroid')]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:132)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at mobileAutomation.androidApp.pages.ShippingPage.verifyPrimaryAddress(ShippingPage.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mobileAutomation.master.Page.pageExecutor(Page.java:92)
	at mobileAutomation.testCases.Buy_Flow.BuyFlow_Android_LLD.verifyAddress(BuyFlow_Android_LLD.java:676)
	at mobileAutomation.testCases.Buy_Flow.BuyFlow_Android_LLD.buy_AutoSuggestor_Guest_COD(BuyFlow_Android_LLD.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mobileAutomation.testCases.Buy_Flow.BuyFlow_Android_LLD.script(BuyFlow_Android_LLD.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mobileAutomation.master.TestCase.testCaseExecutor(TestCase.java:2680)
	at mobileAutomation.testSuites.BuyFlowSuit.flow(BuyFlowSuit.java:222)
	at mobileAutomation.testSuites.BuyFlowSuit.run(BuyFlowSuit.java:182)

### Steps to Reproduce

1. Switching app from NativeView to WebView using driver.setContext()
2. After switching to WebView, Responding to client with driver.getCurrentContext() result: "WEBVIEW_com.xxx.main"
3.  But it still could not find the Element.
4. Android version 6.1.0
5. And in the apk code 
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
			WebView.setWebContentsDebuggingEnabled(true);
		}
Code has also put.

### Technical details:

*  OS:  MAC 
* Node Version: latest
* Browser/OS: Android, 6.1, 
* Appium: 1.6.3 latest

**Comment by kevinansfield** [comment]
Hey @ankitgupta0304, what exactly are you trying to do? This doesn't seem like it's related to Ghost at all.

I'm going to close this as I can't see any bug in Ghost itself and we don't have any mobile apps so I'm not sure what this is relating to. If you are trying to do something with Ghost please head over to our [slack community](https://slack.ghost.org) and post in the #help channel, thanks 😄

**Comment by ankitgupta0304** [comment]
@kevinansfield I am trying to switch my Appium driver from NATIVE to WebView.
While setting the WebContext i am getting
[debug] [Chromedriver] Changed state to 'online'
[debug] [MJSONWP] Responding to client with driver.setContext() result: null

But both VIews are available:
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.xxx.main"]

**Comment by kevinansfield** [comment]
@ankitgupta0304 still, you haven't explained how that has anything to do with this project, are you sure you've opened the issue in the right place? This is the bug tracker for the [Ghost](https://ghost.org) blogging app/platform, we don't have any mobile apps and can't provide support for Appium here.

**Comment by ankitgupta0304** [comment]
@kevinansfield Ohoo Sorry, by mistaken i posted on wrong page.
