### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by 20Fourteen** [TryGhost/Ghost#7847]
Hi, I'm facing a very weird issue and cannot figure out how to fix it.

I've tried setting the email to SendGrid, Gmail and Sendmail (php) but nothing works the node app crashes and I have to restart Ghost, here is the log.

    ERROR: AuthError: Invalid login - 535 Incorrect authentication data 
     
     Error
        at Error.EmailError (/home/xxxx/public_html/xxxx/core/server/errors/email-error.js:6:18)
        at /home/xxxx/public_html/xxxx/core/server/api/mail.js:41:31
        at tryCatcher (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/xxxx/public_html/xxxx/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17) 
    
     "POST /xxxx/ghost/api/v0.1/mail/test/ HTTP/1.1" 500 112 "https://xxxx/xxxx/ghost/settings/labs/" 
    events.js:141
      throw er; // Unhandled 'error' event
      ^
    
    Error: 140125754959648:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:
    
    at Error (native)`

This is my config with Gmail (at the moment).

    config = {

    production: {
        url: 'https://xxxx.xxx',
        mail: {
            transport: 'SMTP',
            options: {
                service: 'Gmail',
                auth: {
                    user: 'xxxx@gmail.com',
                    pass: 'xxxx'
                }
            }
        },
        database: {

I'm on A2 shared hosting which supports node, I installed Ghost via softaculous.

Any ideas or pointers where I should be looking?

**Many thanks**

**Comment by acburdine** [comment]
Hey @20Fourteen, sorry to hear you're having trouble!

It appears the login credentials are wrong in the snippet you posted. I know that if you have two factor authentication on a gmail account you have to set up mail using an app password. 

If you have further issues, can you swing by our [slack channel](https://slack.ghost.org) and ask for help there? We can provide better help there that we can't do in the GitHub issue tracker. Thanks! 😄
