### ISSUE TITLE
Unhandled rejection TypeError:

### ISSUE THREAD

**Issue by vijaycs** [TryGhost/Ghost#7990]
Hi,

I'm invoking sitespeed.io by run method. Please find the code below,

  Sitespeed.run({
  urls: ['https://www.sitespeed.io'],

	depth: 0,
	browsertime: {
    browser: 'chrome',
		connectivity: 'cable',
		iterations: 2,
  }
  }) 

Taken reference from https://github.com/dreamzmaster/gulp-sitespeedio. 

Its launching the given url in the browser and running for given number of iteration but I'm getting below error.

TypeError: /Users/***/node_modules/sitespeed.io/lib/plugins/html/templates/pages.pug:8
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://www.sitespeed.io' of undefined
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://www.sitespeed.io' of undefined
    at Object.eval (eval at wrap (/Users/**/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:144:31)
    at Object.pug_interp [as rows] (eval at wrap (/Users/**/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:4)
    at eval (eval at wrap (/Users/**/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:320:19)
    at template (eval at wrap (/Users/**/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:184)
    at Object.renderTemplate (/Users/**/node_modules/sitespeed.io/lib/plugins/html/renderer.js:28:37)
    at HTMLBuilder._renderSummaryPage (/Users/**/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:196:67)
    at Object.keys.map (/Users/**/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:27)
    at Array.map (native)
    at HTMLBuilder.render (/Users/**/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:8)
    at Object.close (/Users/**/node_modules/sitespeed.io/lib/plugins/html/index.js:26:29)
    at Promise.resolve.filter.map (/Users/**/node_modules/sitespeed.io/lib/sitespeed.js:43:49)
    at tryCatcher (/Users/**/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/**/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/**/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/Users/**/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/Users/**/node_modules/bluebird/js/release/map.js:30:10)

I'm breaking my head for a week to resolve this issue. 

Could you help me understand the issue and provide me the solutions.

**Comment by kevinansfield** [comment]
Hey @vijaycs, sorry to hear you are having problems but have you opened this issue on the right project? This the github page for Ghost (the blogging platform) but your issue seems to be about sitespeed.io, did you mean to open the issue on [their repo](https://github.com/sitespeedio/sitespeed.io)?

I'm going to close this for now as it doesn't appear to have any relation to our project. If there's something particular with Ghost that you are trying to do please head over to our [Slack channel](https://slack.ghost.org) where the community can help - if as a result of that a bug in Ghost itself is found we can open a new issue. Thanks 😄
