### ISSUE TITLE
You do not have permission to dismiss this notification

### ISSUE THREAD

**Issue by nodesocket** [TryGhost/Ghost#8116]
Digging through my Node.js error log and seeing:

````
ERROR: You do not have permission to dismiss this notification.

 Error
    at Error.NoPermissionError (/home/node/blog.mydomain.net/core/server/errors/no-permission-error.js:6:18)
    at destroyNotification (/home/node/blog.mydomain.net/core/server/api/notifications.js:169:21)
    at runTask (/home/node/blog.mydomain.net/core/server/utils/pipeline.js:16:24)
    at /home/node/blog.mydomain.net/core/server/utils/pipeline.js:26:20
    at tryCatcher (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/node/blog.mydomain.net/node_modules/bluebird/js/release/promise.js:567:18)
````

What is this related to?

**Node**: v6.10.0
**Ghost**: 0.11.4

**Comment by kirrg001** [comment]
Hey @nodesocket 👋 Sorry to hear you are having trouble.

It's possible that notifications can be dismissible.

Do you remember what you did to get this error?Steps to reproduce?
Did you upgrade Ghost before you were getting this error?

**Comment by nodesocket** [comment]
My question is that I am not sure I was the one who triggered it. Wondering if a malicious user may have found a security vulnerability? Also, this goes to `stderr` and seems to indicate a node crash right.

**Comment by kirrg001** [comment]
> Also, this goes to stderr and seems to indicate a node crash right?

This error is handled, Ghost won't crash.

> My question is that I am not sure I was the one who triggered it. Wondering if a malicious user may have found a security vulnerability?

No i don't think so. This error can happen if somebody tries to delete a notification, which is not dismissible. To be able to delete a notification the requester need's to pass the authentication.
This error is either a bug or a normal behaviour depending on the use case.

**Comment by kirrg001** [comment]
We can re-open this issue if it turns out it's a bug. Closing for now.

**Comment by ston3o** [comment]
I have the same error:

```
ERROR [2017-09-26 12:37:34] "DELETE /ghost/api/v0.1/notifications/59ca49f0af492e00017d2fb5/" 403 115ms           

NAME: NoPermissionError     
MESSAGE: You do not have permission to dismiss this notification.                                                

level:normal                

NoPermissionError: You do not have permission to dismiss this notification.                                      
    at new NoPermissionError (/var/lib/ghost/versions/1.9.0/node_modules/ghost-ignition/lib/errors/index.js:108:23)
    at destroyNotification (/var/lib/ghost/versions/1.9.0/core/server/api/notifications.js:165:21)               
    at runTask (/var/lib/ghost/versions/1.9.0/core/server/utils/pipeline.js:16:24)                               
    at /var/lib/ghost/versions/1.9.0/core/server/utils/pipeline.js:26:20                                         
    at tryCatcher (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)                 
    at Object.gotValue (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/reduce.js:157:18)         
    at Object.gotAccum (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/reduce.js:144:25)         
    at Object.tryCatcher (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)          
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18) 
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)       
    at Promise._resolveCallback (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18) 
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)       
    at Promise._resolveCallback (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/lib/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by niranjan94** [comment]
Same issue on Ghost 1.9.0

```
Version: 1.9.0
Environment: production
Database: mysql
Mail: SMTP
```

@kirrg001 I believe this should be opened again

**Comment by kirrg001** [comment]
@niranjan94 

Release notifications **are not dismissible** at the moment. This behaviour exists for a long time now. This will change via #5071 - we overhaul notifications - it's in progress already.

Could you please update to `1.9.1` via the CLI? The blue top bar notification should be gone till the next minor release.

**Comment by niranjan94** [comment]
Okay thanks for the info @kirrg001 😄
