### ISSUE TITLE
[alpha.16] missing files when visiting homepage

### ISSUE THREAD

**Issue by draconus** [TryGhost/Ghost#8187]
### Issue Summary

I've updated Ghost via `ghost update` from alpha.15 to alpha.16 and after using `ghost run` I can open the blog via browser without any errors. However when I look at the log that comes from `ghost run` it shows the errors every time I refresh blog homepage.

```
Error: ENOENT: no such file or directory, open 'core/shared/favicon.ico'
    at Error (native)
...
Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.16/core/built/assets/img/404-ghost.png'
    at Error (native)
...
Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.16/core/built/assets/ghost.min.css'
    at Error (native)
```

### Steps to Reproduce

1. Install Ghost alpha.15 with ghost-cli so that it works
2. Update to alpha.16 using `ghost update`
3. `mysql -u root -p` -> `DROP DATABASE ghost_produciton`
4. `ghost run`
5. Open Ghost homepage via browser
6. See the output from `ghost run`

### Technical details:

* Ghost Version: alpha.16
* Node Version: v6.10.0
* OS: Debian 3.16.39-1+deb8u1
* Database: MariaDB

### Log

```
root@ghost:/var/www/ghost# ghost run
[2017-03-18 21:47:15] INFO Creating table: posts
[2017-03-18 21:47:16] INFO Creating table: users
[2017-03-18 21:47:16] INFO Creating table: roles
[2017-03-18 21:47:17] INFO Creating table: roles_users
[2017-03-18 21:47:17] INFO Creating table: permissions
[2017-03-18 21:47:17] INFO Creating table: permissions_users
[2017-03-18 21:47:18] INFO Creating table: permissions_roles
[2017-03-18 21:47:18] INFO Creating table: permissions_apps
[2017-03-18 21:47:18] INFO Creating table: settings
[2017-03-18 21:47:18] INFO Creating table: tags
[2017-03-18 21:47:19] INFO Creating table: posts_tags
[2017-03-18 21:47:20] INFO Creating table: apps
[2017-03-18 21:47:21] INFO Creating table: app_settings
[2017-03-18 21:47:21] INFO Creating table: app_fields
[2017-03-18 21:47:22] INFO Creating table: clients
[2017-03-18 21:47:23] INFO Creating table: client_trusted_domains
[2017-03-18 21:47:23] INFO Creating table: accesstokens
[2017-03-18 21:47:24] INFO Creating table: refreshtokens
[2017-03-18 21:47:26] INFO Creating table: subscribers
[2017-03-18 21:47:26] INFO Creating table: invites
[2017-03-18 21:47:26] INFO Creating table: brute
[2017-03-18 21:47:26] INFO Model: Post
[2017-03-18 21:47:26] INFO Model: Tag
[2017-03-18 21:47:26] INFO Model: Client
[2017-03-18 21:47:27] INFO Model: Role
[2017-03-18 21:47:27] INFO Model: Permission
[2017-03-18 21:47:28] INFO Model: User
[2017-03-18 21:47:28] INFO Relation: Role to Permission
[2017-03-18 21:47:30] INFO Relation: Post to Tag
[2017-03-18 21:47:30] INFO Relation: User to Role
Currently running Ghost 1.0.0 Alpha, this is NOT suitable for production!
 Please switch to the stable branch.
 More information on the Ghost 1.0.0 Alpha at: https://support.ghost.org/v1-0-alpha

Ctrl+C to shut down
Ghost boot: 2152.210ms
INFO [2017-03-18 21:49:29] "GET /" 200 153ms
INFO [2017-03-18 21:49:29] "GET /assets/css/screen.css?v=964e6432e7" 200 18ms
INFO [2017-03-18 21:49:29] "GET /assets/js/jquery.fitvids.js?v=964e6432e7" 200 25ms
INFO [2017-03-18 21:49:29] "GET /assets/js/index.js?v=964e6432e7" 200 26ms
INFO [2017-03-18 21:49:29] "GET /assets/fonts/casper-icons.woff?v=1" 200 14ms
ERROR [2017-03-18 21:49:30] "GET /favicon.ico" 500 39ms

NAME: InternalServerError
CODE: ENOENT
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost/versions/1.0.0-alpha.16/core/server/errors.js:9:26)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.16/core/server/middleware/error-handler.js:69:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, open 'core/shared/favicon.ico'
    at Error (native)

```

**Comment by draconus** [comment]
Oh and another guy from Slack have the same issue

**Comment by acburdine** [comment]
Can confirm, was seeing this behavior since alpha.16 was released, just kept forgetting to open the issue.

**Comment by kirrg001** [comment]
@kevinansfield The files in the built folder have a hash/timestamp name notation?

**Comment by kevinansfield** [comment]
> @kevinansfield The files in the built folder have a hash/timestamp name notation?

Yes, that's expected because we've switched from Ghost's `{{asset}}` helper to using ember-cli.

I'm not sure why the `favicon.ico` request is failing (that shouldn't be fine?) but the `404-ghost.png` and `ghost.min.css` errors are already being tracked in https://github.com/TryGhost/Ghost/issues/8126

**Comment by kirrg001** [comment]
> I'm not sure why the favicon.ico request is failing

I will check later 👍
