### ISSUE TITLE
[Alpha.16] Night mode missing CSS file

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8213]
### Issue Summary

After enabling night mode from admin panel Ghost is unable to load any more pages. Admin panel is unavailable. Log shows missing CSS file - "ghost-dark.css".

### Steps to Reproduce

1. `ghost run`
2. Enable night mode from admin menu
3. Observe the `ghost run` output

### Technical details:

Ghost Version: alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB
Browser: Comodo Dragon

### Log
```
INFO [2017-03-22 22:15:25] "GET /ghost/api/v0.1/users/me/?include=roles" 200 107ms
INFO [2017-03-22 22:15:25] "GET /ghost/api/v0.1/settings/?type=blog%2Ctheme%2Cprivate" 200 31ms
INFO [2017-03-22 22:15:25] "GET /ghost/api/v0.1/notifications/" 200 39ms
ERROR [2017-03-22 22:15:25] "GET /ghost/assets/ghost-dark.css" 404 6ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.16/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.16/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.16/core/built/assets/ghost-dark.css'
    at Error (native)
```

**Comment by kevinansfield** [comment]
@PaszaVonPomiot in alpha.16 the admin area should not be requesting `ghost-dark.css` but instead `ghost-dark-2fc41c7109dd317038b46314ed4ac63c.css` - it sounds like your admin JS files may have been cached. Can you try clearing your cache or opening in a different browser?

**Comment by nuclearpengy** [comment]
Night mode is coming; for real... I think I might just cry with joy.

**Comment by PaszaVonPomiot** [comment]
@kevinansfield well I remember I've tried clearing the cache and it didn't work. I also tried to replicate the problem once again so I've dropped the database, removed all files from ghost folder and did `ghost install 1.0.0-alpha.16`. Unfortunately I faced different problem this time exactly like in alpha.17 - #8216.
Those that mean that some files/config from alpha.17 went back to alpha.16?

**Comment by kevinansfield** [comment]
> Those that mean that some files/config from alpha.17 went back to alpha.16?

No, the necessary files are present in the `alpha.16` package on npm. They are called `default.hbs` and `default-prod.hbs` so weren't skipped by the `.npmignore` file.

It sounds like `alpha.16` isn't being installed if you're seeing exactly the same error.

**Comment by PaszaVonPomiot** [comment]
@kevinansfield okay it appears that there was issue with config. I fixed that now. I've tested now on firefox in incognito mode and night mode problem still exists.
![image](https://cloud.githubusercontent.com/assets/5560454/24275060/fc670f12-102c-11e7-878c-070763e2080e.png)

**Comment by PaszaVonPomiot** [comment]
Persists in alpha.18 and error with `ghost-dark.css` appears also right after signing in to admin panel even when night shift mode is disabled.
