### ISSUE TITLE
[Alpha.17] ECONNREFUSED during initial visit to homepage

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8215]
### Issue Summary

After starting Ghost alpha.17 when I open home page for the first time it displays error in the console. This error appears only during first visit and does not reappear.  After restarting Ghost the error will appear once again.

### Steps to Reproduce

1. Install clean Ghost alpha.17 so that it works
2. `ghost run`
3. Open Ghost home page once
4. Check the error in console

### Technical details:

Ghost Version: alpha.17
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB
Browser: Comodo Dragon

### Log

root@ghost:/var/www/ghost# ghost run
Currently running Ghost 1.0.0 Alpha, this is NOT suitable for production!
 Please switch to the stable branch.
 More information on the Ghost 1.0.0 Alpha at: https://support.ghost.org/v1-0-alpha

Ctrl+C to shut down
Ghost boot: 1293.819ms

[2017-03-23 01:07:28] ERROR

NAME: InternalServerError
CODE: ECONNREFUSED
MESSAGE: The server has encountered an error.

level:critical

/ghost/img/ghosticon.jpg
InternalServerError: The server has encountered an error.
    at new InternalServerError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:71:23)
    at ClientRequest.<anonymous> (/var/www/ghost/versions/1.0.0-alpha.17/core/server/utils/image-size-from-url.js:100:27)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

INFO [2017-03-23 01:07:28] "GET /" 200 126ms
INFO [2017-03-23 01:07:28] "GET /assets/css/screen.css?v=9751a65864" 200 11ms
INFO [2017-03-23 01:07:28] "GET /assets/js/jquery.fitvids.js?v=9751a65864" 200 14ms
INFO [2017-03-23 01:07:28] "GET /assets/js/index.js?v=9751a65864" 200 16ms
INFO [2017-03-23 01:07:28] "GET /assets/fonts/casper-icons.woff?v=1" 200 1ms

**Comment by kirrg001** [comment]
Hey 😎 Thanks for reporting!

PR is coming 🚑

**Comment by kirrg001** [comment]
Closing this one to keep Github clean. This bug will be fixed via #8221.
