### ISSUE TITLE
[Alpha.17] Admin panel not available

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8216]
### Issue Summary

Visiting `http://............./ghost/` produces error "404 - Resource could not be found".
Error is different from #8126 

### Steps to Reproduce

1. Install clean Ghost alpha.17
2. Set up config.production.json with password auth
3. Open ghost admin URL

### Technical details:

Ghost Version: alpha.17
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB
Browser: Comodo Dragon

### Log
```
ERROR [2017-03-23 01:22:17] "GET /ghost/" 404 3ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/response.js:998:5)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:433:12)
    at onstat (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:734:26)
    at FSReqWrap.oncomplete (fs.js:123:15)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/server/admin/views/default-prod.html'
    at Error (native)

ERROR [2017-03-23 01:22:17] "GET /ghost/assets/ghost.min.css?v=9751a65864" 404 2ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/built/assets/ghost.min.css'
    at Error (native)

ERROR [2017-03-23 01:22:17] "GET /ghost/assets/img/404-ghost.png?v=9751a65864" 404 7ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/built/assets/img/404-ghost.png'
    at Error (native)
```

**Comment by ReidWeb** [comment]
I can confirm that I am able to reproduce this exact issue, along with another user in the Slack #help channel yesterday.

Technical details:

Ghost Version: alpha.17
Node Version: v4.8.0
OS: MacOS 10.12.3
Database: MySQL
Browser: Google Chrome

**Comment by kevinansfield** [comment]
@PaszaVonPomiot can you check if this file exists for you? `/var/www/ghost/versions/1.0.0-alpha.17/core/server/admin/views/default-prod.html`

I've checked the alpha.17 release zip and that contains the built production files. How did you install/upgrade?

**Comment by joepierce** [comment]
Hello, @PaszaVonPomiot -- here is what I found in that directory
![screen shot 2017-03-23 at 9 05 09 am](https://cloud.githubusercontent.com/assets/8026754/24254225/f207712c-0fa7-11e7-8aee-5ad105e41c7f.png)

**Comment by kevinansfield** [comment]
@joepierce that doesn't look correct, if you're missing the `views` folder there then you seem to be missing the built client files. How did you install/upgrade Ghost?

**Comment by joepierce** [comment]
details:
Ubuntu 16.04.2 LTS
nginx 1.10.0
MariaDB 10.1.22
nodejs 6.10.1
npm 3.10.10
Ghost-CLI Version: 1.0.0-alpha.14
Ghost 1.0.0-alpha.17
Let's Encrypt SSL

**Comment by kevinansfield** [comment]
@joepierce by "how did you install/upgrade Ghost" I mean the steps or commands that you used

**Comment by joepierce** [comment]
Create Server Platform:

Start by creating a new 512 MB DigitalOcean droplet using the Ubuntu 16.04 image.

YourComputer :~ youruser$ ssh root@123.123.123.123

Changing password for root.(current)

UNIX password:Enter new

UNIX password:Retype new UNIX password:

root@yoursite:~# adduser newunixuser

root@yoursite:~# gpasswd -a newunixuser sudo

root@yoursite:~# sudo usermod -a -G www-data newunixuser

root@yoursite:~# curl -sSL https://agent.digitalocean.com/install.sh | sh

root@yoursite:~# exit

YourComputer :~ youruser$ ssh newunixuser@123.123.123.123
Add SWAP file

The 512 MB image times out running the add ghost-cli command without a swap file. If you are using a larger droplet, please omit this step.

newunixuser@yoursite:~$ sudo nginx -t

newunixuser@yoursite:~$ sudo swapon --show

newunixuser@yoursite:~$ free -h

newunixuser@yoursite:~$ df -h

newunixuser@yoursite:~$ sudo fallocate -l 1G /swapfile

newunixuser@yoursite:~$ ls -lh /swapfile

newunixuser@yoursite:~$ sudo chmod 600 /swapfile

newunixuser@yoursite:~$ ls -lh /swapfile

newunixuser@yoursite:~$ sudo mkswap /swapfile

newunixuser@yoursite:~$ sudo swapon /swapfile

newunixuser@yoursite:~$ sudo swapon --show

newunixuser@yoursite:~$ free -h

newunixuser@yoursite:~$ sudo cp /etc/fstab /etc/fstab.bak

newunixuser@yoursite:~$ echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

newunixuser@yoursite:~$ cat /proc/sys/vm/swappiness

newunixuser@yoursite:~$ sudo sysctl vm.swappiness=10

newunixuser@yoursite:~$ sudo nano /etc/sysctl.conf

At the bottom add:

/etc/sysctl.conf

vm.swappiness=10

newunixuser@yoursite:~$ cat /proc/sys/vm/vfs_cache_pressure

newunixuser@yoursite:~$ sudo sysctl vm.vfs_cache_pressure=50

newunixuser@yoursite:~$ sudo nano /etc/sysctl.conf

At the bottom add:

/etc/sysctl.conf

vm.vfs_cache_pressure=50
Install MariaDB

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~# sudo apt-get install software-properties-common

newunixuser@yoursite:~# sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8

newunixuser@yoursite:~# sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/10.1/ubuntu xenial main'

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~# sudo apt install mariadb-server

newunixuser@yoursite:~# sudo mysql_secure_installation

newunixuser@yoursite:~# sudo apt-get upgrade

newunixuser@yoursite:~# sudo apt-get dist-upgrade

newunixuser@yoursite:~# sudo apt-get autoremove

newunixuser@yoursite:~# sudo apt-get autoclean

newunixuser@yoursite:~#  mysql -u root -p

CREATE USER 'nonrootmariauser'@'localhost' IDENTIFIED BY 'xyzabcdefghijklmnopjwZ';

GRANT ALL PRIVILEGES ON * . * TO 'nonrootmariauser'@'localhost' with grant option;

GRANT PROXY ON ''@'' TO 'nonrootmariauser'@'localhost' with grant option;

FLUSH PRIVILEGES;

exit
Install Nginx

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~# sudo apt-get install nginx

newunixuser@yoursite:~# sudo ufw allow 'Nginx HTTP' && sudo ufw allow 'Nginx HTTPS' && sudo ufw allow http && sudo ufw allow https && sudo ufw allow ssh && sudo ufw disable && sudo ufw enable
Install Ghost Apps

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~$ cd ~

newunixuser@yoursite:~$ curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh

newunixuser@yoursite:~$ sudo bash nodesource_setup.sh

newunixuser@yoursite:~$ sudo apt-get install nodejs

newunixuser@yoursite:~# curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

newunixuser@yoursite:~# echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~# sudo apt-get install yarn

newunixuser@yoursite:~# yarn global add ghost-cli

newunixuser@yoursite:~# sudo apt-get update

newunixuser@yoursite:~# npm i -g ghost-cli
Unattended server updates

newunixuser@yoursite:~# sudo nano /etc/apt/apt.conf.d/50unattended-upgrades

Unattended-Upgrade::Allowed-Origins {

"${distro_id}:${distro_codename}-security";

"${distro_id}:${distro_codename}-updates";

};

Unattended-Upgrade::Mail "admin@yoursite.com";

Unattended-Upgrade::Remove-Unused-Dependencies "true";

Unattended-Upgrade::Automatic-Reboot "true";

Unattended-Upgrade::Automatic-Reboot-Time "02:00";

newunixuser@yoursite:~# sudo nano /etc/apt/apt.conf.d/10periodic

APT::Periodic::Update-Package-Lists "1";

APT::Periodic::Download-Upgradeable-Packages "0";

APT::Periodic::AutocleanInterval "7";

APT::Periodic::Unattended-Upgrade "1";
Auto Snapshots

newunixuser@yoursite:~$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

newunixuser@yoursite:~$ sudo \curl -sSL https://get.rvm.io | bash -s stable --rails

newunixuser@yoursite:~$ source /home/newunixuser/.rvm/scripts/rvm

newunixuser@yoursite:~$ sudo wget https://assets.merqlove.ru.s3.amazonaws.com/do_snapshot/do_snapshot.tgz --no-check-certificate

newunixuser@yoursite:~$ sudo tar -xzf do_snapshot.tgz

newunixuser@yoursite:~$ sudo cp -r do_snapshot /usr/local/

newunixuser@yoursite:~$ sudo ln -s /usr/local/do_snapshot/bin/do_snapshot /usr/local/bin/do_snapshot

newunixuser@yoursite:~$ gem install do_snapshot

newunixuser@yoursite:~$ gem install rest-client

newunixuser@yoursite:~$ rvm cron setup

newunixuser@yoursite:~$ do_snapshot --digital-ocean-access-token abcdefghijklmnopqrstuvwxyz0123456789 --only 12345678 -k 3 -c -v

newunixuser@yoursite:~$ crontab -e

03 00 * * *  do_snapshot --digital-ocean-access-token abcdefghijklmnopqrstuvwxyz0123456789 --only 12345678 -k 3 -c -v

newunixuser@yoursite:~$ sudo apt-get upgrade

newunixuser@yoursite:~$ sudo apt-get dist-upgrade

newunixuser@yoursite:~$ sudo apt-get update

newunixuser@yoursite:~$ sudo nginx -t

newunixuser@yoursite:~$ sudo service nginx restart


newunixuser@yoursite:~# sudo rm -rf /var/www/html/index.nginx-debian.html

newunixuser@yoursite:~# cd /var/www/html/

newunixuser@yoursite:/var/www/html# sudo ghost install

**Comment by joepierce** [comment]
that's every step ^^^

**Comment by kevinansfield** [comment]
@acburdine is there any reason you know of that a `ghost-cli` install would miss the built client files?

**Comment by acburdine** [comment]
So I just got around to testing this out, and it looks like what was published to npm as alpha.17 (that's how Ghost-CLI gets the download) did not have the built index.html that Ghost-Admin needs. Something must have gotten borked with how Ghost was last published.

**Comment by acburdine** [comment]
The other errors are caused (I think) because of browser caching.

**Comment by cxxxc3** [comment]
ERROR [2017-03-23 01:22:17] "GET /ghost/" 404 3ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/response.js:998:5)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:433:12)
    at onstat (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/send/index.js:734:26)
    at FSReqWrap.oncomplete (fs.js:123:15)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/server/admin/views/default-prod.html'
    at Error (native)

ERROR [2017-03-23 01:22:17] "GET /ghost/assets/ghost.min.css?v=9751a65864" 404 2ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/built/assets/ghost.min.css'
    at Error (native)

ERROR [2017-03-23 01:22:17] "GET /ghost/assets/img/404-ghost.png?v=9751a65864" 404 7ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.17/core/server/middleware/error-handler.js:65:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.17/node_modules/express/lib/router/index.js:275:10)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/1.0.0-alpha.17/core/built/assets/img/404-ghost.png'
    at Error (native)
