### ISSUE TITLE
[Alpha.18] IMAGE_SIZE error on homepage

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8268]
### Issue Summary

Opening homepage works fine but log displays IMAGE_SIZE error.

### Steps to Reproduce

1. `ghost update` from alpha.17 to alpha.18
2. `ghost run`
3. Open homepage

### Technical details:

Ghost Version: alpha.18
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon

### Log
```
root@ghost:/var/www/ghost# ghost run
Currently running Ghost 1.0.0 Alpha, this is NOT suitable for production!
 Please switch to the stable branch.
 More information on the Ghost 1.0.0 Alpha at: https://support.ghost.org/v1-0-alpha

Ctrl+C to shut down
Ghost boot: 1444.378ms
[2017-04-04 16:13:25] ERROR

NAME: InternalServerError
CODE: IMAGE_SIZE
MESSAGE: The server has encountered an error.

level:critical

/ghost/img/ghosticon.jpg
InternalServerError: The server has encountered an error.
    at new InternalServerError (/var/www/ghost/versions/1.0.0-alpha.18/node_modules/ghost-ignition/lib/errors/index.js:71:23)
    at IncomingMessage.<anonymous> (/var/www/ghost/versions/1.0.0-alpha.18/core/server/utils/image-size-from-url.js:85:35)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

INFO [2017-04-04 16:13:25] "GET /" 200 116ms
INFO [2017-04-04 16:13:25] "GET /assets/css/screen.css?v=74749e4110" 200 8ms
INFO [2017-04-04 16:13:25] "GET /assets/js/jquery.fitvids.js?v=74749e4110" 200 5ms
INFO [2017-04-04 16:13:25] "GET /assets/js/index.js?v=74749e4110" 200 12ms
INFO [2017-04-04 16:13:25] "GET /assets/fonts/casper-icons.woff?v=1" 200 2ms
```

###

**Comment by kirrg001** [comment]
Hey @PaszaVonPomiot Thanks for your report and thanks so much for your time testing the `alpha` versions. Very appreciating that 👋

This is almost the same report as https://github.com/TryGhost/Ghost/issues/8215. 
The image `/ghost/img/ghosticon.jpg` will be removed via #8221 asap.
