### ISSUE TITLE
[alpha.19] Unable to log in with OAuth

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8318]
### Issue Summary

Login on ghost.org works fine but it doesn't work on newly installed alpha.19
AND
No option to create local admin account.

### Steps to Reproduce

1. Clean install of alpha.19
2. Try to sign in with OAuth

### Technical details:

Ghost Version: alpha.19
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon, Firefox, Edge, Chrome (also in incognito mode)

### Log
```
INFO [2017-04-11 23:04:13] "GET /ghost" 301 1ms
INFO [2017-04-11 23:04:13] "GET /ghost/" 200 3ms
INFO [2017-04-11 23:04:13] "GET /ghost/assets/ghost.min-ac10b897866f101ab2edd962e40611c2.css" 200 17ms
INFO [2017-04-11 23:04:13] "GET /ghost/assets/vendor.min-281d8e24df6b26ac7581e49012de3001.css" 200 19ms
INFO [2017-04-11 23:04:13] "GET /ghost/assets/ghost.min-85e69b8ba0fb33179123b0cd94a1ef0b.js" 200 75ms
INFO [2017-04-11 23:04:14] "GET /ghost/assets/vendor.min-02510c7a0a4d23c9fa775e7794c15a4f.js" 200 217ms
INFO [2017-04-11 23:04:14] "GET /ghost/api/v0.1/configuration/" 200 7ms
INFO [2017-04-11 23:04:14] "GET /ghost/api/v0.1/authentication/setup/" 200 2ms
INFO [2017-04-11 23:04:14] "GET /ghost/api/v0.1/authentication/setup/" 200 2ms
INFO [2017-04-11 23:04:14] "GET /ghost/assets/img/install-welcome-3e448684378da60f50541b9c4ab7f33f.png" 200 113ms
INFO [2017-04-11 23:04:16] "GET /ghost/assets/fonts/ghosticons.woff" 200 1ms
INFO [2017-04-11 23:04:33] "GET /ghost/?code=EcAuKody1l3PyJli1ol79duiQlzpG3E9&state=EVl6X5uXW0MZpIC3" 302 10ms
INFO [2017-04-11 23:04:33] "GET /ghost/" 200 3ms
ERROR [2017-04-11 23:04:33] "POST /ghost/api/v0.1/authentication/token" 500 529ms

NAME: InternalServerError
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost/versions/1.0.0-alpha.19/core/server/errors.js:9:26)
    at prepareError (/var/www/ghost/versions/1.0.0-alpha.19/core/server/middleware/error-handler.js:81:19)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/express/lib/router/route.js:127:14)
    at /var/www/ghost/versions/1.0.0-alpha.19/node_modules/oauth2orize/lib/middleware/token.js:57:25
    at next (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/oauth2orize/lib/server.js:401:23)
    at authenticate (/var/www/ghost/versions/1.0.0-alpha.19/core/server/auth/oauth.js:77:20)
    at Strategy.strategy.error (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/passport/lib/middleware/authenticate.js:340:18)
    at verified (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/passport-oauth2/lib/strategy.js:177:36)
    at .<anonymous> (/var/www/ghost/versions/1.0.0-alpha.19/core/server/auth/auth-strategies.js:208:25)
    at tryCatcher (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/util.js:16:23)

TypeError: Cannot read property 'replace' of null
    at Object.safeString (/var/www/ghost/versions/1.0.0-alpha.19/core/server/utils/index.js:61:24)
    at Function.generateSlug (/var/www/ghost/versions/1.0.0-alpha.19/core/server/models/base/index.js:580:22)
    at generateSlug (/var/www/ghost/versions/1.0.0-alpha.19/core/server/models/user.js:123:45)
    at onSaving (/var/www/ghost/versions/1.0.0-alpha.19/core/server/models/user.js:134:15)
    at onSaving (/var/www/ghost/versions/1.0.0-alpha.19/core/server/models/base/index.js:97:50)
    at /var/www/ghost/versions/1.0.0-alpha.19/node_modules/bookshelf/lib/base/events.js:176:25
    at tryCatcher (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.0.0-alpha.19/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by kirrg001** [comment]
Hey @PaszaVonPomiot 👋 Thanks for your report. Could you try again?
One of our test servers for the alpha was not up-to-date.

**Comment by PaszaVonPomiot** [comment]
Hey @kirrg001, still the same error appears.

**Comment by PaszaVonPomiot** [comment]
OK, I've got the password auth method now so my question is answered. :bowtie:
