### ISSUE TITLE
Improve server response for signup with existing e-mail

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8336]
### Issue Summary

When using Ghost OAuth, if you attempt to sign up via an invite and you are already logged in on https://auth.ghost.org with a user that has the same e-mail as an existing blog user the server will generate an `InternalServerError` - this isn't very helpful for users as there's no indication in the client of what's gone wrong, all they see is a "The server has encountered an error." message.

Example of the server error log:

```
ERROR [2017-04-15 08:32:38] "POST /ghost/api/v0.1/authentication/token" 500 381ms

NAME: InternalServerError
CODE: SQLITE_CONSTRAINT
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/Users/kevinansfield/code/ghost/Ghost/core/server/errors.js:9:26)
    at prepareError (/Users/kevinansfield/code/ghost/Ghost/core/server/middleware/error-handler.js:81:19)
    at Layer.handle_error (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:275:10)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:635:15
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/index.js:260:14)
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/express/lib/router/route.js:127:14)
    at /Users/kevinansfield/code/ghost/Ghost/node_modules/oauth2orize/lib/middleware/token.js:57:25
    at next (/Users/kevinansfield/code/ghost/Ghost/node_modules/oauth2orize/lib/server.js:401:23)
    at authenticate (/Users/kevinansfield/code/ghost/Ghost/core/server/auth/oauth.js:77:20)
    at Strategy.strategy.error (/Users/kevinansfield/code/ghost/Ghost/node_modules/passport/lib/middleware/authenticate.js:340:18)
    at verified (/Users/kevinansfield/code/ghost/Ghost/node_modules/passport-oauth2/lib/strategy.js:177:36)
    at null.<anonymous> (/Users/kevinansfield/code/ghost/Ghost/core/server/auth/auth-strategies.js:190:21)
    at tryCatcher (/Users/kevinansfield/code/ghost/Ghost/node_modules/bluebird/js/release/util.js:16:23)

Error: insert into "users" ("created_at", "created_by", "email", "ghost_auth_access_token", "ghost_auth_id", "id", "image", "name", "password", "slug", "updated_at", "updated_by") values ('2017-04-15 08:32:37', 1, 'kevin@ghost.org', '###', '5845ac50ea3a0905de9e67c0', '58f1daa5cbe0fd5b08e9b88b', '//www.gravatar.com/avatar/3ae045bc198a157401827c8455cd7c99?s=250&d=mm&r=x', 'Testing Account', '###', 'testing-account', '2017-04-15 08:32:37', 1) - SQLITE_CONSTRAINT: UNIQUE constraint failed: users.email
    at Error (native)
```

_Note:_ I've redacted the `ghost_auth_access_token` and `password` entries in the error log manually - is there a way we can strip those from the log output in general?

### Steps to Reproduce

1. Start a development blog using Ghost OAuth
2. Log in and invite yourself with a different email
3. Log out of the blog and from https://auth.ghost.org then accept the invite (create a new Ghost.org user if necessary)
4. Invite yourself again with another new e-mail
5. Log out of the blog only
6. Attempt to accept the invite

Rather than a generic `InternalServerError` we should have an error that indicates a user already exists for that Ghost.org account.

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost/commit/e9a537004b9064c631bba71a054d7b85ec152d12
* Database: SQLite

**Comment by Crizzooo** [comment]
Hey, I just started digging through your source code. Could you tell me a little about the architecture to get me started? 

Which route would we be sending this error on, and what is the condition for it being sent out?

**Comment by kirrg001** [comment]
Hey @Crizzooo Thanks for your interest.

This issue is labeled with `later`. That means that there is no need to fix it right now, because we disabled oauth support. That is totally our fault, because we didn't remove the `beginner` label.

But if you have any questions regarding architecture or which issue you could pick up, come say hello on [slack](https://slack.ghost.org) 👋
