### ISSUE TITLE
ERROR: inviteByName is not defined

### ISSUE THREAD

**Issue by hichnicksemen** [TryGhost/Ghost#8416]
### Issue Summary

Then i try to add new team member, by sending email invite:
 ```
ReferenceError: inviteByName is not defined
    at eval (lodash.templateSources[16]:17:10)
    at /var/www/site/www/core/server/mail/utils.js:30:27
    at tryCatcher (/var/www/site/www/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/site/www/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/site/www/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/site/www/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/site/www/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/www/omgubuntujs/www/node_modules/bluebird/js/release/promise.js:638:18)
    at /var/www/site/www/node_modules/bluebird/js/release/nodeback.js:42:21
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12) 
```

### Steps to Reproduce

1. Open team page
2. Click on "Invite people" button
3. Add email adress
4. Click on "send invitarion now" button

### Technical details:

* Ghost Version: 0.11.8
* Node Version: 6.10.2
* Browser/OS: Chrome/Linux
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @hichnicksemen 👋 Sorry to hear you are having trouble.

This error only happens if the target email template (`core/server/mail/templates/invite-user.html`) does not contain the variable `invitedByName`. But it does on `0.11.8`.

Did you update your blog to a `0.11.8` lately? I assume that something went wrong when upgrading to a newer version?

**Comment by hichnicksemen** [comment]
Hey @kirrg001 thanks for reply! 
I made fresh install of ghost v. 0.11.8 and i checked `core/server/mail/templates/invite-user.html` it contain the `invitedByName` variable.

**Comment by kirrg001** [comment]
Thanks for your fast reply. This error only happens if either the template has a missing variable (which is not the case) or a template variable is not forwarded at all.

Could you please swing by our [slack channel](https://slack.ghost.org)?
We can leave the issue open for now and update it with relevant information.

**Comment by kirrg001** [comment]
@hichnicksemen I'm closing this issue for now. We can re-open as soon as figure out if it's a bug or related to your setup. Come say hello on slack 🙃
