### ISSUE TITLE
🐛 server crashes if blog url has no protocol

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8449]
If i add a url like `localhost:2368` the server crashes. The error log.

```
NAME: InternalServerError
MESSAGE: The server has encountered an error.

level:normal

TypeError: Cannot read property 'replace' of null
    at getSubdir (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:52:34)
    at deduplicateSubDir (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:61:18)
    at Object.urlJoin (/Users/kirrg001/dev/ghost/ghost/core/server/utils/url.js:115:11)
    at frontendRoutes (/Users/kirrg001/dev/ghost/ghost/core/server/blog/routes.js:28:26)
    at setupBlogApp (/Users/kirrg001/dev/ghost/ghost/core/server/blog/app.js:114:17)
    at setupParentApp (/Users/kirrg001/dev/ghost/ghost/core/server/app.js:65:36)
    at /Users/kirrg001/dev/ghost/ghost/core/server/index.js:72:37
```

Ghost: master

**Comment by acburdine** [comment]
In production installs, the CLI will not start Ghost if there is a blog url without protocol, however this is still probably something that would be good to have just as an additional sanity check in Ghost itself.

**Comment by AileenCGN** [comment]
After a conversation on Slack, we decided to also throw an error and interrupt Ghost from starting, if no protocol is given.
