### ISSUE TITLE
error after visit /admin 

### ISSUE THREAD

**Issue by pociej** [TryGhost/Ghost#8505]
### Issue Summary

Hard to say what exactly happens i will describe steps 
### Steps to Reproduce

1.  do instruction in tutorial 
2.  go to localhost:2368
3. navigate to /admin
4  fill the register form 

server side log : 

```INFO [2017-05-31 17:55:53] "GET /admin" 301 3ms
INFO [2017-05-31 17:55:53] "GET /admin/" 301 5ms
[2017-05-31 17:55:54] ERROR

NAME: LatestReleaseError
MESSAGE: Latest release is not available.

level:critical

Checking for updates failed, your blog will continue to function.
If you get this error repeatedly, please seek help from http://support.ghost.org.
LatestReleaseError: Latest release is not available.
    at new InternalServerError (/Users/grzegorz/Projects/ghost/ghost/node_modules/ghost-ignition/lib/errors/index.js:71:23)
    at Object.JSONAPIDeserialize (/Users/grzegorz/Projects/ghost/ghost/node_modules/ghost-ignition/lib/errors/utils.js:100:25)
    at Object.deserialize (/Users/grzegorz/Projects/ghost/ghost/node_modules/ghost-ignition/lib/errors/utils.js:165:63)
    at updateCheckError (/Users/grzegorz/Projects/ghost/ghost/core/server/update-check.js:42:24)
    at tryCatcher (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/grzegorz/Projects/ghost/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)

```

5 . go to localhost : 2368 

Client side error : 500 
Server side : 

```NAME: InternalServerError
MESSAGE: [default.hbs] (title || "").trim is not a function

level:normal

InternalServerError: [default.hbs] (title || "").trim is not a function
    at new GhostError (/Users/grzegorz/Projects/ghost/ghost/core/server/errors.js:9:26)
    at prepareError (/Users/grzegorz/Projects/ghost/ghost/core/server/middleware/error-handler.js:81:19)
    at Layer.handle_error (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:315:13)
    at /Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:275:10)
    at /Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:635:15
    at next (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:260:14)
    at /Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:635:15
    at Immediate.next (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:260:14)
    at Immediate.<anonymous> (/Users/grzegorz/Projects/ghost/ghost/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:572:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)

``` 

### Technical details:

* Ghost Version: 3.10.3
* Node Version: 6.3.1
* Browser/OS: any
* Database: i dint setup any db. Is it needed ? I dont see any prerequirement

**Comment by kirrg001** [comment]
Hey @pociej 👋

Thanks for your report.

You are using the Ghost `1.0` Alpha version. This version is not suitable for a production blog. If you would like to setup a stable blog, you should use our [latest release](https://ghost.org/developers/).

Anyway, the `LatestReleaseError` error is expected, because there is no `1.0` release yet. Sorry for the confusion. We will reconsider showing the error.

> [default.hbs] (title || "").trim is not a function

I can confirm this bug. This happens when your change the blog title in the admin panel to e.g. 1.
The value is then interpreted as an integer and not as a string. You can change your blog title to something else and it should work again 👍

**Comment by pociej** [comment]
Thx a lot :) Yeah i set title to something random like "afa wf123" just you played a bit like drunk monkey :)

**Comment by kirrg001** [comment]
Great 👍 Fix is coming 🚓

**Comment by WGH-** [comment]
Even after a61e6e7 and 34054a3, blog title that is not a number, but happens to be a valid JSON (e.g. `[1]`) will cause this problem, though.
