### ISSUE TITLE
Wrong password leads to confusing error message

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#8565]
### Issue Summary

If you provide a wrong password at the login screen the error message that appears is:

`UnauthorizedError: You are not authorised to make this request.`
http://imgur.com/nnHx6Hs

because it fires before the other which is also in the log

`ValidationError: Your password is incorrect.`

### Steps to Reproduce

1. Complete the setup for ghost
2. Log out
3. Try to log in with a wrong password

#### Full trace
```
ERROR [2017-06-12 07:14:04] "POST /ghost/api/v0.1/authentication/token" 401 370ms

NAME: UnauthorizedError
CODE: PASSWORD_INCORRECT
MESSAGE: You are not authorised to make this request.

level:normal


Your password is incorrect.
Visit and save your profile after logging in to check for problems.
UnauthorizedError: You are not authorised to make this request.
    at new UnauthorizedError (d:\dev\ghost.beta\node_modules\ghost-ignition\lib\errors\index.js:101:23)
    at onError (d:\dev\ghost.beta\core\server\models\user.js:676:43)
    at tryCatcher (d:\dev\ghost.beta\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (d:\dev\ghost.beta\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (d:\dev\ghost.beta\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (d:\dev\ghost.beta\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

ValidationError: Your password is incorrect.
    at new ValidationError (d:\dev\ghost.beta\node_modules\ghost-ignition\lib\errors\index.js:115:23)
    at d:\dev\ghost.beta\core\server\models\user.js:707:39
    at tryCatcher (d:\dev\ghost.beta\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (d:\dev\ghost.beta\node_modules\bluebird\js\release\promise.js:638:18)
    at d:\dev\ghost.beta\node_modules\bluebird\js\release\nodeback.js:42:21
    at d:\dev\ghost.beta\node_modules\bcryptjs\dist\bcrypt.js:297:21
    at d:\dev\ghost.beta\node_modules\bcryptjs\dist\bcrypt.js:1353:21
    at Immediate.next (d:\dev\ghost.beta\node_modules\bcryptjs\dist\bcrypt.js:1233:21)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

### Technical details:

* Ghost Version: 1.0.0 ßeta.1
* Node Version: v6.9.5
* Browser/OS: Firefox 53.0 / Windows 10 1703 (15063.332)
* Database: sqlite3

**Comment by AileenCGN** [comment]
Hey @letsjustfixit! I can confirm this behaviour. Ghost sends the `UnauthorizedError` first and that's what the client pick up then, which is not very useful for the user.
