### ISSUE TITLE
A ProcessError occured when ghost install

### ISSUE THREAD

**Issue by zce** [TryGhost/Ghost#8682]
### Issue Summary

> ✔ Validating config
> Running sudo command: systemctl start ghost_blog-zce-me
> ✔ Starting Ghost
> Running sudo command: systemctl enable ghost_blog-zce-me --quiet
> ☱ Starting GhostFailed to execute operation: No such file or directory
> ✖ Starting Ghost
> A ProcessError occured.
> 
> Error occurred running command: '/bin/sh -c sudo systemctl enable ghost_blog-zce-me --quiet'
> 
> Exit code: 1
> 
> 
> Debug Information:
>     Node Version: v6.10.3
>     Ghost-CLI Version: 1.0.0-rc.2
>     Environment: production
>     Command: 'ghost install'

### Steps to Reproduce

```shell
$ node -v
v6.11.1
$ yarn --version
0.24.6
$ sudo yarn global add ghost-cli
$ ghost -v
Ghost-CLI version: 1.0.0-rc.2
$ sudo ghost install
...
✔ Starting Ghost
Running sudo command: systemctl enable ghost_blog-zce-me --quiet
☱ Starting GhostFailed to execute operation: No such file or directory
✖ Starting Ghost
A ProcessError occured.

Error occurred running command: '/bin/sh -c sudo systemctl enable ghost_blog-zce-me --quiet'

Exit code: 1


Debug Information:
    Node Version: v6.10.3
    Ghost-CLI Version: 1.0.0-rc.2
    Environment: production
    Command: 'ghost install'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-07-13T02_20_30_215Z.log

Please refer to https://docs.ghost.org/docs/installing-ghost-via-the-cli#troubleshooting for troubleshooting.
...
$ ghost ls
/usr/local/share/.config/yarn/global/node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: failed

    at module.exports.sync (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:298:26)
    at handleShell (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:100:9)
    at Function.module.exports.shellSync (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:307:43)
    at SystemdProcessManager.isRunning (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/extensions/systemd/systemd.js:61:19)
    at Instance.get running [as running] (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/instance.js:61:27)
    at Instance.summary (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/instance.js:173:18)
    at instances.map (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/commands/ls.js:9:36)
    at Array.map (native)
    at LsCommand.run (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/commands/ls.js:8:30)
    at Function._run (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/command.js:183:48)
    at Object.handler (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/command.js:108:22)
    at Object.self.runCommand (/usr/local/share/.config/yarn/global/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/usr/local/share/.config/yarn/global/node_modules/yargs/yargs.js:990:30)
    at Object.Yargs.self.parse (/usr/local/share/.config/yarn/global/node_modules/yargs/yargs.js:532:23)
    at Object.run (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/bootstrap.js:153:14)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/bin/ghost:12:11)
```

### Technical details:

* Ghost Version: 1.0.0-rc.1
* Node Version: 6.11.1
* Browser/OS: CentOS 7
* Database: MySQL

**Comment by ErisDS** [comment]
Hi @zce please do not use `sudo` with the ghost-cli commands. You should create a folder in which your user has permissions, and use the `ghost install` command without sudo.

The documentation is being updated to reflect this. 

If run into further problems, I recommend our [slack](https://ghost.org/slack) channel, or otherwise please raise issues on the https://github.com/TryGhost/Ghost-CLI repo.

cc @sebgie

**Comment by zce** [comment]
I'm sorry, thanks
