### ISSUE TITLE
Cannot find module 'node-uuid' - Heroku deploy -Ghost v0.11.10

### ISSUE THREAD

**Issue by paulomcnally** [TryGhost/Ghost#8684]
### Issue Summary

On Deploy on heroku.

`2017-07-13T19:46:18.341756+00:00 heroku[web.1]: Starting process with command `npm start`
2017-07-13T19:46:20.895273+00:00 app[web.1]: 
2017-07-13T19:46:20.895289+00:00 app[web.1]: 
2017-07-13T19:46:20.895288+00:00 app[web.1]: > ghost@0.11.10 start /app
2017-07-13T19:46:20.895288+00:00 app[web.1]: > node index
2017-07-13T19:46:22.387923+00:00 heroku[web.1]: State changed from starting to crashed
2017-07-13T19:46:22.374443+00:00 heroku[web.1]: Process exited with status 0
2017-07-13T19:46:22.267791+00:00 app[web.1]: 
2017-07-13T19:46:22.267809+00:00 app[web.1]: ERROR: Cannot find module 'node-uuid' 
2017-07-13T19:46:22.267810+00:00 app[web.1]:  
2017-07-13T19:46:22.267811+00:00 app[web.1]:  Error: Cannot find module 'node-uuid'
2017-07-13T19:46:22.267812+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-07-13T19:46:22.267812+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-07-13T19:46:22.267813+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-07-13T19:46:22.267814+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-07-13T19:46:22.267814+00:00 app[web.1]:     at Object.<anonymous> (/app/core/server/models/base.js:18:18)
2017-07-13T19:46:22.267815+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-07-13T19:46:22.267816+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-07-13T19:46:22.267817+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-07-13T19:46:22.267817+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-07-13T19:46:22.267818+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-07-13T19:46:22.267819+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-07-13T19:46:22.267819+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-07-13T19:46:22.267820+00:00 app[web.1]:     at Object.init (/app/core/server/models/index.js:35:20)
2017-07-13T19:46:22.267821+00:00 app[web.1]:     at /app/core/server/index.js:78:16
2017-07-13T19:46:22.267822+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2017-07-13T19:46:22.267825+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2017-07-13T19:46:22.267827+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2017-07-13T19:46:22.267827+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2017-07-13T19:46:22.267828+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
2017-07-13T19:46:22.267829+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2017-07-13T19:46:22.267830+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
2017-07-13T19:46:22.267829+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)`

### Technical details:

* Ghost Version: v0.11.10
* Node Version: v6.11.1
* Browser/OS: Heroku
* Database: PG

**Comment by AileenCGN** [comment]
Hi @paulomcnally, sorry to hear you are having trouble upgrading. Unfortunately this sounds like an environment issue rather than a bug in Ghost so I'll have to close this issue as we only use Github for bug tracking and on-going development. If you head over to our Slack team and ask in the #help channel the community is usually very good at finding where the problem may be and pointing you in the right direction 😃

If it turns out to be an issue with Ghost itself in the end, we can always reopen it.
