### ISSUE TITLE
Importing invalid dates result in exception

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#8703]
### Issue Summary

Importer accepts invalid dates. When importing posts with published_at/modified_at set to `0000-00-00T00:00:00.000Z`the importer doesn't show an error. Visiting the post afterwards results in an exception.

```
ERROR: [default.hbs] Invalid time value 
 Rendering Error Page 
 Ghost caught a processing error in the middleware layer. 
 RangeError: [default.hbs] Invalid time value
    at getPublishedDate (/home/ghost/core/server/data/meta/published_date.js:7:53)
    at getMetaData (/home/ghost/core/server/data/meta/index.js:45:24)
    at Object.ghost_head (/home/ghost/core/server/helpers/ghost_head.js:87:23)
    at Object.<anonymous> (/home/ghost/core/server/helpers/index.js:64:28)
    at Function.Waiter.resolve (/home/ghost/node_modules/express-hbs/lib/async.js:83:3)
    at Object.<anonymous> (/home/ghost/node_modules/express-hbs/lib/hbs.js:396:18)
    at Object.eval (eval at createFunctionContext (/home/ghost/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:1:0), <anonymous>:14:166)
    at main (/home/ghost/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/ghost/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/ghost/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at renderTemplate (/home/ghost/node_modules/express-hbs/lib/hbs.js:483:13)
    at _stackRenderer (/home/ghost/node_modules/express-hbs/lib/hbs.js:524:9)
    at Waiter.callback (/home/ghost/node_modules/express-hbs/lib/hbs.js:503:7)
    at Waiter.resolve (/home/ghost/node_modules/express-hbs/lib/async.js:43:12)
    at /home/ghost/node_modules/express-hbs/lib/async.js:84:15
    at /home/ghost/core/server/helpers/index.js:65:13
    at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ghost/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ghost/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:17:14)
```

### Steps to Reproduce

1. Create an import file that has one post with updated_at/modified_at set to `"0000-00-00T00:00:00.000Z"`
2. Import
3. Visit the post with the modified date

Not sure if there are other ways to get into that state. I am able to reproduce the behaviour when importing.

### Technical details:

* Ghost Version: 0.11.10
* Node Version: 6.11.0
* Browser/OS: Chrome latest
* Database: MySQL

**Comment by ErisDS** [comment]
Going to reopen this as we're seeing slightly different incarnations of the same problem.
