### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings': Ghost 1.0 on FreeBSD 11

### ISSUE THREAD

**Issue by neelchauhan** [TryGhost/Ghost#8741]
### Issue Summary

When I run Ghost 1.0 on FreeBSD 11.0, I get this error:

    An error occurred.
    Message: 'Command failed: knex-migrator-migrate --init --mgpath /root/gh/current
    { Error: Cannot find module './build/Release/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/default/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/Debug/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    
    null'

This error happens on my server and on my desktop, both running FreeBSD 11.0, and happens on both MySQL and SQLite modes.

### Steps to Reproduce

1. Have a FreeBSD box ready
2. Run `pkg install node6` and then `pkg install npm3`
3. Run `npm install ghost-cli`
4. Make a new directory, and execute `ghost install`
5. Follow the steps, except with saying no to systemd and nginx
6. Try to run Ghost by running (GHOST_DIR)/current/index.js
7. You get this error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected it to start Ghost like it did on the 0.11.x versions, but instead got this error.

### Technical details:

* Ghost Version: 1.0
* Node Version: 6.10.1
* Browser/OS: FreeBSD 11.0 amd64
* Database: SQLite (but MySQL also had this error)

**Comment by acburdine** [comment]
@neelchauhan this is actually an issue with [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI), can you open this issue there?
