### ISSUE TITLE
Ghost broken on Node 8

### ISSUE THREAD

**Issue by wan-qy** [TryGhost/Ghost#8770]
### Technical details:

* Ghost Version: 0.11.11/1.0.2
* Node Version: node 8.2.1 
* Browser/OS: windows 15063
* Database: sqlite3

---

```log
D:\Ghost-0.11.11\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (D:\Ghost-0.11.11\node_modules\require-dir\index.js:93:37)
    at Object.<anonymous> (D:\Ghost-0.11.11\node_modules\gscan\lib\checker.js:8:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Ghost-0.11.11\node_modules\gscan\lib\index.js:3:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Ghost-0.11.11\core\server\api\themes.js:5:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghost@0.11.11 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ghost@0.11.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\somebody\AppData\Roaming\npm-cache\_logs\2017-07-28T15_20_17_964Z-debug.log
```

---

* reason 

refs : [NODE 8.0.0 and NPM 4.2.0 ERROR express-load require.extensions.hasOwnProperty is not a function](https://stackoverflow.com/questions/44298322/node-8-0-0-and-npm-4-2-0-error-express-load-require-extensions-hasownproperty-is)
>This is not an npm issue, and strictly a node.js issue.require.extensions has been deprecated since node v0.10.6 and upgrading to node 8, which fully drops support for it, causes that error.

And ghost itself and gscan use require-dir `0.1.0`, which does not support node 8.

---

* how to fix:

refs : [Broken on node v8](https://github.com/aseemk/requireDir/issues/45)
This problem have been fixed on newer version of require-dir. I switched the version of require-dir to `0.3.2` and ghost works well now.

**Comment by ErisDS** [comment]
https://docs.ghost.org/docs/supported-node-versions

**Comment by thekyriarchy** [comment]
So Node 8.10 should be supported?

**Comment by kirrg001** [comment]
@thekyriarchy 

Ghost 1.x
https://docs.ghost.org/docs/supported-node-versions

Ghost 0.x
https://docs.ghost.org/v0.11/docs/supported-node-versions
