### ISSUE TITLE
can't start my blog

### ISSUE THREAD

**Issue by Huang-Jinxian** [TryGhost/Ghost#8783]
The following is my error, and I can't solve it.
[2017-07-30 16:25:39] ERROR

NAME: DatabaseIsNotOkError
CODE: MIGRATION_TABLE_IS_MISSING
MESSAGE: Please run knex-migrator init

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
Error
    at DatabaseIsNotOkError.KnexMigrateError (E:\GhostBlog\node_modules\knex-migrator\lib\errors.js:7:26)
    at new DatabaseIsNotOkError (E:\GhostBlog\node_modules\knex-migrator\lib\errors.js:19:26)
    at onMigrationsLookupError (E:\GhostBlog\node_modules\knex-migrator\lib\index.js:512:23)
    at tryCatcher (E:\GhostBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\GhostBlog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\GhostBlog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\GhostBlog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\GhostBlog\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (E:\GhostBlog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\GhostBlog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\GhostBlog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! ghost@1.0.2 start: `node index`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ghost@1.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huang\AppData\Roaming\npm-cache\_logs\2017-07-30T16_25_39_040Z-debug.log

**Comment by acburdine** [comment]
Hi @Huang-Jinxian!

As shown by the error you posted above, Ghost-CLI is failing to start because your database hasn't been initialized yet. There are clear instructions as to how to resolve the issue shown in the stack trace, namely to install knex-migrator globally (`npm install -g knex-migrator`) and then run `knex-migrator init` to initialize your database.

However, if you are trying to get Ghost 1.0 set up for production use, the recommended, supported way of doing so is through [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI) - it will install everything for you and take care of migrating your database so that you won't get this error 😄 

Going to close this though as it's not an actual bug, and the directions to solve the issue are very clear in the stack trace.

**Comment by YOnoda** [comment]
Hi,

I also faced this problem. I ran `knex-migrator init`, and it seemed the migration succeeded, with the last output is `[2017-08-03 20:51:24] INFO Finished database init!`.

However, `ghost run -D` returns the following error:

    NAME: DatabaseIsNotOkError
    CODE: MIGRATION_TABLE_IS_MISSING
    MESSAGE: Please run knex-migrator init

`knex-migrator health` returns `[2017-08-03 20:54:59] INFO Woohoo, Database is healthy`, but when I checked the DB no table has been created.

What am I missing? I set `paths:migrationPath` to `"/home/me/project/current/core/server/data/migrations"` in `config.production.json`, for your information...

**Comment by YOnoda** [comment]
Hmmm... It seems that the project is irrelevant as long as the database setting is the same, so I fixed it up by creating a dummy directory and ran `ghost install` there (with the same DB settings). During the installation process the database migration is done and now I could run my app successfully.

**Comment by mitchellkrogza** [comment]
The magic command after running `ghost install` is to run `ghost setup migrate`

`ghost install` (latest) does not create the database despite a person giving it all the info to do so ??? 

Took me an hour to figure this out and then on this page - https://docs.ghost.org/v1.0.0/docs/cli-setup they actually say "ghost setup is the real magic in Ghost CLI" 

..... and lower down on the page they happen to mention running `ghost setup migrate` once I did that the blog worked instantly (after a restart of the ghost service and nginx of course) because the actual install did not create the database tables at all.
