### ISSUE TITLE
Unable to upload blog icon that is 60x60 px, 4kb and in png format

### ISSUE THREAD

**Issue by grantwinney** [TryGhost/Ghost#8797]
### Issue Summary

I attempted to upload a "publication icon" via the admin screen. It's 60x60 px and 4kb, in `png` format, so it should be okay. But I keep getting:

> Blog icon must be a square .ico or .png file between 60px – 1,000px, under 100kb.

Looking at the console output, it attempted a POST to https://grantwinney.com/ghost/api/v0.1/uploads/icon/ but got a 422 in response. 

Here's the output of the _"...production.error.log"_ file:

```json
{
	"name": "Log",
	"hostname": "ghost-blog",
	"pid": 1601,
	"level": 50,
	"req": {
		"meta": {
			"requestId": "09b25980-761a-11e7-bc6b-abd7697343ef",
			"userId": "1"
		},
		"url": "/uploads/icon/",
		"method": "POST",
		"originalUrl": "/ghost/api/v0.1/uploads/icon/",
		"params": {},
		"headers": {
			"x-forwarded-for": "192.182.255.2",
			"x-forwarded-proto": "https",
			"x-real-ip": "192.182.255.2",
			"host": "grantwinney.com",
			"connection": "close",
			"content-length": "2010",
			"origin": "https://grantwinney.com",
			"x-requested-with": "XMLHttpRequest",
			"content-type": "multipart/form-data; boundary=----WebKitFormBoundarywUybUygeIOrKGeXD",
			"accept": "text/plain, */*; q=0.01",
			"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36",
			"x-ghost-version": "1.2",
			"dnt": "1",
			"referer": "https://grantwinney.com/ghost/",
			"accept-encoding": "gzip, deflate, br",
			"accept-language": "en-US,en;q=0.8"
		},
		"body": {},
		"query": {}
	},
	"res": {
		"_headers": {
			"x-powered-by": "Express",
			"cache-control": "no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0",
			"access-control-allow-origin": "https://grantwinney.com",
			"vary": "Origin, Accept-Encoding",
			"content-type": "application/json; charset=utf-8",
			"content-length": "140",
			"etag": "W/\"8c-OHQ99jnxlHCzO0uLwFlA5EWw1Ps\""
		},
		"statusCode": 422,
		"responseTime": "40ms"
	},
	"err": {
		"id": "09b825e0-761a-11e7-bc6b-abd7697343ef",
		"domain": "https://grantwinney.com",
		"code": null,
		"name": "ValidationError",
		"statusCode": 422,
		"level": "normal",
		"message": "Blog icon must be a square .ico or .png file between 60px – 1,000px, under 100kb.",
		"stack": "ValidationError: Blog icon must be a square .ico or .png file between 60px – 1,000px, under 100kb.\n    at new ValidationError (/var/www/ghost/versions/1.2.0/node_modules/ghost-ignition/lib/errors/index.js:115:23)\n    at /var/www/ghost/versions/1.2.0/core/server/middleware/validation/blog-icon.js:62:29\n    at tryCatcher (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.2.0/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"
	},
	"msg": "Blog icon must be a square .ico or .png file between 60px – 1,000px, under 100kb.",
	"time": "2017-07-31T17:59:46.243Z",
	"v": 0
}
```

I *think* I see the reason for the error - there's a possible issue with the validation in the "core/server/middleware/validation/blog-icon.js" file, where it checks that the minimum width is `<= 60` even though it seems like the intention was to allow 60px.

[I opened a pull request](https://github.com/TryGhost/Ghost/pull/8799), in case I'm right about the fix.

### Steps to Reproduce

1. Create a 60x60 px image, save in png format.
2. Attempt to upload image.

### Technical details:

* OS: Ubuntu 16.04.2 LTS
* Node Version: v6.11.1
* Ghost-CLI version: 1.0.0
* Ghost Version (at /var/www/ghost): 1.2.0
* Database: mysql Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using EditLine wrapper
* Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by AileenCGN** [comment]
Good catch @grantwinney!! I can confirm this behaviour.

**Comment by jonathan-kosgei** [comment]
I'm running into this on V3.4.0 with a 100x100px png.
