### ISSUE TITLE
Database Migration from ghost v1.0.0-alpha.17 to ghost v1.2.0 Fails

### ISSUE THREAD

**Issue by compengi** [TryGhost/Ghost#8803]
### Issue Summary

I'm doing a fresh install of the current node version as an upgrade to my previous ghost v1.0.0-alpha.17 installation on top of the existing database . At the migration step, the installation fails, with the following error:

✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-08-01 08:33:29] ERROR

NAME: MigrationScript
CODE: ER_BAD_FIELD_ERROR
MESSAGE: select `posts`.* from `posts` where `posts`.`title` = 'Setting up your own Ghost theme' and `posts`.`slug` = 'themes' and `posts`.`mobiledoc` = '{\"version\":\"0.3.1\",\"markups\":[],\"atoms\":[],\"cards\":[[\"card-markdown\",{\"cardName\":\"card-markdown\",\"markdown\":\"Creating a totally custom design for your publication\\n\\nGhost comes with a beautiful default theme called Casper, which is designed to be a clean, readable publication layout and can be easily adapted for most purposes. However, Ghost can also be completely themed to suit your needs. Rather than just giving you a few basic settings which act as a poor proxy for code, we just let you write code.\\n\\nThere are a huge range of both free and premium pre-built themes which you can get from the [Ghost Theme Marketplace](http://marketplace.ghost.org), or you can simply create your own from scratch.\\n\\n[![marketplace](https://casper.ghost.org/v1.0.0/images/marketplace.jpg)](http://marketplace.ghost.org)\\n\\n> Anyone can write a completely custom Ghost theme, with just some solid knowledge of HTML and CSS\\n\\nGhost themes are written with a templating language called handlebars, which has a bunch of dynamic helpers to insert your data into template files. Like `{{author.name}}`, for example, outputs the name of the current author.\\n\\nThe best way to learn how to write your own Ghost theme is to have a look at [the source code for Casper](https://github.com/TryGhost/Casper), which is heavily commented and should give you a sense of how everything fits together.\\n\\n- `default.hbs` is the main template file, all contexts will load inside this file unless specifically told to use a different template.\\n- `post.hbs` is the file used in the context of viewing a post.\\n- `index.hbs` is the file used in the context of viewing the home page.\\n- and so on\\n\\nWe\'ve got [full and extensive theme documentation](http://themes.ghost.org/docs/about) which outlines every template file, context and helper that you can use.\\n\\nIf you want to chat with other people making Ghost themes to get any advice or help, there\'s also a **#themes** channel in our [public Slack community](https://slack.ghost.org) which we always recommend joining!\"}]],\"sections\":[[10,0]]}' and `posts`.`feature_image` = 'https://casper.ghost.org/v1.0.0/images/design.jpg' and `posts`.`featured` = false and `posts`.`page` = false and `posts`.`status` = 'published' and `posts`.`meta_title` is null and `posts`.`meta_description` is null and `posts`.`author_id` = '5951f5fca366002ebd5dbef7' and `posts`.`created_by` = '5951f5fca366002ebd5dbef7' and `posts`.`published_at` = '2017-08-01 06:33:29' and `posts`.`published_by` = '5951f5fca366002ebd5dbef7' limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'posts.feature_image' in 'where clause'

level:normal

Error occurred while executing the following migration: 2-create-fixtures.js
MigrationScript: select `posts`.* from `posts` where `posts`.`title` = 'Setting up your own Ghost theme' and `posts`.`slug` = 'themes' and `posts`.`mobiledoc` = '{\"version\":\"0.3.1\",\"markups\":[],\"atoms\":[],\"cards\":[[\"card-markdown\",{\"cardName\":\"card-markdown\",\"markdown\":\"Creating a totally custom design for your publication\\n\\nGhost comes with a beautiful default theme called Casper, which is designed to be a clean, readable publication layout and can be easily adapted for most purposes. However, Ghost can also be completely themed to suit your needs. Rather than just giving you a few basic settings which act as a poor proxy for code, we just let you write code.\\n\\nThere are a huge range of both free and premium pre-built themes which you can get from the [Ghost Theme Marketplace](http://marketplace.ghost.org), or you can simply create your own from scratch.\\n\\n[![marketplace](https://casper.ghost.org/v1.0.0/images/marketplace.jpg)](http://marketplace.ghost.org)\\n\\n> Anyone can write a completely custom Ghost theme, with just some solid knowledge of HTML and CSS\\n\\nGhost themes are written with a templating language called handlebars, which has a bunch of dynamic helpers to insert your data into template files. Like `{{author.name}}`, for example, outputs the name of the current author.\\n\\nThe best way to learn how to write your own Ghost theme is to have a look at [the source code for Casper](https://github.com/TryGhost/Casper), which is heavily commented and should give you a sense of how everything fits together.\\n\\n- `default.hbs` is the main template file, all contexts will load inside this file unless specifically told to use a different template.\\n- `post.hbs` is the file used in the context of viewing a post.\\n- `index.hbs` is the file used in the context of viewing the home page.\\n- and so on\\n\\nWe\'ve got [full and extensive theme documentation](http://themes.ghost.org/docs/about) which outlines every template file, context and helper that you can use.\\n\\nIf you want to chat with other people making Ghost themes to get any advice or help, there\'s also a **#themes** channel in our [public Slack community](https://slack.ghost.org) which we always recommend joining!\"}]],\"sections\":[[10,0]]}' and `posts`.`feature_image` = 'https://casper.ghost.org/v1.0.0/images/design.jpg' and `posts`.`featured` = false and `posts`.`page` = false and `posts`.`status` = 'published' and `posts`.`meta_title` is null and `posts`.`meta_description` is null and `posts`.`author_id` = '5951f5fca366002ebd5dbef7' and `posts`.`created_by` = '5951f5fca366002ebd5dbef7' and `posts`.`published_at` = '2017-08-01 06:33:29' and `posts`.`published_by` = '5951f5fca366002ebd5dbef7' limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'posts.feature_image' in 'where clause'
    at MigrationScript.KnexMigrateError (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScript (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:26:26)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:349:19
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: ER_BAD_FIELD_ERROR: Unknown column 'posts.feature_image' in 'where clause'
    at Query.Sequence._packetToError (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:208:25)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:197:17)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/transaction.js:274:21
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/method.js:39:29)
    at Client_MySQL.trxClient.query (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/transaction.js:271:34)
    at Runner.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/method.js:15:34)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/runner.js:65:21
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)

### Technical details:

* Ghost Version: 1.2.0
* Node Version: v6.11.1
* Ghost-CLI Version: 1.0.1
* Database: MySQL v14.14

**Comment by ErisDS** [comment]
Hi @compengi, the pre-release versions of Ghost do not have database versions written for them. 

You will need to install a fresh stable version, i.e. 1.0.0 or higher.

Documentation is here: https://docs.ghost.org/docs/upgrade

If you have further questions or problems with upgrading, please drop by the #help channel in [slack](https://ghost.org/slack).
