### ISSUE TITLE
Error upgrading from 1.3.0 -> 1.4.0 via ghost-cli (v1.0.3)

### ISSUE THREAD

**Issue by darrenmhill** [TryGhost/Ghost#8828]
Details below:

✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -E -u ghost /usr/local/share/.config/yarn/global/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-08-02 11:14:16] ERROR

NAME: InternalServerError
CODE: ECONNREFUSED
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new KnexMigrateError (/usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/errors.js:7:26)
    at /usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/database.js:58:19
    at tryCatcher (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
    at Protocol._enqueue (/usr/local/share/.config/yarn/global/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/usr/local/share/.config/yarn/global/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/local/share/.config/yarn/global/node_modules/mysql/lib/Connection.js:130:18)
    at /usr/local/share/.config/yarn/global/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/usr/local/share/.config/yarn/global/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/usr/local/share/.config/yarn/global/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/usr/local/share/.config/yarn/global/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/usr/local/share/.config/yarn/global/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/usr/local/share/.config/yarn/global/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/usr/local/share/.config/yarn/global/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/usr/local/share/.config/yarn/global/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/usr/local/share/.config/yarn/global/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/usr/local/share/.config/yarn/global/node_modules/knex/lib/index.js:60:34)
    at Object.connect (/usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/database.js:24:12)
    at Object.createDatabaseIfNotExist (/usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/database.js:41:30)
    at KnexMigrator.init (/usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/index.js:73:21)
    at KnexMigrator.migrate (/usr/local/share/.config/yarn/global/node_modules/knex-migrator/lib/index.js:160:21)
    at /usr/local/share/.config/yarn/global/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
    at tryCatcher (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)

'

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: production
    Command: 'ghost update'

**Comment by darrenmhill** [comment]
Also, what's the correct method to roll-back to a previous version? Currently I'm just changing the 'current' symlink back to another version (1.3.0 in this case).

**Comment by ErisDS** [comment]
ECONNREFUSED 127.0.0.1:3306 means that the connection to your MySQL service failed.

However, this issue occurred with a Ghost CLI command, therefore can you please re-raise this on the [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI) repo.

**Comment by ErisDS** [comment]
https://docs.ghost.org/docs/upgrade#section-what-to-do-when-an-upgrade-fails
