### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by seungha-kim** [TryGhost/Ghost#8829]
### Issue Summary

can't access admin home (`/ghost`) after fresh install 1.4.0
detail error message (it is printed in web browser):

```
Error: No default engine was specified and no extension was provided.
    at new View (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/response.js:971:7)
    at HTMLErrorRender (/home/seungha/ghost-test/versions/1.4.0/core/server/middleware/error-handler.js:86:9)
    at Layer.handle_error (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at prepareError (/home/seungha/ghost-test/versions/1.4.0/core/server/middleware/error-handler.js:58:5)
    at Layer.handle_error (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at /home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/home/seungha/ghost-test/versions/1.4.0/node_modules/express/lib/response.js:1003:5)
```

and after I upgraded Ghost from 1.1.0 to 1.4.0, it showed 404 page.

### Technical details:

* Ghost Version: 1.4.0
* Node Version: 6.11.1
* Browser/OS: Manjaro
* Database: SQLite3

**Comment by seungha-kim** [comment]
I installed Ghost via `ghost install local` command.

**Comment by NistorCristian** [comment]
The same thing happened to me ... On a fresh install using Ghost CLI

**Comment by TomasBankauskas** [comment]
Just updated Ghost from 1.2.0 to 1.4.0 and got the same error.

### Technical details:

* Ghost Version: 1.4.0
* Node Version: 6.11.1

**Comment by philmillman** [comment]
+1 on ghost 1.4.0, node 6.9.4

**Comment by Kuzoin** [comment]
The same problem - update from 1.3 to 1.4 via CLI

**Comment by kirrg001** [comment]
Thanks for the report.

I can confirm this. **This should only affect the development installation, because the admin view is missing in the npm 1.4.0 version**.

**Comment by kirrg001** [comment]
You can manually sort this out by copying `current/core/server/admin/views/default-prod.html` to `current/core/server/admin/views/default.html` and restart Ghost via `ghost restart`.

**Comment by Kuzoin** [comment]
Thanks, this works :)

**Comment by kirrg001** [comment]
`1.5.0` was released.

**Comment by seungha-kim** [comment]
@kirrg001 It works well. Thank you!

**Comment by art1fa** [comment]
After upgrading from `1.25.6` to `2.6.0` I get exactly this error after trying to access the admin page. The `current/core/server/admin/views/` is actually empty and copying a `default.html` from a previous version didn't help.
