### ISSUE TITLE
Ghost cannot be started after upgrading to 1.5.2

### ISSUE THREAD

**Issue by fwang49asu** [TryGhost/Ghost#8887]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

1. Upgrading to 1.5.2 by running: 
```sh
ghost upgrade
```
2. Ghost cannot be started from the systemctl or command:
```sh
ghost run
```
### Technical details:

* Ghost Version: 1.5.2
* Ghost CLI Version: 1.0.3
* Node Version: 6.11.2
* Browser/OS: Linux
* Database: MySQL

# error output: 
/usr/lib/node_modules/ghost-cli/lib/process-manager.js:56
        throw error;
        ^
The server has encountered an error.
ghost@myserver:/var/www/ghost$ [2017-08-13 23:18:53] ERROR

NAME: InternalServerError
CODE: ECONNREFUSED
MESSAGE: The server has encountered an error.
level:normal
InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost/versions/1.5.2/core/server/errors.js:9:26)
    at /var/www/ghost/versions/1.5.2/index.js:38:15
    at tryCatcher (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/1.5.2/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/var/www/ghost/versions/1.5.2/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/var/www/ghost/versions/1.5.2/node_modules/mysql/lib/Connection.js:130:18)
    at /var/www/ghost/versions/1.5.2/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/var/www/ghost/versions/1.5.2/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/var/www/ghost/versions/1.5.2/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/var/www/ghost/versions/1.5.2/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/var/www/ghost/versions/1.5.2/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/var/www/ghost/versions/1.5.2/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /var/www/ghost/versions/1.5.2/node_modules/knex/lib/client.js:289:19
    at Promise._execute (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/1.5.2/node_modules/bluebird/js/release/promise.js:79:10)

**Comment by vikaspotluri123** [comment]
Looks like something's funky with your database connection. I'm not going to reply anymore, since this type of question should be asked in the [slack](https://slack.ghost.org/) channel according to the [support guidelines](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md)

**Comment by fwang49asu** [comment]
seems to be a config issue. closing the issue.
