### ISSUE TITLE
Ghost process exited with code: 0

### ISSUE THREAD

**Issue by YOnoda** [TryGhost/Ghost#8939]
Hi,

When I tried running Ghost by `ghost start -D`, it got the error `Ghost process exited with code: 0`. I checked my log file but it only showed the following, which is close to useless.

```
Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.1.1
    Environment: development
    Command: 'ghost start -D'
Message: Ghost process exited with code: 0
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:47:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

What is happening here?

**Comment by acburdine** [comment]
@YOnoda can you re-open this issue in the ghost-cli repo? https://github.com/TryGhost/Ghost-CLI
