### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9089]
Steps to reproduce:

1. Add `0000-00-00 00:00:00` as value for `published_at` of any post.
2. Serve the post on the frontend.

You will see this error, which is unhandled. The blog does not respond.

```
RangeError: [default.hbs] Invalid time value
    at getPublishedDate (/home/ghost/core/server/data/meta/published_date.js:7:53)
    at getMetaData (/home/ghost/core/server/data/meta/index.js:57:24)
```

### Tasks
- [x] add a protection

Ghost: master

**Comment by kirrg001** [comment]
We have a test to protect this case, [see]( https://github.com/TryGhost/Ghost/blob/1.11.0/core/test/utils/fixtures/export/lts/export-003.json#L23) and [see](https://github.com/TryGhost/Ghost/blob/1.11.0/core/test/integration/data/importer/importers/data_spec.js#L97).
