### ISSUE TITLE
Ghost will fail to start if theme name can be interpreted as a number

### ISSUE THREAD

**Issue by WGH-** [TryGhost/Ghost#9182]
Suppose Ghost theme is named `1.4` (which actually happened when I uploaded older Casper theme release downloaded from Github as `1.4.zip`).

When you select the theme in the settings, everything will work fine. Until you restart the Ghost.

It will fail to start again. The reason is that in the database, theme name is saved as `1.4`. Somehow, this string gets converted to number, causing some major confusion. In order to fix this, you'll have to edit the database manually, changing theme name to `"1.4"` (with quotes).

Here is traceback extracted from a log file:
```
The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost/versions/1.14.1/core/server/errors.js:9:26)
    at /var/www/ghost/versions/1.14.1/index.js:38:15
    at tryCatcher (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: Path must be a string. Received 1.4
    at assertPath (path.js:7:11)
    at join (path.js:1218:7)
    at Object.readPackage [as one] (/var/www/ghost/versions/1.14.1/core/server/utils/packages/read-packages.js:46:24)
    at Object.loadOneTheme (/var/www/ghost/versions/1.14.1/core/server/themes/loader.js:20:10)
    at Object.initThemes [as init] (/var/www/ghost/versions/1.14.1/core/server/themes/index.js:31:14)
    at /var/www/ghost/versions/1.14.1/core/server/index.js:58:20
    at tryCatcher (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.14.1/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by WGH-** [comment]
It seems that #8505 was not fixed properly, after all.

**Comment by AileenCGN** [comment]
I can confirm this behaviour. Just renamed the `.zip` file to 1.4 and after restarting getting the same error message.
