### ISSUE TITLE
SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by Fei-Guang** [TryGhost/Ghost#9255]
### Issue Summary
config aws ses as the mail service provide then invite user , the following error reported 
EmailError: Failed to send email. Reason: 140169759840064:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:825:
.
    at EmailError.GhostError (/var/www/ghost/versions/1.17.3/core/server/errors.js:9:26)
    at new EmailError (/var/www/ghost/versions/1.17.3/core/server/errors.js:45:20)
    at MailComposer.returnCallback (/var/www/ghost/versions/1.17.3/core/server/mail/GhostMailer.js:78:31)
    at SMTPConnectionPool._onConnectionError (/var/www/ghost/versions/1.17.3/node_modules/simplesmtp/lib/pool.js:334:17)
    at emitOne (events.js:96:13)
    at SMTPClient.emit (events.js:188:7)
    at SMTPClient._onError (/var/www/ghost/versions/1.17.3/node_modules/simplesmtp/lib/client.js:373:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

### Steps to Reproduce

ghost version: 1.17.3

```
config.production.json

"mail": {
    "transport": "SMTP",
    "options": {
        "host": "email-smtp.us-east-1.amazonaws.com",
        "port": 587,
        "service": "SES",
        "auth": {
            "user": "AKIAI2C5PXS3S5HAP",
            "pass": "AkzHZIQBLGJAUpAuSG5toH7+zHp8SO4Ln"
        }
    }
  }
```

### Technical details:

* Ghost Version:1.17.3
* Node Version:6.12.0
* Browser/OS:chrome
* Database:mysql

**Comment by kirrg001** [comment]
Hi @Fei-Guang!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. 

Try using port 2465.

Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
