### ISSUE TITLE
Error Parsing Filter on every Post page load.

### ISSUE THREAD

**Issue by impguard** [TryGhost/Ghost#9275]
### Issue Summary

Error parsing filter on every post load. I have Ghost setup in Heroku using https://github.com/cobyism/ghost-on-heroku. It's been setup for more than a year, and I recently did the work to migrate to Ghost >1.0.

This involved exporting my old posts running in Postgres, upgrading, and importing them back.

Right now, each time I load a particular post, I see in my Heroku logs:

```
[2017-11-26 22:21:39] ERROR

NAME: ValidationError
MESSAGE: The request failed validation.

level:normal

Error parsing filter
For more information on how to use filter, see http://api.ghost.org/docs/filter
ValidationError: The request failed validation.
    at new ValidationError (/app/node_modules/ghost-ignition/lib/errors/index.js:115:23)
    at Object.combineFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:28:19)
    at fetchAndCombineFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:144:41)
    at applyDefaultAndCustomFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:166:22)
    at Function.findPage (/app/node_modules/ghost/core/server/models/base/index.js:561:24)
    at modelQuery (/app/node_modules/ghost/core/server/api/posts.js:57:32)
    at runTask (/app/node_modules/ghost/core/server/utils/pipeline.js:16:24)
    at /app/node_modules/ghost/core/server/utils/pipeline.js:26:20
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: Query Error: unexpected character in filter at char 1
tags:+id:-5a1b30868f4be80
-----^
Expecting 'NOT', 'LBRACKET', 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', 'GT', 'LT', 'GTE', 'LTE', got 'AND'
    at Object.parser.parseError (/app/node_modules/ghost-gql/dist/parser.js:320:12)
    at Object.parse (/app/node_modules/ghost-gql/dist/parser.js:236:22)
    at Object.exports.parse (/app/node_modules/ghost-gql/lib/gql.js:19:19)
    at /app/node_modules/ghost/core/server/models/plugins/filter.js:25:46
    at arrayMap (/app/node_modules/lodash/lodash.js:660:23)
    at Function.map (/app/node_modules/lodash/lodash.js:9571:14)
    at Object.combineFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:24:24)
    at fetchAndCombineFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:144:41)
    at applyDefaultAndCustomFilters (/app/node_modules/ghost/core/server/models/plugins/filter.js:166:22)
    at Function.findPage (/app/node_modules/ghost/core/server/models/base/index.js:561:24)
    at modelQuery (/app/node_modules/ghost/core/server/api/posts.js:57:32)
    at runTask (/app/node_modules/ghost/core/server/utils/pipeline.js:16:24)
    at /app/node_modules/ghost/core/server/utils/pipeline.js:26:20
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
```

### Steps to Reproduce

I believe this is my environment specific, was hoping for some clues with a potential setup problem.

1. Create a new post
2. Publish the post
3. Navigate to it from the main page.

### Technical details:

* Ghost Version: 1.18.0
* Node Version: 6.11.x
* Browser/OS: Chrome
* Database: JawsDB

**Comment by AileenCGN** [comment]
Hi @impguard, 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

**Comment by impguard** [comment]
Will do. Sorry about that!
