### ISSUE TITLE
Theme activation errror :-Error: Request was rejected because it was invalid

### ISSUE THREAD

**Issue by Samimveza** [TryGhost/Ghost#9412]
I've been getting this error when i'm upload a theme to ghost.

"Error: Request was rejected because it was invalid
    at r.n (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:2653:13)
    at r.n (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:8242:3)
    at new r (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:8242:47)
    at o.handleResponse (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:8270:38)
    at o.handleResponse (http://www.vidhoster.info/ghost/assets/ghost.min-cacd557831bf335039038d2adb92bd95.js:1139:679)
    at o.n [as handleResponse] (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:4127:9)
    at o.<anonymous> (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:8257:88)
    at u (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:1319:118)
    at Object.fireWith [as rejectWith] (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:1320:710)
    at x (http://www.vidhoster.info/ghost/assets/vendor.min-13c16025984b9d69673007089966ca90.js:1593:468)"

**The payload** is The custom error module does not recognize this error.

**Comment by kirrg001** [comment]
Hey @Samimveza!

Sorry that you are having trouble.

But please swing by our [slack](https://slack.ghost.org/) community - https://slack.ghost.org and ask in the `#help` channel. 

Furthermore, please respect our [support guidelines](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) before raising an issue. 
And if you are convinced that you discovered a bug, please don't just throw an error stack at us without steps to reproduce or without giving us enough context.

We can always re-open the issue if it turns out it's a problem in Ghost.

**Comment by Samimveza** [comment]
Ok, Thanks Kirrgg001, think i know why i've got the error, my theme is based on an old ghost version.
