### ISSUE TITLE
Startup error after upgrading to 1.21.1

### ISSUE THREAD

**Issue by thedotedge** [TryGhost/Ghost#9450]
### Issue Summary

Ghost fails to start after upgrade.

### Steps to Reproduce
```
ghost start
✔ Checking current folder permissions
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
Running sudo command: systemctl start ghost_freelancehunt-com
? Password [hidden]
Running sudo command: systemctl stop ghost_freelancehunt-com
✖ Starting Ghost
A GhostError occurred.

Message: Ghost did not start.
Suggestion: journalctl -u ghost_freelancehunt-com -n 50

Debug Information:
    OS: linux, v4.14.12-x86_64-linode92
    Node Version: v6.12.2
    Ghost-CLI Version: 1.5.1
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost/.ghost/logs/ghost-cli-debug-2018-02-10T12_10_33_156Z.log

Try running ghost doctor to check your system for known issues.
```

```
cat  /home/ghost/.ghost/logs/ghost-cli-debug-2018-02-10T12_10_33_156Z.log
Debug Information:
    OS: linux, v4.14.12-x86_64-linode92
    Node Version: v6.12.2
    Ghost-CLI Version: 1.5.1
    Environment: production
    Command: 'ghost start'
Message: Ghost did not start.
Suggestion: journalctl -u ghost_freelancehunt-com -n 50
Stack: Error: Ghost did not start.
    at connectToGhostSocket.then.catch (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:92:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Original Error Message:
Message: connect ECONNREFUSED 127.0.0.1:2369
Stack: Error: connect ECONNREFUSED 127.0.0.1:2369
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```
No config changes has been done before the upgrade and it contains different IP for ghost:
```
"server": {
    "port": 2369,
    "host": "192.168.157.188"
  },
``

No other service is listening on port 2369 and ghost is not running. Running `ghost run` works fine.

### Technical details:

* Ghost Version: 1.21.1
* Ghost-CLI version: 1.5.1
* Node Version: v6.12.2
* Browser/OS: CentOS 7

**Comment by kirrg001** [comment]
> Message: Ghost did not start.
> Suggestion: journalctl -u ghost_freelancehunt-com -n 50

You have to run this command to get the reason why Ghost was not started. Please try to read the error message more carefully in the future.

---

Please use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org for any questions or raise a bug in the [Ghost CLI](https://github.com/TryGhost/Ghost-CLI) repository. Thanks!

**Comment by thedotedge** [comment]
Hi Katharina, I did not attach the output of this command because it was empty. 

```
journalctl -u ghost_freelancehunt-com -n 50
No journal files were found.
-- No entries --
```

**Comment by thedotedge** [comment]
Cross-linking to https://github.com/TryGhost/Ghost-CLI/issues/639
