### ISSUE TITLE
Ghost upgrade failed on knex migration run

### ISSUE THREAD

**Issue by BlueHatbRit** [TryGhost/Ghost#9537]
During a ghost upgrade from 1.21.6 to 1.21.7 I encountered the following error. A `ghost update --force` seems to have sorted it but I thought I'd submit the issue with the error details to try and understand what might have gone wrong.

### Steps to Reproduce

1. Install Ghost 1.21.6 on Ubuntu 16.04.3 (LTS) to /var/www using the ghost-cli (with a local mysql install).
2. Run `ghost update` on the /var/www installation to move from Ghost 1.21.6 to 1.21.7 (the latest).

The following error was produced:

```
✔ Checking for available migrations
✔ Checking for latest Ghost version
ℹ Downloading and updating Ghost [skipped]
Running sudo command: systemctl stop ghost_www-elliotblackburn-com
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
sudo: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate: command not found

'


Debug Information:
    Node Version: v8.9.4
    Ghost-CLI Version: 1.4.2
    Environment: production
    Command: 'ghost update'
```

Here is the log output:

```
Debug Information:
    Node Version: v8.9.4
    Ghost-CLI Version: 1.4.2
    Environment: production
    Command: 'ghost update'
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --in$
sudo: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate: command not found

'

Stack: Error: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate $
sudo: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate: command not found


    at Promise.all.then.arr (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Code: 1
```

### Technical details:

* Ghost Version: 1.21.6
* Node Version: 8.9.4
* Browser/OS: n/a
* Database: MySQL 14.14 Distrib 5.7.21

**Comment by BlueHatbRit** [comment]
No worries, apologies for getting it in the wrong repo!

**Comment by kirrg001** [comment]
@BlueHatbRit No problem :)
