### ISSUE TITLE
DatabaseIsNotOkError problem

### ISSUE THREAD

**Issue by adanteng** [TryGhost/Ghost#9622]
After run `ghost update`, can not start again, need some help.

```
lihao@ubuntu:~/ghost$ ghost version
Ghost-CLI version: 1.7.3
Ghost Version (at ~/ghost): 1.22.5
```

```
lihao@ubuntu:~/ghost$ knex-migrator migrate
[2018-05-10 06:48:56] INFO Finished database migration!
lihao@ubuntu:~/ghost$ ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
Running sudo command: node current/index.js
[2018-05-10 06:49:02] WARN knex-migrator is skipping 1.9
[2018-05-10 06:49:02] WARN Current version in MigratorConfig.js is smaller then requested version, use --force to proceed!
[2018-05-10 06:49:02] WARN Please run `knex-migrator migrate --v 1.9 --force` to proceed!
[2018-05-10 06:49:02] ERROR

NAME: DatabaseIsNotOkError
CODE: DB_NEEDS_MIGRATION
MESSAGE: Migrations are missing. Please run `knex-migrator migrate`.

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
DatabaseIsNotOkError: Migrations are missing. Please run `knex-migrator migrate`.
    at DatabaseIsNotOkError.KnexMigrateError (/home/lihao/ghost/versions/1.22.5/node_modules/knex-migrator/lib/errors.js:7:26)
    at new DatabaseIsNotOkError (/home/lihao/ghost/versions/1.22.5/node_modules/knex-migrator/lib/errors.js:19:26)
    at /home/lihao/ghost/versions/1.22.5/node_modules/knex-migrator/lib/index.js:1066:27
    at /home/lihao/ghost/versions/1.22.5/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/lihao/ghost/versions/1.22.5/node_modules/lodash/lodash.js:3010:24)
    at /home/lihao/ghost/versions/1.22.5/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/home/lihao/ghost/versions/1.22.5/node_modules/lodash/lodash.js:9342:14)
    at /home/lihao/ghost/versions/1.22.5/node_modules/knex-migrator/lib/index.js:1063:15
    at tryCatcher (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/lihao/ghost/versions/1.22.5/node_modules/bluebird/js/release/promise.js:524:17)
```

**Comment by AileenCGN** [comment]
Hey @adanteng   👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

This is also the wrong repository. If you think this is a bug, please open an issue in the [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI) repository and provide as much information as possible. Otherwise there's no way for us to reproduce your case and fix it.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
