### ISSUE TITLE
After upload ico, MESSAGE: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by sqvds** [TryGhost/Ghost#9672]
### Issue Summary

ERROR [2018-06-07 13:32:15] "GET /favicon.ico" 500 3ms

NAME: InternalServerError
MESSAGE: Cannot read property 'then' of undefined

level:normal

InternalServerError: Cannot read property 'then' of undefined
    at new GhostError (/var/lib/ghost/versions/1.23.1/core/server/lib/common/errors.js:9:26)
    at prepareError (/var/lib/ghost/versions/1.23.1/core/server/web/middleware/error-handler.js:39:19)
    at Layer.handle_error (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)

TypeError: Cannot read property 'then' of undefined
    at serveFavicon (/var/lib/ghost/versions/1.23.1/core/server/web/middleware/serve-favicon.js:54:21)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at urlRedirects (/var/lib/ghost/versions/1.23.1/core/server/web/middleware/url-redirects.js:111:5)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:174:3)
    at router (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/var/lib/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:635:15)

### To Reproduce

I just upload my ico， and  begain occer this error

### Technical details:

* Ghost Version: 1.23.1
* Node Version: 6
* Browser/OS: chrome/windows
* Database: mysql

**Comment by kirrg001** [comment]
Hi @sqvds  👋

This is for sure caused because you are using a custom storage adapter.

Please use our [forum](https://forum.ghost.org) for help. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.
