### ISSUE TITLE
Custom Storage Module

### ISSUE THREAD

**Issue by huuquynh** [TryGhost/Ghost#9746]
### Issue Summary

Firstly, I tried with Google Cloud Storage module from official document: https://github.com/thombuchi/ghost-google-cloud-storage. It could not start ghost, and I think it is outdated or too old, because I found another one: https://github.com/O-io/ghost-storage-adapter-gcloud

With the new one, the ghost starts normal, but when beginning browse site, it was stuck at loading page, likes overtime. I think maybe it's from the plugin. I had posted an issue to the plugin too.

But I tried another one: ghost-github, and I got the same error. I removed old custom storage plugin first, only using one storage plugin.

Here the error log:

`(node:21383) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
(node:21383) Warning: a promise was created in a handler at /home/leo/ghost-1.24.9/core/server/services/routing/controllers/collection.js:67:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/home/leo/ghost-1.24.9/node_modules/bluebird/js/release/promise.js:196:13)
ERROR [2018-07-23 07:28:05] "GET /" 500 120004ms

NAME: InternalServerError
MESSAGE: [default.hbs] Cannot read property 'then' of undefined

level:normal

InternalServerError: [default.hbs] Cannot read property 'then' of undefined
`

### To Reproduce

1. Install Ghost with yarn, without ghost-cli, because I want to deploy Ghost running on Google App Engine.
2. Add custom storage modules to try on localhost.

### Technical details:

* Ghost Version: 1.24.9
* Node Version: 8.11.3
* Browser/OS: Chrome/Linux
* Database: mysql

**Comment by m1guelpf** [comment]
Had this same issue, seems to be caused by .getImageDimensions call on the ghost_head template tag. My workaround was to use the unreleased feature apps to make a ghost_head tag that didn't include the image dimensions. Want me to share it?

**Comment by huuquynh** [comment]
Oh. You're right. Take a deep look under the stack traces:

```
    at getImageSizeFromFilePath (/home/leo/ghost-1.24.9/core/server/lib/image/image-size.js:188:9)
    at Object.getImageSizeFromUrl (/home/leo/ghost-1.24.9/core/server/lib/image/image-size.js:87:16)
    at Object.getCachedImageSizeFromUrl (/home/leo/ghost-1.24.9/core/server/lib/image/cached-image-size-from-url.js:21:26)
    at getImageDimensions (/home/leo/ghost-1.24.9/core/server/data/meta/image-dimensions.js:14:30)
    at getMetaData (/home/leo/ghost-1.24.9/core/server/data/meta/index.js:97:26)
    at Object.ghost_head (/home/leo/ghost-1.24.9/core/server/helpers/ghost_head.js:124:12)

```
Yes. Please share to me your temporary fixed code! Many thanks!

**Comment by m1guelpf** [comment]
@huuquynh You'll need to create a `apps/add-tags` folder inside your content directory, then add this three files inside:
<details>
<summary>package.json</summary>

``` json
{
    "name": "add-tags",
    "version": "0.0.1",
    "dependencies": {
        "ghost-app": "0.0.2"
    },
    "ghost": {
        "permissions": {
            "helpers": [
                "meta_tags"
            ]
        }
    }
}
```
</details>

<details>
<summary>index.js</summary>

``` js
var App = require('ghost-app'),
    AddTags,
    {settingsCache, config, blogIcon, escapeExpression, SafeString} = require('ghost/core/server/helpers/proxy'),
    path = require('path'),
    {getMetaData, finaliseStructuredData, getAjaxHelper, _} = require(path.resolve(path.dirname(module.parent.filename), '../../../../../../content/apps/add-tags/helpers'))

AddTags = App.extend({

    install: function () {},

    uninstall: function () {},

    deactivate: function () {},
    
    activate: function () {
        this.app.helpers.register('meta_tags', this.handleMetaTags);
    },

    handleMetaTags: function (options) {
        // if server error page do nothing
        if (options.data.root.statusCode >= 500) {
            return;
        }

        var head = [],
            dataRoot = options.data.root,
            context = dataRoot._locals.context ? dataRoot._locals.context : null,
            client = dataRoot._locals.client,
            safeVersion = dataRoot._locals.safeVersion,
            postCodeInjection = dataRoot && dataRoot.post ? dataRoot.post.codeinjection_head : null,
            globalCodeinjection = settingsCache.get('ghost_head'),
            useStructuredData = !config.isPrivacyDisabled('useStructuredData'),
            referrerPolicy = config.get('referrerPolicy') ? config.get('referrerPolicy') : 'no-referrer-when-downgrade',
            favicon = blogIcon.getIconUrl(),
            iconType = blogIcon.getIconType(favicon)
            metaData = getMetaData(dataRoot, dataRoot);
        
        if (context) {
            // head is our main array that holds our meta data
            if (metaData.metaDescription && metaData.metaDescription.length > 0) {
                head.push('<meta name="description" content="' + escapeExpression(metaData.metaDescription) + '" />');
            }

            head.push('<link rel="shortcut icon" href="' + favicon + '" type="image/' + iconType + '" />');
            head.push('<link rel="canonical" href="' +
                escapeExpression(metaData.canonicalUrl) + '" />');
            head.push('<meta name="referrer" content="' + referrerPolicy + '" />');

            // show amp link in post when 1. we are not on the amp page and 2. amp is enabled
            if (context.includes('post') && !context.includes('amp') && settingsCache.get('amp')) {
                head.push('<link rel="amphtml" href="' +
                    escapeExpression(metaData.ampUrl) + '" />');
            }

            if (metaData.previousUrl) {
                head.push('<link rel="prev" href="' +
                    escapeExpression(metaData.previousUrl) + '" />');
            }

            if (metaData.nextUrl) {
                head.push('<link rel="next" href="' +
                    escapeExpression(metaData.nextUrl) + '" />');
            }

            if (!context.includes('paged') && useStructuredData) {
                head.push('');
                head.push.apply(head, finaliseStructuredData(metaData));
                head.push('');

                if (metaData.schema) {
                    head.push('<script type="application/ld+json">\n' +
                        JSON.stringify(metaData.schema, null, '    ') +
                        '\n    </script>\n');
                }
            }

            if (client && client.id && client.secret && !context.includes('amp')) {
                head.push(getAjaxHelper(client.id, client.secret));
            }
        }
        head.push('<meta name="generator" content="MP Blog ' +
            escapeExpression(safeVersion) + '" />');

        head.push('<link rel="alternate" type="application/rss+xml" title="' +
            escapeExpression(metaData.blog.title) + '" href="' +
            escapeExpression(metaData.rssUrl) + '" />');

        // no code injection for amp context!!!
        if (!context.includes('amp')) {
            if (!_.isEmpty(globalCodeinjection)) {
                head.push(globalCodeinjection);
            }

            if (!_.isEmpty(postCodeInjection)) {
                head.push(postCodeInjection);
            }
        }
        // return JSON.stringify(head);
        return new SafeString(head.join('\n    ').trim());
    }
});

module.exports = AddTags;
```
</details>

<details>
<summary>helpers.js</summary>

```
var Promise = require('bluebird'),
    settingsCache = require('ghost/core/server/services/settings/cache'),
    urlService = require('ghost/core/server/services/url'),
    common = require('ghost/core/server/lib/common'),
    getUrl = require('ghost/core/server/data/meta/url'),
    getCanonicalUrl = require('ghost/core/server/data/meta/canonical_url'),
    getAmpUrl = require('ghost/core/server/data/meta/amp_url'),
    getPaginatedUrl = require('ghost/core/server/data/meta/paginated_url'),
    getAuthorUrl = require('ghost/core/server/data/meta/author_url'),
    getBlogLogo = require('ghost/core/server/data/meta/blog_logo'),
    getRssUrl = require('ghost/core/server/data/meta/rss_url'),
    getTitle = require('ghost/core/server/data/meta/title'),
    getDescription = require('ghost/core/server/data/meta/description'),
    getCoverImage = require('ghost/core/server/data/meta/cover_image'),
    getAuthorImage = require('ghost/core/server/data/meta/author_image'),
    getAuthorFacebook = require('ghost/core/server/data/meta/author_fb_url'),
    getCreatorTwitter = require('ghost/core/server/data/meta/creator_url'),
    getKeywords = require('ghost/core/server/data/meta/keywords'),
    getPublishedDate = require('ghost/core/server/data/meta/published_date'),
    getModifiedDate = require('ghost/core/server/data/meta/modified_date'),
    getOgType = require('ghost/core/server/data/meta/og_type'),
    getOgImage = require('ghost/core/server/data/meta/og_image'),
    getTwitterImage = require('ghost/core/server/data/meta/twitter_image'),
    getStructuredData = require('ghost/core/server/data/meta/structured_data'),
    getSchema = require('ghost/core/server/data/meta/schema'),
    getExcerpt = require('ghost/core/server/data/meta/excerpt'),
    _ = require('lodash'),
    {escapeExpression, metaData} = require('ghost/core/server/helpers/proxy');

function getMetaData(data, root) {
    var metaData = {
            url: getUrl(data, true),
            canonicalUrl: getCanonicalUrl(data),
            ampUrl: getAmpUrl(data),
            previousUrl: getPaginatedUrl('prev', data, true),
            nextUrl: getPaginatedUrl('next', data, true),
            authorUrl: getAuthorUrl(data, true),
            rssUrl: getRssUrl(data, true),
            metaTitle: getTitle(data, root),
            metaDescription: getDescription(data, root) || null,
            coverImage: {
                url: getCoverImage(data, true)
            },
            authorImage: {
                url: getAuthorImage(data, true)
            },
            ogImage: {
                url: getOgImage(data, true)
            },
            ogTitle: getTitle(data, root, {
                property: 'og'
            }),
            ogDescription: getDescription(data, root, {
                property: 'og'
            }),
            twitterImage: getTwitterImage(data, true),
            twitterTitle: getTitle(data, root, {
                property: 'twitter'
            }),
            twitterDescription: getDescription(data, root, {
                property: 'twitter'
            }),
            authorFacebook: getAuthorFacebook(data),
            creatorTwitter: getCreatorTwitter(data),
            keywords: getKeywords(data),
            publishedDate: getPublishedDate(data),
            modifiedDate: getModifiedDate(data),
            ogType: getOgType(data),
            // @TODO: pass into each meta helper - wrap each helper
            blog: {
                title: settingsCache.get('title'),
                description: settingsCache.get('description'),
                url: urlService.utils.urlFor('home', true),
                facebook: settingsCache.get('facebook'),
                twitter: settingsCache.get('twitter'),
                timezone: settingsCache.get('active_timezone'),
                navigation: settingsCache.get('navigation'),
                icon: settingsCache.get('icon'),
                cover_image: settingsCache.get('cover_image'),
                logo: getBlogLogo(),
                amp: settingsCache.get('amp')
            }
        },
        customExcerpt,
        metaDescription,
        fallbackExcerpt;

    // TODO: cleanup these if statements
    if (data.post) {
        // There's a specific order for description fields (not <meta name="description" /> !!) in structured data
        // and schema.org which is used the description fields (see https://github.com/TryGhost/Ghost/issues/8793):
        // 1. CASE: custom_excerpt is populated via the UI
        // 2. CASE: no custom_excerpt, but meta_description is poplated via the UI
        // 3. CASE: fall back to automated excerpt of 50 words if neither custom_excerpt nor meta_description is provided
        customExcerpt = data.post.custom_excerpt;
        metaDescription = data.post.meta_description;
        fallbackExcerpt = data.post.html ? getExcerpt(data.post.html, {
            words: 50
        }) : '';

        metaData.excerpt = customExcerpt ? customExcerpt : metaDescription ? metaDescription : fallbackExcerpt;
    }

    if (data.post && data.post.primary_author && data.post.primary_author.name) {
        metaData.authorName = data.post.primary_author.name;
    }
    metaData.structuredData = getStructuredData(metaData);
    metaData.schema = getSchema(metaData, data);
    return metaData;

    return new Promise(function () {

    }).catch(function (err) {
        common.logging.error(err);
        return metaData;
    });
}

function finaliseStructuredData(metaData) {
    var head = [];

    _.each(metaData.structuredData, function (content, property) {
        if (property === 'article:tag') {
            _.each(metaData.keywords, function (keyword) {
                if (keyword !== '') {
                    keyword = escapeExpression(keyword);
                    head.push(writeMetaTag(property,
                        escapeExpression(keyword)));
                }
            });
            head.push('');
        } else if (content !== null && content !== undefined) {
            head.push(writeMetaTag(property,
                escapeExpression(content)));
        }
    });

    return head;
}

function writeMetaTag(property, content, type) {
    type = type || property.substring(0, 7) === 'twitter' ? 'name' : 'property';
    return '<meta ' + type + '="' + property + '" content="' + content + '" />';
}

function getAjaxHelper(clientId, clientSecret) {
    return '<script src="' +
        metaData.getAssetUrl('public/ghost-sdk.js', true) +
        '"></script>\n' +
        '<script>\n' +
        'ghost.init({\n' +
        '\tclientId: "' + clientId + '",\n' +
        '\tclientSecret: "' + clientSecret + '"\n' +
        '});\n' +
        '</script>';
}

module.exports = {
    getMetaData,
    finaliseStructuredData,
    getAjaxHelper,
    _
};
```
</details>

Then, you'll need to enable the app by following [this guide](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs#installing) (the app name is `add-tags`).

**Comment by huuquynh** [comment]
Thanks in advance! I'm going to try now and will report soon.

**Comment by huuquynh** [comment]
No luck. Nothing change. I had read but do not understand what is the way that the add-tas app solves the issue.

**Comment by m1guelpf** [comment]
Oh right, forgot the last part. Once you've installed the app, replace the {{ghost_head}} tag with {{meta_tags}} in your theme files

**Comment by huuquynh** [comment]
It's very strange. While waiting for your replies, I'm going to find other plugins, and found one: https://github.com/wangkezun/ghost-github-storage. It runs so well, without using your app and no change in theme to replace {{ghost_head}}.

Thank you very much. But the issue will be there with others plugins.
