### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by abhijithvijayan** [TryGhost/Ghost#9748]
Cannot read property 'url' of undefined error pops up from now on trying to publish posts.

![capture](https://user-images.githubusercontent.com/34790378/43145985-cf934f56-8f7d-11e8-95c0-87e56515113a.JPG)

and I noticed this 

![capture](https://user-images.githubusercontent.com/34790378/43146474-e88b6196-8f7e-11e8-851f-9f85904b3f84.JPG)

even though this option was already on.

![capture](https://user-images.githubusercontent.com/34790378/43146307-9d5aaf10-8f7e-11e8-962a-4db0aa1e30f9.JPG)

- node vv8.11.3
- Ghost-CLI version: 1.8.0
- Ghost Version (at /home/ghost): 1.23.1
- mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

**Comment by kirrg001** [comment]
Hey!

Can you please share the error log from your server?

See [ghost log](https://docs.ghost.org/docs/cli-log).

Thanks!

**Comment by abhijithvijayan** [comment]
[2018-07-24 20:37:27] INFO "GET /ghost/api/v0.1/themes/" 200 117ms
[2018-07-24 20:37:27] INFO "GET /ghost/api/v0.1/themes/" 200 117ms
[2018-07-24 20:37:31] WARN Theme's file locales/en.json not found.
[2018-07-24 20:37:31] WARN Theme's file locales/en.json not found.
[2018-07-24 20:37:31] INFO "PUT /ghost/api/v0.1/themes/casper-final/activate/" 200 303ms
[2018-07-24 20:37:31] INFO "PUT /ghost/api/v0.1/themes/casper-final/activate/" 200 303ms
[2018-07-24 20:37:49] INFO "GET /ghost/api/v0.1/tags/?limit=all" 200 33ms
[2018-07-24 20:37:49] INFO "GET /ghost/api/v0.1/tags/?limit=all" 200 33ms
[2018-07-24 20:37:49] INFO "GET /ghost/api/v0.1/users/?limit=all&include=roles" 200 58ms
[2018-07-24 20:37:49] INFO "GET /ghost/api/v0.1/users/?limit=all&include=roles" 200 58ms
[2018-07-24 20:37:56] INFO "GET /ghost/api/v0.1/slugs/post/temp-post/" 200 45ms
[2018-07-24 20:37:56] INFO "GET /ghost/api/v0.1/slugs/post/temp-post/" 200 45ms
[2018-07-24 20:37:56] INFO "POST /ghost/api/v0.1/posts/?include=authors,tags,authors.roles" 201 230ms
[2018-07-24 20:37:56] INFO "POST /ghost/api/v0.1/posts/?include=authors,tags,authors.roles" 201 230ms
[2018-07-24 20:38:01] INFO "PUT /ghost/api/v0.1/posts/5b5740ccdac6374689278ed6/?include=authors,tags,authors.roles" 200 116ms
[2018-07-24 20:38:01] INFO "PUT /ghost/api/v0.1/posts/5b5740ccdac6374689278ed6/?include=authors,tags,authors.roles" 200 116ms
[2018-07-24 20:38:08] ERROR "PUT /ghost/api/v0.1/posts/5b5740ccdac6374689278ed6/?include=authors,tags,authors.roles" 500 122ms

NAME: InternalServerError
MESSAGE: Cannot read property 'url' of undefined

level: normal

InternalServerError: Cannot read property 'url' of undefined
    at new GhostError (/home/ghost/versions/1.23.1/core/server/lib/common/errors.js:9:26)
    at prepareError (/home/ghost/versions/1.23.1/core/server/web/middleware/error-handler.js:39:19)
    at Layer.handle_error (/home/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:635:15
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:260:14)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/route.js:127:14)
    at onAPIError (/home/ghost/versions/1.23.1/core/server/api/index.js:290:13)

TypeError: Cannot read property 'url' of undefined
    at ping (/home/ghost/versions/1.23.1/core/server/services/slack.js:36:23)
    at EventRegistry.listener (/home/ghost/versions/1.23.1/core/server/services/slack.js:79:5)
    at emitTwo (events.js:131:20)
    at EventRegistry.emit (events.js:214:7)
    at _.each (/home/ghost/versions/1.23.1/core/server/models/base/index.js:136:35)
    at arrayEach (/home/ghost/versions/1.23.1/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/home/ghost/versions/1.23.1/node_modules/lodash/lodash.js:9342:14)
    at Function.options.transacting.once (/home/ghost/versions/1.23.1/core/server/models/base/index.js:134:19)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Function.emit (events.js:211:7)
    at Function.t.commit (/home/ghost/versions/1.23.1/core/server/models/plugins/transaction-events.js:14:19)
    at Child.<anonymous> (/home/ghost/versions/1.23.1/node_modules/knex/lib/transaction.js:87:31)
    at Child.tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)

[2018-07-24 20:38:08] ERROR "PUT /ghost/api/v0.1/posts/5b5740ccdac6374689278ed6/?include=authors,tags,authors.roles" 500 122ms

NAME: InternalServerError
MESSAGE: Cannot read property 'url' of undefined

level: normal

InternalServerError: Cannot read property 'url' of undefined
    at new GhostError (/home/ghost/versions/1.23.1/core/server/lib/common/errors.js:9:26)
    at prepareError (/home/ghost/versions/1.23.1/core/server/web/middleware/error-handler.js:39:19)
    at Layer.handle_error (/home/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/ghost/versions/1.23.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:315:13)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:275:10)
    at /home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:635:15
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/index.js:260:14)
    at next (/home/ghost/versions/1.23.1/node_modules/express/lib/router/route.js:127:14)
    at onAPIError (/home/ghost/versions/1.23.1/core/server/api/index.js:290:13)

TypeError: Cannot read property 'url' of undefined
    at ping (/home/ghost/versions/1.23.1/core/server/services/slack.js:36:23)
    at EventRegistry.listener (/home/ghost/versions/1.23.1/core/server/services/slack.js:79:5)
    at emitTwo (events.js:131:20)
    at EventRegistry.emit (events.js:214:7)
    at _.each (/home/ghost/versions/1.23.1/core/server/models/base/index.js:136:35)
    at arrayEach (/home/ghost/versions/1.23.1/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/home/ghost/versions/1.23.1/node_modules/lodash/lodash.js:9342:14)
    at Function.options.transacting.once (/home/ghost/versions/1.23.1/core/server/models/base/index.js:134:19)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Function.emit (events.js:211:7)
    at Function.t.commit (/home/ghost/versions/1.23.1/core/server/models/plugins/transaction-events.js:14:19)
    at Child.<anonymous> (/home/ghost/versions/1.23.1/node_modules/knex/lib/transaction.js:87:31)
    at Child.tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)

[2018-07-24 20:38:08] ERROR

NAME: InternalServerError
MESSAGE: Response code 405 (Method Not Allowed)

level: normal

The xmlrpc service was unable to send a ping request, your blog will continue to function.
If you get this error repeatedly, please seek help on http://docs.ghost.org.
InternalServerError: Response code 405 (Method Not Allowed)
    at new GhostError (/home/ghost/versions/1.23.1/core/server/lib/common/errors.js:9:26)
    at /home/ghost/versions/1.23.1/core/server/services/xmlrpc.js:75:38
    at tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

HTTPError: Response code 405 (Method Not Allowed)
    at stream.catch.then.data (/home/ghost/versions/1.23.1/node_modules/got/index.js:182:13)
    at tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

[2018-07-24 20:38:08] ERROR

NAME: InternalServerError
MESSAGE: Response code 405 (Method Not Allowed)

level: normal

The xmlrpc service was unable to send a ping request, your blog will continue to function.
If you get this error repeatedly, please seek help on http://docs.ghost.org.
InternalServerError: Response code 405 (Method Not Allowed)
    at new GhostError (/home/ghost/versions/1.23.1/core/server/lib/common/errors.js:9:26)
    at /home/ghost/versions/1.23.1/core/server/services/xmlrpc.js:75:38
    at tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

HTTPError: Response code 405 (Method Not Allowed)
    at stream.catch.then.data (/home/ghost/versions/1.23.1/node_modules/got/index.js:182:13)
    at tryCatcher (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ghost/versions/1.23.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by kirrg001** [comment]
Ah okay i see. Please upgrade to the latest Ghost version with the CLI.
This was fixed in [1.24.2](https://github.com/TryGhost/Ghost/releases/tag/1.24.2).

**Comment by abhijithvijayan** [comment]
Thanks
