### ISSUE TITLE
[1.25.0] Migrations fail for archaic imported posts

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost#9751]
### Issue Summary

When trying to update Ghost from 1.24.8 to 1.25.0, migrations fail.

### More Information

I migrated to Ghost last year, from WordPress. In WordPress, I had a couple of post drafts which were just titles and no content

The migration was WP(??)-> Ghost(LTS)-> Ghost(1.3??)

I didn't run into any issues with the migration, and everything was going well until the 1.25.0 migrations ran in the CLI.

<details>
<summary> Ghost-CLI Debug log</summary>
<pre>Debug Information:
    OS: Debian, v9.5
    Node Version: v8.11.2
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost update --verbose'
Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
Suggestion: ghost update --rollback
--------------- stderr ---------------
[2018-07-24 16:18:55] ERROR

NAME: MigrationScriptError
MESSAGE: Cannot read property 'cards' of null

level:normal

Error occurred while executing the following migration: 1-update-koenig-beta-html.js
MigrationScriptError: Cannot read property 'cards' of null
    at MigrationScriptError.KnexMigrateError (.../ghost/versions/1.25.0/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (.../ghost/versions/1.25.0/node_modules/knex-migrator/lib/errors.js:26:26)
    at .../ghost/versions/1.25.0/node_modules/knex-migrator/lib/index.js:585:19
    at tryCatcher (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

TypeError: Cannot read property 'cards' of null
    at Promise.map.concurrency (.../ghost/versions/1.25.0/core/server/data/migrations/versions/1.25/1-update-koenig-beta-html.js:48:31)
    at tryCatcher (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (.../ghost/versions/1.25.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
</pre>
</details>

<br />

After rolling back to 1.24.8, I did some digging, and found a couple of posts where the mobiledoc field was null (`SELECT id FROM posts WHERE mobiledoc IS NULL;`), although I have no clue where in the migration from WP to LTS to 1.x the `null` value was set

```bash
> SELECT title,html,mobiledoc FROM posts WHERE id='598cf99b89042c2622eea9df'
+----------------------------------------+------+-----------+
| title                                  | html | mobiledoc |
+----------------------------------------+------+-----------+
| {draft title}                          |      | NULL      |
+----------------------------------------+------+-----------+
```

I went to edit the post (`https://my.blog/ghost/#/editor/598cf99b89042c2622eea9df`), and just saved with `ctrl+s` without making any changes...

```bash
> SELECT title,html,mobiledoc FROM posts WHERE id='598cf99b89042c2622eea9df';
+----------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------+
| title                                  | html                                 | mobiledoc                                                                                 |
+----------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------+
| {draft title}                          | <div class="kg-post"><p></p></div>   | {"version":"0.3.1","markups":[],"atoms":[],"cards":[],"sections":[[1,"p",[[0,[],0,""]]]]} |
+----------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------+
```

Attempting to update Ghost now is successful, I'm on 1.25.0 now

### Technical details:

* Ghost Version: 1.24.8 -> 1.25.0
* Node Version: v8.11.2
* Browser/OS: N/A
* Database: MySQL

**Comment by kirrg001** [comment]
> Would there be any disadvantage w/ falling back to '' instead of null? 

Hm i don't think so, `null` is fine IMO. cc @kevinansfield

**Comment by kirrg001** [comment]
I would suggest to just fix the migration script in 1.25 and in Ghost 2.0 we have to iterate over all posts anyway and do:

- adapt importer to not store null values for mobiledoc fields
- if mobiledoc is null, set empty mobiledoc structure

**Comment by vikaspotluri123** [comment]
That's what I was thinking as well 😄

**Comment by kirrg001** [comment]
The fix was merged and will be released asap.

I have added TODO to https://github.com/TryGhost/Ghost/pull/9750. We need to think about if we want to do something against the mobiledoc field being null in general. That would mean we also need to protect saving null values from external clients. I am not 100% sure yet, need some time to think about it.

I'll close this issue for now.
