### ISSUE TITLE
Import content failed - Cannot read property 'users' of undefined

### ISSUE THREAD

**Issue by FooBarWidget** [TryGhost/Ghost#9754]
### Issue Summary

I'm unable to import into a local dev install my export of my production blog. I get this error: Cannot read property 'users' of undefined.

I'm aware of the version discrepancy between dev and production. I'm trying to upgrade Ghost in production to the latest version, but due to various issues (environmental cruft that's built up since the Ghost 0.7 days) I can't easily do that. As an intermediate step I'm trying to get Ghost working in a local dev environment first through export/import, after which I will try to migrate my production Ghost to an entirely new and clean environment. But I'm failing at this intermediate step.

### To Reproduce

1. Export a production blog.
2. Create a local dev install with a single user.
3. Go to Labs and import the exported JSON there.

I see the following stack trace in the log file:

~~~
InternalServerError: Cannot read property 'users' of undefined
    at new GhostError (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/common/errors.js:9:26)
    at prepareError (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/web/middleware/error-handler.js:42:19)
    at Layer.handle_error (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:315:13)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:315:13)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:275:10)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:635:15
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/index.js:260:14)
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/route.js:127:14)
    at onAPIError (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/api/index.js:291:13)

TypeError: Cannot read property 'users' of undefined
    at new Base (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/importers/data/base.js:30:56)
    at new UsersImporter (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/importers/data/users.js:8:9)
    at Object.init (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/importers/data/index.js:23:27)
    at Object.doImport (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/importers/data/index.js:52:14)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/index.js:332:37
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/sequence.js:10:21
From previous event:
    at sequence (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/sequence.js:9:20)
    at ImportManager.doImport (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/index.js:337:16)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/index.js:368:25
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ImportManager.importFromFile (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/data/importer/index.js:365:12)
    at importContent (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/api/db.js:86:29)
    at runTask (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/pipeline.js:16:24)
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/pipeline.js:26:20
From previous event:
    at /Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/pipeline.js:25:24
    at runCallback (timers.js:810:20)
From previous event:
    at pipeline (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/lib/promise/pipeline.js:23:30)
    at importContent (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/api/db.js:98:16)
    at apiHandler (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/api/index.js:269:16)
    at Layer.handle [as handle_request] (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/route.js:137:13)
    at uploadValidation (/Users/hongli/Projects/phusion_blog/versions/1.25.2/core/server/web/middleware/validation/upload.js:31:9)
    at Layer.handle [as handle_request] (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/express/lib/router/route.js:137:13)
    at Immediate._onImmediate (/Users/hongli/Projects/phusion_blog/versions/1.25.2/node_modules/multer/lib/make-middleware.js:53:37)
    at runCallback (timers.js:814:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
~~~

Could this be related to the user accounts? My dev install only has two accounts: the ghost user and the newly created admin user. My production install has about 10 accounts.

### Technical details:

* Ghost Version: 1.25.2 (dev), 1.19.0 (production)
* Node Version: 8.11.3 (dev), 6.12.2 (production)
* Browser/OS: macOS Sierra, Chrome 68
* Database: sqlite (both dev and production)

**Comment by kirrg001** [comment]
Hey!

I can't tell why it's failing without having the JSON, but the error stack looks like that the file to import is either corrupt or is empty. Have you manually edited the export JSON file or deleted something from it?

**Comment by FooBarWidget** [comment]
I did not modify the JSON export. Here is the export for your review, with sensitive information stripped out. I scrubbed user account password fields and a Slack webhook URL.

[phusion-blog.ghost.2018-07-26.json.zip](https://github.com/TryGhost/Ghost/files/2232399/phusion-blog.ghost.2018-07-26.json.zip)

**Comment by kirrg001** [comment]
The JSON imports fine for me. I would suggest to reinstall your blog using the [Ghost CLI](https://docs.ghost.org/docs/install). If you need further help, please use our [forum](https://forum.ghost.org).

**Comment by FooBarWidget** [comment]
Do you mean reinstalling the production blog or the development blog? I *did* install the development blog with Ghost CLI.
