### ISSUE TITLE
App installation doesn't work

### ISSUE THREAD

**Issue by andheiberg** [TryGhost/Ghost#9882]
I'm following https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs

Once I restart Ghost I get:

```
bcurious    | [2018-09-18 08:07:20] ERROR
bcurious    |
bcurious    | NAME: InternalServerError
bcurious    | CODE: MODULE_NOT_FOUND
bcurious    | MESSAGE: The server has encountered an error.
bcurious    |
bcurious    | level:normal
bcurious    |
bcurious    | The app will not be loaded
bcurious    | Check with the app creator, or read the app documentation for more details on app requirements
bcurious    | InternalServerError: The server has encountered an error.
bcurious    |     at new GhostError (/var/lib/ghost/versions/2.0.3/core/server/lib/common/errors.js:9:26)
bcurious    |     at /var/lib/ghost/versions/2.0.3/core/server/services/apps/index.js:71:38
bcurious    |     at tryCatcher (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/util.js:16:23)
bcurious    |     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:512:31)
bcurious    |     at Promise._settlePromise (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:569:18)
bcurious    |     at Promise._settlePromise0 (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:614:10)
bcurious    |     at Promise._settlePromises (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:689:18)
bcurious    |     at Async._drainQueue (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:133:16)
bcurious    |     at Async._drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:143:10)
bcurious    |     at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:17:14)
bcurious    |     at runCallback (timers.js:810:20)
bcurious    |     at tryOnImmediate (timers.js:768:5)
bcurious    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
bcurious    |
bcurious    | Error: Cannot find module 'ghost-app'
bcurious    |     at Function.Module._resolveFilename (module.js:547:15)
bcurious    |     at Function.Module._load (module.js:474:25)
bcurious    |     at Module.require (module.js:596:17)
bcurious    |     at Module.requireProxy [as require] (/var/lib/ghost/versions/2.0.3/core/server/services/apps/sandbox.js:84:28)
bcurious    |     at require (internal/module.js:11:18)
bcurious    |     at Object.<anonymous> (/var/lib/ghost/content/apps/podcast/index.js:1:73)
bcurious    |     at Module._compile (module.js:652:30)
bcurious    |     at Object.Module._extensions..js (module.js:663:10)
bcurious    |     at Module.load (module.js:565:32)
bcurious    |     at AppSandbox.loadModuleSandboxed [as loadModule] (/var/lib/ghost/versions/2.0.3/core/server/services/apps/sandbox.js:87:19)
bcurious    |     at AppSandbox.loadAppSandboxed [as loadApp] (/var/lib/ghost/versions/2.0.3/core/server/services/apps/sandbox.js:16:17)
bcurious    |     at loadApp (/var/lib/ghost/versions/2.0.3/core/server/services/apps/loader.js:45:20)
bcurious    |     at getAppByName (/var/lib/ghost/versions/2.0.3/core/server/services/apps/loader.js:50:20)
bcurious    |     at /var/lib/ghost/versions/2.0.3/core/server/services/apps/loader.js:93:31
bcurious    |     at tryCatcher (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/util.js:16:23)
bcurious    |     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:512:31)
```

**Comment by andheiberg** [comment]
Turns out I had incorrectly named `packages.json` with a capital P causing npm not to find the file.
