### ISSUE TITLE
Can't add helpers in Ghost app

### ISSUE THREAD

**Issue by andheiberg** [TryGhost/Ghost#9883]
I followed https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs and got below when restarting the server.

```
bcurious    | [2018-09-18 08:15:46] ERROR
bcurious    |
bcurious    | NAME: InternalServerError
bcurious    | MESSAGE: The server has encountered an error.
bcurious    |
bcurious    | level:normal
bcurious    |
bcurious    | The app will not be loaded
bcurious    | Check with the app creator, or read the app documentation for more details on app requirements
bcurious    | InternalServerError: The server has encountered an error.
bcurious    |     at new GhostError (/var/lib/ghost/versions/2.0.3/core/server/lib/common/errors.js:9:26)
bcurious    |     at /var/lib/ghost/versions/2.0.3/core/server/services/apps/index.js:71:38
bcurious    |     at tryCatcher (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/util.js:16:23)
bcurious    |     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:512:31)
bcurious    |     at Promise._settlePromise (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:569:18)
bcurious    |     at Promise._settlePromise0 (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:614:10)
bcurious    |     at Promise._settlePromises (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:689:18)
bcurious    |     at Async._drainQueue (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:133:16)
bcurious    |     at Async._drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:143:10)
bcurious    |     at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:17:14)
bcurious    |     at runCallback (timers.js:810:20)
bcurious    |     at tryOnImmediate (timers.js:768:5)
bcurious    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
bcurious    |
bcurious    | TypeError: Cannot read property 'helpers' of undefined
bcurious    |     at child.activate (/var/lib/ghost/content/apps/podcast/index.js:8:16)
bcurious    |     at /var/lib/ghost/content/apps/podcast/node_modules/ghost-app/lib/helpers.js:58:38
bcurious    |     at NearFulfilledProxy.when (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:487:43)
bcurious    |     at Promise._message (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:412:25)
bcurious    |     at Array.deliver (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:305:7)
bcurious    |     at runHandlers (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:371:12)
bcurious    |     at Array.<anonymous> (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:338:5)
bcurious    |     at runHandlers (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:371:12)
bcurious    |     at drainQueue (/var/lib/ghost/content/apps/podcast/node_modules/when/when.js:822:3)
bcurious    |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
bcurious    |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

Suggesting that `this.ghost` is undefined.

**Comment by andheiberg** [comment]
Looks like you need to use `this.app.helpers.register`. Even so I can't import my theme as I'm being told "ThemeValidationError: Theme is not compatible or contains errors. Missing helper"

**Comment by andheiberg** [comment]
Turns out this is intended behaviour :( https://github.com/TryGhost/gscan/issues/86
