### ISSUE TITLE
Migration failed on sqlite

### ISSUE THREAD

**Issue by meal** [TryGhost/Ghost#9930]
After pulling newest ghost docker image I've run into this issue:

### Issue Summary

2018-10-01T12:53:00.513735829Z NAME: MigrationScriptError
2018-10-01T12:53:00.513739773Z CODE: SQLITE_MISMATCH
2018-10-01T12:53:00.513743580Z MESSAGE: insert into `clients` (`created_at`, `created_by`, `id`, `name`, `secret`, `slug`, `status`, `type`, `updated_at`, `updated_by`, `uuid`) values ('2018-10-01 12:53:00', 1, '[CUT]', 'Ghost Scheduler', '[CUT]', 'ghost-scheduler', 'enabled', 'web', '2018-10-01 12:53:00', 1, '37e139a4-7ecc-4bfe-aee1-1fb65421242a') - SQLITE_MISMATCH: datatype mismatch

### To Reproduce

1. `docker pull ghost`
2. `docker run` with your options and ghost:latest image

It should migrate to the newest version and run correctly.

### Technical details:

* Ghost Version: 2.1.4
* Node Version: default for 2.1.4 image
* Browser/OS: N/A
* Database: sqlite

**Comment by kirrg001** [comment]
Hey :)

This looks like a fresh installation to me.
It looks like it tries to add the `id` fields as integers, but these are strings. 

Have you used Ghost 0.11 before? Can you pls share the full log?

**Comment by meal** [comment]
I have issued this configuration for over 2 years so I've updated from very early ghost version (0.11 was first I think)

Here is entire output of `docker logs ghost`

```[2018-10-01 12:53:00] INFO Creating table: posts 
[2018-10-01 12:53:00] INFO Creating table: users 
[2018-10-01 12:53:00] INFO Creating table: posts_authors 
[2018-10-01 12:53:00] INFO Creating table: roles 
[2018-10-01 12:53:00] INFO Creating table: roles_users 
[2018-10-01 12:53:00] INFO Creating table: permissions 
[2018-10-01 12:53:00] INFO Creating table: permissions_users 
[2018-10-01 12:53:00] INFO Creating table: permissions_roles 
[2018-10-01 12:53:00] INFO Creating table: permissions_apps 
[2018-10-01 12:53:00] INFO Creating table: settings 
[2018-10-01 12:53:00] INFO Creating table: tags 
[2018-10-01 12:53:00] INFO Creating table: posts_tags 
[2018-10-01 12:53:00] INFO Creating table: apps 
[2018-10-01 12:53:00] INFO Creating table: app_settings 
[2018-10-01 12:53:00] INFO Creating table: app_fields 
[2018-10-01 12:53:00] INFO Creating table: clients 
[2018-10-01 12:53:00] INFO Creating table: client_trusted_domains 
[2018-10-01 12:53:00] INFO Creating table: accesstokens 
[2018-10-01 12:53:00] INFO Creating table: refreshtokens 
[2018-10-01 12:53:00] INFO Creating table: subscribers 
[2018-10-01 12:53:00] INFO Creating table: invites 
[2018-10-01 12:53:00] INFO Creating table: brute 
[2018-10-01 12:53:00] INFO Creating table: webhooks 
[2018-10-01 12:53:00] INFO Model: Tag 
[2018-10-01 12:53:00] INFO Model: Client 
[2018-10-01 12:53:00] ERROR

NAME: MigrationScriptError
CODE: SQLITE_MISMATCH
MESSAGE: insert into `clients` (`created_at`, `created_by`, `id`, `name`, `secret`, `slug`, `status`, `type`, `updated_at`, `updated_by`, `uuid`) values ('2018-10-01 12:53:00', 1, '[CUT]', 'Ghost Scheduler', '[CUT]', 'ghost-scheduler', 'enabled', 'web', '2018-10-01 12:53:00', 1, '37e139a4-7ecc-4bfe-aee1-1fb65421242a') - SQLITE_MISMATCH: datatype mismatch

level:normal

{"config":{"transaction":true},"name":"2-create-fixtures.js"}
"Error occurred while executing the following migration: 2-create-fixtures.js"
ERROR DETAILS:
    empty

MigrationScriptError: insert into `clients` (`created_at`, `created_by`, `id`, `name`, `secret`, `slug`, `status`, `type`, `updated_at`, `updated_by`, `uuid`) values ('2018-10-01 12:53:00', 1, '[CUT]', 'Ghost Scheduler', '[CUT]', 'ghost-scheduler', 'enabled', 'web', '2018-10-01 12:53:00', 1, '37e139a4-7ecc-4bfe-aee1-1fb65421242a') - SQLITE_MISMATCH: datatype mismatch
    at MigrationScriptError.KnexMigrateError (/var/lib/ghost/versions/2.1.4/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (/var/lib/ghost/versions/2.1.4/node_modules/knex-migrator/lib/errors.js:26:26)
    at /var/lib/ghost/versions/2.1.4/node_modules/knex-migrator/lib/index.js:636:19
    at tryCatcher (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.1.4/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Error: SQLITE_MISMATCH: datatype mismatch

```

And this is how I run ghost (I'm running this command for almost 2 years after every ghost update (`docker pull ghost`, `docker stop ghost`, `docker rm ghost` and then this:)

```docker run -d --name ghost -v /home/meal/ghost:/var/lib/ghost/content -p 2368:2368 -e NODE_ENV=production -e VIRTUAL_HOST=MYURL --add-host=docker:172.17.0.1 ghost```

**Comment by kirrg001** [comment]
I can't reproduce this. The query works fine for me. Might be something with your setup?
My assumption is that your target database is an older database with an old schema definition? Maybe double check that the target database is empty and has the correct schema definitions. But just a guess.

I'd suggest to ask for help in our [forum](https://forum.ghost.org/). I'm watching the forum.
