### ISSUE TITLE
Failed to load resource: the server  401 Status Error in V2.2.1

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#9975]
After updating the Ghost to Latest Version
I got this Below error on Browser Console while login to the Admin Dashboard

```
/ghost/api/v2/admin/users/me/?include=roles:1 Failed to load resource: the server responded with a status of 401 ()
```

**Comment by mskian** [comment]
Rollback to Previous Version `ghost update --rollback` Not Getting this Error

**Comment by allouis** [comment]
Hi @mskian could you share any server logs for this error?

**Comment by mskian** [comment]
@allouis 

```
$ ghost log -f

[2018-10-10 02:57:15] ERROR "GET /ghost/api/v2/admin/users/me/?include=roles" 401 23ms

NAME: UnauthorizedError
MESSAGE: Access denied.

level: normal

empty
empty
ERROR DETAILS:
    empty

UnauthorizedError: Access denied.
    at new UnauthorizedError (/var/www/ghost/versions/2.2.1/node_modules/ghost-ignition/lib/errors/index.js:101:23)
    at ensureUser (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:95:10)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at getUser (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:79:16)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at cookieCsrfProtection (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:104:16)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express-session/index.js:489:7
    at SessionModel.findOne.then (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/store.js:24:28)
    at tryCatcher (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:693:18)
```

**Comment by allouis** [comment]
Thanks :) Do you get this error _after_ you attempt to login? Or just when you visit the login page? 

Would you be able to give me some steps to take to try and reproduce this - that way i'll be able to helper much quicker! Thank you!

**Comment by mskian** [comment]
@allouis  Just visit a Login page

**Comment by allouis** [comment]
@mskian This is expected behaviour :relaxed: We make a request in order to know if you're logged in or not, if it fails then we prompt for a login :+1:

**Comment by mskian** [comment]
@allouis After Successfully Login to the Admin dashboard Spot this error on Browser console 

```
/ghost/api/v2/admin/users/me/?include=roles:1 Failed to load resource: the server responded with a status of 401 ()
```

**Comment by allouis** [comment]
@mskian could you check the timestamp on that request? It might be left over from before?

Alternatively you can visit the login page, clear the network logs and then log in - you shouldn't see any errors.

**Comment by mskian** [comment]
My Development Site

```
:2368/ghost/api/v2/admin/users/me/?include=roles:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
:2368/ghost/api/v2/admin/session:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
:2368/ghost/api/v2/admin/session:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by mskian** [comment]
Got this Error log While open a Login Page

```
NAME: UnauthorizedError
MESSAGE: Access denied.

level: normal

empty
empty
ERROR DETAILS:
    empty

UnauthorizedError: Access denied.
    at new UnauthorizedError (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/ghost-ignition/lib/errors/index.js:101:23)
    at ensureUser (/home/groot/Santhosh/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:95:10)
    at Layer.handle [as handle_request] (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at getUser (/home/groot/Santhosh/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:79:16)
    at Layer.handle [as handle_request] (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at cookieCsrfProtection (/home/groot/Santhosh/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:104:16)
    at Layer.handle [as handle_request] (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at session (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express-session/index.js:454:7)
    at getSession (/home/groot/Santhosh/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:48:12)
    at Layer.handle [as handle_request] (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/groot/Santhosh/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by allouis** [comment]
> you previously mention that it's after a successful login to the admin panel. What happened to suggest it was successful?

> Some steps to take to replicate this would be awesome 1st_place_medal
Importantly what is happening, and what do you think should be happening? Not just in the console, but when interfacing with the application!

I can't help with this issue until you give me some more information - sorry!

**Comment by mskian** [comment]
✅ No Login Issue
✅ No Error in Dashboard
❌ but got that console error & ghost log error while opening an admin login page

**Comment by allouis** [comment]
Aha - thanks :relaxed:

So there's nothing to worry about here, as I mentioned before this is expected behaviour :+1: 

> This is expected behaviour relaxed We make a request in order to know if you're logged in or not, if it fails then we prompt for a login +1

Hope you have fun with your new install :ghost:
